Repository redhat-developer/odo, pull requests merged in 2018-11, with the labels that each got.

#856 Make link handling common across both components and services
  cmd/link.go
  pkg/component/component.go
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/secret/secret.go
  pkg/secret/secret_test.go
Labels: kind/enhancement

#847 Improve odo link support
  cmd/link.go
  cmd/service.go
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/service/service.go
  pkg/service/service_test.go
  tests/e2e/e2e.go
  tests/e2e/service_test.go
Labels: kind/enhancement

#949 Factor out creation of contextual information (project, application, component) to make it easier to manage and facilitate refactoring of commands
  cmd/application.go
  cmd/catalog.go
  cmd/cmdutils.go
  cmd/component.go
  cmd/create.go
  cmd/delete.go
  cmd/describe.go
  cmd/link.go
  cmd/list.go
  cmd/log.go
  cmd/project.go
  cmd/push.go
  cmd/root.go
  cmd/service.go
  cmd/service_test.go
  cmd/storage.go
  cmd/update.go
  cmd/url.go
  cmd/version.go
  cmd/watch.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/genericclioptions/fakecontext.go
  pkg/odo/util/client.go
  pkg/odo/util/completion/completion.go
  pkg/odo/util/completion/completionhandlers.go
Labels: kind/code refactoring, size/M

#985 Properly init context and improve information provided to handlers.
  cmd/service_test.go
  docs/completion-architecture.md
  pkg/odo/util/completion/completion.go
  pkg/odo/util/completion/completionhandlers.go
Labels: kind/bug

#871 Re-organize code according to kubectl/oc conventions
  cmd/cli-doc/cli-doc.go
  cmd/odo/odo.go
  pkg/odo/cli/application/application.go
  pkg/odo/cli/catalog/catalog.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/component/component.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/describe.go
  pkg/odo/cli/component/link.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/component/log.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/component/update.go
  pkg/odo/cli/component/watch.go
  pkg/odo/cli/login/login.go
  pkg/odo/cli/logout/logout.go
  pkg/odo/cli/project/project.go
  pkg/odo/cli/service/create.go
  pkg/odo/cli/service/delete.go
  pkg/odo/cli/service/list.go
  pkg/odo/cli/service/service.go
  pkg/odo/cli/service/service_test.go
  pkg/odo/cli/storage/storage.go
  pkg/odo/cli/utils/utils.go
  pkg/odo/cli/version/version.go
Labels: priority/High, size/XL
