Repository redhat-developer/odo, pull requests merged in 2019-08, with the labels that each got.

#1966 Add newline spacing to odo app --help
  pkg/odo/cli/application/application.go
Labels: approved, lgtm, size/XS

#1973 Fixes help message for path flag in odo list
  pkg/odo/cli/component/list.go
Labels: approved, lgtm, size/XS

#1954 recover from panic to give more graceful error message
  pkg/occlient/occlient_test.go
  pkg/odo/cli/component/create.go
  pkg/util/util.go
  tests/integration/component.go
Labels: approved, lgtm, ok-to-test, size/M

#1959 Update labels to match gorkem/app-labels recommendations
  pkg/application/labels/labels.go
  pkg/component/component.go
  pkg/component/labels/labels.go
  pkg/occlient/occlient_test.go
  pkg/odo/cli/service/service_test.go
  pkg/odo/cli/storage/storage_test.go
  pkg/service/service_test.go
  pkg/testingutil/deploymentconfigs.go
  pkg/url/labels/labels.go
  pkg/url/url_test.go
  tests/e2escenarios/core_beta_flow.go
  tests/helper/helper_oc.go
Labels: approved, lgtm, priority/High, release-note-action-required, size/L

#1983 Fixing random input applied by ginkgo in test script
  tests/integration/generic_test.go
Labels: approved, lgtm, size/XS

#1985 removed unnecessary HasAvailableLocalFlag checks from root usage template
  pkg/odo/cli/cli.go
Labels: approved, lgtm, size/XS

#1991 odo_bootstrapper_image-docs-small-fixes
  docs/development.adoc
Labels: approved, lgtm, size/S

#1987 Bumps version to v1.0.0-beta4
  docs/cli-reference.adoc
  pkg/odo/cli/version/version.go
  scripts/installer.sh
Labels: approved, lgtm, size/L

#1920 Makes it possible to list services outside a component directory
  pkg/odo/cli/service/list.go
  pkg/odo/genericclioptions/context.go
  tests/integration/service_test.go
Labels: approved, lgtm, size/M

#1996 Updating build/version
  build/VERSION
Labels: approved, lgtm, size/XS

#1982 resolved a lint error and handled some ignored errors in file_indexer
  pkg/util/file_indexer.go
Labels: approved, lgtm, size/S

#1840 added a Mount Volume for ODO_S2I_DEPLOYMENT_DIR
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/occlient/templates.go
  pkg/occlient/volumes.go
Labels: approved, lgtm, size/XL

#1986 Fixes delete --all flag for not pushed components
  pkg/odo/cli/component/delete.go
  tests/helper/helper_filesystem.go
  tests/integration/component.go
Labels: approved, lgtm, size/M

#1917 I1464 machine readable output
  docs/machine-output.md
Labels: approved, lgtm, ok-to-test, size/L

#2004 removed the mattermost link and added google groups link in templates
  .github/ISSUE_TEMPLATE/Bug.md
  .github/ISSUE_TEMPLATE/Documentation.md
  .github/ISSUE_TEMPLATE/Enhancement.md
  .github/ISSUE_TEMPLATE/Feature.md
Labels: approved, lgtm, size/S

#2007 added the google group in Readme
  README.adoc
Labels: approved, lgtm, size/XS

#2000 report PR number to benchmark collector
  tests/benchmark/benchmark_test.go
  tests/helper/reporter/httpMeasurementReporter.go
Labels: approved, lgtm, size/M

#2008 fail quickly if there is an error while creating service
  pkg/odo/cli/service/create.go
Labels: approved, lgtm, size/XS

#2011 Remove Suraj from OWNERS and replace him with Dharmit
  OWNERS
  pkg/auth/OWNERS
  pkg/catalog/OWNERS
  pkg/occlient/OWNERS
  pkg/odo/OWNERS
  pkg/secret/OWNERS
  pkg/service/OWNERS
  pkg/util/OWNERS
  site/OWNERS
Labels: approved, lgtm, size/M

#2001 Create, list and edit services using "--app" and "--project" flags (without a context)
  pkg/odo/genericclioptions/context.go
  tests/integration/service_test.go
Labels: approved, lgtm, size/S

#2022 fix service integration test
  tests/integration/service_test.go
Labels: approved, lgtm, size/XS

#2006 Small update to help.
  pkg/odo/cli/url/create.go
Labels: approved, lgtm, size/XS

#2003 using relative filepaths in file indexer and added versioned file index
  pkg/odo/cli/component/common_push.go
  pkg/util/file_indexer.go
Labels: approved, lgtm, size/M

#1912 Run all integration test in parallel
  Makefile
  docs/development.adoc
  pkg/preference/preference.go
  tests/e2escenarios/core_beta_flow.go
  tests/integration/cmd_app_test.go
  tests/integration/cmd_pref_config_test.go
  tests/integration/cmd_storage_test.go
  tests/integration/cmd_watch_test.go
  tests/integration/component.go
  tests/integration/generic_test.go
  tests/integration/java_test.go
  tests/integration/json_test.go
  tests/integration/loginlogout/cmd_login_logout_test.go
  tests/integration/loginlogout/loginlogout_suite_test.go
  tests/integration/servicecatalog/cmd_link_unlink_test.go
  tests/integration/servicecatalog/service_test.go
  tests/integration/servicecatalog/servicecatalog_suite_test.go
  tests/integration/source_test.go
Labels: approved, lgtm, size/L

#2026 Documentation on how to manage environment variables
  docs/getting-started.adoc
Labels: approved, lgtm, size/S

#1999 Propagate deleted files to the container
  pkg/occlient/occlient.go
  pkg/odo/cli/component/common_push.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/integration/cmd_push_test.go
Labels: approved, lgtm, size/L

#1916 Adds `odo create project -o json` output
  pkg/log/status.go
  pkg/machineoutput/types.go
  pkg/odo/cli/project/create.go
  pkg/odo/util/cmdutils.go
  pkg/project/project.go
  tests/integration/json_test.go
Labels: approved, lgtm, size/L

#2038 add defaults to the available global params
  pkg/preference/preference.go
Labels: approved, lgtm, size/S

#2009 change the release extension from .gz to .tar.gz
  scripts/installer.sh
  scripts/prepare-release.sh
Labels: approved, lgtm, size/S

#2047 Making cross compile independent of gox vender package
  Makefile
  scripts/openshiftci-presubmit-unittests.sh
Labels: approved, lgtm, size/S

#2053 Documentation on uninstallation procedure
  docs/installation.adoc
Labels: approved, lgtm, size/S

#2037 Adds `odo project delete -o json`
  pkg/odo/cli/project/delete.go
  tests/integration/json_test.go
Labels: approved, lgtm, size/M

#2060 chore: pretty badges in README
  README.adoc
Labels: approved, lgtm, size/XS

#1997 Adds "odo service create --context" feature
  pkg/odo/cli/service/create.go
  pkg/odo/cli/service/delete.go
  pkg/odo/cli/service/list.go
  tests/integration/servicecatalog/service_test.go
Labels: approved, lgtm, size/M

#2034 List all urls even if they are only in local config or only in cluster
  pkg/component/component.go
  pkg/occlient/occlient.go
  pkg/odo/cli/application/application.go
  pkg/odo/cli/component/component.go
  pkg/odo/cli/project/project.go
  pkg/odo/cli/url/list.go
  pkg/odo/util/cmdutils.go
  pkg/odo/util/completion/completionhandlers.go
  pkg/url/types.go
  pkg/url/url.go
  pkg/url/url_test.go
  tests/integration/json_test.go
  tests/integration/url_test.go
Labels: approved, lgtm, size/L

#2027 rename odo-supervisord-image to odo-init-image
  docs/development.adoc
  pkg/component/component.go
  pkg/occlient/occlient.go
  pkg/occlient/templates.go
Labels: approved, lgtm, size/S

#2041 Remove "Ignoring error as it usually means flag wasn't set"
  pkg/odo/genericclioptions/context.go
Labels: approved, lgtm, size/S
