Repository redhat-developer/odo, pull requests merged in 2019-12, with the labels that each got.

#2421 resolve odo list --help having different output then odo component list --help
  pkg/odo/cli/component/list.go
Labels: approved, kind/bug, lgtm, size/XS

#2411 Add link to slack channel
  README.adoc
Labels: approved, kind/docs, lgtm, size/XS

#2413 Add `odo preference set PushTimeout` / pod timeout configuration
  pkg/occlient/occlient.go
  pkg/odo/cli/preference/preference.go
  pkg/odo/cli/preference/set.go
  pkg/odo/cli/preference/unset.go
  pkg/odo/cli/preference/view.go
  pkg/preference/preference.go
  pkg/preference/preference_test.go
  tests/integration/cmd_push_test.go
Labels: approved, kind/feature, lgtm, size/L

#2427 Detect component has yet to be built
  pkg/catalog/catalog.go
  pkg/occlient/occlient.go
  pkg/occlient/templates.go
Labels: approved, kind/bug, lgtm, size/XS

#2430 Release 1.0.2
  Dockerfile.rhel
  pkg/version/version.go
  scripts/bump-version.sh
  scripts/installer.sh
  scripts/rpm-prepare.sh
Labels: approved, kind/feature, lgtm, size/S

#2431 Update build to 1.0.2
  build/VERSION
Labels: approved, kind/feature, lgtm, size/XS

#2433 Run component commands with and without shortcut commands
  tests/integration/component.go
Labels: approved, kind/bug, lgtm, size/M

#2440 Removes redundant check for existence of component
  pkg/odo/cli/component/delete.go
Labels: approved, kind/bug, lgtm, size/XS

#2429 Fix help output for url and storage
  pkg/odo/cli/storage/create.go
  pkg/odo/cli/storage/delete.go
  pkg/odo/cli/storage/list.go
  pkg/odo/cli/storage/storage.go
  pkg/odo/cli/url/url.go
Labels: approved, kind/cleanup, lgtm, size/S

#2435 Add check for "FIt" script
  Makefile
  scripts/check-fit.sh
Labels: approved, lgtm, size/S

#2307 Use the absolute path when using odo push
  pkg/occlient/occlient.go
  pkg/odo/cli/component/common_push.go
  pkg/odo/cli/component/push.go
  pkg/util/file_indexer.go
  tests/integration/cmd_push_test.go
Labels: approved, lgtm, size/L

#2442 cleanup OWNERS file
  OWNERS
  pkg/application/OWNERS
  pkg/auth/OWNERS
  pkg/catalog/OWNERS
  pkg/component/OWNERS
  pkg/config/OWNERS
  pkg/log/OWNERS
  pkg/notify/OWNERS
  pkg/occlient/OWNERS
  pkg/odo/OWNERS
  pkg/project/OWNERS
  pkg/secret/OWNERS
  pkg/service/OWNERS
  pkg/storage/OWNERS
  pkg/testingutil/OWNERS
  pkg/url/OWNERS
  pkg/util/OWNERS
  scripts/OWNERS
  tests/OWNERS
Labels: approved, lgtm, size/L

#2446 Update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, size/S

#2367 Fixes watch unit
  pkg/component/watch_test.go
Labels: approved, kind/bug, lgtm, size/XL

#2453 Adds PROJECT field to 'odo list' output
  pkg/odo/cli/component/list.go
Labels: approved, kind/feature, lgtm, size/XS

#2449 Update documentation issue template
  .github/ISSUE_TEMPLATE/Documentation.md
Labels: approved, lgtm, size/XS

#2451 remove ImageStreamRef from machine readable output
  pkg/catalog/types.go
Labels: approved, kind/api-change, kind/cleanup, lgtm, size/XS

#2450 Do not run e2e test in verbose
  .travis.yml
  scripts/openshiftci-presubmit-all-tests.sh
Labels: approved, kind/test, lgtm, size/XS

#2454 Adds warning component name and project change
  pkg/odo/cli/config/set.go
Labels: approved, kind/feature, size/S

#2420 changed DEBUG_MODE to DEV_MODE in odo-debug design doc
  docs/proposals/odo-debug.md
Labels: approved, kind/code-refactoring, lgtm, size/XS

#2466 Replace "for" loop with map
  pkg/occlient/occlient.go
Labels: approved, kind/code-refactoring, lgtm, size/XS

#2447 Deleting a component also unlinks it from components it might be linked to
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/odo/cli/component/delete.go
  tests/integration/cmd_link_unlink_test.go
Labels: approved, kind/bug, lgtm, size/L

#2469 Remove enhancement labels
  .github/ISSUE_TEMPLATE/Enhancement.md
  scripts/changelog-script.sh
Labels: approved, kind/feature, lgtm, size/M

#2475 fix links to google group
  README.adoc
Labels: approved, kind/documentation, lgtm, ok-to-test, size/XS

#2484 Update changelog script
  scripts/changelog-script.sh
Labels: size/XS

#2441 Unit test add odo-file-index.json to gitignore file
  pkg/testingutil/filesystem/default_fs.go
  pkg/testingutil/filesystem/fake_fs.go
  pkg/testingutil/filesystem/filesystem.go
  pkg/util/file_indexer.go
  pkg/util/file_indexer_test.go
Labels: approved, kind/test, lgtm, size/L

#2489 remove duplicate code from context.go file
  pkg/odo/genericclioptions/context.go
Labels: approved, lgtm, size/XS

#2486 add supportedTags list in the odo catalog list component json output
  pkg/catalog/catalog.go
  pkg/catalog/types.go
  pkg/odo/cli/catalog/list/components.go
  tests/integration/component.go
Labels: approved, kind/feature, lgtm, size/S
