Repository redhat-developer/odo, pull requests merged in 2019-10, with the labels that each got.

#2145 Disable ginkgo verbose mode
  .travis.yml
  Makefile
  docs/development.adoc
  scripts/openshiftci-presubmit-benchmark.sh
  scripts/openshiftci-presubmit-e2etests.sh
  scripts/openshiftci-presubmit-integrationtests.sh
Labels: approved, lgtm, size/M

#2209 fix --binary flag when --context is not set
  pkg/component/component.go
  pkg/odo/cli/component/create.go
  tests/integration/component.go
Labels: approved, lgtm, size/S

#2200 Fixes odo list with path flag
  pkg/component/component.go
  tests/integration/component.go
Labels: approved, lgtm, size/M

#2162 Modifies the paths for deletion according to linux containers
  pkg/occlient/occlient.go
Labels: approved, lgtm, size/XS

#2214 Removing Odo References from CLI
  docs/cli-reference.adoc
  pkg/odo/cli/catalog/list/components.go
  pkg/odo/cli/utils/terminal.go
Labels: approved, lgtm, ok-to-test, size/L

#2187 Move dev documentation to /dev
  README.adoc
  docs/dev/ci-reference.adoc
  docs/dev/completion-architecture.adoc
  docs/dev/development.adoc
  docs/dev/logging.adoc
  docs/dev/machine-output.md
  docs/dev/tdd-workflow.adoc
  docs/dev/validation-architecture.adoc
Labels: approved, lgtm, size/XS

#2218 Bump odo version to 1.0.0-beta6 in "build/VERSION" file
  build/VERSION
Labels: approved, lgtm, size/XS

#2226 Edits to Deploying an application using odo Section of README
  README.adoc
Labels: approved, lgtm, ok-to-test, size/XS

#2234 Add crc stop to Deploy Application Section of README
  README.adoc
Labels: approved, lgtm, ok-to-test, size/XS

#2238 Removes app,project and component flag from storage commands
  pkg/odo/cli/storage/create.go
  pkg/odo/cli/storage/delete.go
  pkg/odo/cli/storage/list.go
  pkg/odo/cli/storage/mount.go
  pkg/odo/cli/storage/unmount.go
  tests/integration/cmd_storage_test.go
Labels: approved, lgtm, size/M

#2167 Fixes double deployment for git components on second push and later
  pkg/occlient/occlient_test.go
  pkg/occlient/templates.go
  tests/integration/cmd_url_test.go
Labels: approved, lgtm, size/S

#2241 Correct odo debug Typo
  docs/cli-reference.adoc
  pkg/odo/cli/debug/debug.go
Labels: approved, lgtm, ok-to-test, size/XS

#2240 Adds unit test for project list
  pkg/project/project_test.go
Labels: approved, lgtm, size/M

#2229 ServiceTypeList should be List in machine output
  pkg/catalog/catalog.go
  pkg/odo/cli/catalog/util/util_test.go
  tests/integration/servicecatalog/cmd_service_test.go
Labels: approved, lgtm, size/S

#2246 removed example for --component from storage
  pkg/odo/cli/storage/delete.go
  pkg/odo/cli/storage/mount.go
  pkg/odo/cli/storage/unmount.go
Labels: approved, lgtm, size/S

#2221 Fixes project wait flag
  Makefile
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  tests/integration/project/cmd_project_test.go
  tests/integration/project/project_suite_test.go
Labels: approved, lgtm, size/S

#2242 Updates the help usage of odo
  pkg/odo/cli/cli.go
  pkg/odo/cli/component/component.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/describe.go
  pkg/odo/cli/config/config.go
  tests/integration/generic_test.go
Labels: approved, lgtm, size/M

#2231 Updates `odo describe` output
  pkg/log/status.go
  pkg/odo/util/cmdutils.go
Labels: approved, lgtm, size/M

#2245 add explicit Unsupported in catalog list component
  pkg/odo/cli/catalog/list/components.go
Labels: approved, lgtm, size/XS

#2228 Machine output for `odo app list` should be `Kind: List`
  docs/dev/machine-output.md
  pkg/application/application.go
  tests/integration/cmd_app_test.go
Labels: approved, lgtm, size/S

#2230 ComponentTypeList should be List in machine output
  pkg/catalog/catalog.go
  tests/integration/component.go
Labels: approved, lgtm, size/XS

#2255 Fix Grammar for odo Error for Project Create and Set
  pkg/odo/genericclioptions/context.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#2252 Update test reports path in gitignore file
  .gitignore
Labels: approved, lgtm, size/XS

#2247 remove --app, --component and --project from odo url
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/url.go
Labels: approved, lgtm, release-note, size/S

#2263 Include service and link command tests
  Makefile
Labels: approved, lgtm, size/XS

#2264 Updates help for odo url create / delete
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/delete.go
Labels: approved, lgtm, size/XS

#2268 Making debug command test target in sync
  Makefile
Labels: approved, lgtm, size/XS

#2269 Automatically set component's ports in interactive mode
  pkg/odo/cli/component/create.go
Labels: approved, lgtm, size/S

#2211 Check that --binary is in --context folder
  pkg/component/component.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/push.go
  tests/integration/component.go
Labels: approved, lgtm, size/M

#2267 show formatted json for machine readable output
  pkg/machineoutput/types.go
  pkg/odo/cli/application/describe.go
  pkg/odo/cli/application/list.go
  pkg/odo/cli/component/describe.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/project/list.go
  pkg/odo/cli/storage/create.go
  pkg/odo/cli/storage/list.go
  pkg/odo/cli/url/list.go
  pkg/util/util.go
  tests/helper/helper_generic.go
  tests/integration/component.go
  tests/integration/project/cmd_project_test.go
Labels: approved, lgtm, size/M

#2265 Fix issue with failing NodeJS component after the container gets restarted
  pkg/occlient/occlient.go
  tests/helper/helper_oc.go
  tests/integration/servicecatalog/cmd_link_unlink_test.go
Labels: approved, lgtm, size/S

#2233 Add secrets to `odo describe`
  pkg/odo/cli/application/describe.go
  pkg/odo/cli/component/describe.go
  pkg/odo/util/cmdutils.go
Labels: approved, lgtm, size/S

#2213 Updates environment variable output
  pkg/odo/cli/component/common_link.go
  tests/integration/servicecatalog/cmd_link_unlink_test.go
Labels: approved, lgtm, size/M

#2278 Change Odo Reference to odo for cli-docs
  cmd/cli-doc/cli-doc.go
Labels: approved, lgtm, ok-to-test, size/XS

#2279 show warning for unsupported image types
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  pkg/odo/cli/component/create.go
  tests/integration/component.go
Labels: approved, lgtm, size/M

#2280 show error when using odo watch on git components
  pkg/odo/cli/component/watch.go
  tests/integration/cmd_watch_test.go
Labels: approved, lgtm, size/S

#2283 Updating spec to use `make prepare-release` to create binaries
  rpms/openshift-odo.spec
Labels: approved, lgtm, size/S

#2276 Bump odo version to 1.0.0-beta7
  Dockerfile.rhel
  docs/cli-reference.adoc
  pkg/odo/cli/version/version.go
  scripts/installer.sh
  scripts/rpm-prepare.sh
Labels: approved, lgtm, size/L

#2292 Updating default bootstrapper image to GA'ed image
  pkg/occlient/occlient.go
Labels: approved, lgtm, size/XS

#2296 Bumping version to 1.0.0
  Dockerfile.rhel
  pkg/odo/cli/version/version.go
  scripts/installer.sh
  scripts/rpm-prepare.sh
Labels: approved, lgtm, size/XS

#2294 Point all new documentation to docs.openshift.com
  README.adoc
  docs/cli-reference.adoc
  docs/examples.adoc
  docs/getting-started.adoc
  docs/installation.adoc
Labels: approved, lgtm, size/XXL

#2302 Removed forgotten focus from integration tests
  tests/integration/project/cmd_project_test.go
Labels: approved, lgtm, size/XS

#2160 Errors out if json machine output has not been implemented
  pkg/odo/cli/application/describe.go
  pkg/odo/cli/application/list.go
  pkg/odo/cli/catalog/list/components.go
  pkg/odo/cli/catalog/list/services.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/describe.go
  pkg/odo/cli/component/link.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/component/log.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/component/unlink.go
  pkg/odo/cli/component/update.go
  pkg/odo/cli/component/watch.go
  pkg/odo/cli/project/create.go
  pkg/odo/cli/project/delete.go
  pkg/odo/cli/project/list.go
  pkg/odo/cli/service/list.go
  pkg/odo/cli/storage/create.go
  pkg/odo/cli/storage/list.go
  pkg/odo/cli/url/list.go
  pkg/odo/genericclioptions/runnable.go
  pkg/odo/util/cmdutils.go
  tests/integration/component.go
Labels: approved, lgtm, size/L

#2315 Update odo version info for 4.3 cluster
  tests/integration/generic_test.go
Labels: approved, lgtm, size/XS

#2257 Adds unit test for project create
  pkg/project/project.go
  pkg/project/project_test.go
Labels: approved, lgtm, size/M

#2317 Update to 1.0.0
  build/VERSION
Labels: approved, lgtm, size/XS

#2275 Fails if user tries to unset invalid environment variable
  pkg/config/env_var.go
  pkg/config/env_var_test.go
  pkg/odo/cli/config/unset.go
  tests/integration/cmd_pref_config_test.go
Labels: approved, lgtm, size/L

#2329 Fix Kubernetes version in odo version info
  tests/integration/generic_test.go
Labels: approved, lgtm, size/XS

#2325 Modifies the PR commit template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, kind/docs, lgtm, size/S

#2324 Updates the asciinema tutorial on the README.adoc
  README.adoc
Labels: approved, kind/docs, lgtm, size/XS
