Repository redhat-developer/odo, pull requests merged in 2019-07, with the labels that each got.

#1837 Added --all flag to odo list
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/types.go
  pkg/odo/cli/component/list.go
  tests/integration/cmd_app_test.go
  tests/integration/component.go
  tests/integration/json_test.go
Labels: approved, lgtm, size/M

#1830 Run generic test file in parallel
  Makefile
  docs/development.adoc
  tests/integration/generic_test.go
Labels: approved, lgtm, size/L

#1860 Multiple odo push should retain the environment variable in OpenShift deployment
  pkg/component/component.go
  tests/integration/component.go
Labels: approved, lgtm, size/M

#1881 Fixing link test flake
  tests/helper/helper_generic.go
  tests/integration/cmd_app_test.go
  tests/integration/cmd_link_unlink_test.go
  tests/integration/component.go
  tests/integration/generic_test.go
  tests/integration/url_test.go
Labels: approved, lgtm, size/M

#1861 Add notes with regards to no component deployed when using odo describe
  pkg/config/config.go
  pkg/odo/cli/component/describe.go
  pkg/odo/genericclioptions/context.go
Labels: approved, lgtm, size/S

#1883 Fixes the odo logout issue.
  .travis.yml
  pkg/odo/genericclioptions/context.go
  scripts/openshiftci-presubmit-benchmark.sh
  scripts/openshiftci-presubmit-e2e-scenarios.sh
  scripts/openshiftci-presubmit-e2e.sh
Labels: approved, lgtm, size/S

#1844 Run java test specs in parallel
  Makefile
  docs/development.adoc
  tests/integration/java_test.go
Labels: approved, lgtm, size/M

#1887 changed config to preference in the new version output
  pkg/odo/cli/version/version.go
Labels: approved, lgtm, size/XS

#1668 Adding now flag to component create command and refactoring for common push
  pkg/odo/cli/component/common_push.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/push.go
  pkg/odo/genericclioptions/add_flags.go
  pkg/odo/genericclioptions/context.go
  tests/integration/component.go
Labels: approved, lgtm, size/XL

#1890 Fix generic test flake
  tests/helper/helper_oc.go
Labels: approved, lgtm, size/XS

#1851 Run e2e scenarios test in parallel
  Makefile
  docs/development.adoc
  scripts/openshiftci-presubmit-e2e-scenarios.sh
  tests/e2escenarios/core_beta_flow.go
Labels: approved, lgtm, size/L

#1843 Run source test specs in parallel
  Makefile
  docs/development.adoc
  tests/e2escenarios/core_beta_flow.go
  tests/integration/source_test.go
Labels: approved, lgtm, size/M

#1828 `--port` is no longer mandatory for `odo url create`
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/url/create.go
  pkg/url/url.go
  pkg/url/url_test.go
  tests/integration/json_test.go
  tests/integration/url_test.go
Labels: approved, lgtm, size/L

#1901 Fix backticks and minor grammar fix
  docs/completion-architecture.adoc
Labels: approved, lgtm, size/XS

#1900 check if the config file exists for odo config
  pkg/odo/cli/config/set.go
  pkg/odo/cli/config/unset.go
  pkg/odo/cli/config/view.go
  tests/e2escenarios/core_beta_flow.go
  tests/integration/cmd_pref_config_test.go
Labels: approved, lgtm, size/M

#1904 Include project name in component spec
  pkg/component/component.go
  pkg/component/component_test.go
  tests/integration/cmd_app_test.go
  tests/integration/json_test.go
Labels: approved, lgtm, size/S

#1867 Removed active field for application
  pkg/application/application_test.go
  pkg/application/types.go
  pkg/odo/cli/application/application.go
  tests/integration/cmd_app_test.go
Labels: approved, lgtm, size/S

#1896 Fix broken links in Getting Started guide
  docs/getting-started.adoc
Labels: approved, lgtm, ok-to-test, size/XS

#1905 optimize component.exists function
  pkg/component/component.go
Labels: approved, lgtm, size/S

#1885 Add ports information to odo describe
  pkg/component/component.go
  pkg/component/types.go
  pkg/odo/cli/component/describe.go
  tests/integration/json_test.go
Labels: approved, lgtm, size/S

#1906 Update wildfly s2i source location
  docs/examples.adoc
Labels: approved, lgtm, size/XS

#1902 Fix CmdShouldFail false positive
  tests/e2escenarios/core_beta_flow.go
  tests/integration/cmd_app_test.go
  tests/integration/cmd_storage_test.go
  tests/integration/cmd_watch_test.go
  tests/integration/component.go
  tests/integration/generic_test.go
  tests/integration/login_test.go
  tests/integration/url_test.go
Labels: approved, lgtm, size/S

#1924 use order less slice comparison in unit tests
  pkg/occlient/occlient_test.go
Labels: approved, lgtm, size/S

#1919 having no components in an app shouldn't be an error
  pkg/odo/cli/application/describe.go
  tests/integration/cmd_app_test.go
Labels: approved, lgtm, size/XS

#1933 consistent component name and resolved failing numeric dir push
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/odo/cli/component/create.go
  tests/integration/component.go
Labels: approved, lgtm, size/M

#1921 used relative path to SourceLocation for binary
  pkg/odo/cli/component/create.go
  tests/integration/java_test.go
Labels: approved, lgtm, size/S

#1926 Added minor notes for new developers.
  docs/development.adoc
Labels: approved, lgtm, size/S

#1918 Add 'org.jboss.container.deployments-dir' to S2IDeploymentsDir
  pkg/occlient/occlient.go
Labels: approved, lgtm, size/XS

#1849 Implementation of a walker for smart odo push
  .travis.yml
  Makefile
  pkg/odo/cli/component/common_push.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/version/version.go
  pkg/util/fileIndexer.go
  scripts/openshiftci-presubmit-e2e.sh
  tests/helper/helper_filesystem.go
  tests/integration/cmd_push_test.go
  tests/integration/generic_test.go
Labels: approved, lgtm, size/XL

#1875 Update login test in sync with other test
  .travis.yml
  Makefile
  docs/development.adoc
  tests/integration/cmd_login_logout_test.go
Labels: approved, lgtm, size/M

#1939 I1773 globalodoconfig docs
  docs/cli-reference.adoc
Labels: approved, lgtm, ok-to-test, size/S

#1948 Add message with program and arguments to helper_run.go output
  tests/helper/helper_run.go
Labels: approved, lgtm, size/S

#1963 Fixing oc describe dc test falke
  tests/helper/helper_oc.go
  tests/integration/component.go
Labels: approved, lgtm, size/S

#1965 Removes an extra exist call and removes the spinner around it
  pkg/odo/cli/component/common_push.go
Labels: approved, lgtm, size/S

#1962 Enabled component sub test in Makefile
  Makefile
Labels: approved, lgtm, size/XS

#1898 Make --output a global parameter, disable logging, fix bug
  pkg/log/status.go
  pkg/odo/cli/application/delete.go
  pkg/odo/cli/application/describe.go
  pkg/odo/cli/application/list.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/component/describe.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/project/list.go
  pkg/odo/cli/storage/create.go
  pkg/odo/cli/storage/list.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/list.go
  pkg/odo/genericclioptions/add_flags.go
  pkg/odo/genericclioptions/runnable.go
Labels: approved, lgtm, size/L

#1958 Introduce gosec for security checks
  Makefile
  pkg/util/config_util.go
  tests/helper/helper_filesystem.go
  tests/helper/helper_http.go
  tests/integration/component.go
Labels: approved, lgtm, size/S
