Repository redhat-developer/odo, pull requests merged in 2019-11, with the labels that each got.

#2334 change "from" to "to" for odo link
  pkg/odo/cli/component/common_link.go
Labels: approved, kind/cleanup, lgtm, ok-to-test, size/XS

#2363 Adding sleep to project test flake
  tests/integration/project/cmd_project_test.go
Labels: approved, kind/flake, lgtm, size/XS

#2362 change checks of ODO_SRC_PATH/src in tests and a temporary fix for project list flake
  tests/integration/cmd_debug_test.go
  tests/integration/cmd_push_test.go
  tests/integration/component.go
Labels: approved, kind/bug, lgtm, size/M

#2273 Add managed-by labels
  Makefile
  docs/dev/development.adoc
  pkg/application/application_test.go
  pkg/application/labels/labels.go
  pkg/application/labels/labels_test.go
  pkg/component/component.go
  pkg/component/labels/labels_test.go
  pkg/odo/cli/version/version.go
  pkg/storage/labels/labels_test.go
  pkg/storage/storage_test.go
  pkg/url/labels/labels_test.go
  pkg/url/url.go
  pkg/url/url_test.go
  pkg/version/version.go
  scripts/bump-version.sh
  tests/helper/helper_oc.go
  tests/integration/cmd_push_test.go
Labels: approved, lgtm, size/L

#2341 Add "odo component create" back to shortcuts.
  pkg/odo/cli/component/create.go
Labels: approved, kind/feature, lgtm, size/XS

#2300 Separating out link tests from service catalog dependent tests
  Makefile
  scripts/openshiftci-presubmit-integrationtests.sh
  tests/integration/cmd_link_unlink_test.go
  tests/integration/servicecatalog/cmd_link_unlink_test.go
  tests/integration/servicecatalog/cmd_service_test.go
Labels: approved, lgtm, size/L

#2335 Remove TDD docs, add more info on running tests
  docs/dev/development.adoc
  docs/dev/tdd-workflow.adoc
Labels: approved, kind/docs, lgtm, size/M

#2340 Refactor templates
  .github/ISSUE_TEMPLATE/Bug.md
  .github/ISSUE_TEMPLATE/Documentation.md
  .github/ISSUE_TEMPLATE/Enhancement.md
Labels: approved, kind/cleanup, lgtm, size/S

#2342 Refactoring output of machine output
  pkg/odo/cli/application/describe.go
  pkg/odo/cli/application/list.go
  pkg/odo/cli/component/describe.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/project/list.go
  pkg/odo/cli/storage/create.go
  pkg/odo/cli/storage/list.go
  pkg/odo/cli/url/list.go
  pkg/util/util.go
Labels: approved, lgtm, size/M

#2344 Update the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, kind/cleanup, lgtm, size/S

#2332 Adds golintCI to travis job
  .travis.yml
  Makefile
  pkg/application/application.go
  pkg/auth/login.go
  pkg/component/component_test.go
  pkg/component/watch.go
  pkg/component/watch_test.go
  pkg/config/config.go
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/occlient/volumes.go
  pkg/odo/cli/application/application.go
  pkg/odo/cli/application/delete.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/component/common_push.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/describe.go
  pkg/odo/cli/debug/portforward.go
  pkg/odo/cli/storage/mount.go
  pkg/odo/cli/storage/unmount.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/genericclioptions/runnable.go
  pkg/odo/util/cmdutils.go
  pkg/service/service.go
  pkg/testingutil/deploymentconfigs.go
  pkg/util/file_indexer.go
  pkg/util/util_test.go
  tests/helper/helper_filesystem.go
  tests/helper/helper_generic.go
  tests/helper/reporter/httpMeasurementReporter.go
  tests/helper/reporter/junitReporter.go
  tests/integration/cmd_pref_config_test.go
  tests/integration/component.go
Labels: approved, kind/cleanup, lgtm, size/L

#2373 New release of odo! 1.0.1
  Dockerfile.rhel
  pkg/version/version.go
  scripts/installer.sh
  scripts/rpm-prepare.sh
Labels: approved, kind/feature, lgtm, size/XS

#2376 Update build version to 1.0.1
  build/VERSION
Labels: approved, kind/feature, lgtm, size/XS

#2375 Remove Space from Project Create Success Message
  pkg/odo/cli/project/create.go
Labels: approved, kind/cleanup, lgtm, ok-to-test, size/XS

#2384 Build and package for all RHEL architectures
  rpms/openshift-odo.spec
  scripts/cross-compile.sh
Labels: approved, kind/feature, lgtm, ok-to-test, size/S

#2391 Update doc since Codewind project already used odo
  README.adoc
Labels: approved, kind/docs, lgtm, ok-to-test, size/XS

#2381 Updating to supported java component test in link test file
  tests/integration/cmd_link_unlink_test.go
Labels: approved, kind/feature, kind/test, lgtm, size/S

#2378 Add env variable "ODO_LOG_LEVEL" to control odo verbosity (#2351)
  cmd/odo/odo.go
  docs/dev/logging.adoc
Labels: approved, kind/feature, lgtm, ok-to-test, size/S

#2396 Fixing typo in test file
  tests/e2escenarios/e2e_beta_test.go
Labels: approved, kind/cleanup, lgtm, size/XS

#2368 Update the development guide + add changelog script
  docs/dev/development.adoc
  scripts/changelog-script.sh
Labels: approved, kind/code-refactoring, kind/docs, lgtm, size/M

#2336 renamed Url to URL to resolve lint warning and consistency
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/config/config.go
  pkg/config/fakeConfig.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/delete.go
  pkg/odo/cli/url/list.go
  pkg/url/types.go
  pkg/url/url.go
  tests/integration/servicecatalog/cmd_link_unlink_test.go
Labels: approved, kind/cleanup, lgtm, size/L

#2383 Remove automated deployments through TravisCI
  .travis.yml
Labels: approved, kind/cleanup, lgtm, size/M

#2308 Fixes the symlink path for the binary flag
  pkg/odo/cli/component/create.go
  tests/helper/helper_filesystem.go
  tests/integration/component.go
Labels: approved, lgtm, size/M

#2348 Add italic font when describing what to do next
  pkg/auth/login.go
  pkg/log/status.go
  pkg/odo/cli/application/list.go
  pkg/odo/cli/component/common_link.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/config/set.go
  pkg/odo/cli/config/unset.go
  pkg/odo/cli/preference/set.go
  pkg/odo/cli/preference/unset.go
  pkg/odo/cli/service/create.go
  pkg/odo/cli/storage/create.go
  pkg/odo/cli/storage/delete.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/delete.go
  tests/integration/component.go
Labels: approved, kind/docs, kind/feature, lgtm, size/M

#2345 Remove machineoutput annotation from odo create
  pkg/odo/cli/component/create.go
  tests/integration/component.go
  tests/integration/project/cmd_project_test.go
Labels: approved, kind/cleanup, lgtm, size/S

#2401 Add all test target to a single OpenShift CI presubmit file
  scripts/openshiftci-presubmit-all-tests.sh
Labels: approved, kind/test, lgtm, size/M

#2346 Cleanup service creation output
  pkg/odo/cli/service/create.go
Labels: approved, kind/cleanup, kind/feature, lgtm, size/XS

#2326 Disable context / checking for config when using autocompletion
  pkg/config/config.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/util/completion/completion.go
Labels: approved, lgtm, size/L

#2305 Adding odo file index json to gitignore file
  pkg/util/file_indexer.go
  tests/integration/cmd_push_test.go
Labels: approved, lgtm, size/M

#2403 Disabling ginkgo JUNIT report generator
  scripts/openshiftci-presubmit-all-tests.sh
  scripts/openshiftci-presubmit-e2etests.sh
  scripts/openshiftci-presubmit-integrationtests.sh
  tests/e2escenarios/e2escenarios_suite_test.go
  tests/integration/integration_suite_test.go
  tests/integration/loginlogout/loginlogout_suite_test.go
  tests/integration/project/project_suite_test.go
  tests/integration/servicecatalog/servicecatalog_suite_test.go
Labels: approved, kind/test, lgtm, size/M

#2407 Cleaning up OpenShift CI files
  scripts/openshiftci-presubmit-benchmark.sh
  scripts/openshiftci-presubmit-e2etests.sh
  scripts/openshiftci-presubmit-integrationtests.sh
Labels: approved, kind/cleanup, kind/test, lgtm, size/M

#2399 Fixes odo describe for non pushed components
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/config/fakeConfig.go
  pkg/odo/cli/component/describe.go
  pkg/odo/util/cmdutils.go
  tests/integration/component.go
Labels: approved, lgtm, size/L

#2125 Set DC as ownerReference for objects created on OpenShift cluster
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/occlient/volumes.go
  pkg/url/url_test.go
  tests/integration/generic_test.go
Labels: approved, lgtm, size/L

#2412 Remove site since we now use OpenShift docs
  site/404.html
  site/CNAME
  site/Gemfile
  site/Gemfile.lock
  site/LICENSE
  site/OWNERS
  site/README.adoc
  site/_config.yml
  site/_data/menu.yml
  site/_includes/head.html
  site/_includes/header.html
  site/_includes/menu.html
  site/_includes/scripts.html
  site/_layouts/default.html
  site/_layouts/index.html
  site/build.sh
  site/css/default.css
  site/css/hljs-github.min.css
  site/css/main.css
  site/css/pilcrow.css
  site/feed.xml
  site/img/android-chrome-192x192.png
  site/img/android-chrome-512x512.png
  site/img/apple-touch-icon.png
  site/img/browserconfig.xml
  site/img/demo.gif
  site/img/favicon-16x16.png
  site/img/favicon-32x32.png
  site/img/favicon.ico
  site/img/icons/netcore.png
  site/img/icons/node.png
  site/img/icons/perl.png
  site/img/icons/php.png
  site/img/icons/python.png
  site/img/icons/ruby.png
  site/img/kubernetes.png
  site/img/logo-big.png
  site/img/logo.png
  site/img/logo.svg
  site/img/manifest.json
  site/img/minimal-jekyll.png
  site/img/mstile-150x150.png
  site/img/pattern.png
  site/img/redhat-logo.png
  site/img/safari-pinned-tab.svg
  site/img/site.webmanifest
  site/img/waves.png
  site/img/whale.gif
  site/index.md
  site/js/icons.js
  site/pre.sh
  site/serve.sh
Labels: approved, kind/cleanup, lgtm, size/XXL

#2398 Adding wait flag test in link command test
  tests/integration/cmd_link_unlink_test.go
Labels: approved, kind/test, lgtm, size/M

#2410 Modify unit tests for deleting odo config dir to be tabular
  pkg/config/config_test.go
Labels: approved, kind/cleanup, kind/code-refactoring, kind/test, lgtm, size/L
