Repository redhat-developer/odo, pull requests merged in 2019-03, with the labels that each got.

#1401 Remove terminal specific command from e2e component test file
  tests/e2e/component.go
  tests/e2e/utils.go
Labels: approved, lgtm, size/M

#1418 added type meta in config and preference structs
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/preference/preference.go
  pkg/preference/preference_test.go
Labels: approved, lgtm, size/L

#1417 Removing CODEOWNERS as prow OWNERS have taken off
  CODEOWNERS
Labels: approved, lgtm, size/M

#1409 Remove terminal specific command from e2e source test file
  tests/e2e/source_test.go
Labels: approved, lgtm, size/S

#1408 Remove terminal specific command from e2e service test file
  tests/e2e/service_test.go
Labels: approved, lgtm, size/XS

#1395 json output for odo url create
  pkg/odo/cli/component/ui/ui.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/delete.go
  pkg/odo/cli/url/list.go
  pkg/odo/genericclioptions/add_flags.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/genericclioptions/context_flags.go
  pkg/odo/util/cmdutils.go
  pkg/url/types.go
  pkg/url/url.go
  pkg/url/url_test.go
  pkg/util/util.go
  tests/e2e/json_test.go
Labels: approved, lgtm, size/L

#1424 Updating development docs with information on prow.
  docs/development.md
Labels: approved, lgtm, size/S

#1425 Avoid use of odo core package in testsuite
  tests/e2e/e2e_test.go
Labels: approved, lgtm, size/XS

#1423 List all sub-commands within odo help
  pkg/odo/cli/cli.go
  pkg/odo/cli/component/component.go
  pkg/odo/cli/component/log.go
  pkg/odo/cli/utils/utils.go
Labels: approved, lgtm, size/M

#1422 Re-organize examples for odo create
  pkg/odo/cli/component/create.go
Labels: approved, lgtm, size/M

#1436 Fix typo in development guide
  docs/development.md
Labels: approved, lgtm, ok-to-test, size/S

#1437 Adding our own base image to test on Openshift CI
  openshift-ci/build-root/Dockerfile
  openshift-ci/build-root/README.md
Labels: approved, lgtm, size/S

#1438 development.md: link to openshift Prow, not k8s one.
  docs/development.md
Labels: approved, lgtm, size/XS

#1420 Clarify Odo terminology
  README.md
  docs/ci-reference.md
  docs/development.md
  docs/examples.md
  docs/getting-started.md
  docs/installation.md
  docs/logging.md
  docs/tdd-workflow.md
Labels: approved, lgtm, size/M

#1413 Remove terminal specific command from e2e test file
  tests/e2e/e2e_test.go
  tests/e2e/utils.go
Labels: approved, size/L

#1404 Added json output for storage create
  pkg/odo/cli/storage/create.go
  pkg/odo/cli/storage/list.go
  pkg/odo/cli/storage/storage.go
  pkg/odo/util/cmdutils.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  pkg/storage/types.go
  pkg/util/util.go
  tests/e2e/json_test.go
Labels: approved, lgtm, size/L

#1319 Fixing issue #804 Improving delete command to list affected children
  pkg/application/application.go
  pkg/odo/cli/application/application.go
  pkg/odo/cli/application/delete.go
  pkg/odo/cli/application/list.go
  pkg/odo/cli/component/component.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/project/delete.go
  pkg/odo/cli/project/project.go
  tests/e2e/e2e_test.go
Labels: approved, lgtm, size/L

#1441 Adding scripts to handle initialization of cluster for openshift CI.
  Makefile
  docs/ci-reference.md
  openshift-ci/build-root/Dockerfile
  scripts/configure-installer-tests-cluster.sh
  tests/e2e/e2e_test.go
Labels: approved, do-not-merge/hold, size/L

#1452 Fixing script to be able to skip logging in as admin, if needed
  docs/ci-reference.md
  scripts/configure-installer-tests-cluster.sh
Labels: approved, lgtm, priority/Critical, size/M

#1451 Fixing username as per e2e_test file
  scripts/configure-installer-tests-cluster.sh
Labels: approved, lgtm, size/XS

#1410 Remove terminal specific command from e2e java test file
  tests/e2e/java_test.go
  tests/e2e/utils.go
Labels: approved, lgtm, size/M

#1453 local config improvements
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/occlient/occlient.go
  pkg/odo/cli/config/set.go
  pkg/odo/cli/config/unset.go
  pkg/odo/cli/config/view.go
  tests/e2e/e2e_test.go
Labels: approved, do-not-merge/hold, lgtm, size/L

#1454 Updating re to run e2e_test on 4.0 cluster
  tests/e2e/e2e_test.go
  tests/e2e/utils.go
Labels: approved, lgtm, size/S

#1460 Removing unnessaary make bin from script.
  scripts/configure-installer-tests-cluster.sh
  tests/e2e/e2e_test.go
Labels: approved, lgtm, size/M

#1457 remove GetConfiguration from config and preference
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/odo/cli/config/set.go
  pkg/odo/cli/config/unset.go
  pkg/odo/cli/preference/set.go
  pkg/odo/cli/preference/unset.go
  pkg/preference/preference.go
  pkg/util/config_util.go
Labels: approved, lgtm, size/L

#1211 Adds color support for Windows
  glide.lock
  glide.yaml
  pkg/log/fidget/spinner.go
  pkg/log/status.go
  vendor/gopkg.in/AlecAivazis/survey.v1/terminal/LICENSE.txt
Labels: approved, lgtm, size/L

#1469 Updating source tests to use dotnet 2.0 IS specifically
  tests/e2e/source_test.go
Labels: approved, lgtm, size/XS

#1468 Run component test on OpenShift 4.0 cluster
  tests/e2e/component.go
  tests/e2e/e2e.go
Labels: approved, lgtm, size/XS

#1474 [DEMO PR] This is for purpose of showing off OpenShift CI
  demo/demo
Labels: approved, lgtm, size/XS

#1477 Increasing wait time and detecting failure of login as developer
  scripts/configure-installer-tests-cluster.sh
Labels: approved, lgtm, size/S

#1456 Add -o json flag to `odo app delete`
  pkg/odo/cli/application/delete.go
  tests/e2e/json_test.go
Labels: approved, lgtm, size/S

#1478 Increasing timeout for accessing health endpoint
  tests/e2e/component.go
Labels: approved, lgtm, size/XS

#1495 Remove gifs from site
  _layouts/index.html
Labels: size/XS

#1462 Readme edits
  README.md
Labels: approved, lgtm, ok-to-test, size/L

#1494 Remove demo file
  demo/demo
Labels: approved, lgtm, size/XS

#1498 Fixes link for installation document
  docs/getting-started.md
Labels: approved, lgtm, size/XS

#1434 Add notes with regards to listing subcommands.
  pkg/odo/cli/cli.go
  pkg/odo/cli/utils/utils.go
Labels: approved, do-not-merge/hold, size/S

#1506 Update site with new repo
  _config.yml
Labels: size/XS

#1502 Adding runCmdShouldPass function with retry and turning off failing test on openshift ci
  tests/e2e/e2e.go
  tests/e2e/e2e_test.go
  tests/e2e/utils.go
Labels: approved, do-not-merge/hold, size/M

#1501 bumb supervisord image version
  pkg/occlient/occlient.go
Labels: approved, lgtm, size/XS

#1360 Apply ComponentSettings as part of component push
  pkg/application/application.go
  pkg/application/application_test.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/occlient/templates.go
  pkg/odo/cli/application/application.go
  pkg/odo/cli/application/create.go
  pkg/odo/cli/application/delete.go
  pkg/odo/cli/application/describe.go
  pkg/odo/cli/application/get.go
  pkg/odo/cli/application/list.go
  pkg/odo/cli/application/set.go
  pkg/odo/cli/component/component.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/component/set.go
  pkg/odo/cli/component/ui/ui.go
  pkg/odo/cli/component/update.go
  pkg/odo/cli/project/delete.go
  pkg/odo/cli/project/project.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/genericclioptions/context_flags.go
  pkg/odo/util/completion/completionhandlers.go
  pkg/preference/preference.go
  pkg/preference/preference_test.go
  pkg/project/project.go
  pkg/project/project_test.go
  pkg/testingutil/configs.go
  pkg/util/util.go
  tests/e2e/component.go
  tests/e2e/e2e.go
  tests/e2e/e2e_test.go
  tests/e2e/java_test.go
  tests/e2e/json_test.go
  tests/e2e/link_test.go
  tests/e2e/login_test.go
  tests/e2e/service_test.go
  tests/e2e/source_test.go
  tests/e2e/utils.go
  tests/e2e/watch_test.go
Labels: approved, lgtm, size/XXL

#1508 Group TravisCI jobs
  .travis.yml
Labels: approved, lgtm, size/M

#1518 Fixing error when user lists component in directory without one
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/occlient/occlient_test.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/component/update.go
  pkg/odo/genericclioptions/context.go
  tests/e2e/component.go
Labels: approved, lgtm, size/M

#1524 resolved panic on port set
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/odo/cli/config/view.go
  tests/e2e/e2e_test.go
Labels: approved, lgtm, size/L

#1275 Adds --show-log to odo push
  pkg/component/component.go
  pkg/component/watch.go
  pkg/component/watch_test.go
  pkg/log/status.go
  pkg/odo/cli/component/push.go
  tests/e2e/e2e_test.go
Labels: approved, lgtm, size/M

#1528 removed spacing in delete info prints
  pkg/odo/cli/application/application.go
  pkg/odo/cli/component/component.go
  pkg/odo/cli/project/project.go
Labels: approved, lgtm, size/M

#1449 added env variables in component config
  pkg/config/config.go
  pkg/config/env_var.go
  pkg/config/env_var_test.go
  pkg/odo/cli/config/set.go
  pkg/odo/cli/config/unset.go
  pkg/odo/cli/config/view.go
  pkg/util/util.go
  tests/e2e/component.go
  tests/e2e/e2e_test.go
  tests/e2e/watch_test.go
Labels: approved, lgtm, size/L

#1534 fix: prevent panic when no classes are available
  pkg/odo/cli/service/create.go
Labels: approved, lgtm, size/XS
