Repository redhat-developer/odo, pull requests merged in 2019-09, with the labels that each got.

#1974 Update test to reflect changes done in odo-supervisord-image#27
  Makefile
  pkg/occlient/occlient.go
  tests/helper/helper_oc.go
  tests/integration/cmd_push_test.go
Labels: approved, lgtm, size/M

#2075 Release 1.0.0-beta5
  docs/cli-reference.adoc
  pkg/odo/cli/version/version.go
  scripts/installer.sh
Labels: approved, lgtm, size/M

#2040 add parameter map population in non-interactive service creation
  pkg/odo/cli/service/create.go
  tests/integration/servicecatalog/service_test.go
Labels: approved, lgtm, size/M

#2080 Update build/VERSION for 1.0.0-beta5
  build/VERSION
Labels: approved, lgtm, size/XS

#2083 Add cross compiling script
  Makefile
  scripts/cross-compile.sh
Labels: approved, lgtm, size/M

#1998 Dockerfile is used by CI to publish odo artifacts
  Dockerfile.rhel
Labels: approved, lgtm, size/S

#2072 update quay.io/openshiftdo/init image to 0.10.0
  pkg/occlient/occlient.go
  tests/integration/cmd_push_test.go
Labels: approved, lgtm, size/S

#2066 Adds `odo catalog list services -o json`
  pkg/machineoutput/types.go
  pkg/occlient/occlient.go
  pkg/odo/cli/catalog/list/services.go
  pkg/odo/util/cmdutils.go
  pkg/project/project.go
  tests/integration/servicecatalog/cmd_service_test.go
Labels: approved, lgtm, size/M

#2035 Prints environment variables added/removed to a component by doing odo link/unlink
  pkg/odo/cli/component/common_link.go
  tests/integration/servicecatalog/cmd_link_unlink_test.go
Labels: approved, lgtm, size/M

#2094 Remove required --port within README and Getting Started guides
  README.adoc
  docs/getting-started.adoc
Labels: approved, lgtm, size/XS

#2096 Remove newline from odo create output
  pkg/odo/cli/component/create.go
Labels: approved, lgtm, size/XS

#2097 Modifies info output of url delete and url create
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/delete.go
  pkg/odo/genericclioptions/printtemplates/messages.go
  pkg/odo/genericclioptions/printtemplates/messages_test.go
Labels: approved, lgtm, size/M

#2100 Adding osbs labels to cli artifacts image
  Dockerfile.rhel
  docs/development.adoc
  scripts/bump-version.sh
Labels: approved, lgtm, size/S

#2059 update tests so they run on openshift 4.2
  pkg/occlient/occlient.go
  tests/benchmark/basic_benchmark.go
  tests/e2escenarios/e2e_beta_test.go
  tests/e2escenarios/e2e_java_test.go
  tests/e2escenarios/e2e_source_test.go
  tests/helper/helper_oc.go
  tests/integration/cmd_storage_test.go
  tests/integration/component.go
  tests/integration/servicecatalog/cmd_service_test.go
Labels: approved, lgtm, size/M

#2101 Removing unuse OpenShift CI script files
  scripts/openshiftci-presubmit-e2e-scenarios.sh
  scripts/openshiftci-presubmit-e2e.sh
Labels: approved, lgtm, ok-to-test, size/M

#2086 Makes update information italic text
  cmd/odo/odo.go
  pkg/log/status.go
  pkg/odo/cli/version/version.go
Labels: approved, lgtm, size/S

#2108 Import dotnet20 image stream on openshift42 cluster
  tests/e2escenarios/e2e_source_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#2078 Removes connection check with OpenShift cluster
  pkg/occlient/occlient.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/version/version.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/genericclioptions/context_flags.go
Labels: approved, lgtm, size/M

#2091 Removes overlapping messages for odo git components
  pkg/component/component.go
  pkg/odo/cli/component/common_push.go
Labels: approved, lgtm, size/M

#2112 Remove creating project info
  pkg/odo/cli/component/common_push.go
Labels: approved, lgtm, size/XS

#2110 Reduces amount of lines in release info / update
  pkg/odo/cli/version/version.go
Labels: approved, lgtm, size/S

#2039 [merge after https://github.com/openshift/odo/pull/2009] change .gz to .tar.gz in docs
  README.adoc
  docs/installation.adoc
Labels: approved, lgtm, size/XS

#2118 Fix source path for windows platform
  tests/integration/cmd_app_test.go
  tests/integration/component.go
Labels: approved, lgtm, size/S

#2124 Fix typo in app test file
  tests/integration/cmd_app_test.go
Labels: approved, lgtm, size/XS

#2137 Fixing JustAfterEach error on windows platform
  tests/integration/cmd_pref_config_test.go
  tests/integration/generic_test.go
  tests/integration/servicecatalog/cmd_service_test.go
Labels: approved, lgtm, size/XS

#2123 Add development doc on machine readable output
  docs/development.adoc
Labels: approved, lgtm, size/M

#2128 Fix JSON output context path on windows platform
  tests/integration/component.go
Labels: approved, lgtm, size/S

#2098 Adds `odo service list -o json`
  pkg/odo/cli/application/application.go
  pkg/odo/cli/application/describe.go
  pkg/odo/cli/project/project.go
  pkg/odo/cli/service/list.go
  pkg/odo/util/completion/completionhandlers.go
  pkg/service/service.go
  pkg/service/service_test.go
  pkg/service/types.go
  tests/integration/servicecatalog/cmd_service_test.go
Labels: approved, lgtm, size/L

#1995 Proposal document: odo debug
  docs/proposals/odo-debug.md
Labels: approved, lgtm, size/L

#2141 Add tests/reports to .gitignore
  .gitignore
Labels: approved, lgtm, size/XS

#2143 Fix typo to correctly show the purpose of odo
  docs/cli-reference.adoc
  pkg/odo/cli/cli.go
Labels: approved, lgtm, size/XS

#2046 Fixes list output in odo directory when component is not pushed
  pkg/application/application.go
  pkg/application/application_test.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/config/config.go
  pkg/config/fakeConfig.go
  pkg/occlient/occlient.go
  pkg/odo/cli/application/application.go
  pkg/odo/cli/application/describe.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/project/project.go
  pkg/odo/cli/storage/storage_test.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/util/completion/completionhandlers.go
  pkg/odo/util/completion/completionhandlers_test.go
  tests/integration/component.go
  tests/integration/servicecatalog/cmd_service_test.go
Labels: approved, lgtm, size/XL

#2130 Replace dump-init with go-init
  pkg/occlient/occlient.go
  pkg/occlient/templates.go
Labels: approved, lgtm, size/S

#2134 Remove context check for search
  pkg/odo/genericclioptions/context.go
Labels: approved, lgtm, size/XS

#2140 add nodejs minishift images in supported
  pkg/catalog/catalog.go
Labels: approved, lgtm, size/S

#2144 changed all references of odo-supervisord-image to odo-init-image
  pkg/occlient/occlient.go
Labels: approved, lgtm, size/S

#2146 Improve look and feel of integration test doc
  docs/development.adoc
Labels: approved, lgtm, size/S

#2099 Removes apps from project specs and speeds up the query
  .travis.yml
  Makefile
  pkg/odo/cli/project/list.go
  pkg/project/project.go
  pkg/project/types.go
  scripts/openshiftci-presubmit-integrationtests.sh
  tests/integration/cmd_project_test.go
Labels: approved, lgtm, size/M

#2133 Refactor catalog code
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  pkg/catalog/types.go
  pkg/component/component.go
  pkg/machineoutput/types.go
  pkg/occlient/occlient.go
  pkg/occlient/utils.go
  pkg/occlient/utils_test.go
  pkg/odo/cli/catalog/list/components.go
  pkg/odo/cli/catalog/list/services.go
  pkg/odo/cli/catalog/search/component.go
  pkg/odo/cli/catalog/search/service.go
  pkg/odo/cli/catalog/util/util.go
  pkg/odo/cli/catalog/util/util_test.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/ui/ui.go
  pkg/odo/util/completion/completionhandlers.go
  pkg/service/service.go
  tests/integration/component.go
  tests/integration/servicecatalog/cmd_service_test.go
Labels: approved, lgtm, size/XL

#2151 Delete .PHONY openshiftci-presubmit-e2e From Makefile
  Makefile
Labels: approved, lgtm, size/XS

#2152 Fixing wrong info provided for integration test comment
  Makefile
Labels: approved, lgtm, size/XS

#2107 Setting up rpm spec for odo for rpm build
  Makefile
  docs/development.adoc
  rpms/openshift-odo.spec
  scripts/rpm-local-build.sh
  scripts/rpm-prepare.sh
Labels: approved, lgtm, size/L

#2043 odo experimental debug port-forward command
  .travis.yml
  Makefile
  docs/getting-started.adoc
  pkg/component/component.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/debug/portforward.go
  pkg/occlient/occlient.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/config/set.go
  pkg/odo/cli/config/unset.go
  pkg/odo/cli/config/view.go
  pkg/odo/cli/debug/debug.go
  pkg/odo/cli/debug/portforward.go
  scripts/openshiftci-presubmit-integrationtests.sh
  tests/helper/helper_http.go
  tests/helper/helper_run.go
  tests/integration/cmd_app_test.go
  tests/integration/cmd_debug_test.go
  tests/integration/component.go
Labels: approved, lgtm, need-docs, size/XL

#2036 Fix slowSpecThreshold flag in Makefile
  Makefile
Labels: approved, lgtm, size/M

#2164 Fixing login flake
  tests/integration/loginlogout/cmd_login_logout_test.go
Labels: approved, lgtm, size/M

#2177 update init image to 0.13.0
  pkg/occlient/occlient.go
Labels: approved, lgtm, size/XS

#2159 Fix spelling errors in catalog list components
  pkg/odo/cli/catalog/list/components.go
Labels: approved, lgtm, size/XS

#2182 Bump odo version to 1.0.0-beta6
  Dockerfile.rhel
  docs/cli-reference.adoc
  docs/development.adoc
  pkg/odo/cli/version/version.go
  scripts/installer.sh
  scripts/rpm-prepare.sh
Labels: approved, lgtm, size/M

#2185 Fixing no such file or directory issue
  tests/integration/component.go
Labels: approved, lgtm, size/XS

#2199 fix sha256 generation for release
  scripts/prepare-release.sh
Labels: approved, lgtm, size/XS

#2197 Fixes path for odo create interactive
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/ui/ui.go
Labels: approved, lgtm, size/S

#2190 log stdout and stderr of tar command
  pkg/occlient/occlient.go
Labels: approved, lgtm, size/S

#2198 Adds message to inform user to do odo push for storage changes to tak…
  pkg/odo/cli/storage/create.go
  pkg/odo/cli/storage/delete.go
Labels: approved, lgtm, size/XS

#2188 Updates the README formatting and adds crc
  README.adoc
Labels: approved, lgtm, size/S

#2166 Fixing login, service and link reports path
  tests/integration/loginlogout/loginlogout_suite_test.go
  tests/integration/servicecatalog/servicecatalog_suite_test.go
Labels: approved, lgtm, size/XS

#2169 Updates machine readable output for `odo app`
  docs/machine-output.md
  pkg/application/application.go
  tests/integration/cmd_app_test.go
Labels: approved, lgtm, size/S

#2149 Add tests for odo catalog search failing
  tests/integration/generic_test.go
  tests/integration/servicecatalog/cmd_service_test.go
Labels: approved, lgtm, size/S

#2205 Fix typo in `odo debug` help output
  pkg/odo/cli/debug/portforward.go
Labels: approved, lgtm, size/XS

#2206 Fix random ginkgo input in test script
  tests/integration/cmd_pref_config_test.go
Labels: approved, lgtm, size/XS

#2210 odo create - small examples and help cleanup
  pkg/odo/cli/component/create.go
Labels: approved, kind/docs, lgtm, size/M
