Repository redhat-developer/odo, pull requests merged in 2019-05, with the labels that each got.

#1683 added check to see if component exists or not
  pkg/odo/cli/component/watch.go
  pkg/odo/genericclioptions/context.go
  tests/e2e/watch_test.go
Labels: approved, lgtm, size/M

#1689 Adds capitalization to all flags
  pkg/odo/cli/cli.go
  pkg/odo/cli/login/login.go
  pkg/odo/cli/utils/utils.go
  pkg/odo/util/cmdutils.go
Labels: approved, lgtm, size/M

#1693 Change README .md References to .adoc
  README.adoc
Labels: approved, lgtm, ok-to-test, size/S

#1694 Change the cases at a few places in help message
  pkg/config/config.go
  pkg/odo/cli/config/config.go
Labels: approved, lgtm, size/S

#1690 Removes unnecessary logging flags
  docs/logging.adoc
  pkg/odo/cli/cli.go
Labels: approved, lgtm, size/S

#1697 Print appropriate parameter name when trying to set its value again
  pkg/odo/cli/preference/set.go
Labels: approved, lgtm, size/XS

#1691 Change UI Language for Component Prompt
  pkg/odo/cli/component/ui/ui.go
Labels: approved, lgtm, ok-to-test, size/S

#1701 Update Deploying an application using odo Section and Fixing Broken Links
  README.adoc
Labels: approved, lgtm, ok-to-test, size/M

#1710 resolved the consecutive project deletion issue
  pkg/occlient/occlient.go
  pkg/odo/cli/project/delete.go
  tests/integration/generic_test.go
Labels: approved, lgtm, size/M

#1656 Fix CLI reference page
  docs/cli-reference.adoc
Labels: approved, lgtm, size/L

#1652 Fixes issue of odo login not working correctly
  pkg/auth/login.go
  pkg/log/status.go
Labels: approved, lgtm, size/M

#1703 Making pre-test setup script check api server stability
  scripts/configure-installer-tests-cluster.sh
Labels: approved, lgtm, size/S

#1714 Don't check for config file to list components and services
  pkg/odo/genericclioptions/context.go
Labels: approved, lgtm, size/XS

#1684 Deploy fix
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/occlient/templates.go
  pkg/occlient/utils.go
Labels: approved, lgtm, size/L

#1724 Remove references to Mattermost chat
  README.adoc
  docs/img/mattermost.svg
Labels: approved, lgtm, size/XS

#1727 resolved typo in the tests
  tests/integration/integration_suite_test.go
Labels: approved, lgtm, size/XS

#1716 Update the CLI reference doc generation script
  cmd/cli-doc/cli-doc.go
  docs/cli-reference.adoc
  pkg/odo/cli/cli.go
Labels: approved, lgtm, size/XL

#1719 use more robust project.exists function
  pkg/occlient/occlient.go
  pkg/project/project.go
  tests/integration/component.go
Labels: approved, lgtm, size/M

#1705 Fixes invalid paths when using rsync with Windows
  pkg/component/component.go
  pkg/occlient/occlient.go
Labels: approved, lgtm, os/windows, size/M

#1731 added --all flag for component deletion and test for it
  pkg/config/config.go
  pkg/odo/cli/component/delete.go
  tests/integration/component.go
Labels: approved, lgtm, size/M

#1732 Add dharmit to OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#1547 Storage workflow
  .travis.yml
  Makefile
  pkg/component/component.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/storage.go
  pkg/config/storage_test.go
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/occlient/volumes.go
  pkg/occlient/volumes_test.go
  pkg/odo/cli/application/application.go
  pkg/odo/cli/component/component.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/project/project.go
  pkg/odo/cli/storage/create.go
  pkg/odo/cli/storage/delete.go
  pkg/odo/cli/storage/list.go
  pkg/odo/cli/storage/storage.go
  pkg/odo/util/cmdutils.go
  pkg/odo/util/completion/completionhandlers.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  pkg/testingutil/deploymentconfigs.go
  pkg/testingutil/pvcs.go
  scripts/openshiftci-presubmit-e2e.sh
  tests/helper/helper_oc.go
  tests/integration/json_test.go
  tests/integration/storage_test.go
  tests/integration/watch_test.go
Labels: approved, lgtm, size/XXL

#1734 Hide "component get" command
  pkg/odo/cli/cli.go
  pkg/odo/cli/component/get.go
Labels: approved, lgtm, size/S

#1741 resolved the broken link to .wwhrd.yml
  docs/development.adoc
Labels: approved, lgtm, size/XS

#1738 Uncommenting git component push issue
  tests/integration/generic_test.go
  tests/integration/java_test.go
  tests/integration/json_test.go
Labels: approved, lgtm, size/S

#1735 Format and synchronize README and installation page
  README.adoc
  docs/installation.adoc
Labels: approved, lgtm, size/L

#1711 Fixes ignore behaviour with Windows
  pkg/component/watch.go
  pkg/util/util.go
Labels: approved, lgtm, os/windows, size/S

#1728 correct output for `odo app delete`
  pkg/application/application.go
  pkg/odo/cli/application/delete.go
  tests/integration/component.go
Labels: approved, lgtm, size/S

#1747 resolved development docs and bump-version.sh script
  Makefile
  docs/development.adoc
  scripts/bump-version.sh
Labels: approved, lgtm, size/S

#1746 Release v1.0.0-beta2
  docs/cli-reference.adoc
  pkg/odo/cli/version/version.go
  scripts/install.sh
Labels: approved, lgtm, release-note, size/M

#1751 bump VERSION file to v1.0.0-beta2
  build/VERSION
Labels: approved, lgtm, size/XS

#1744 Update link test as per new test flow
  tests/helper/helper_oc.go
  tests/integration/link_test.go
Labels: approved, lgtm, size/L

#1748 developement.adoc: update brew packaging guide
  docs/development.adoc
Labels: approved, lgtm, size/S

#1753 Adding test spec for catalog list without comp dir
  tests/integration/generic_test.go
Labels: approved, lgtm, size/S

#1763 Add "shortcut" section to odo help
  pkg/odo/cli/application/application.go
  pkg/odo/cli/catalog/catalog.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/component/component.go
  pkg/odo/cli/config/config.go
  pkg/odo/cli/preference/preference.go
  pkg/odo/cli/project/project.go
  pkg/odo/cli/service/service.go
  pkg/odo/cli/storage/storage.go
  pkg/odo/cli/url/url.go
Labels: approved, lgtm, size/S

#1757 Uncommenting/restructuring test step in source test
  tests/helper/odo_utils.go
  tests/integration/java_test.go
  tests/integration/json_test.go
  tests/integration/service_test.go
  tests/integration/source_test.go
Labels: approved, lgtm, size/M

#1765 create the preference file lazily
  pkg/preference/preference.go
  pkg/preference/preference_test.go
Labels: approved, lgtm, size/S

#1754 Added v4 log level to project creation
  tests/helper/odo_utils.go
Labels: approved, lgtm, size/XS

#1740 Fixes the issue of 4 deployments for git components
  pkg/component/component.go
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/occlient/templates.go
  pkg/odo/cli/component/push.go
  tests/helper/helper_oc.go
  tests/integration/component.go
Labels: approved, lgtm, size/XL

#1767 Remove multiple "odo app list" entries
  pkg/application/application.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, lgtm, size/M
