Repository redhat-developer/odo, pull requests merged in 2019-06, with the labels that each got.

#1785 fix infinite wait in CreateNewProject
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
Labels: approved, lgtm, size/M

#1787 Modifies TestRemoveDuplicate to remove flake
  pkg/util/util_test.go
Labels: approved, lgtm, size/XS

#1764 Fixes bug of path directories not working correctly with interactive UI
  pkg/component/component.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/ui/ui.go
Labels: approved, lgtm, size/M

#1758 Use local config info for viewing odo config
  pkg/odo/cli/config/view.go
  tests/integration/config_test.go
Labels: approved, lgtm, size/S

#1774 Improve URL creation and deletion UX / UI output
  pkg/catalog/catalog.go
  pkg/component/component.go
  pkg/config/config.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/delete.go
Labels: approved, lgtm, size/L

#1784 Renamed global preference file to preference.yaml from config.yaml
  pkg/preference/preference.go
Labels: approved, lgtm, release-note-action-required, size/XS

#1779 Modifies odo app commands to work outside a directory
  .travis.yml
  Makefile
  pkg/odo/cli/application/application.go
  pkg/odo/cli/application/delete.go
  pkg/odo/cli/application/describe.go
  pkg/odo/cli/application/list.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/util/cmdutils.go
  scripts/openshiftci-presubmit-e2e.sh
  tests/integration/cmd_app_test.go
Labels: approved, lgtm, size/L

#1795 Adds a timer to UI / UX output
  pkg/log/fidget/spinner.go
  pkg/log/status.go
Labels: approved, lgtm, size/S

#1792 Adds the functionality of running some component commands outside a odo directory
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/describe.go
  pkg/odo/cli/component/list.go
  pkg/odo/genericclioptions/context.go
  tests/integration/component.go
Labels: approved, lgtm, size/M

#1771 Added path flag and respective logic
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/types.go
  pkg/odo/cli/component/list.go
  pkg/odo/genericclioptions/context.go
  tests/integration/json_test.go
Labels: approved, lgtm, size/L

#1807 Uncommenting spec in java test file
  tests/integration/java_test.go
  tests/integration/service_test.go
  tests/integration/source_test.go
Labels: approved, lgtm, size/S

#1796 Comments out the update e2e tests
  tests/integration/component.go
Labels: approved, lgtm, size/L

#1759 Running spec parallelly for clean test template
  .travis.yml
  Makefile
  scripts/openshiftci-presubmit-e2e.sh
  tests/template/template_cleantest_test.go
Labels: approved, lgtm, size/S

#1802 Rename install.sh to installer.sh and Add Uninstall
  README.adoc
  scripts/bump-version.sh
  scripts/install.sh
  scripts/installer.sh
  scripts/test-install.sh
  scripts/test-installer.sh
Labels: approved, lgtm, ok-to-test, size/XL

#1814 Fixes links to the install script
  .travis.yml
  README.adoc
  docs/development.adoc
  pkg/notify/notify.go
Labels: approved, lgtm, size/XS

#1812 Bumps version to v1.0.0-beta3
  docs/cli-reference.adoc
  pkg/odo/cli/version/version.go
  scripts/installer.sh
Labels: approved, lgtm, size/XS

#1820 Bumps the version in build/version
  build/VERSION
Labels: approved, lgtm, size/XS

#1815 Don't allow user to create a URL name longer than 63 characters
  pkg/odo/cli/url/create.go
  tests/integration/generic_test.go
Labels: approved, lgtm, size/S

#1809 List apps deployed via servers within odo app list
  pkg/application/application.go
  pkg/component/component.go
  pkg/log/status.go
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
Labels: approved, lgtm, size/L

#1797 Run component test in parallel
  Makefile
  docs/development.adoc
  tests/integration/cmd_cmp_sub_test.go
  tests/integration/cmd_cmp_test.go
  tests/integration/component.go
Labels: approved, lgtm, size/L

#1842 resolved various typos
  docs/development.adoc
  docs/proposals/odo-config-file.md
Labels: approved, lgtm, size/XS

#1804 Run app command test in parallel
  .travis.yml
  Makefile
  docs/development.adoc
  scripts/openshiftci-presubmit-e2e.sh
  tests/integration/cmd_app_test.go
  tests/integration/json_test.go
Labels: approved, lgtm, size/L

#1816 Run storage command test in parallel
  .travis.yml
  Makefile
  docs/development.adoc
  scripts/openshiftci-presubmit-e2e.sh
  tests/helper/helper_oc.go
  tests/integration/cmd_storage_test.go
  tests/integration/json_test.go
  tests/integration/storage_test.go
Labels: approved, lgtm, size/L

#1833 Change Odo References to odo
  docs/cli-reference.adoc
  pkg/odo/cli/cli.go
  pkg/odo/cli/component/common_link.go
  pkg/odo/cli/config/set.go
  pkg/odo/cli/config/unset.go
  pkg/odo/cli/preference/preference.go
  pkg/odo/cli/preference/set.go
  pkg/odo/cli/preference/unset.go
  pkg/odo/cli/utils/terminal.go
  pkg/odo/cli/utils/utils.go
  pkg/odo/cli/version/version.go
  site/README.adoc
Labels: approved, lgtm, ok-to-test, size/L

#1826 Run watch command test in parallel
  Makefile
  docs/development.adoc
  tests/integration/cmd_watch_test.go
  tests/integration/watch_test.go
Labels: approved, lgtm, size/L

#1789 Run json format test in parallel
  Makefile
  docs/development.adoc
  tests/integration/json_test.go
Labels: approved, lgtm, size/M

#1824 Switch to using string-based formatting for time elapsed
  pkg/log/fidget/spinner.go
  pkg/log/status.go
Labels: approved, lgtm, size/S

#1841 Add benchmark tests
  Makefile
  pkg/catalog/catalog.go
  scripts/openshiftci-presubmit-benchmark.sh
  tests/benchmark/basic_benchmark.go
  tests/benchmark/benchmark_test.go
  tests/helper/helper_filesystem.go
  tests/helper/reporter/httpMeasurementReporter.go
Labels: approved, lgtm, size/L

#1857 Fix example link
  pkg/odo/cli/component/create.go
Labels: approved, lgtm, size/XS

#1858 Fix weird subcommand missing output
  pkg/odo/cli/cli.go
Labels: approved, lgtm, size/XS

#1839 Run service test specs in parallel
  Makefile
  docs/development.adoc
  tests/integration/service_test.go
Labels: approved, lgtm, size/M

#1856 Add capitalization to error messages
  pkg/odo/genericclioptions/context.go
  pkg/odo/util/cmdutils.go
Labels: approved, lgtm, size/XS

#1862 Small typo fix in helper scripts in test
  tests/helper/helper_filesystem.go
Labels: approved, lgtm, size/XS

#1853 Drop warning message for Service Catalog
  pkg/application/application.go
Labels: approved, lgtm, size/XS

#1829 Run preference and config command test in parallel
  Makefile
  docs/development.adoc
  tests/integration/cmd_pref_config_test.go
Labels: approved, lgtm, size/L

#1850 Remove connection checks for `odo config`
  pkg/odo/cli/config/set.go
  pkg/odo/cli/config/unset.go
  tests/integration/cmd_pref_config_test.go
Labels: approved, lgtm, size/S

#1743 Updating url to indicate if url is present or absent in config and cluster respectively
  .travis.yml
  Makefile
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/delete.go
  pkg/odo/cli/url/list.go
  pkg/odo/genericclioptions/printtemplates/messages.go
  pkg/odo/genericclioptions/printtemplates/messages_test.go
  scripts/openshiftci-presubmit-e2e.sh
  tests/helper/helper_generic.go
  tests/integration/generic_test.go
  tests/integration/url_test.go
Labels: approved, lgtm, size/L

#1873 Removed broken links and added adapter links in readme
  README.adoc
Labels: approved, lgtm, size/S
