Repository redhat-developer/odo, pull requests merged in 2019-04, with the labels that each got.

#1517 Various e2e fixes for OpenShiftCI
  pkg/occlient/occlient.go
  scripts/configure-installer-tests-cluster.sh
  tests/e2e/component.go
  tests/e2e/e2e.go
  tests/e2e/e2e_test.go
  tests/e2e/java_test.go
  tests/e2e/json_test.go
  tests/e2e/service_test.go
  tests/e2e/source_test.go
  tests/e2e/utils.go
  tests/e2e/watch_test.go
Labels: approved, lgtm, size/M

#1533 Odo pr review process
  docs/development.md
Labels: approved, lgtm, size/S

#1497 Add .odoignore documentation
  docs/getting-started.md
Labels: approved, lgtm, size/S

#1525 Review getting started document
  docs/getting-started.md
Labels: approved, lgtm, size/L

#1370 Added machine readable struct for `odo project list`
  pkg/odo/cli/project/list.go
  pkg/odo/cli/url/list.go
  pkg/odo/util/completion/completionhandlers.go
  pkg/project/project.go
  pkg/project/types.go
  tests/e2e/json_test.go
Labels: approved, lgtm, size/L

#1541 Fix issue of 2 deployments on one odo push
  pkg/occlient/templates.go
Labels: approved, lgtm, size/XS

#1536 Adding .exe extension for make bin on Windows
  Makefile
Labels: approved, lgtm, size/XS

#1538 Update OpenShift version based on what minishift supports
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#1556 Removing extra backticks
  README.md
Labels: approved, lgtm, size/XS

#1446 Implement new odo workflow for: odo watch
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/component/watch.go
  pkg/odo/cli/utils/utils.go
  pkg/odo/genericclioptions/context.go
Labels: approved, lgtm, size/L

#1555 Review of Installation doc
  docs/installation.adoc
  docs/installation.md
Labels: approved, lgtm, size/L

#1562 added env variables from config to create and update component
  pkg/component/component.go
  pkg/config/env_var.go
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/odo/cli/component/create.go
Labels: approved, lgtm, size/M

#1532 Short circuiting invalid context file in context.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/occlient/occlient_test.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/component/update.go
  pkg/odo/cli/component/watch.go
  pkg/odo/cli/config/set.go
  pkg/odo/cli/config/unset.go
  pkg/odo/cli/config/view.go
  pkg/odo/genericclioptions/context.go
  tests/e2e/component.go
  tests/e2e/e2e_test.go
Labels: approved, lgtm, size/L

#1564 Typo in documentation issue templates
  .github/ISSUE_TEMPLATE/Documentation.md
Labels: approved, lgtm, size/XS

#1554 Adding context flag function and updating all components to use it
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/describe.go
  pkg/odo/cli/component/get.go
  pkg/odo/cli/component/link.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/component/log.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/component/unlink.go
  pkg/odo/cli/component/update.go
  pkg/odo/cli/component/watch.go
  pkg/odo/genericclioptions/add_flags.go
Labels: approved, lgtm, size/M

#1516 Scripts to run on OpenShift CI
  Makefile
  scripts/openshiftci-presubmit-e2e.sh
  scripts/openshiftci-presubmit-unittests.sh
Labels: approved, lgtm, size/M

#1529 Add `--config` and `--source` flags to push
  Makefile
  pkg/odo/cli/component/push.go
  tests/e2e/component.go
  tests/e2e/helper/helper_oc.go
  tests/e2e/helper/helper_run.go
  tests/e2e/source_test.go
Labels: approved, lgtm, size/L

#1566 Readme conversion from .md to .adoc
  README.adoc
  README.md
Labels: approved, lgtm, size/L

#1571 Converted 7 docs to .adoc
  docs/ci-reference.adoc
  docs/cli-reference.adoc
  docs/completion-architecture.adoc
  docs/examples.adoc
  docs/logging.adoc
  docs/tdd-workflow.adoc
  docs/validation-architecture.adoc
Labels: approved, lgtm, size/XXL

#1572 Adding the GSG adoc version and changes to the workflow.
  docs/getting-started.adoc
Labels: approved, lgtm, size/L

#1574 Changed `odo` to OpenShift Do in headings/titles…
  docs/installation.adoc
Labels: approved, lgtm, size/M

#1569 Increases checks when deploying DeploymentConfig
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/occlient/templates.go
  pkg/occlient/utils.go
  tests/e2e/e2e_test.go
Labels: approved, lgtm, size/L

#1577 openshiftci-presubmit-unittests: get gox before attemting make cross
  Makefile
  scripts/openshiftci-presubmit-unittests.sh
Labels: approved, lgtm, size/XS

#1579 OWNERS file for gh-pages
  OWNERS
Labels: size/S

#1568 Development guide review and adoc conversion
  docs/development.adoc
Labels: approved, lgtm, size/L

#1582 typo in travis.yml
  .travis.yml
Labels: approved, lgtm, size/XS

#1586 remove inactive people from OWNERS
  OWNERS
  pkg/catalog/OWNERS
  pkg/occlient/OWNERS
  pkg/odo/OWNERS
  pkg/secret/OWNERS
  pkg/service/OWNERS
Labels: approved, lgtm, size/M

#1559 e2e test: core scenario for beta
  Makefile
  scripts/openshiftci-presubmit-e2e-scenarios.sh
  tests/e2escenarios/core_beta_flow.go
  tests/e2escenarios/e2escenarios_test.go
  tests/e2escenarios/examples/source/openjdk/pom.xml
  tests/e2escenarios/examples/source/openjdk/src/main/java/Application.java
  tests/e2escenarios/examples/source/openjdk/src/main/java/MessageProducer.java
  tests/e2escenarios/helper/helper_filesystem.go
  tests/e2escenarios/helper/helper_generic.go
  tests/e2escenarios/helper/helper_http.go
  tests/e2escenarios/helper/helper_oc.go
  tests/e2escenarios/helper/helper_run.go
Labels: approved, lgtm, size/XL

#1527 added context in config
  pkg/odo/cli/config/set.go
  pkg/odo/cli/config/unset.go
  pkg/odo/cli/config/view.go
  pkg/odo/genericclioptions/add_flags.go
  tests/e2e/e2e_test.go
  tests/e2e/utils.go
Labels: approved, lgtm, ok-to-test, priority/High, size/L

#1519 odo url new flow
  pkg/component/component.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/delete.go
  pkg/odo/cli/url/list.go
  pkg/url/url.go
  pkg/url/url_test.go
  tests/e2e/component.go
  tests/e2e/e2e_test.go
  tests/e2e/java_test.go
  tests/e2e/json_test.go
  tests/e2e/source_test.go
  tests/e2e/utils.go
Labels: approved, lgtm, priority/High, size/L

#1575 Lang. and other fixes for homepage
  _layouts/index.html
Labels: approved, lgtm, ok-to-test, size/M

#1550 Fixed empty `odo url list -o json`
  pkg/odo/cli/url/list.go
  tests/e2e/json_test.go
Labels: approved, lgtm, size/M

#1540 Fixes the issue of storage unmounting during odo push
  pkg/occlient/occlient.go
Labels: approved, lgtm, size/M

#1608 Logic fix for OpenShift depoymentconfig triggers
  pkg/occlient/utils.go
Labels: approved, lgtm, size/XS

#1607 Copy over EnvFrom across component updates
  pkg/occlient/occlient.go
Labels: approved, lgtm, size/XS

#1591 Fixes typo from 'wil' to 'will' in various files
  README.adoc
  docs/cli-reference.adoc
  pkg/odo/cli/component/create.go
  pkg/odo/cli/version/version.go
Labels: approved, lgtm, ok-to-test, size/XS

#1526 config behavior according to new workflow
  pkg/odo/cli/component/create.go
  tests/e2e/component.go
  tests/e2e/e2e_test.go
  tests/e2e/java_test.go
  tests/e2e/source_test.go
  tests/e2e/v2_component_test.go
Labels: approved, lgtm, priority/High, size/XXL

#1600 inform user to run odo push after odo config
  pkg/odo/cli/config/set.go
  tests/e2e/json_test.go
  tests/e2escenarios/core_beta_flow.go
  tests/e2escenarios/helper/helper_oc.go
  tests/e2escenarios/helper/helper_run.go
Labels: approved, lgtm, size/M

#1619 increase ocUpdateTimeout to 5 minutes
  pkg/occlient/occlient.go
Labels: approved, lgtm, size/XS

#1606 Create component even in new project
  pkg/odo/cli/component/push.go
  tests/e2e/component.go
Labels: approved, lgtm, size/M

#1598 uncomment and fix service tests
  scripts/oc-cluster.sh
  scripts/travis-check-pods.sh
  tests/e2e/service_test.go
Labels: approved, lgtm, size/L

#1617 used default appName as 'app'
  pkg/application/application.go
  pkg/application/application_test.go
  pkg/odo/genericclioptions/context.go
  tests/e2e/component.go
Labels: approved, lgtm, size/L

#1622 Improve project list
  pkg/odo/cli/project/list.go
  pkg/odo/util/completion/completionhandlers.go
  pkg/project/project.go
Labels: approved, lgtm, size/S

#1627 e2e test namespace cleanup
  tests/e2e/e2e_test.go
Labels: approved, lgtm, size/XS

#1601 Make local and binary file locations relative
  pkg/config/config.go
  pkg/occlient/occlient.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/push.go
  pkg/util/util.go
Labels: approved, lgtm, size/L

#1614 resolved resource limit not reflecting on unsetting
  pkg/occlient/templates.go
  tests/e2e/component.go
Labels: approved, lgtm, size/S

#1637 Updated getting started guide
  docs/getting-started.adoc
Labels: approved, lgtm, size/S

#1639 v1.0.0-beta1
  README.adoc
  docs/cli-reference.md
  pkg/odo/cli/version/version.go
  scripts/bump-version.sh
  scripts/install.sh
  tests/e2e/e2e_test.go
Labels: approved, lgtm, size/L

#1629 Improving format of commands in the main guides.
  README.adoc
  docs/development.adoc
  docs/getting-started.adoc
  docs/installation.adoc
Labels: approved, lgtm, size/M

#1640 run all test in verbose mode
  Makefile
Labels: approved, lgtm, size/M

#1644 Adds the odo website to the master branch
  .gitignore
  site/404.html
  site/CNAME
  site/Gemfile
  site/Gemfile.lock
  site/LICENSE
  site/OWNERS
  site/README.adoc
  site/_config.yml
  site/_data/menu.yml
  site/_includes/head.html
  site/_includes/header.html
  site/_includes/menu.html
  site/_includes/scripts.html
  site/_layouts/default.html
  site/_layouts/index.html
  site/build.sh
  site/css/default.css
  site/css/hljs-github.min.css
  site/css/main.css
  site/css/pilcrow.css
  site/feed.xml
  site/img/android-chrome-192x192.png
  site/img/android-chrome-512x512.png
  site/img/apple-touch-icon.png
  site/img/browserconfig.xml
  site/img/demo.gif
  site/img/favicon-16x16.png
  site/img/favicon-32x32.png
  site/img/favicon.ico
  site/img/icons/netcore.png
  site/img/icons/node.png
  site/img/icons/perl.png
  site/img/icons/php.png
  site/img/icons/python.png
  site/img/icons/ruby.png
  site/img/kubernetes.png
  site/img/logo-big.png
  site/img/logo.png
  site/img/logo.svg
  site/img/manifest.json
  site/img/minimal-jekyll.png
  site/img/mstile-150x150.png
  site/img/pattern.png
  site/img/redhat-logo.png
  site/img/safari-pinned-tab.svg
  site/img/site.webmanifest
  site/img/waves.png
  site/img/whale.gif
  site/index.md
  site/js/icons.js
  site/pre.sh
  site/serve.sh
Labels: approved, lgtm, size/XXL

#1625 use Gomega matchers for json output
  tests/e2e/json_test.go
Labels: approved, lgtm, size/M

#1645 Remove markdown documentation and disable synchronization script
  .travis.yml
  docs/ci-reference.md
  docs/cli-reference.md
  docs/completion-architecture.md
  docs/development.md
  docs/examples.md
  docs/getting-started.md
  docs/installation.md
  docs/logging.md
  docs/tdd-workflow.md
  docs/validation-architecture.md
Labels: approved, lgtm, size/XXL

#1658 Adds spinner to "Applying component settings" / ApplyConfig function
  pkg/component/component.go
Labels: approved, lgtm, size/XS

#1657 Remove leftover logging
  pkg/odo/cli/component/create.go
Labels: approved, lgtm, size/XS

#1659 Add show parameter to `odo watch`
  pkg/component/watch.go
  pkg/odo/cli/component/watch.go
Labels: approved, lgtm, size/XS

#1665 OWNERS files cleanup
  OWNERS
  pkg/application/OWNERS
  pkg/auth/OWNERS
  pkg/component/OWNERS
  pkg/config/OWNERS
  pkg/odo/OWNERS
  pkg/util/OWNERS
  scripts/OWNERS
  site/OWNERS
Labels: approved, lgtm, size/M

#1666 Fix typo with wildfly in create command and docs
  docs/cli-reference.adoc
  pkg/odo/cli/component/create.go
Labels: approved, lgtm, ok-to-test, size/XS
