Repository redhat-developer/odo, pull requests merged in 2020-11, with the labels that each got.

#4180 Update required s2i imagestreams for nodejs and java on IBM Z.
  scripts/configure-installer-tests-cluster-s390x.sh
Labels: approved, area/System-PZ, kind/bug, lgtm

#4182 nit: remove the 'Devfile path' log even when using --s2i in odo create --context
  pkg/odo/cli/component/create.go
Labels: approved, lgtm

#4181 Update required s2i imagestreams for nodejs and java on IBM Power
  scripts/configure-installer-tests-cluster-ppc64le.sh
Labels: approved, area/System-PZ, kind/bug, lgtm, ok-to-test

#4120 Adds subDir checkout for git components
  docs/file-reference/index.md
  pkg/devfile/parser/configurables_test.go
  pkg/devfile/parser/data/2.0.0/devfileJsonSchema200.go
  pkg/devfile/parser/data/common/types.go
  pkg/devfile/parser/parse_test.go
  pkg/devfile/parser/types_test.go
  pkg/odo/cli/component/create.go
  pkg/testingutil/filesystem/default_fs.go
  pkg/testingutil/filesystem/fake_fs.go
  pkg/testingutil/filesystem/filesystem.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/examples/source/devfiles/nodejs/devfile-with-subDir.yaml
  tests/examples/source/devfiles/springboot/devfile-with-subDir.yaml
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, lgtm

#4149 check if devfile exist in the context folder instead of working directory
  pkg/component/component_full_description.go
  pkg/odo/cli/component/component.go
  tests/integration/component.go
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, kind/bug, lgtm

#4070 Adding ubi8/nodejs-12 images as supported
  pkg/catalog/catalog.go
  pkg/devfile/adapters/common/utils.go
  pkg/util/util.go
  scripts/configure-installer-tests-cluster.sh
  tests/e2escenarios/e2e_images_test.go
  tests/image-streams/supported-nodejs.json
Labels: approved, kind/bug, kind/feature, lgtm

#4139 Fix absolute path for test on macos
  tests/integration/component.go
Labels: approved, kind/failing-test, lgtm

#4134 Refactor & cleanup kclient generators code before migrating to devfile/parser
  pkg/component/component_full_description.go
  pkg/devfile/adapters/common/types.go
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/common/utils_test.go
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/docker/utils/utils.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/component/status_test.go
  pkg/devfile/adapters/kubernetes/storage/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils_test.go
  pkg/devfile/validate/generic/components.go
  pkg/devfile/validate/generic/components_test.go
  pkg/devfile/validate/generic/errors.go
  pkg/kclient/deployments_test.go
  pkg/kclient/fake/ingress.go
  pkg/kclient/generator/generators.go
  pkg/kclient/generator/generators_test.go
  pkg/kclient/generator/utils.go
  pkg/kclient/generator/utils_test.go
  pkg/kclient/generators.go
  pkg/kclient/generators_test.go
  pkg/kclient/ingress_test.go
  pkg/kclient/kclient.go
  pkg/kclient/secrets.go
  pkg/kclient/secrets_test.go
  pkg/kclient/services_test.go
  pkg/kclient/supervisord.go
  pkg/kclient/volumes.go
  pkg/kclient/volumes_test.go
  pkg/occlient/occlient.go
  pkg/occlient/templates.go
  pkg/odo/cli/component/common_link.go
  pkg/odo/cli/component/status.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/list.go
  pkg/sync/adapter.go
  pkg/sync/adapter_test.go
  pkg/testingutil/devfile.go
  pkg/url/status_test.go
  pkg/url/url.go
  pkg/url/url_test.go
Labels: approved, kind/cleanup, kind/code-refactoring, lgtm

#4193 Ignore Configmap mounted in DeploymentConfig
  pkg/occlient/occlient.go
  pkg/storage/storage.go
Labels: approved, kind/bug, lgtm, ok-to-test

#4189 resolve the panic on odo list when the project contains non-odo DCs
  pkg/component/component.go
Labels: approved, kind/bug, lgtm

#4215 Update configure-installer-tests-cluster-s390x to support nodejs12 e2e test
  scripts/configure-installer-tests-cluster-s390x.sh
Labels: approved, area/System-PZ, kind/bug, kind/feature, lgtm

#4207 Use example from the repo instead of downloading it
  tests/examples/source/web-nodejs-sample/.gitignore
  tests/examples/source/web-nodejs-sample/app/app.js
  tests/examples/source/web-nodejs-sample/package-lock.json
  tests/examples/source/web-nodejs-sample/package.json
  tests/integration/devfile/cmd_devfile_log_test.go
Labels: approved, kind/cleanup, lgtm

#4225 resolve .kube/config.lock: file exists flake
  tests/helper/helper_generic.go
Labels: approved, kind/failing-test, lgtm

#4224 Add Roadmap for the next 3 milestones in the Readme
  README.adoc
Labels: approved, lgtm

#4212 Remove pushcommand from envinfo
  pkg/envinfo/envinfo.go
  pkg/envinfo/envinfo_test.go
Labels: approved, lgtm

#4211 Moves project related code from occlient.go to a new file
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/occlient/projects.go
  pkg/occlient/projects_test.go
  pkg/odo/util/completion/completionhandlers.go
  pkg/project/project.go
Labels: approved, kind/cleanup, kind/code-refactoring, lgtm

#4140 Document Operator installation on minikube
  docs/public/operator-hub.adoc
  docs/public/operators-on-minikube.adoc
Labels: approved, kind/documentation, lgtm

#4179 #3377 adding odo devfile support test
  .travis.yml
  Makefile
  tests/e2escenarios/e2e_devfile_test.go
Labels: approved, lgtm

#4202 List only installed Operators; some refactor
  pkg/catalog/catalog.go
  pkg/odo/cli/catalog/list/services.go
  pkg/odo/cli/component/link.go
  pkg/odo/cli/component/unlink.go
  pkg/odo/cli/service/create.go
  pkg/odo/cli/service/delete.go
  pkg/odo/cli/service/list.go
  pkg/odo/util/cmdutils.go
  pkg/service/service.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/bug, kind/code-refactoring, lgtm

#4214 Junit test report generation
  scripts/openshiftci-periodic-tests.sh
  scripts/openshiftci-presubmit-all-tests.sh
  tests/e2escenarios/e2escenarios_suite_test.go
  tests/helper/reporter/junitReporter.go
  tests/integration/debug/debug_suite_test.go
  tests/integration/devfile/debug/debug_suite_test.go
  tests/integration/devfile/devfile_suite_test.go
  tests/integration/devfile/docker/docker_suite_test.go
  tests/integration/integration_suite_test.go
  tests/integration/loginlogout/loginlogout_suite_test.go
  tests/integration/project/project_suite_test.go
  tests/integration/servicecatalog/servicecatalog_suite_test.go
Labels: approved, lgtm

#4229 Update configure-installer-tests-cluster-ppc64le to support nodejs12 e2e test
  scripts/configure-installer-tests-cluster-ppc64le.sh
Labels: approved, area/System-PZ, kind/bug, kind/feature, lgtm, ok-to-test

#4248 Increase timeout for Operator Hub tests
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/flake, lgtm

#4246 Update
  chosen-docs/openshift-docs/sample-applications.md
  scripts/sync.sh
Labels: approved, kind/bug, lgtm

#4231 Move functions to separate files in context package
  pkg/odo/genericclioptions/add_flags.go
  pkg/odo/genericclioptions/client.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/genericclioptions/context_flags.go
  pkg/odo/genericclioptions/flag.go
  pkg/odo/genericclioptions/localprovider.go
  pkg/odo/genericclioptions/resolve.go
  pkg/odo/genericclioptions/util.go
Labels: approved, kind/code-refactoring, lgtm

#4226 Refactors pvc code in occlient and kclient
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/storage/utils.go
  pkg/devfile/adapters/kubernetes/storage/utils_test.go
  pkg/kclient/volumes.go
  pkg/kclient/volumes_test.go
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/occlient/volumes.go
  pkg/occlient/volumes_test.go
  pkg/storage/storage.go
Labels: approved, kind/cleanup, kind/code-refactoring, lgtm

#4194 Splitting configure-installer-test-cluster into a library.
  scripts/configure-cluster/common/auth.sh
  scripts/configure-cluster/common/setup-operators.sh
  scripts/configure-installer-tests-cluster-ppc64le.sh
  scripts/configure-installer-tests-cluster-s390x.sh
  scripts/configure-installer-tests-cluster.sh
  scripts/openshiftci-periodic-tests.sh
  scripts/openshiftci-presubmit-all-tests.sh
  tests/integration/loginlogout/cmd_login_logout_test.go
Labels: approved, lgtm

#4251 Bumping odo version v2.0.1 -> v2.0.2
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#4213 Moves route related code from occlient.go to a new file
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/occlient/routes.go
  pkg/occlient/routes_test.go
Labels: approved, kind/cleanup, kind/code-refactoring, lgtm

#4252 add aditi as approver in top level OWNERS file
  OWNERS
Labels: approved, lgtm

#4206 Adding the latest java image ubi8/openjdk-11 in odo supported list
  pkg/catalog/catalog.go
  pkg/devfile/adapters/common/utils.go
  scripts/configure-installer-tests-cluster.sh
  tests/e2escenarios/e2e_images_test.go
Labels: approved, kind/failing-test, kind/feature, lgtm

#4177 remove duplicate list and refactor
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/devfile_component.go
  pkg/component/pushed_component.go
  pkg/component/types.go
  pkg/odo/cli/component/list.go
  pkg/odo/util/completion/completionhandlers.go
  pkg/testingutil/deploymentconfigs.go
  pkg/testingutil/deployments.go
  pkg/url/url.go
  tests/helper/helper_generic.go
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, kind/bug, kind/cleanup, lgtm

#4258 Add Tomas, Aditi and Mrinal to owners
  OWNERS
Labels: approved, lgtm

#4249 Add 'Operators on minikube' doc and update other docs
  chosen-docs/upstream/operators-on-minikube.md
  docs/creating-a-multicomponent-application-with-odo.md
  docs/creating-a-single-component-application-with-odo.md
  docs/creating-an-application-with-a-database.md
  docs/odo-architecture.md
  docs/operator-hub.md
  docs/operators-on-minikube.md
  docs/sample-applications.md
  file-reference/index.html
  index.md
  slate/source/index.html.md
Labels: approved, kind/documentation, lgtm

#4250 Refactors, cleans and moves some resources to the new files.
  pkg/component/component.go
  pkg/component/component_full_description.go
  pkg/component/pushed_component.go
  pkg/debug/portforward.go
  pkg/kclient/events.go
  pkg/kclient/events_test.go
  pkg/kclient/pods.go
  pkg/kclient/pods_test.go
  pkg/kclient/secrets.go
  pkg/kclient/secrets_test.go
  pkg/kclient/services.go
  pkg/kclient/services_test.go
  pkg/occlient/deploymentConfigs.go
  pkg/occlient/deploymentConfigs_test.go
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/occlient/pods.go
  pkg/occlient/utils.go
  pkg/odo/cli/component/common_link.go
  pkg/odo/cli/service/create.go
  pkg/odo/util/cmdutils.go
  pkg/secret/secret.go
  pkg/secret/secret_test.go
  pkg/service/service.go
  pkg/storage/storage.go
  pkg/testingutil/services.go
Labels: approved, kind/cleanup, kind/code-refactoring, lgtm

#4254 add json output for odo env view
  pkg/envinfo/envinfo.go
  pkg/envinfo/local_config_provider_mocks.go
  pkg/odo/cli/env/view.go
Labels: approved, kind/bug, lgtm

#4264 resolve need for image stream tags to be in order in catalog list
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
Labels: approved, lgtm

#4263 Use the generators from devfile/library
  go.mod
  go.sum
  pkg/component/component_full_description.go
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/docker/utils/utils.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/storage/utils.go
  pkg/kclient/deployments.go
  pkg/kclient/deployments_test.go
  pkg/kclient/fake/ingress.go
  pkg/kclient/generator/generators.go
  pkg/kclient/generator/generators_test.go
  pkg/kclient/generator/utils.go
  pkg/kclient/generator/utils_test.go
  pkg/kclient/ingress.go
  pkg/kclient/ingress_test.go
  pkg/kclient/services.go
  pkg/kclient/services_test.go
  pkg/kclient/volumes.go
  pkg/kclient/volumes_test.go
  pkg/occlient/occlient.go
  pkg/occlient/routes.go
  pkg/occlient/templates.go
  pkg/occlient/volumes.go
  pkg/odo/cli/component/common_link.go
  pkg/odo/cli/component/status.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/list.go
  pkg/sync/adapter.go
  pkg/sync/adapter_test.go
  pkg/testingutil/devfile.go
  pkg/url/status_test.go
  pkg/url/url.go
  pkg/url/url_test.go
  vendor/github.com/devfile/library/pkg/devfile/generator/generators.go
  vendor/github.com/devfile/library/pkg/devfile/generator/utils.go
  vendor/github.com/devfile/library/pkg/devfile/parse.go
  vendor/github.com/devfile/library/pkg/devfile/parser/context/apiVersion.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/helper.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/interface.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/components.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/header.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/versions.go
  vendor/modules.txt
Labels: approved, kind/cleanup, kind/code-refactoring, lgtm
