Repository redhat-developer/odo, pull requests merged in 2020-01, with the labels that each got.

#2492 extracted some common code into a function in occlient for cleanup
  pkg/occlient/occlient.go
Labels: approved, lgtm, size/M

#2281 Fix odo update
  pkg/occlient/occlient.go
  pkg/odo/cli/component/common_push.go
  pkg/odo/cli/component/update.go
  tests/integration/component.go
Labels: approved, lgtm, size/L

#2494 resolve wrong argument in errorf - use component name instead of all args
  pkg/component/component.go
Labels: approved, kind/cleanup, lgtm, size/XS

#2497 fix wwhrd licence detection
  .wwhrd.yml
Labels: approved, lgtm, size/S

#2496 update the odo init image to v1.0.2
  pkg/occlient/occlient.go
Labels: approved, lgtm, size/XS

#2458 Implement a stub kclient package for odo
  pkg/kclient/fakeclient.go
  pkg/kclient/kclient.go
  pkg/kclient/pods.go
  pkg/kclient/pods_test.go
Labels: approved, kind/feature, lgtm, ok-to-test, size/L

#2457 Verify local config after component create
  tests/helper/helper_configValidate.go
  tests/integration/component.go
Labels: approved, kind/test, lgtm, size/L

#2502 removed , from describe example for app and component
  pkg/odo/cli/application/describe.go
  pkg/odo/cli/component/describe.go
Labels: approved, kind/cleanup, lgtm, size/XS

#2504 Bump release version 1.0.2 -> 1.0.3
  Dockerfile.rhel
  pkg/version/version.go
  scripts/installer.sh
  scripts/rpm-prepare.sh
Labels: approved, lgtm, size/XS

#2499 Verify deployment config after component create with flags
  tests/helper/helper_oc.go
  tests/integration/component.go
Labels: approved, kind/test, lgtm, size/S

#2508 resolve typo in function comments
  tests/helper/helper_oc.go
Labels: approved, lgtm, size/XS

#2503 Describe services with multiple plans correctly
  pkg/service/types.go
  tests/integration/servicecatalog/cmd_service_test.go
Labels: approved, kind/bug, lgtm, size/M

#2498 Proposal for Operator Hub integration with odo
  docs/proposals/operator-hub.md
Labels: approved, kind/design, kind/feature, lgtm, size/L

#2505 fix git commit in odo version
  Makefile
Labels: approved, lgtm, size/XS

#2506 Fixed unit test for GetPVCFromName with extra validation
  pkg/occlient/occlient_test.go
Labels: approved, kind/bug, lgtm, size/S

#2515 added check for conflicting flags
  pkg/odo/genericclioptions/runnable.go
  tests/integration/cmd_link_unlink_test.go
  tests/integration/component.go
  tests/integration/servicecatalog/cmd_link_unlink_test.go
  tests/integration/servicecatalog/cmd_service_test.go
Labels: approved, lgtm, size/M

#2524 Resolved platfrom specific file separator in test
  tests/integration/cmd_push_test.go
Labels: approved, kind/bug, kind/test, lgtm, size/S

#2521 Bumping version v1.0.3 -> v1.1.0
  Dockerfile.rhel
  pkg/version/version.go
  scripts/installer.sh
  scripts/rpm-prepare.sh
Labels: approved, lgtm, size/XS

#2522 add test for java component to verify reflection of deleted files
  tests/examples/source/openjdk/src/main/java/AnotherMessageProducer.java
  tests/helper/helper_oc.go
  tests/integration/cmd_push_test.go
Labels: approved, kind/test, lgtm, size/M

#2501 Validation for empty values in pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
Labels: approved, kind/feature, kind/test, lgtm, size/S

#2526 Update VERSION to 1.0.3
  build/VERSION
Labels: approved, lgtm, size/XS

#2531 Updating build/VERSION to 1.1.0
  build/VERSION
Labels: approved, lgtm, size/XS

#2535 issue template: basic starting template for user story
  .github/ISSUE_TEMPLATE/UserStory.md
Labels: approved, lgtm, size/S

#2509 Add kclient functions for creating deployments
  pkg/kclient/deployments.go
  pkg/kclient/deployments_test.go
  pkg/kclient/generators.go
  pkg/kclient/generators_test.go
Labels: approved, kind/feature, lgtm, ok-to-test, size/L

#2406 Testing build fix
  pkg/component/component.go
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
Labels: approved, kind/flake, lgtm, size/M

#2552 Including testingutil package in test coverage report
  Makefile
  scripts/generate-coverage.sh
Labels: approved, kind/bug, lgtm, size/XS

#2554 Update User Story Issue template
  .github/ISSUE_TEMPLATE/UserStory.md
Labels: approved, lgtm, size/S
