Repository redhat-developer/odo, pull requests merged in 2020-09, with the labels that each got.

#3849 Applying secret to namespace for authenticated registry for ppc64le
  scripts/configure-installer-tests-cluster-ppc64le.sh
Labels: approved, area/System-PZ, area/testing, kind/bug, kind/feature, lgtm, ok-to-test

#3861 Update s2i image from library.
  scripts/configure-installer-tests-cluster-s390x.sh
Labels: approved, area/System-PZ, lgtm, ok-to-test

#3859 Fix #3838: Component is left in broken state after redeployment of the pod
  pkg/sync/adapter.go
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, kind/bug, lgtm, ok-to-test

#3764 Add registry priority to ensure registry/component display order
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  pkg/catalog/types.go
  pkg/odo/cli/catalog/list/components.go
  pkg/odo/cli/env/env.go
  pkg/odo/cli/env/env_test.go
  pkg/odo/cli/registry/list.go
Labels: approved, area/devfile, kind/bug, lgtm

#3851 Logging of Deployment and Pod statuses
  pkg/kclient/deployments.go
  pkg/kclient/pods.go
  pkg/occlient/occlient.go
Labels: approved, kind/flake, lgtm

#3874 Update regex for OdoVersion in integration/generic test.
  tests/integration/generic_test.go
Labels: approved, area/System-PZ, kind/bug, lgtm, ok-to-test

#3742 PreStart Feature PR
  docs/file-reference/index.md
  docs/public/using-devfile-lifecycle-events.adoc
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/common/utils_test.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/storage/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils_test.go
  pkg/devfile/parser/data/common/command_helper.go
  pkg/devfile/parser/data/common/command_helper_test.go
  tests/examples/source/devfiles/nodejs/devfile-with-valid-events.yaml
  tests/helper/helper_cli.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, kind/feature, lgtm

#3884 Update doc references to spring boot [skip ci]
  docs/dev/experimental-mode.adoc
  docs/public/deploying-a-devfile-using-odo.adoc
Labels: approved, kind/documentation, lgtm

#3877 Update the README to reflect Devfile
  README.adoc
  docs/public/understanding-odo.adoc
Labels: approved, kind/documentation

#3836 Implementing missing --now for component create with devfile
  pkg/odo/cli/component/create.go
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, kind/feature, lgtm

#3873 Update s2i image from library for ppc64le
  scripts/configure-installer-tests-cluster-ppc64le.sh
Labels: approved, area/System-PZ, kind/bug, lgtm, ok-to-test

#3876 Categorizes debugging information
  docs/dev/logging.adoc
  pkg/devfile/adapters/common/command.go
  pkg/devfile/adapters/common/exec.go
  pkg/devfile/adapters/common/generic.go
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/docker/storage/utils.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/storage/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/parser/context/apiVersion.go
  pkg/devfile/parser/context/content.go
  pkg/devfile/parser/context/context.go
  pkg/devfile/parser/context/schema.go
  pkg/devfile/parser/data/helper.go
  pkg/devfile/parser/parse.go
  pkg/devfile/parser/writer.go
  pkg/devfile/validate/events.go
  pkg/devfile/validate/validate.go
  pkg/kclient/deployments.go
  pkg/kclient/namespace.go
  pkg/kclient/operators.go
  pkg/kclient/pods.go
  pkg/lclient/images.go
  pkg/occlient/occlient.go
  pkg/occlient/utils.go
  pkg/occlient/volumes.go
Labels: approved, kind/cleanup, lgtm

#3895 use go get to download gosec
  Makefile
Labels: approved, kind/failing-test, lgtm

#3896 Makefile docker target clean up
  Makefile
Labels: approved, kind/cleanup, lgtm

#3881 Enable integration test for s2i to devfile conversion
  pkg/devfile/parser/context/context.go
  pkg/devfile/parser/writer.go
  pkg/occlient/utils.go
  pkg/odo/cli/utils/convert.go
  pkg/sync/adapter.go
  tests/integration/component.go
Labels: approved, lgtm

#3885 Sync operators on 4.* cluster
  scripts/setup-operators.sh
Labels: approved, kind/bug, kind/feature, lgtm

#3903 Add debug to analyze flake on travis CI
  .travis.yml
Labels: approved, kind/failing-test, kind/feature, kind/flake, lgtm

#3857 move URL info to devfile
  pkg/component/component.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils_test.go
  pkg/devfile/parser/configurables.go
  pkg/devfile/parser/data/2.0.0/devfileJsonSchema200.go
  pkg/devfile/parser/data/common/types.go
  pkg/devfile/parser/representation.go
  pkg/envinfo/envinfo.go
  pkg/odo/cli/component/common_push.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/delete.go
  pkg/odo/cli/url/describe.go
  pkg/odo/cli/url/list.go
  pkg/url/url.go
  pkg/url/url_test.go
  tests/examples/source/devfiles/nodejs/devfile-with-multiple-endpoints.yaml
  tests/integration/component.go
  tests/integration/devfile/cmd_devfile_delete_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_url_pushtarget_test.go
Labels: approved, area/devfile, area/url, lgtm

#3904 Cleaning up odo rpm spec and scripts
  rpms/openshift-odo.spec
  scripts/openshiftci-presubmit-unittests.sh
  scripts/rpm-local-build.sh
  scripts/rpm-prepare.sh
  scripts/rpm-x86_64-test.sh
Labels: approved, kind/cleanup, lgtm

#3939 Update s2i image from library for ppc64le
  scripts/configure-installer-tests-cluster-ppc64le.sh
Labels: approved, area/System-PZ, kind/bug, lgtm, ok-to-test

#3946 Fix test failure caused by updating springboot devfile
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, lgtm

#3941 Fix default registry support
  pkg/preference/preference.go
  pkg/preference/preference_test.go
Labels: approved, area/registry, kind/bug, lgtm

#3907 Implement clonePath, update source code sync location
  pkg/sync/adapter.go
  pkg/sync/adapter_test.go
  tests/examples/source/devfiles/nodejs/devfile-with-multiple-projects.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-projects.yaml
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, kind/feature, lgtm, required-for-v2

#3927 Update commands ouputs in docs.
  docs/public/community.adoc
  docs/public/deploying-a-devfile-using-odo.adoc
  docs/public/operator-hub.adoc
Labels: approved, kind/documentation, lgtm, required-for-v2

#3960 Update installation page to indicate beta-1
  docs/public/installing-odo.adoc
Labels: kind/documentation

#3799 Update springboot devfile
  tests/examples/source/devfiles/springboot/devfile-with-metadataname-foobar.yaml
  tests/examples/source/devfiles/springboot/devfile.yaml
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, lgtm

#3900 Improve URL format validation
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, area/devfile, kind/bug, lgtm

#3938 Move Operator Hub out of experimental mode
  pkg/component/component.go
  pkg/kclient/deployments.go
  pkg/occlient/occlient.go
  pkg/odo/cli/catalog/list/services.go
  pkg/odo/cli/component/common_link.go
  pkg/odo/cli/component/link.go
  pkg/odo/cli/component/unlink.go
  pkg/odo/cli/service/create.go
  pkg/odo/cli/service/delete.go
  pkg/odo/cli/service/list.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/util/cmdutils.go
  tests/integration/cmd_link_unlink_test.go
  tests/integration/operatorhub/cmd_service_test.go
  tests/integration/servicecatalog/cmd_service_test.go
Labels: approved, kind/code-refactoring, kind/feature, lgtm

#3926 Update CLI reference.
  docs/odo-cli-reference.md
Labels: approved, kind/documentation, lgtm, required-for-v2

#3898 Remove command group type init
  pkg/devfile/adapters/common/command.go
  pkg/devfile/adapters/common/command_test.go
  pkg/devfile/adapters/common/generic.go
  pkg/devfile/adapters/common/types.go
  pkg/devfile/adapters/common/utils_test.go
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/parser/data/common/types.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/watch.go
  pkg/watch/watch.go
  tests/examples/source/devfilesV1/springboot/devfile-init-without-build.yaml
  tests/examples/source/devfilesV1/springboot/devfile-init.yaml
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, kind/cleanup, lgtm

#3908 Add test-case for validating devfiles on component create
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, kind/bug, lgtm

#3928 Updates docs to use the new schema changes for commands and components
  docs/file-reference/index.md
  docs/public/debugging-using-devfile.adoc
  docs/public/using-devfile-lifecycle-events.adoc
Labels: approved, kind/documentation, lgtm, required-for-v2

#3912 Migrate devfile cmd validation to validate pkg
  pkg/devfile/adapters/common/command.go
  pkg/devfile/adapters/common/command_test.go
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/common/utils_test.go
  pkg/devfile/parse.go
  pkg/devfile/parser/data/2.0.0/components.go
  pkg/devfile/parser/data/common/component_helper.go
  pkg/devfile/parser/data/common/component_helper_test.go
  pkg/devfile/validate/commands.go
  pkg/devfile/validate/commands_test.go
  pkg/devfile/validate/errors.go
  pkg/devfile/validate/events.go
  pkg/devfile/validate/events_test.go
  pkg/devfile/validate/validate.go
  tests/examples/source/devfiles/nodejs/devfile-with-valid-events.yaml
  tests/examples/source/devfiles/nodejs/devfileCompositeInvalidComponent.yaml
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, kind/cleanup, kind/code-refactoring, lgtm

#3930 update s2i to devfile conversion as per new url design
  pkg/odo/cli/utils/convert.go
  tests/integration/component.go
Labels: approved, area/regression, kind/bug, lgtm, required-for-v2

#3942 Add mandatory file ignores when using --ignore flag
  pkg/odo/genericclioptions/context.go
  pkg/util/file_indexer.go
  tests/integration/devfile/cmd_devfile_watch_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, kind/bug, lgtm

#3958 Clarify description of the force-build flag in help text for odo push
  pkg/odo/cli/component/push.go
Labels: approved, kind/cleanup, lgtm

#3735 Fix odo log for multi containers devfile
  pkg/kclient/pods.go
  tests/integration/devfile/cmd_devfile_log_test.go
Labels: approved, lgtm

#3888 Document for s2i to devfile conversion
  docs/public/s2i-to-devfile.adoc
Labels: approved, lgtm

#3957 s2i component fix: use Config instead of ContainerConfig for port detection
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
Labels: approved, kind/bug, lgtm

#3954 Remove references to Docker support
  docs/public/community.adoc
  docs/public/deploying-a-devfile-using-odo.adoc
Labels: approved, kind/documentation, lgtm

#3977 Add instructions on how to install VSCode plugin
  docs/public/installing-odo.adoc
Labels: approved, kind/documentation, lgtm

#3984 vendor: switch location of goautoneg to github
  go.mod
  go.sum
Labels: approved, lgtm

#3981 Remove url describe command
  pkg/odo/cli/url/describe.go
  pkg/odo/cli/url/url.go
  pkg/url/url.go
  pkg/url/url_test.go
  tests/integration/cmd_url_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_url_test.go
Labels: approved, lgtm

#3949 Remove the namespace flag from odo
  pkg/odo/cli/component/common_push.go
  pkg/odo/cli/component/push.go
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, kind/cleanup, lgtm

#3951 Switch to use project instead of namespace in env
  pkg/envinfo/envinfo.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/env/env.go
  pkg/odo/cli/env/env_test.go
  pkg/odo/cli/env/set.go
  pkg/odo/cli/env/view.go
  pkg/odo/cli/utils/convert.go
  tests/integration/devfile/cmd_devfile_env_test.go
Labels: approved, kind/code-refactoring, lgtm, required-for-v2

#3963 Update odo debug --help screen
  pkg/odo/cli/debug/debug.go
  pkg/odo/cli/debug/portforward.go
Labels: approved, kind/cleanup, lgtm

#3917 add test for odo url create --context flag
  tests/integration/devfile/cmd_devfile_url_test.go
Labels: approved, area/testing, lgtm

#3950 3923- url creation with optional port flag
  pkg/odo/cli/url/create.go
  tests/integration/devfile/cmd_devfile_url_test.go
Labels: approved, area/devfile, area/url, kind/bug, lgtm

#3843 implement odo describe for devfile
  Makefile
  pkg/application/application.go
  pkg/catalog/catalog.go
  pkg/component/component.go
  pkg/component/component_full_description.go
  pkg/component/component_test.go
  pkg/component/pushed_component.go
  pkg/component/types.go
  pkg/config/config.go
  pkg/config/fakeConfig.go
  pkg/envinfo/envinfo.go
  pkg/envinfo/envinfo_test.go
  pkg/kclient/kclient.go
  pkg/kclient/operators.go
  pkg/occlient/fakeclient.go
  pkg/occlient/occlient.go
  pkg/occlient/volumes.go
  pkg/odo/cli/component/component.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/describe.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/config/set.go
  pkg/odo/cli/config/unset.go
  pkg/odo/cli/config/view.go
  pkg/odo/cli/env/set.go
  pkg/odo/cli/env/unset.go
  pkg/odo/cli/env/view.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/list.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/util/completion/completionhandlers.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  pkg/url/url.go
  pkg/url/url_test.go
  tests/integration/component.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/cmd_devfile_describe_test.go
Labels: approved, kind/bug, lgtm, required-for-v2

#3920 apiVersion test migrated to devfileV2
  pkg/devfile/parser/context/apiVersion_test.go
Labels: approved, lgtm

#3993 Prints help message based on backend cluster
  pkg/odo/cli/component/link.go
Labels: approved, kind/bug, lgtm

#4003 Adds a blog folder
  docs/blog/template.md
Labels: kind/documentation

#4010 Do not check for CSV when initializing odo link command
  pkg/odo/cli/component/link.go
  tests/integration/cmd_link_unlink_test.go
Labels: approved, kind/cleanup, kind/code-refactoring, lgtm

#3982 Document odo and Operator Hub integration
  docs/public/operator-hub.adoc
Labels: approved, kind/documentation, required-for-v2

#3964 odo list follow up implementation
  pkg/component/component.go
  pkg/component/devfile_component.go
  pkg/component/devfile_repr.go
  pkg/component/pushed_component.go
  pkg/component/types.go
  pkg/devfile/parser/configurables.go
  pkg/envinfo/envinfo.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/config/view.go
  pkg/odo/genericclioptions/context.go
  tests/integration/cmd_app_test.go
  tests/integration/component.go
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, lgtm, required-for-v2

#4021 Release 2.0.0
  Dockerfile.rhel
  scripts/rpm-prepare.sh
Labels: kind/feature

#4022 Update build version to 2.0.0
  build/VERSION
Labels: kind/feature

#3974 Update s2i image for the library change on s390x plaftorm.
  scripts/configure-installer-tests-cluster-s390x.sh
Labels: approved, area/System-PZ, kind/bug, lgtm, ok-to-test

#3989 removed some irrelevant steps from odo create and cleanup
  pkg/odo/cli/component/create.go
Labels: approved, kind/cleanup, lgtm, required-for-v2

#4012 replace unrecognised vendor dependency in go mod
  go.mod
  go.sum
Labels: approved, kind/failing-test, lgtm

#3987 3968-add more optional metadata
  pkg/devfile/parser/data/2.0.0/devfileJsonSchema200.go
  pkg/devfile/parser/data/common/types.go
Labels: approved, area/devfile, kind/bug, lgtm

#4020 Update asciinema on the README
  README.adoc
Labels: approved, kind/documentation, lgtm

#4019 Added missing s2i flag for e2e test
  tests/e2escenarios/e2e_images_test.go
Labels: approved, kind/failing-test, lgtm

#3979 Save PROJECT_SOURCE for containers mounting source
  docs/file-reference/index.md
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils_test.go
  pkg/devfile/validate/components.go
  pkg/devfile/validate/components_test.go
  pkg/devfile/validate/errors.go
  pkg/sync/adapter.go
  pkg/sync/adapter_test.go
  pkg/testingutil/devfile.go
  tests/examples/source/devfiles/nodejs/devfile-with-multiple-projects.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-projects.yaml
  tests/helper/helper_cli.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/devfile/cmd_devfile_describe_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, kind/feature, lgtm

#4006 Index Doc Update - Volume, Composite Cmd
  docs/file-reference/index.md
Labels: approved, lgtm

#3999 Fix minor docs issue in community page
  docs/public/community.adoc
Labels: approved, kind/documentation, lgtm

#4025 Fixing issues with RPMS
  rpms/openshift-odo.spec
Labels: approved, lgtm

#4026 Add blog post regarding 2.0.0 GA release
  docs/blog/2020-09-24-odo-200-ga-release.md
Labels: kind/documentation

#3972 Update the debugging documentation
  docs/public/debugging-using-devfile.adoc
Labels: kind/documentation

#4032 Update the installation page and blog
  docs/blog/2020-09-24-odo-200-ga-release.md
  docs/public/installing-odo.adoc
Labels: kind/documentation

#4034 Minor change to index title
  _config.yml
Labels: approved, lgtm

#4000 Update integration testcases and e2e testcases for ppc64le support
  scripts/configure-installer-tests-cluster-ppc64le.sh
  scripts/openshiftci-presubmit-all-tests.sh
  tests/e2escenarios/e2e_java_test.go
  tests/e2escenarios/e2e_source_test.go
Labels: approved, kind/feature, lgtm, ok-to-test

#3743 Secure starter project support
  docs/public/secure-registry.adoc
  pkg/catalog/catalog.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/registry/util/util.go
  pkg/util/util.go
Labels: approved, area/devfile, kind/feature, lgtm

#4029 make odo list's output for no components consistent
  pkg/odo/cli/component/list.go
Labels: approved, kind/bug, lgtm

#4041 Fixes sections in Opreator Hub documentation
  docs/public/operator-hub.adoc
Labels: approved, kind/documentation, lgtm

#4001 Don't allow duplicate command IDs
  pkg/devfile/validate/commands.go
  pkg/devfile/validate/commands_test.go
  pkg/devfile/validate/validate.go
Labels: approved, kind/bug, lgtm

#4040 Update doc to support installation on IBM Z for the latest version.[skip ci]
  docs/public/installing-odo.adoc
Labels: approved, area/System-PZ, kind/documentation, lgtm

#4039 Show debugger config matching default local port 5858
  docs/public/debugging-using-devfile.adoc
Labels: approved, lgtm

#4049 Update doc to support installation on IBM Power for the latest version.[skip ci]
  docs/public/installing-odo.adoc
Labels: approved, kind/documentation, lgtm, ok-to-test

#3936 Adds a document regarding the usage of storage commands.
  docs/public/using-storage.adoc
Labels: approved, kind/documentation, lgtm, required-for-v2

#4047 Refractor before and after each also few clean up in test scripts
  tests/e2escenarios/e2e_beta_test.go
  tests/e2escenarios/e2e_images_test.go
  tests/e2escenarios/e2e_java_test.go
  tests/e2escenarios/e2e_source_test.go
  tests/helper/helper_generic.go
  tests/helper/helper_oc.go
  tests/integration/cmd_app_test.go
  tests/integration/cmd_debug_test.go
  tests/integration/cmd_link_unlink_test.go
  tests/integration/cmd_pref_config_test.go
  tests/integration/cmd_push_test.go
  tests/integration/cmd_storage_test.go
  tests/integration/cmd_url_test.go
  tests/integration/cmd_watch_test.go
  tests/integration/component.go
  tests/integration/debug/cmd_debug_test.go
  tests/integration/devfile/cmd_devfile_catalog_test.go
  tests/integration/devfile/cmd_devfile_config_test.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/cmd_devfile_debug_test.go
  tests/integration/devfile/cmd_devfile_delete_test.go
  tests/integration/devfile/cmd_devfile_describe_test.go
  tests/integration/devfile/cmd_devfile_env_test.go
  tests/integration/devfile/cmd_devfile_exec_test.go
  tests/integration/devfile/cmd_devfile_log_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/cmd_devfile_registry_test.go
  tests/integration/devfile/cmd_devfile_storage_test.go
  tests/integration/devfile/cmd_devfile_test_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
  tests/integration/devfile/cmd_devfile_watch_test.go
  tests/integration/devfile/debug/cmd_devfile_debug_test.go
  tests/integration/generic_test.go
  tests/integration/project/cmd_project_test.go
  tests/integration/servicecatalog/cmd_link_unlink_test.go
  tests/integration/servicecatalog/cmd_service_test.go
Labels: approved, area/testing, kind/cleanup, kind/code-refactoring, lgtm
