Repository redhat-developer/odo, pull requests merged in 2020-04, with the labels that each got.

#2755 do not create service if the devfile does not contain endpoint
  pkg/devfile/adapters/kubernetes/component/adapter.go
  tests/examples/source/devfiles/nodejs/devfile-no-endpoints.yaml
  tests/helper/helper_oc.go
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, kind/bug, lgtm, ok-to-test

#2802 Change the messaging to avoid confusion
  pkg/odo/cli/catalog/util/util.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/code-refactoring, lgtm

#2771 Assemble and organise devfile integration tests Files
  Makefile
  tests/integration/devfile/cmd_devfile_catalog_test.go
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, kind/design, lgtm

#2768 Fixing e2e image test flake
  tests/e2escenarios/e2e_images_test.go
Labels: approved, kind/flake, lgtm

#2735 Devfile command execution
  pkg/component/component.go
  pkg/devfile/adapters/common/command.go
  pkg/devfile/adapters/common/command_test.go
  pkg/devfile/adapters/common/types.go
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/common/utils_test.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils_test.go
  pkg/devfile/versions/1.0.0/components.go
  pkg/devfile/versions/common/types.go
  pkg/devfile/versions/interface.go
  pkg/exec/exec.go
  pkg/kclient/generators.go
  pkg/kclient/supervisord.go
  pkg/kclient/volumes_test.go
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/occlient/templates.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/push.go
  pkg/sync/sync.go
  pkg/testingutil/devfile.go
  tests/examples/source/devfiles/nodejs-multicontainer/devfile.yaml
  tests/examples/source/devfiles/nodejs/devfile-no-endpoints.yaml
  tests/examples/source/devfiles/nodejs/devfile.yaml
Labels: approved, kind/feature, lgtm

#2762 Odo url Ingress support
  .travis.yml
  Makefile
  pkg/component/component.go
  pkg/envinfo/envinfo.go
  pkg/envinfo/envinfo_test.go
  pkg/kclient/generators.go
  pkg/kclient/generators_test.go
  pkg/kclient/ingress.go
  pkg/kclient/ingress_test.go
  pkg/kclient/secrets.go
  pkg/kclient/secrets_test.go
  pkg/odo/cli/component/common_push.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/delete.go
  pkg/odo/cli/url/describe.go
  pkg/odo/cli/url/list.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/util/cmdutils.go
  pkg/url/url.go
  pkg/url/url_test.go
  tests/helper/helper_filesystem.go
  tests/helper/helper_generic.go
  tests/integration/devfile/cmd_devfile_catalog_test.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
  tests/integration/devfile/cmd_devfile_watch_test.go
Labels: approved, kind/feature, lgtm, ok-to-test

#2729 update supported image list and use the updated bootstrap image for CI
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
Labels: approved, kind/feature, lgtm

#2811 Fix sync when the pod gets re-created
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/kclient/pods.go
  pkg/kclient/pods_test.go
Labels: approved, kind/bug, lgtm

#2821 Update bootstrap image to 1.1.2
  pkg/devfile/adapters/common/utils.go
Labels: approved, kind/feature, lgtm

#2830 Update Go version and base image on Openshift CI
  openshift-ci/build-root/Dockerfile
Labels: approved, lgtm

#2532 Adding machine output to component create
  pkg/odo/cli/component/create.go
  tests/integration/component.go
Labels: approved, kind/bug, kind/feature, lgtm, size/M

#2797 Fix --namespace flag bug for odo create
  pkg/odo/cli/component/create.go
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, kind/bug, lgtm

#2829 Remove yusuf from OWNERS file
  OWNERS
Labels: approved, lgtm

#2763 Adds delete function for devfiles support.
  .travis.yml
  Makefile
  pkg/devfile/adapters/common/interface.go
  pkg/devfile/adapters/interface.go
  pkg/devfile/adapters/kubernetes/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/kclient/deployments.go
  pkg/kclient/deployments_test.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/devfile.go
  pkg/testingutil/deployments.go
  tests/integration/devfile/cmd_devfile_delete_test.go
Labels: approved, kind/feature, lgtm

#2837 Update documentation on glide
  docs/dev/development.adoc
Labels: approved, kind/documentation, lgtm

#2726 2669 devfile parser refactor and odo specific validations
  pkg/devfile/adapters/common/command.go
  pkg/devfile/adapters/common/command_test.go
  pkg/devfile/adapters/common/types.go
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/common/utils_test.go
  pkg/devfile/adapters/helper.go
  pkg/devfile/adapters/helper_test.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils_test.go
  pkg/devfile/parse.go
  pkg/devfile/parser/context/apiVersion.go
  pkg/devfile/parser/context/apiVersion_test.go
  pkg/devfile/parser/context/content.go
  pkg/devfile/parser/context/content_test.go
  pkg/devfile/parser/context/context.go
  pkg/devfile/parser/context/fs.go
  pkg/devfile/parser/context/schema.go
  pkg/devfile/parser/context/schema_test.go
  pkg/devfile/parser/data/1.0.0/components.go
  pkg/devfile/parser/data/1.0.0/devfileJsonSchema100.go
  pkg/devfile/parser/data/1.0.0/types.go
  pkg/devfile/parser/data/common/types.go
  pkg/devfile/parser/data/helper.go
  pkg/devfile/parser/data/helper_test.go
  pkg/devfile/parser/data/interface.go
  pkg/devfile/parser/data/versions.go
  pkg/devfile/parser/parse.go
  pkg/devfile/parser/types.go
  pkg/devfile/parser/writer.go
  pkg/devfile/parser/writer_test.go
  pkg/devfile/validate/components.go
  pkg/devfile/validate/components_test.go
  pkg/devfile/validate/validate.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/watch.go
  pkg/odo/cli/url/create.go
  pkg/testingutil/devfile.go
Labels: approved, kind/feature, lgtm

#2786 Adds disclaimer that experimental mode is enabled
  pkg/log/status.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/push.go
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, kind/documentation, lgtm

#2836 Shortens warning output for event information
  pkg/occlient/occlient.go
Labels: approved, kind/code-refactoring, lgtm

#2839 Don't panic when an invalid component name is passed in
  pkg/odo/cli/component/push.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/delete.go
  pkg/odo/cli/url/describe.go
  pkg/odo/cli/url/list.go
  pkg/odo/genericclioptions/context.go
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, kind/bug, lgtm

#2845 Add quotes around the commands being executed during odo push
  pkg/devfile/adapters/kubernetes/component/adapter.go
Labels: approved, kind/code-refactoring, lgtm

#2690 Add Unknown State to Component.
  pkg/application/application.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/types.go
  pkg/occlient/occlient.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/describe.go
  pkg/odo/cli/component/list.go
  pkg/odo/util/cmdutils.go
  pkg/util/util.go
  tests/integration/component.go
Labels: approved, kind/bug, lgtm, size/M

#2757 Add documentation to skip CI when pushing docs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, kind/documentation, lgtm

#2856 Bumping odo version to v1.1.2
  Dockerfile.rhel
  pkg/version/version.go
  scripts/installer.sh
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#2860 Update build number to 1.1.2
  build/VERSION
Labels: kind/feature

#2844 Update documentation links from 4.2 to 4.3
  README.adoc
  scripts/changelog-script.sh
Labels: approved, kind/documentation, lgtm

#2739 Add ability to create new service backed by an operator
  pkg/kclient/deployments.go
  pkg/kclient/kclient.go
  pkg/kclient/operators.go
  pkg/odo/cli/service/create.go
  pkg/service/service.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/feature, lgtm

#2870 Fixes now flag push.
  pkg/odo/cli/component/common_push.go
  tests/integration/cmd_pref_config_test.go
Labels: approved, kind/flake, lgtm

#2871 OS version details used in travis CI
  .travis.yml
Labels: approved, kind/feature, lgtm

#2841 add owner reference to ingress and tlssecert metadata
  pkg/devfile/adapters/common/types.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/kclient/secrets.go
  pkg/kclient/secrets_test.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/genericclioptions/context.go
  pkg/url/url.go
  tests/integration/devfile/cmd_devfile_delete_test.go
Labels: approved, kind/bug, lgtm, ok-to-test

#2732 Wait for component deletion, Add `--wait` flag to `odo delete`
  pkg/application/application.go
  pkg/component/component.go
  pkg/occlient/occlient.go
  pkg/odo/cli/application/delete.go
  pkg/odo/cli/component/delete.go
  tests/helper/helper_oc.go
  tests/integration/component.go
Labels: approved, kind/feature, lgtm

#2817 Adds secure field to url list table ouput and json output.
  pkg/odo/cli/url/list.go
  pkg/url/types.go
  pkg/url/url.go
  tests/integration/cmd_url_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
Labels: approved, kind/feature, lgtm

#2872 Fix documentation so that it would proper render
  docs/dev/experimental-mode.adoc
Labels: approved, kind/documentation, lgtm

#2875 Add documentation for `odo url create ` for host flag
  pkg/odo/cli/url/create.go
Labels: approved, kind/documentation, lgtm

#2861 Remove references to OpenShift cluster
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/delete.go
Labels: approved, kind/cleanup, lgtm

#2810 Print yaml definition of CR when asked for dry-run
  pkg/odo/cli/service/create.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/feature, lgtm

#2806 Implement a basic, first pass `odo push` with Docker support
  .travis.yml
  Makefile
  pkg/devfile/adapters/docker/adapter.go
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/docker/component/adapter_test.go
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/docker/component/utils_test.go
  pkg/devfile/adapters/docker/utils/utils.go
  pkg/devfile/adapters/docker/utils/utils_test.go
  pkg/devfile/adapters/helper.go
  pkg/lclient/client.go
  pkg/lclient/containers.go
  pkg/lclient/containers_test.go
  pkg/lclient/fakeclient.go
  pkg/lclient/generators.go
  pkg/lclient/generators_test.go
  pkg/lclient/images.go
  pkg/lclient/storage.go
  pkg/lclient/storage_test.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/genericclioptions/context.go
  tests/helper/helper_docker.go
  tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
  tests/integration/devfile/docker/docker_suite_test.go
Labels: approved, kind/feature, lgtm

#2809 Setup Kubernetes cluster on travis CI and handle odo project create on Kubernetes and Openshift cluster
  .travis.yml
  tests/helper/kubernetes_utils.go
  tests/integration/devfile/cmd_devfile_catalog_test.go
Labels: approved, area/devfile, kind/test, lgtm

#2896 Add push target into sample
  pkg/odo/cli/preference/set.go
  pkg/odo/cli/preference/unset.go
Labels: approved, kind/bug, lgtm, ok-to-test

#2798 odo create support existing devfile.yaml
  pkg/odo/cli/component/create.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/cmd_devfile_delete_test.go
  tests/integration/devfile/cmd_devfile_watch_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
Labels: approved, kind/feature, lgtm

#2895 Fixes watch test
  pkg/watch/watch.go
  pkg/watch/watch_test.go
Labels: approved, kind/bug, kind/cleanup, kind/flake, lgtm

#2882 nit： add <myproject> as param to command line
  pkg/odo/cli/project/set.go
Labels: approved, kind/feature, lgtm, ok-to-test

#2880 add source type field in all odo list variants ( json and standard )
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/types.go
  pkg/odo/cli/component/list.go
  tests/integration/cmd_app_test.go
  tests/integration/component.go
Labels: approved, lgtm

#2842 Improves odo delete for devfiles
  pkg/odo/cli/component/delete.go
  tests/integration/devfile/cmd_devfile_delete_test.go
Labels: approved, kind/bug, kind/code-refactoring, lgtm

#2903 remove benchmark tests
  .travis.yml
  Makefile
  scripts/openshiftci-presubmit-all-tests.sh
  tests/benchmark/basic_benchmark.go
  tests/benchmark/benchmark_test.go
Labels: approved, lgtm

#2915 [Devfile] Add a spinner for deployment rollout
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/kclient/deployments.go
Labels: approved, area/devfile, kind/bug, lgtm

#2864 Remove -q param in odo project command
  pkg/odo/cli/project/project.go
Labels: approved, kind/bug, lgtm, ok-to-test

#2916 devfile watch Interation test on kubernetes cluster using travis CI
  .travis.yml
  tests/integration/devfile/cmd_devfile_watch_test.go
Labels: approved, kind/test, lgtm

#2733 Extend with plugins
  pkg/odo/cli/cli.go
  pkg/odo/cli/plugins/plugin_handler.go
  tests/integration/plugin_handler_test.go
Labels: approved, lgtm

#2942 Optimize total test time in CI
  Makefile
  docs/dev/development.adoc
Labels: approved, kind/feature, lgtm

#2946 Odo cli binary release version 1.1.3
  Dockerfile.rhel
  pkg/version/version.go
  scripts/installer.sh
  scripts/rpm-prepare.sh
Labels: kind/feature

#2947 Add elsony as approver for Docker code
  pkg/devfile/adapters/docker/OWNERS
  pkg/lclient/OWNERS
Labels: approved, lgtm

#2950 Update build version for odo release 1.1.3
  build/VERSION
Labels: approved, kind/feature, lgtm

#2949 Update release documentation
  docs/dev/development.adoc
Labels: approved, kind/documentation, lgtm

#2911 [Local] Create docker volumes from volumes defined in devfile
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/docker/component/utils_test.go
  pkg/devfile/adapters/docker/storage/adapter.go
  pkg/devfile/adapters/docker/storage/adapter_test.go
  pkg/devfile/adapters/docker/storage/utils.go
  pkg/devfile/adapters/docker/storage/utils_test.go
  pkg/devfile/adapters/docker/utils/utils.go
  pkg/devfile/adapters/docker/utils/utils_test.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/lclient/containers.go
  pkg/lclient/storage.go
  pkg/lclient/storage_test.go
  tests/helper/helper_docker.go
  tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
Labels: approved, area/devfile, area/local, kind/feature, lgtm

#2944 Make sure that desired operators are installed in CI
  scripts/configure-installer-tests-cluster.sh
  scripts/setup-operators-41.sh
  scripts/setup-operators.sh
Labels: approved, kind/flake, lgtm

#2869 Update odo readme and docs for the experimental mode
  README.adoc
  docs/dev/experimental-mode.adoc
Labels: approved, kind/documentation, lgtm

#2951 add johnmcollier as pkg/devfile approver
  pkg/devfile/OWNERS
Labels: approved, lgtm

#2945 remove .circleci as we don't use it
  .circleci/config.yml
Labels: approved, lgtm

#2906 local docker support for url creation and deletion
  .travis.yml
  Makefile
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/docker/component/utils_test.go
  pkg/devfile/adapters/docker/utils/utils.go
  pkg/devfile/adapters/docker/utils/utils_test.go
  pkg/envinfo/envinfo.go
  pkg/lclient/containers.go
  pkg/lclient/generators.go
  pkg/lclient/generators_test.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/url/create.go
  pkg/url/url.go
  tests/integration/devfile/cmd_devfile_url_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_url_test.go
Labels: approved, area/devfile, kind/feature, lgtm

#2917 --context support for odo create
  pkg/odo/cli/component/create.go
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, area/devfile, kind/feature, lgtm

#2901 Create operator backed service from a yaml file
  Makefile
  pkg/odo/cli/service/create.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/feature, lgtm

#2988 Address failing Gosec G601
  pkg/odo/util/completion/completionhandlers.go
  pkg/storage/storage.go
Labels: approved, kind/bug, lgtm

#2990 Add Devfile documentation to site
  README.md
  chosen-docs/upstream/deploying-a-devfile-using-odo.md
  docs/deploying-a-devfile-using-odo.md
  index.md
Labels: kind/documentation

#2991 Remove uneeded documentation regarding devfile
  chosen-docs/upstream/deploying-a-devfile-using-odo.md
Labels: kind/documentation

#2992 Run synchronization script
  docs/deploying-a-devfile-using-odo.md
Labels: kind/documentation

#2982 Update some recursive logs to V(5)
  pkg/sync/sync.go
  pkg/util/file_indexer.go
Labels: approved, kind/code-refactoring, lgtm

#3006 Revert "Update some recursive logs to V(5)"
  pkg/sync/sync.go
  pkg/util/file_indexer.go
Labels: lgtm

#3009 Remove capitalization of odo
  _config.yml
  docs/deploying-a-devfile-using-odo.md
  docs/installing-odo.md
  index.md
Labels: kind/documentation

#3001 Run test on two ginkgo test node
  Makefile
  docs/dev/development.adoc
Labels: approved, kind/feature, lgtm

#2922 Docker Devfile Component Sync and Execution
  pkg/component/component.go
  pkg/devfile/adapters/common/command_test.go
  pkg/devfile/adapters/common/types.go
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/common/utils_test.go
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/docker/component/adapter_test.go
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/docker/component/utils_test.go
  pkg/devfile/adapters/docker/utils/utils.go
  pkg/devfile/adapters/docker/utils/utils_test.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils_test.go
  pkg/exec/devfile.go
  pkg/exec/exec.go
  pkg/kclient/pods.go
  pkg/lclient/client.go
  pkg/lclient/containers.go
  pkg/lclient/containers_test.go
  pkg/lclient/fakeclient.go
  pkg/lclient/generators.go
  pkg/lclient/generators_test.go
  pkg/lclient/images_test.go
  pkg/lclient/mock_client.go
  pkg/lclient/storage_test.go
  pkg/occlient/occlient.go
  pkg/odo/cli/component/devfile.go
  pkg/sync/adapter.go
  pkg/sync/adapter_test.go
  pkg/sync/sync.go
  pkg/testingutil/devfile.go
  tests/helper/helper_docker.go
  tests/helper/helper_generic.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_url_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, kind/feature, lgtm

#3013 Release 1.2.0 of odo
  Dockerfile.rhel
  pkg/version/version.go
  scripts/installer.sh
  scripts/rpm-prepare.sh
Labels: kind/feature

#3016 Update build version to 1.2.0
  build/VERSION
Labels: kind/feature

#3018 Fix flakey tests
  pkg/url/url_test.go
  pkg/util/util_test.go
Labels: kind/flake

#3019 Disables another flakey test with util_test.go
  pkg/util/util_test.go
Labels: kind/flake

#2894 avoid list component name in s2i mode
  pkg/odo/cli/component/watch.go
Labels: approved, kind/bug, lgtm, ok-to-test

#2965 Fix parallel test run failure for devfile integration test
  tests/helper/kubernetes_utils.go
  tests/integration/devfile/cmd_devfile_catalog_test.go
  tests/integration/devfile/cmd_devfile_watch_test.go
Labels: approved, kind/bug, lgtm

#3010 Adding eventually duration in operator test file
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/bug, lgtm

#3021 Revert "Update build version to 1.2.0"
  build/VERSION
Labels: approved, lgtm

#2909 [Devfile] Remove namespace flag from odo commands
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/component/watch.go
  pkg/odo/genericclioptions/context.go
  tests/integration/cmd_watch_test.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/cmd_devfile_delete_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
  tests/integration/devfile/cmd_devfile_watch_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, area/devfile, kind/cleanup, lgtm

#2925 Assemble oc and kubectl helper runner
  tests/helper/helper_cli.go
  tests/helper/helper_docker.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/cmd_push_test.go
  tests/integration/cmd_storage_test.go
Labels: approved, kind/code-refactoring, lgtm

#3025 Fix naming to match future direction with starting with k8s
  README.adoc
Labels: approved, lgtm

#2926 add json output for listing operator backed services
  pkg/machineoutput/services.go
  pkg/odo/cli/catalog/list/services.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/feature, lgtm

#3030 use just odo instead of odo (OpenShift Do)
  cmd/cli-doc/cli-doc.go
  pkg/odo/cli/cli.go
  rpms/openshift-odo.spec
  scripts/sync-docs.sh
Labels: approved, lgtm

#3040 Avoid racing condition between set and unset KUBECONFIG
  tests/helper/helper_generic.go
  tests/helper/kubernetes_utils.go
  tests/integration/devfile/cmd_devfile_catalog_test.go
  tests/integration/devfile/cmd_devfile_watch_test.go
Labels: approved, kind/bug, lgtm

#2885 Adds route support of URLs for openshift clusters
  pkg/component/component.go
  pkg/envinfo/envinfo.go
  pkg/kclient/fake/ingress.go
  pkg/kclient/fake/secrets.go
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/occlient/volumes_test.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/describe.go
  pkg/odo/cli/url/list.go
  pkg/odo/util/cmdutils.go
  pkg/testingutil/routes.go
  pkg/url/types.go
  pkg/url/url.go
  pkg/url/url_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
Labels: approved, kind/code-refactoring, kind/feature, lgtm

#2653 Add debug machine readable output json
  pkg/debug/info.go
  pkg/debug/info_test.go
  pkg/odo/cli/debug/info.go
  tests/integration/cmd_debug_test.go
  tests/integration/debug/cmd_debug_test.go
Labels: approved, lgtm, size/L

#3039 Don't list imagestreams when using Docker
  .travis.yml
  Makefile
  pkg/odo/cli/catalog/list/components.go
  tests/integration/devfile/docker/cmd_docker_devfile_catalog_test.go
Labels: approved, area/devfile, area/local, kind/bug, lgtm

#2907 Adding init command capability to devfiles
  pkg/devfile/adapters/common/command.go
  pkg/devfile/adapters/common/command_test.go
  pkg/devfile/adapters/common/types.go
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/parser/data/common/types.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/push.go
  pkg/testingutil/devfile.go
  tests/examples/source/devfiles/nodejs/devfile-with-volumes.yaml
  tests/examples/source/devfiles/nodejs/devfile-without-devinit.yaml
  tests/examples/source/devfiles/springboot/devfile-init-without-build.yaml
  tests/examples/source/devfiles/springboot/devfile-init.yaml
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
Labels: approved, lgtm, ok-to-test

#3008 Fixes odo describe for multiple URLs of unpushed component
  pkg/component/component.go
  pkg/config/fakeConfig.go
  pkg/odo/cli/config/set.go
  tests/integration/component.go
Labels: approved, kind/bug, lgtm

#2966 Fix `odo component describe <component-name>` for not pushed components
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/describe.go
  pkg/odo/genericclioptions/context.go
  tests/integration/component.go
Labels: approved, lgtm

#3049 Adding messaging and script updates to ensure smoother golang updates
  docs/dev/development.adoc
  rpms/openshift-odo.spec
  scripts/rpm-prepare.sh
Labels: approved, kind/documentation, kind/feature, lgtm
