Repository redhat-developer/odo, pull requests merged in 2020-07, with the labels that each got.

#3459 Update Node devfile tests
  docs/public/debugging-using-devfile.adoc
  pkg/odo/cli/component/create.go
  tests/examples/source/devfiles/nodejs/devfile-no-endpoints.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-debugrun.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-multiple-defaults.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-restart.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-sparseCheckoutDir.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-volumes.yaml
  tests/examples/source/devfiles/nodejs/devfile-without-devbuild.yaml
  tests/examples/source/devfiles/nodejs/devfile-without-devinit.yaml
  tests/examples/source/devfiles/nodejs/devfile.yaml
  tests/examples/source/devfiles/nodejs/project/app/app.js
  tests/examples/source/devfiles/nodejs/project/package.json
  tests/examples/source/devfiles/nodejs/project/server.js
  tests/examples/source/devfiles/nodejs/project/test/test.js
  tests/integration/devfile/cmd_devfile_catalog_test.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/cmd_devfile_debug_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/debug/cmd_devfile_debug_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_url_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, lgtm

#3331 refactoring: remove redundant PlatformAdapter interface
  pkg/devfile/adapters/helper.go
  pkg/devfile/adapters/interface.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/watch.go
Labels: approved, kind/cleanup, lgtm

#3242 Corrected 'List' type struct definitions
  pkg/catalog/types.go
  pkg/machineoutput/services.go
  pkg/machineoutput/types.go
  pkg/odo/cli/catalog/util/util.go
  pkg/odo/cli/catalog/util/util_test.go
  pkg/service/service.go
  pkg/service/types.go
  pkg/url/types.go
  tests/integration/servicecatalog/cmd_service_test.go
Labels: approved, kind/cleanup, lgtm

#3450 Add odo service list -o json message
  pkg/odo/cli/service/list.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/bug, lgtm

#3457 update odo watch to remove [component name] arg also resolved bugs in odo watch test utils
  pkg/odo/cli/component/watch.go
  pkg/odo/genericclioptions/context.go
  tests/helper/helper_generic.go
  tests/integration/devfile/utils/utils.go
Labels: approved, lgtm

#3419 fix #3380: `odo create --help` should mention `odo catalog list components` instead of `odo catalog list`
  pkg/odo/cli/component/create.go
Labels: approved, kind/bug, lgtm

#3295 Add support for SourceMapping field in devfiles
  pkg/devfile/adapters/common/types.go
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/docker/component/utils_test.go
  pkg/devfile/adapters/docker/utils/utils_test.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/lclient/client.go
  pkg/lclient/containers_test.go
  pkg/lclient/fakeclient.go
  pkg/sync/adapter.go
  pkg/sync/adapter_test.go
  tests/examples/source/devfiles/nodejs/devfileSourceMapping.yaml
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
Labels: approved, kind/feature, lgtm

#3425 Rename --downloadSource to --starter
  docs/public/deploying-a-devfile-using-odo.adoc
  pkg/odo/cli/component/create.go
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, kind/cleanup, lgtm

#3448 Add unsupported component info in watch help UX
  pkg/odo/cli/component/watch.go
  tests/integration/cmd_watch_test.go
  tests/integration/devfile/cmd_devfile_watch_test.go
Labels: approved, kind/bug, lgtm

#3411 Adding latest minikube version on travis
  .travis.yml
Labels: approved, kind/feature, lgtm

#3259 Add validation for parameters passed with command
  pkg/config/config.go
  pkg/odo/cli/config/set.go
Labels: approved, kind/bug, lgtm

#3462 Copy kubeconfig to temporary file and add permissions
  scripts/configure-installer-tests-cluster.sh
  tests/integration/loginlogout/cmd_login_logout_test.go
Labels: approved, kind/feature, lgtm

#3473 resolved some incorrect comments
  pkg/debug/info_test.go
  pkg/devfile/parser/data/2.0.0/types.go
  pkg/devfile/parser/data/common/types.go
  pkg/kclient/deployments.go
  pkg/odo/cli/debug/portforward.go
  pkg/odo/cli/url/describe.go
  pkg/project/types.go
  pkg/storage/types.go
  pkg/testingutil/deployments.go
  pkg/url/url.go
  pkg/util/concurrent.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/integration/cmd_debug_test.go
  tests/integration/devfile/cmd_devfile_debug_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_url_test.go
Labels: approved, lgtm

#3455 Update tests to use updated stack names
  docs/dev/experimental-mode.adoc
  docs/public/deploying-a-devfile-using-odo.adoc
  tests/integration/devfile/cmd_devfile_catalog_test.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/cmd_devfile_registry_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_catalog_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, kind/failing-test, lgtm

#2751 Make write odo-file-index.json after push success
  pkg/odo/cli/component/common_push.go
  pkg/sync/adapter.go
  pkg/util/file_indexer.go
Labels: approved, kind/bug, lgtm, ok-to-test

#3464 Building redistributable only on x86_64 and updating golang version to 1.13
  .travis.yml
  Dockerfile.rhel
  docs/dev/development.adoc
  openshift-ci/build-root/Dockerfile
  rpms/openshift-odo.spec
  scripts/rpm-local-build.sh
  scripts/rpm-prepare.sh
Labels: approved, kind/cleanup, lgtm

#3226 Fix #2707 : `odo catalog list components -o json` does not have `imageStreamRef` in json output after update from v1.0.x to v1.1.0
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  pkg/catalog/types.go
Labels: approved, kind/bug, lgtm

#3254 Push odo without an .odo directory
  pkg/devfile/parser/data/1.0.0/components.go
  pkg/envinfo/envinfo.go
  pkg/odo/cli/component/common_push.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/push.go
  pkg/odo/genericclioptions/context.go
  pkg/testingutil/devfile.go
  tests/examples/source/devfiles/springboot/devfile-with-metadataname-foobar.yaml
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, kind/feature, lgtm

#3384 Implement `odo log` for devfiles
  .travis.yml
  Makefile
  pkg/devfile/adapters/common/interface.go
  pkg/devfile/adapters/docker/adapter.go
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/interface.go
  pkg/devfile/adapters/kubernetes/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/kclient/pods.go
  pkg/lclient/client.go
  pkg/lclient/containers.go
  pkg/lclient/containers_test.go
  pkg/lclient/fakeclient.go
  pkg/lclient/mock_client.go
  pkg/occlient/occlient.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/log.go
  pkg/util/util.go
  tests/integration/devfile/cmd_devfile_log_test.go
Labels: approved, lgtm

#3535 Fix delete context on Windows
  tests/integration/devfile/debug/cmd_devfile_debug_test.go
Labels: approved, kind/bug, lgtm

#3538 Fixing location field for odo catalog describe component jave-openliberty
  tests/integration/devfile/cmd_devfile_catalog_test.go
Labels: approved, kind/bug, lgtm

#3519 Add "Understanding odo" Documentation
  docs/public/understanding-odo.adoc
Labels: kind/documentation

#3525 update help message for --ref to show that its only valid for git components
  pkg/odo/cli/component/create.go
Labels: approved, kind/documentation, lgtm

#3100 Extend download source to support revisions
  pkg/odo/cli/component/create.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, kind/feature, lgtm, ok-to-test

#3366 catalog search service honor experiment flag
  pkg/kclient/operators.go
  pkg/odo/cli/catalog/search/service.go
  pkg/odo/cli/catalog/util/util.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, lgtm

#3523 use MatchJSON in tests wherever needed
  tests/integration/component.go
Labels: approved, area/Windows, lgtm

#3405 Update odo delete for no component and devfile.yaml
  pkg/devfile/adapters/common/interface.go
  pkg/devfile/adapters/docker/adapter.go
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/docker/component/adapter_test.go
  pkg/devfile/adapters/docker/utils/utils.go
  pkg/devfile/adapters/docker/utils/utils_test.go
  pkg/devfile/adapters/kubernetes/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils_test.go
  pkg/kclient/deployments_test.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/watch.go
  pkg/odo/genericclioptions/context.go
  tests/integration/devfile/cmd_devfile_delete_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_delete_test.go
Labels: approved, kind/bug, lgtm

#3541 Adds a error message for creation of routes with host flag
  pkg/odo/cli/url/create.go
  tests/integration/devfile/cmd_devfile_delete_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
Labels: approved, kind/bug, lgtm

#3528 Fixing kubeconfig path and login session for 4.x cluster
  scripts/configure-installer-tests-cluster.sh
  scripts/openshiftci-periodic-tests.sh
  scripts/openshiftci-presubmit-all-tests.sh
  tests/integration/loginlogout/cmd_login_logout_test.go
Labels: approved, kind/bug, kind/cleanup, kind/feature, lgtm

#3453 added deprecation and error messages for 'odo update`
  pkg/odo/cli/component/update.go
Labels: approved, area/component, lgtm

#3522 implement machine readable output for odo preference view
  pkg/odo/cli/preference/view.go
  pkg/preference/machine_output.go
Labels: approved, lgtm

#3524 use linux path separator for commands executed on pod
  tests/integration/cmd_push_test.go
Labels: approved, area/Windows, lgtm

#3561 Change service list output to make linking easier
  pkg/odo/cli/service/list.go
Labels: approved, area/UX, kind/code-refactoring, lgtm

#3556 PR acceptance criteria template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, kind/documentation, lgtm

#3083 Adds exec command for devfile components with kube push target
  .travis.yml
  Makefile
  pkg/devfile/adapters/common/interface.go
  pkg/devfile/adapters/docker/adapter.go
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/interface.go
  pkg/devfile/adapters/kubernetes/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/component/component.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/exec.go
  tests/integration/devfile/cmd_devfile_exec.go
  tests/integration/devfile/docker/cmd_docker_devfile_exec_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, kind/feature, lgtm

#3504 Update periodic job link in README
  docs/dev/ci-reference.adoc
  docs/dev/development.adoc
  docs/dev/test-architecture.adoc
Labels: approved, kind/documentation, lgtm

#3232 Expose oc build timeout in preference
  pkg/component/component.go
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/odo/cli/preference/set.go
  pkg/odo/cli/preference/unset.go
  pkg/odo/cli/preference/view.go
  pkg/preference/machine_output.go
  pkg/preference/preference.go
  pkg/preference/preference_test.go
  tests/integration/generic_test.go
Labels: approved, kind/feature, lgtm

#3546 Uncomment odo project list json test
  tests/integration/generic_test.go
  tests/integration/project/cmd_project_test.go
Labels: approved, kind/cleanup, lgtm

#3582 Fix empty devfile overriding issue for `odo create --devfile ./devfile.yaml`
  pkg/util/util.go
  tests/helper/helper_filesystem.go
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, area/devfile, kind/bug, lgtm

#3555 debugging push test failure on multistage test infra
  tests/helper/helper_oc.go
  tests/integration/component.go
Labels: approved, kind/bug, lgtm

#3593 Update URLs. [skip ci]
  README.adoc
Labels: approved, kind/documentation, lgtm

#3588 Clean ups
  pkg/config/config.go
  pkg/devfile/parser/context/context.go
  pkg/devfile/parser/data/helper.go
  pkg/devfile/parser/data/versions.go
  pkg/devfile/validate/validate.go
  pkg/envinfo/envinfo.go
  pkg/preference/preference.go
  pkg/util/defaults.go
Labels: approved, kind/cleanup, lgtm

#3572 Docs: secure registry docs
  docs/public/secure-registry.adoc
Labels: approved, area/devfile, kind/documentation, lgtm

#3598 Enabling verbose only for Integration test
  scripts/openshiftci-presubmit-all-tests.sh
Labels: approved, lgtm

#3413 Lifecycle events proposal
  docs/proposals/lifecycle_events.md
Labels: approved, kind/design, lgtm, ok-to-test

#3533 Implement support for postStart lifecycle events
  pkg/devfile/adapters/common/command.go
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  tests/examples/source/devfiles/nodejs/devfile-with-post-start.yaml
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
Labels: approved, kind/feature, lgtm, ok-to-test

#3564 Adds support for deletion of Operator backed service
  pkg/kclient/deployments.go
  pkg/kclient/operators.go
  pkg/odo/cli/service/delete.go
  pkg/service/service.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/feature, lgtm

#3606 Fixing project create on both kubernetes and openshift for devfile url test
  tests/integration/devfile/cmd_devfile_url_test.go
Labels: approved, kind/bug, kind/failing-test, lgtm

#3590 Update `odo deploy` proposal to use go's text/template format for template variables
  docs/proposals/odo-deploy.md
Labels: approved, kind/design, lgtm, ok-to-test

#3537 Support environment variables in command
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils_test.go
  pkg/exec/devfile.go
  tests/examples/source/devfiles/nodejs/devfile-with-multiple-defaults.yaml
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, area/devfile, kind/user-story, lgtm

#3601 moved odo specific logic out of devfile/parser package
  pkg/devfile/parse.go
  pkg/devfile/parser/parse.go
  pkg/devfile/parser/types.go
  pkg/devfile/validate/components.go
  pkg/devfile/validate/components_test.go
  pkg/devfile/validate/validate.go
  pkg/odo/cli/catalog/describe/component.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/component/test.go
  pkg/odo/cli/component/watch.go
  pkg/odo/cli/url/create.go
Labels: approved, lgtm

#3608 Including exit code in stderr verification
  scripts/openshiftci-presubmit-all-tests.sh
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/component.go
Labels: approved, area/testing, kind/bug, kind/failing-test, lgtm

#3536 Reset index when force pushed
  pkg/sync/adapter.go
Labels: approved, kind/bug, lgtm, ok-to-test

#3591 Improve `odo url create`
  pkg/odo/cli/url/create.go
  pkg/odo/util/validation/validation.go
  tests/integration/devfile/cmd_devfile_url_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_url_test.go
  tests/integration/generic_test.go
Labels: approved, kind/bug, lgtm

#3611 Fix post start event logged message
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
Labels: approved, lgtm

#3505 List created components for devfile v2
  pkg/application/labels/labels.go
  pkg/devfile/adapters/common/types.go
  pkg/devfile/adapters/helper.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/parser/data/2.0.0/types.go
  pkg/envinfo/envinfo.go
  pkg/kclient/deployments.go
  pkg/kclient/deployments_test.go
  pkg/kclient/generators.go
  pkg/occlient/occlient.go
  pkg/odo/cli/component/component.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/exec.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/component/test.go
  pkg/odo/cli/component/watch.go
  pkg/odo/genericclioptions/context.go
  pkg/project/labels.go
  tests/examples/source/devfiles/nodejs/devfile-no-endpoints.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-debugrun.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-multiple-defaults.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-post-start.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-restart.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-sparseCheckoutDir.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-testgroup.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-volumes.yaml
  tests/examples/source/devfiles/nodejs/devfile-without-devbuild.yaml
  tests/examples/source/devfiles/nodejs/devfile-without-devinit.yaml
  tests/examples/source/devfiles/nodejs/devfile.yaml
  tests/helper/helper_generic.go
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, lgtm

#3614 resolved some incorrect comments
  pkg/odo/cli/component/common_push.go
  pkg/sync/adapter.go
Labels: approved, lgtm

#3483 Update Devfile doc for Kubernetes and add quarkus doc
  docs/public/deploying-a-devfile-using-odo.adoc
Labels: approved, lgtm

#3622 Release 1.2.4
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: kind/feature

#3623 Fix building RPM
  rpms/openshift-odo.spec
Labels: kind/bug

#3624 Fix package name
  rpms/openshift-odo.spec
Labels: kind/bug

#3620 Commenting project list -o json CI flake
  tests/integration/project/cmd_project_test.go
Labels: approved, lgtm

#3432 Adds parent devfile support for devfile v2
  pkg/devfile/parse.go
  pkg/devfile/parser/context/content.go
  pkg/devfile/parser/context/context.go
  pkg/devfile/parser/context/context_test.go
  pkg/devfile/parser/data/1.0.0/components.go
  pkg/devfile/parser/data/2.0.0/components.go
  pkg/devfile/parser/data/2.0.0/types.go
  pkg/devfile/parser/data/common/types.go
  pkg/devfile/parser/data/interface.go
  pkg/devfile/parser/parse.go
  pkg/devfile/parser/parse_test.go
  pkg/devfile/parser/types.go
  pkg/devfile/parser/types_test.go
  pkg/odo/cli/catalog/describe/component.go
  pkg/odo/cli/component/watch.go
  pkg/testingutil/devfile.go
  tests/examples/source/devfiles/nodejs/devfile-with-parent.yaml
  tests/examples/source/devfiles/openliberty/devfile-with-multi-layer-parent.yaml
  tests/examples/source/devfiles/openliberty/devfile-with-parent.yaml
  tests/examples/source/devfiles/openliberty/project/pom.xml
  tests/examples/source/devfiles/openliberty/project/src/main/java/dev/appsody/starter/StarterApplication.java
  tests/examples/source/devfiles/openliberty/project/src/main/java/dev/appsody/starter/StarterResource.java
  tests/examples/source/devfiles/openliberty/project/src/main/java/dev/appsody/starter/health/StarterLivenessCheck.java
  tests/examples/source/devfiles/openliberty/project/src/main/java/dev/appsody/starter/health/StarterReadinessCheck.java
  tests/examples/source/devfiles/openliberty/project/src/main/liberty/config/server.xml
  tests/examples/source/devfiles/openliberty/project/src/main/webapp/WEB-INF/beans.xml
  tests/examples/source/devfiles/openliberty/project/src/main/webapp/index.html
  tests/examples/source/devfiles/openliberty/project/src/test/java/it/dev/appsody/starter/HealthEndpointTest.java
  tests/helper/helper_cli.go
  tests/helper/helper_docker.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, kind/feature, lgtm

#3617 Add more logs when the folder is not empty
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, lgtm

#3597 Adds runMode to env for debugging with odo watch.
  pkg/envinfo/envinfo.go
  pkg/envinfo/fake.go
  pkg/odo/cli/component/devfile.go
  pkg/watch/watch.go
  pkg/watch/watch_test.go
  tests/helper/helper_filesystem.go
  tests/integration/devfile/cmd_devfile_debug_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
  tests/integration/devfile/cmd_devfile_watch_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, kind/bug, lgtm

#3618 Customise and cleanup create test
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, kind/cleanup, lgtm

#3629 Renames devfile exec test file to cmd_devfile_exec_test
  tests/integration/devfile/cmd_devfile_exec_test.go
Labels: approved, kind/cleanup, lgtm

#3529 CI support for IBM Z
  Makefile
  docs/dev/test-architecture-s390x.adoc
  scripts/configure-installer-tests-cluster-s390x.sh
  scripts/openshiftci-presubmit-all-tests.sh
Labels: approved, area/System-PZ, lgtm, ok-to-test

#3636 Clean up and customise debug test
  tests/integration/devfile/cmd_devfile_debug_test.go
Labels: approved, kind/cleanup, lgtm

#3633 Update build/VERSION to 1.2.4
  build/VERSION
Labels: approved, kind/feature, lgtm

#3637 moved the deprecation warning from examples and moved to long desc
  pkg/odo/cli/component/update.go
Labels: approved, kind/cleanup, lgtm

#3526 show project download info at UI
  pkg/odo/cli/component/create.go
Labels: approved, lgtm

#3587 Remove deprecated images and update tests
  .travis.yml
  Makefile
  README.adoc
  docs/dev/test-architecture.adoc
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  scripts/supported-311-is.sh
  tests/image-streams/supported-java.json
  tests/image-streams/supported-nodejs.json
  tests/integration/component.go
Labels: approved, kind/cleanup, kind/documentation, lgtm

#3625 Clean up and customisation for delete tests
  tests/integration/devfile/cmd_devfile_delete_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, kind/cleanup, kind/code-refactoring, lgtm

#3635 adding tests to verify the private registry images
  tests/e2escenarios/e2e_images_test.go
Labels: approved, kind/failing-test, lgtm

#3627 Update devfile schema
  pkg/devfile/parser/data/2.0.0/devfileJsonSchema200.go
  pkg/devfile/parser/data/2.0.0/types.go
  tests/examples/source/devfiles/nodejs/devfile-with-debugrun.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-invalid-volmount.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-multiple-defaults.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-post-start.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-volume-components.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-volumes.yaml
  tests/examples/source/devfiles/nodejs/devfile-without-devbuild.yaml
  tests/examples/source/devfiles/nodejs/devfile-without-devinit.yaml
  tests/examples/source/devfiles/nodejs/devfile.yaml
  tests/examples/source/devfiles/nodejs/devfileCompositeCommands.yaml
  tests/examples/source/devfiles/nodejs/devfileCompositeCommandsParallel.yaml
  tests/examples/source/devfiles/nodejs/devfileCompositeNonExistent.yaml
  tests/examples/source/devfiles/nodejs/devfileCompositeRun.yaml
  tests/examples/source/devfiles/nodejs/devfileNestedCompCommands.yaml
  tests/examples/source/devfiles/nodejs/devfileSourceMapping.yaml
  tests/examples/source/devfiles/springboot/devfile-with-metadataname-foobar.yaml
  tests/examples/source/devfiles/springboot/devfile.yaml
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
Labels: approved, kind/feature, lgtm

#3509 Use the name provided on CLI to create an Operator backed service
  pkg/odo/cli/component/common_link.go
  pkg/odo/cli/service/create.go
  pkg/odo/cli/service/delete.go
  pkg/service/service.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/code-refactoring, kind/feature, lgtm

#3630 Add proposal for updating the file sync location
  docs/proposals/file-sync-location.md
Labels: approved, kind/design, lgtm

#3573 Remove additional / unneeded logging flags
  docs/dev/logging.adoc
  pkg/odo/cli/cli.go
Labels: approved, kind/cleanup, lgtm

#3650 Fixes GetPVCSize() for the cli helpers.
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, kind/bug, lgtm

#3660 Makes service create command consistent with how it's done for Service Catalog
  docs/public/operator-hub.adoc
  pkg/odo/cli/service/create.go
  pkg/service/service.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/cleanup, kind/code-refactoring, lgtm

#3549 Convert s2i components to devfile
  pkg/devfile/parser/data/1.0.0/components.go
  pkg/devfile/parser/data/2.0.0/components.go
  pkg/devfile/parser/data/2.0.0/types.go
  pkg/devfile/parser/data/common/errors.go
  pkg/devfile/parser/data/common/types.go
  pkg/devfile/parser/data/helper_test.go
  pkg/devfile/parser/data/interface.go
  pkg/devfile/parser/data/versions.go
  pkg/occlient/utils.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/utils/convert.go
  pkg/odo/cli/utils/utils.go
  pkg/testingutil/devfile.go
  tests/integration/component.go
Labels: approved, kind/feature, lgtm

#3475 cleanup #3403: removed --memory, --min-memory. --max-memory, --cpu, --min-cpu, --max-cpu flags from 'odo create' command
  pkg/component/component.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/config/set.go
  pkg/odo/util/validation/validators.go
  tests/e2escenarios/e2e_images_test.go
  tests/integration/cmd_push_test.go
  tests/integration/component.go
  tests/integration/generic_test.go
Labels: approved, kind/cleanup, lgtm

#3487 Adds documentation on Devfile file reference
  docs/file-reference/index.md
  docs/public/deploying-a-devfile-using-odo.adoc
Labels: kind/documentation

#3675 Update file reference documentation
  docs/file-reference/index.md
Labels: kind/documentation
