Repository redhat-developer/odo, pull requests merged in 2020-12, with the labels that each got.

#4261 Refactors and moves buildConfigs, imageStreams and some other resources
  pkg/catalog/catalog.go
  pkg/component/component.go
  pkg/kclient/deployments.go
  pkg/kclient/utils.go
  pkg/kclient/utils_test.go
  pkg/occlient/buildConfigs.go
  pkg/occlient/buildConfigs_test.go
  pkg/occlient/deploymentConfigs.go
  pkg/occlient/deploymentConfigs_test.go
  pkg/occlient/imageStreams.go
  pkg/occlient/imageStreams_test.go
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/occlient/utils.go
  pkg/occlient/utils_test.go
  pkg/occlient/volumes.go
Labels: approved, kind/cleanup, kind/code-refactoring, lgtm

#4234 windows path seperator fix
  tests/e2escenarios/e2e_images_test.go
  tests/helper/helper_oc.go
  tests/integration/devfile/utils/utils.go
Labels: approved, kind/bug, lgtm

#4268 Update the prow help command link
  docs/dev/development.adoc
Labels: approved, kind/documentation, lgtm

#4119 Add Open Liberty to devfile doc
  docs/public/deploying-a-devfile-using-odo.adoc
Labels: approved, kind/documentation, lgtm, ok-to-test

#4275 remove packages imported twice
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/devfile/adapters/docker/storage/adapter_test.go
  pkg/kclient/secrets_test.go
  pkg/occlient/occlient_test.go
  pkg/odo/cli/cli.go
  pkg/project/project_test.go
  pkg/testingutil/services.go
Labels: approved, kind/cleanup, lgtm

#4282 Add a note to the Operators docs. [skip ci]
  docs/public/operator-hub.adoc
Labels: approved, kind/documentation, lgtm

#4272 Refactors service catalog and discovery client code
  pkg/application/application.go
  pkg/catalog/catalog.go
  pkg/kclient/fakeclient.go
  pkg/kclient/kclient.go
  pkg/kclient/operators.go
  pkg/kclient/serviceCatalog.go
  pkg/kclient/serviceCatalog_test.go
  pkg/occlient/deploymentConfigs.go
  pkg/occlient/deploymentConfigs_test.go
  pkg/occlient/fakeclient.go
  pkg/occlient/imageStreams.go
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/occlient/projects.go
  pkg/occlient/routes.go
  pkg/odo/cli/component/common_link.go
  pkg/odo/cli/component/link.go
  pkg/odo/cli/component/unlink.go
  pkg/odo/cli/service/create.go
  pkg/odo/util/completion/completionhandlers.go
  pkg/project/project_test.go
  pkg/service/service.go
  pkg/service/service_test.go
  pkg/url/status_test.go
Labels: approved, kind/cleanup, kind/code-refactoring, lgtm

#4286 OpenLiberrty documentation and Operator installation warning
  docs/deploying-a-devfile-using-odo.md
  docs/operator-hub.md
Labels: approved, lgtm

#4267 Fixes export and execution of env variables for devfile commands
  pkg/devfile/adapters/common/command_simple.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/examples/source/devfiles/nodejs/devfile-with-multiple-defaults.yaml
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, lgtm

#4274 Makes odo work with v0.3.0 of Service Binding Operator
  docs/public/install-service-binding-operator.adoc
  docs/public/operator-hub.adoc
  docs/public/operators-on-minikube.adoc
  go.mod
  go.sum
  pkg/kclient/operators.go
  pkg/odo/cli/component/common_link.go
  pkg/odo/cli/component/link.go
  scripts/configure-cluster/common/setup-operators.sh
  tests/integration/operatorhub/cmd_service_test.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/apis/operators/v1alpha1/doc.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/apis/operators/v1alpha1/register.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/apis/operators/v1alpha1/servicebinding_types.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/apis/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/apis/operators/v1alpha1/zz_generated.openapi.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/scheme/scheme.go
Labels: approved, kind/api-change, kind/documentation, lgtm

#4283 Modifies WaitForDeploymentRollout() to collect events.
  pkg/component/component.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/kclient/deployments.go
  pkg/kclient/pods.go
  pkg/kclient/pods_test.go
  pkg/kclient/utils.go
  pkg/kclient/utils_test.go
  pkg/odo/cli/component/common_link.go
Labels: approved, kind/flake, lgtm

#4294 Bumping odo version v2.0.2 -> v2.0.3
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#4293 More documentation on Operators and small fixes
  chosen-docs/upstream/install-service-binding-operator.md
  docs/configuring-the-odo-cli.md
  docs/creating-a-multicomponent-application-with-odo.md
  docs/creating-a-single-component-application-with-odo.md
  docs/creating-an-application-with-a-database.md
  docs/install-service-binding-operator.md
  docs/odo-architecture.md
  docs/operator-hub.md
  docs/operators-on-minikube.md
  index.md
Labels: approved, kind/documentation, lgtm

#4297 Fix incorrect link for Operators on minikube
  index.md
Labels: approved, kind/documentation, lgtm

#4291 Removes ExecCMDInContainer() and ExtractProjectToComponent() from the occlient.
  pkg/component/component.go
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/docker/component/status.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/status.go
  pkg/kclient/pods.go
  pkg/lclient/containers.go
  pkg/lclient/containers_test.go
  pkg/occlient/occlient.go
  pkg/sync/adapter_test.go
  pkg/sync/mock/sync.go
Labels: approved, kind/cleanup, kind/code-refactoring, lgtm

#4265 Update CI reference doc
  docs/dev/ci-reference.adoc
Labels: approved, kind/cleanup, kind/documentation, lgtm

#4247 Handling absolute and relative source path file uri
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/integration/component.go
Labels: approved, kind/bug, kind/failing-test, lgtm, release-note

#4306 Update docs to install SBO from OperatorHub.io
  docs/public/install-service-binding-operator.adoc
Labels: approved, kind/documentation, lgtm

#4310 Update docs to install SBO from OperatorHub.io
  docs/install-service-binding-operator.md
Labels: approved, kind/documentation

#4312 Changed block comment to reflect what the code actually does.
  pkg/component/component.go
Labels: approved, kind/code-refactoring, lgtm

#4300 Don't fail the command if listing a CR's instances fails
  pkg/odo/cli/service/list.go
  pkg/service/service.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/bug, lgtm

#4307 Fix odo hang when cluster is unreachable
  pkg/kclient/kclient.go
  pkg/odo/cli/component/common_link.go
  pkg/odo/cli/component/link.go
  pkg/odo/cli/component/unlink.go
  pkg/odo/cli/service/create.go
Labels: approved, lgtm

#4176 #4062 Update installing odo on Windows section to fix filename and ad…
  docs/public/installing-odo.adoc
  rpms/openshift-odo.spec
  scripts/prepare-release.sh
Labels: approved, kind/documentation, lgtm

#4320 Update installing odo on Windows section
  docs/installing-odo.md
Labels: approved, kind/documentation

#4296 3823 refactor json
  go.mod
  go.sum
  tests/helper/helper_generic.go
  tests/integration/cmd_app_test.go
  tests/integration/cmd_pref_config_test.go
  tests/integration/cmd_storage_test.go
  tests/integration/cmd_url_test.go
  tests/integration/component.go
  tests/integration/devfile/cmd_devfile_describe_test.go
  tests/integration/devfile/cmd_devfile_storage_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_url_test.go
  tests/integration/generic_test.go
  tests/integration/project/cmd_project_test.go
  vendor/github.com/tidwall/gjson/LICENSE
  vendor/github.com/tidwall/gjson/README.md
  vendor/github.com/tidwall/gjson/SYNTAX.md
  vendor/github.com/tidwall/gjson/gjson.go
  vendor/github.com/tidwall/gjson/go.mod
  vendor/github.com/tidwall/gjson/go.sum
  vendor/github.com/tidwall/gjson/logo.png
  vendor/github.com/tidwall/match/.travis.yml
  vendor/github.com/tidwall/match/LICENSE
  vendor/github.com/tidwall/match/README.md
  vendor/github.com/tidwall/match/match.go
  vendor/github.com/tidwall/pretty/.travis.yml
  vendor/github.com/tidwall/pretty/LICENSE
  vendor/github.com/tidwall/pretty/README.md
  vendor/github.com/tidwall/pretty/pretty.go
  vendor/github.com/xanzy/ssh-agent/go.mod
  vendor/github.com/xanzy/ssh-agent/go.sum
  vendor/github.com/xanzy/ssh-agent/pageant_windows.go
  vendor/github.com/xanzy/ssh-agent/sshagent_windows.go
  vendor/modules.txt
Labels: approved, lgtm

#4323 Follow same initialization pattern as other clients
  pkg/kclient/kclient.go
Labels: approved, kind/cleanup, kind/code-refactoring, lgtm

#4316 Implement PVC for odo source volume
  go.sum
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/storage/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/odo/cli/preference/view.go
  pkg/preference/preference.go
  pkg/storage/labels/labels.go
  pkg/storage/storage.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/cmd_devfile_storage_test.go
Labels: approved, lgtm

#4324 Execute make target consecutively even on failure
  scripts/openshiftci-presubmit-all-tests.sh
Labels: approved, kind/feature, lgtm

#4332 override an env file if found without a devfile on odo create
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/interactive_create.go
  tests/helper/helper_run.go
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, kind/bug, lgtm
