Repository redhat-developer/odo, pull requests merged in 2020-05, with the labels that each got.

#3063 Update README
  README.adoc
Labels: kind/documentation

#2996 Remove oc setup for devfile push docker target
  .travis.yml
  Makefile
Labels: approved, area/testing, kind/cleanup, lgtm

#3043 Add support for command attribute `restart`
  pkg/devfile/adapters/common/command.go
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/exec/devfile.go
  tests/examples/source/devfiles/nodejs/devfile-with-restart.yaml
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, area/devfile, lgtm

#3058 Debug json flake fix
  tests/integration/cmd_debug_test.go
Labels: approved, kind/bug, kind/flake, lgtm

#3066 Integration test only for pr validation
  scripts/openshiftci-presubmit-integration-tests.sh
Labels: approved, kind/cleanup, lgtm

#3080 Clarifies 1 code reviewer, 1 approver
  docs/dev/development.adoc
Labels: kind/documentation, lgtm

#3045 Add devfile and community documentation to /public
  docs/public/community.adoc
  docs/public/deploying-a-devfile-using-odo.adoc
Labels: kind/documentation

#3056 Add instructions how to do commit signing
  docs/dev/development.adoc
Labels: approved, kind/documentation

#3084 Update web
  docs/configuring-the-odo-cli.md
  docs/creating-a-multicomponent-application-with-odo.md
  docs/creating-a-single-component-application-with-odo.md
  docs/creating-an-application-with-a-database.md
  docs/debugging-applications-in-odo.md
  docs/deploying-a-devfile-using-odo.md
  docs/installing-odo.md
  docs/odo-architecture.md
  docs/odo-cli-reference.md
  docs/understanding-odo.md
  docs/using-sample-applications.md
  index.md
Labels: kind/documentation, lgtm

#3087 Update site
  docs/configuring-the-odo-cli.md
  docs/creating-a-multicomponent-application-with-odo.md
  docs/creating-a-single-component-application-with-odo.md
  docs/creating-an-application-with-a-database.md
  docs/debugging-applications-in-odo.md
  docs/deploying-a-devfile-using-odo.md
  docs/installing-odo.md
  docs/odo-architecture.md
  docs/odo-cli-reference.md
  docs/understanding-odo.md
  docs/using-sample-applications.md
Labels: kind/documentation

#3088 Update notes regarding pandoc
  README.md
Labels: kind/documentation

#2962 Fixing component description to consider local config and cluster
  docs/dev/machine-output.adoc
  pkg/component/component_full_description.go
  pkg/odo/cli/component/describe.go
  tests/integration/component.go
Labels: approved, kind/bug, lgtm

#3037 Display warning if env.yaml has urls for another push target but no valid urls for current push target
  pkg/devfile/adapters/interface.go
  pkg/envinfo/envinfo.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/url/create.go
  pkg/url/url.go
  pkg/url/url_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_url_test.go
Labels: approved, area/devfile, area/url, kind/bug, lgtm

#3082 Adding execute permission to integration presubmit file
  scripts/openshiftci-presubmit-integration-tests.sh
Labels: approved, kind/bug, lgtm

#3109 Upgrade the minikube version on travis CI
  .travis.yml
  scripts/oc-cluster.sh
Labels: approved, kind/feature, lgtm

#3090 Support context in `odo push` commands
  pkg/devfile/adapters/common/types.go
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/helper.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/component/watch.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/cmd_devfile_watch_test.go
Labels: approved, area/devfile, kind/feature, lgtm

#3054 Fixes second push after creating and pushing URL
  pkg/kclient/fake/ingress.go
  pkg/url/url.go
  pkg/url/url_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
Labels: approved, kind/bug, lgtm

#3065 Remove devfile integration test dependency on git clone
  .DS_Store
  .gitignore
  .travis.yml
  tests/examples/source/devfiles/nodejs/project/app/app.js
  tests/examples/source/devfiles/nodejs/project/package.json
  tests/examples/source/devfiles/springboot/project/.gitignore
  tests/examples/source/devfiles/springboot/project/pom.xml
  tests/examples/source/devfiles/springboot/project/src/main/java/application/Info.java
  tests/examples/source/devfiles/springboot/project/src/main/java/application/SBApplication.java
  tests/examples/source/devfiles/springboot/project/src/main/java/application/rest/v1/Example.java
  tests/examples/source/devfiles/springboot/project/src/main/resources/application-local.properties
  tests/examples/source/devfiles/springboot/project/src/main/resources/application.properties
  tests/examples/source/openjdk-sb-postgresql/.gitignore
  tests/examples/source/openjdk/.gitignore
  tests/examples/source/wildfly/.gitignore
  tests/integration/devfile/cmd_devfile_delete_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_delete_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_url_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, kind/cleanup, kind/flake, lgtm

#2881 Remedy panic slice-out-bounds error when using `odo update`
  pkg/occlient/occlient.go
  pkg/occlient/volumes.go
  pkg/occlient/volumes_test.go
Labels: approved, kind/bug, lgtm

#3120 Update Docker Supervisord Initialization Spinner and Supervisord Vol Name
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/docker/component/utils_test.go
  pkg/devfile/adapters/docker/storage/utils.go
  pkg/devfile/adapters/docker/storage/utils_test.go
  pkg/devfile/adapters/docker/utils/utils.go
Labels: approved, kind/bug, kind/cleanup, lgtm

#2940 Dynamic registry support
  .travis.yml
  Makefile
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  pkg/catalog/types.go
  pkg/odo/cli/catalog/list/components.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/registry/add.go
  pkg/odo/cli/registry/delete.go
  pkg/odo/cli/registry/list.go
  pkg/odo/cli/registry/registry.go
  pkg/odo/cli/registry/update.go
  pkg/preference/preference.go
  pkg/preference/preference_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/integration/devfile/cmd_devfile_catalog_test.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/cmd_devfile_registry_test.go
Labels: approved, area/devfile, kind/feature, lgtm

#3029 Documentation for Odo integration with Operator Hub
  docs/public/operator-hub.adoc
Labels: approved, do-not-merge/hold, kind/documentation

#3146 Update bootstrap odo-init-image to 1.1.3
  pkg/devfile/adapters/common/utils.go
Labels: approved, kind/feature, lgtm

#2993 Add storage volume deletion to 'odo delete' docker devfile deletion
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/docker/component/adapter_test.go
  pkg/lclient/storage.go
  pkg/lclient/storage_test.go
  tests/helper/helper_docker.go
  tests/integration/devfile/docker/cmd_docker_devfile_delete_test.go
Labels: approved, area/devfile, kind/feature, lgtm, ok-to-test

#3119 Set ResponseHeaderTimeout for GET requests
  pkg/util/util.go
Labels: approved, area/devfile, kind/bug, lgtm

#3103 JSON output: use odo.dev instead of odo.openshift.io apigroup
  docs/dev/development.adoc
  docs/dev/machine-output.adoc
  docs/proposals/odo-debug.md
  pkg/application/application.go
  pkg/catalog/catalog.go
  pkg/component/component.go
  pkg/component/component_full_description.go
  pkg/component/component_test.go
  pkg/config/config.go
  pkg/machineoutput/types.go
  pkg/odo/cli/catalog/util/util_test.go
  pkg/preference/preference.go
  pkg/project/project.go
  pkg/service/service.go
  pkg/service/service_test.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  pkg/url/url.go
  tests/integration/cmd_app_test.go
  tests/integration/cmd_storage_test.go
  tests/integration/cmd_url_test.go
  tests/integration/component.go
  tests/integration/devfile/cmd_devfile_url_test.go
  tests/integration/generic_test.go
  tests/integration/project/cmd_project_test.go
Labels: approved, kind/api-change, kind/cleanup, lgtm

#3159 Synchronizes docs to the site
  docs/installing-odo.md
Labels: kind/documentation

#3053 Updated README
  README.adoc
Labels: approved, kind/documentation, lgtm

#3121 Don't set a default value for -o flag and fix `ODO_LOG_LEVEL` check
  cmd/odo/odo.go
  pkg/odo/cli/cli.go
  pkg/odo/genericclioptions/runnable.go
Labels: approved, kind/bug, lgtm

#3150 fix: improve documentation
  docs/public/deploying-a-devfile-using-odo.adoc
Labels: approved, kind/documentation, lgtm

#3086 url list and describe for docker
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/docker/component/utils_test.go
  pkg/devfile/adapters/docker/utils/utils.go
  pkg/devfile/adapters/docker/utils/utils_test.go
  pkg/lclient/containers_test.go
  pkg/lclient/fakeclient.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/describe.go
  pkg/odo/cli/url/list.go
  pkg/url/types.go
  pkg/url/url.go
  pkg/url/url_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_url_test.go
  vendor/github.com/docker/docker/api/types/types.go
Labels: approved, area/devfile, area/local, area/url, kind/feature, lgtm

#3069 List services started from operators
  pkg/kclient/deployments.go
  pkg/kclient/operators.go
  pkg/odo/cli/service/list.go
  pkg/service/service.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/feature, lgtm

#3044 Allow a project to be specified in --downloadSource
  pkg/odo/cli/component/create.go
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, area/devfile, kind/feature, lgtm, ok-to-test

#3116 Fix URL create on Docker with no Kube config
  pkg/odo/cli/url/create.go
Labels: approved, area/devfile, area/local, kind/bug, lgtm

#3158 Add operator hub documentation
  docs/public/operator-hub.adoc
Labels: kind/documentation, lgtm

#3181 Release 1.2.1 of odo
  Dockerfile.rhel
  pkg/version/version.go
  scripts/installer.sh
  scripts/rpm-prepare.sh
Labels: approved, kind/feature, lgtm

#3183 Remove logo / mentions of Red Hat & IBM
  _config.yml
  assets/img/ibm.png
  assets/img/redhat_ibm.png
  doks-theme/_includes/site-head.html
  doks-theme/_layouts/homepage.html
  favicon.ico
  index.md
Labels: kind/documentation

#3124 Fix odo fake component create on kubernetes cluster
  pkg/occlient/occlient.go
  pkg/odo/cli/component/create.go
Labels: approved, kind/bug, lgtm

#3189 add mik-dass and dharmit as top level approvers
  OWNERS
Labels: approved, lgtm

#3191 Add Operator Hub documentation, fix scripts, sync docs.
  chosen-docs/upstream/operator-hub.md
  docs/creating-a-multicomponent-application-with-odo.md
  docs/creating-a-single-component-application-with-odo.md
  docs/creating-an-application-with-a-database.md
  docs/deploying-a-devfile-using-odo.md
  docs/odo-architecture.md
  docs/operator-hub.md
  docs/understanding-odo.md
  docs/using-sample-applications.md
  index.md
  scripts/sync.sh
Labels: kind/documentation

#3171 Add .gitignore files for jekyll / site
  .gitignore
Labels: approved, kind/code-refactoring, lgtm

#3112 Performance improvement for odo catalog list components when using devfiles
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  pkg/catalog/types.go
  pkg/odo/cli/catalog/list/components.go
  pkg/odo/util/completion/completionhandlers.go
  pkg/util/concurrent.go
  pkg/util/util.go
Labels: approved, area/devfile, kind/feature, lgtm, ok-to-test

#3194 V2 command
  pkg/devfile/adapters/common/command.go
  pkg/devfile/adapters/common/command_test.go
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/parser/data/common/types.go
  pkg/exec/devfile.go
Labels: kind/code-refactoring

#3195 Fixes utils of k8s adapter
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/kclient/generators.go
Labels: kind/code-refactoring

#3196 Update Command Logic to use groups
  pkg/devfile/adapters/common/command.go
Labels: kind/code-refactoring

#3186 JSON output for service list in experimental mode
  pkg/odo/cli/service/list.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/feature, lgtm

#3200 Updates create logic to v2
  pkg/odo/cli/component/create.go
Labels: kind/code-refactoring

#3187 Adds a document for debugging applications using devfiles
  docs/public/debugging-using-devfile.adoc
Labels: approved, kind/documentation, lgtm

#3198 Fixes utils of docker adapter
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/docker/utils/utils.go
Labels: kind/code-refactoring

#3206 Update Docker and Kubernetes adapter to use groups
  pkg/devfile/adapters/common/command.go
  pkg/devfile/adapters/common/types.go
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
Labels: kind/code-refactoring

#3219 Fixes lower and upper case for commands
  pkg/devfile/parser/data/1.0.0/components.go
Labels: kind/code-refactoring, lgtm

#2397 Add --wait to project delete
  pkg/occlient/occlient.go
  pkg/odo/cli/project/delete.go
  pkg/project/project.go
  pkg/project/project_test.go
  tests/integration/project/cmd_project_test.go
Labels: approved, kind/feature, lgtm, size/L

#3228 Fixes type of project and components for devfile v1
  pkg/devfile/parser/data/1.0.0/components.go
  pkg/devfile/parser/data/2.0.0/types.go
  pkg/devfile/validate/components.go
  pkg/odo/cli/component/create.go
Labels: kind/code-refactoring, lgtm

#3223 Run devfile docker url tests without kube config
  .travis.yml
  Makefile
  tests/integration/devfile/docker/cmd_docker_devfile_url_pushtarget_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_url_test.go
Labels: approved, area/devfile, kind/cleanup, lgtm

#3204 Setting golang version uniformly accross repo and updating docs
  .travis.yml
  Dockerfile.rhel
  docs/dev/development.adoc
  openshift-ci/build-root/Dockerfile
Labels: approved, kind/code-refactoring, kind/documentation, lgtm

#3224 Fix odo describe not listing all the ports after first url is created
  pkg/component/component.go
  tests/integration/component.go
Labels: approved, lgtm, ok-to-test

#3172 Support listing devfile components with no devBuild command
  pkg/catalog/catalog.go
  tests/integration/devfile/cmd_devfile_catalog_test.go
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, area/devfile, kind/bug, lgtm

#3238 replace secured with secure
  pkg/odo/cli/url/create.go
Labels: approved, kind/bug, lgtm

#3233 Running devfile integration tests on kubernetes cluster
  docs/dev/development.adoc
Labels: approved, kind/documentation, lgtm

#3240 Fixes unit tests
  pkg/devfile/adapters/docker/component/adapter_test.go
  pkg/devfile/adapters/docker/component/utils_test.go
  pkg/devfile/adapters/docker/storage/adapter_test.go
  pkg/devfile/adapters/docker/storage/utils_test.go
  pkg/devfile/adapters/docker/utils/utils_test.go
  pkg/devfile/adapters/helper_test.go
  pkg/devfile/adapters/kubernetes/storage/utils_test.go
  pkg/devfile/adapters/kubernetes/utils/utils_test.go
  pkg/devfile/validate/components_test.go
  pkg/kclient/volumes_test.go
  pkg/sync/adapter_test.go
  pkg/testingutil/devfile.go
Labels: kind/code-refactoring

#3239 Modify operator hub tests to run in separate namespaces
  Makefile
  scripts/setup-operators.sh
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/cleanup, kind/failing-test, lgtm

#3075 Add devfile command flags to watch
  .travis.yml
  Makefile
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/envinfo/envinfo.go
  pkg/envinfo/envinfo_test.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/component/watch.go
  pkg/watch/watch.go
  pkg/watch/watch_test.go
  tests/e2escenarios/e2e_images_test.go
  tests/integration/devfile/cmd_devfile_watch_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_watch_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, kind/feature, lgtm

#3042 Adding sparseCheckoutDir functionality to devfiles
  pkg/odo/cli/component/create.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/examples/source/devfiles/nodejs/devfile-with-sparseCheckoutDir.yaml
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, area/devfile, kind/feature, lgtm, ok-to-test

#3218 Run test locally against 4.* Cluster
  docs/dev/development.adoc
Labels: approved, kind/documentation, lgtm

#3163 Update samples for deploying a devfile in deploying-a-devfile-using-odo.adoc
  docs/public/deploying-a-devfile-using-odo.adoc
Labels: approved, kind/documentation, lgtm

#3258 Fix regression by sparse checkout dir PR on devfile V2
  pkg/devfile/parser/data/1.0.0/components.go
  pkg/devfile/parser/data/1.0.0/types.go
  pkg/odo/cli/component/create.go
Labels: kind/code-refactoring

#3267 Address review comments for devfile V2 PR
  pkg/devfile/adapters/common/command.go
  pkg/devfile/adapters/common/types.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/parser/data/common/types.go
Labels: kind/code-refactoring

#3251 Replace multiple expect statement with MatchAllInOutput and DontMatchAllInOutput
  tests/e2escenarios/e2e_beta_test.go
  tests/integration/cmd_pref_config_test.go
  tests/integration/cmd_push_test.go
  tests/integration/component.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
  tests/integration/devfile/utils/utils.go
  tests/integration/generic_test.go
  tests/integration/operatorhub/cmd_service_test.go
  tests/integration/servicecatalog/cmd_link_unlink_test.go
  tests/integration/servicecatalog/cmd_service_test.go
Labels: approved, kind/cleanup, kind/code-refactoring, lgtm
