Repository redhat-developer/odo, pull requests merged in 2020-03, with the labels that each got.

#2648 Adds auto selection of port if the default port is occupied
  Makefile
  pkg/debug/info_test.go
  pkg/odo/cli/debug/portforward.go
  pkg/testingutil/httputils.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/helper/helper_http.go
  tests/helper/helper_run.go
  tests/integration/cmd_debug_test.go
  tests/integration/debug/cmd_debug_test.go
  tests/integration/debug/debug_suite_test.go
Labels: approved, kind/feature, lgtm, size/L

#2660 fix failing gosec check
  pkg/component/component.go
  pkg/occlient/occlient.go
  pkg/util/config_util.go
  pkg/util/file_indexer.go
  pkg/util/util.go
  tests/helper/helper_filesystem.go
Labels: approved, lgtm, size/S

#2626 Move file sync to its own package
  pkg/component/component.go
  pkg/kclient/pods.go
  pkg/occlient/occlient.go
  pkg/sync/sync.go
Labels: approved, kind/code-refactoring, kind/feature, lgtm, size/L

#2632 Fix odo describe for not pushed components
  pkg/odo/util/cmdutils.go
  pkg/storage/storage.go
  tests/integration/component.go
Labels: approved, lgtm, size/M

#2636 create env.yaml file, add kclient function for ingress support
  pkg/envinfo/envinfo.go
  pkg/envinfo/envinfo_test.go
  pkg/kclient/generators.go
  pkg/kclient/generators_test.go
  pkg/kclient/ingress.go
  pkg/kclient/secrets.go
  pkg/odo/cli/component/common_push.go
  pkg/odo/cli/url/create.go
Labels: approved, kind/feature, lgtm, ok-to-test, size/XL

#2631 removed duplicate LocalConfigInfo and redundent file reads
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/odo/cli/component/common_push.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/describe.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/component/watch.go
  pkg/odo/cli/config/set.go
  pkg/odo/cli/config/unset.go
  pkg/odo/cli/debug/info.go
  pkg/odo/cli/debug/portforward.go
  pkg/odo/cli/storage/create.go
  pkg/odo/cli/storage/delete.go
  pkg/odo/cli/storage/list.go
  pkg/odo/cli/url/delete.go
  pkg/odo/cli/url/list.go
  pkg/odo/genericclioptions/context.go
Labels: approved, kind/code-refactoring, lgtm, size/L

#2645 Fix odo catalog describe service command to not require odo config file
  pkg/odo/cli/catalog/describe/service.go
  pkg/odo/genericclioptions/context.go
Labels: approved, lgtm, size/S

#2656 Implement PushTarget preference
  pkg/odo/cli/preference/view.go
  pkg/odo/util/pushtarget/pushtarget.go
  pkg/odo/util/pushtarget/pushtarget_test.go
  pkg/preference/preference.go
  pkg/preference/preference_test.go
  tests/integration/cmd_pref_config_test.go
Labels: approved, kind/feature, lgtm, size/L

#2676 added a CmdShouldFail test helper which retries until it fails
  tests/helper/helper_run.go
Labels: approved, kind/feature, lgtm, size/S

#2685 Update Google Groups Link
  README.adoc
Labels: approved, lgtm, size/XS

#2644 Update Storage Type
  docs/dev/machine-output.md
  pkg/odo/cli/storage/list.go
  pkg/odo/cli/storage/storage.go
  pkg/odo/util/cmdutils.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  pkg/storage/types.go
  tests/integration/cmd_storage_test.go
Labels: approved, lgtm, release-note, size/M

#2637 Devfile support for odo catalog list components
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  pkg/catalog/types.go
  pkg/odo/cli/catalog/list/components.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, kind/feature, lgtm, ok-to-test, size/XL

#2562 Unit test on windows
  .travis.yml
  pkg/component/watch_test.go
  pkg/debug/info_test.go
  pkg/occlient/occlient.go
  pkg/odo/cli/service/ui/ui_test.go
  pkg/testingutil/survey_ui.go
  pkg/util/util_test.go
Labels: approved, kind/feature, lgtm, size/M

#2649 run validate with unit tests on OpenShift CI
  .travis.yml
  Makefile
  scripts/openshiftci-presubmit-unittests.sh
Labels: approved, lgtm, size/S

#2675 Rename -all flag for odo list and Update description
  pkg/odo/cli/component/list.go
  tests/integration/component.go
Labels: approved, lgtm, size/S

#2651 Add Volume Storage Adapter for Devfiles
  pkg/devfile/adapters/common/interface.go
  pkg/devfile/adapters/common/types.go
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/common/utils_test.go
  pkg/devfile/adapters/kubernetes/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/storage/adapter.go
  pkg/devfile/adapters/kubernetes/storage/utils.go
  pkg/devfile/adapters/kubernetes/storage/utils_test.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/kclient/deployments_test.go
  pkg/kclient/fakeclient.go
  pkg/kclient/generators.go
  pkg/kclient/kclient.go
  pkg/kclient/pods_test.go
  pkg/kclient/volumes.go
  pkg/kclient/volumes_test.go
  pkg/odo/cli/component/devfile.go
  pkg/testingutil/devfile.go
Labels: approved, kind/feature, lgtm, size/XL

#2698 Update CheckForExistence to get right resource
  tests/helper/helper_oc.go
Labels: approved, kind/cleanup, lgtm, size/XS

#2711 Release 1.1.1 of odo
  Dockerfile.rhel
  pkg/version/version.go
  scripts/installer.sh
  scripts/rpm-prepare.sh
Labels: approved, lgtm, size/XS

#2715 Update build version to 1.1.1
  build/VERSION
Labels: kind/feature, size/XS

#2681 File sync for devfiles
  .travis.yml
  Makefile
  pkg/component/component.go
  pkg/devfile/adapters/common/interface.go
  pkg/devfile/adapters/helper.go
  pkg/devfile/adapters/interface.go
  pkg/devfile/adapters/kubernetes/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/versions/1.0.0/components.go
  pkg/devfile/versions/interface.go
  pkg/kclient/generators.go
  pkg/kclient/generators_test.go
  pkg/kclient/pods.go
  pkg/kclient/volumes_test.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/push.go
  pkg/sync/sync.go
  pkg/testingutil/devfile.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/examples/source/devfiles/nodejs-multicontainer/.gitignore
  tests/examples/source/devfiles/nodejs-multicontainer/devfile.yaml
  tests/examples/source/devfiles/nodejs-multicontainer/package.json
  tests/examples/source/devfiles/nodejs-multicontainer/server.js
  tests/examples/source/devfiles/nodejs/.gitignore
  tests/examples/source/devfiles/nodejs/devfile.yaml
  tests/examples/source/devfiles/nodejs/package.json
  tests/examples/source/devfiles/nodejs/server.js
  tests/helper/helper_oc.go
  tests/integration/cmd_devfile_push_test.go
Labels: approved, kind/feature, lgtm, size/XXL

#2712 Update release script
  scripts/changelog-script.sh
Labels: approved, kind/cleanup, lgtm, size/XS

#2718 Create a secret directory in docker file for private registry
  openshift-ci/build-root/Dockerfile
Labels: approved, kind/bug, lgtm, size/XS

#2687 Update the README with corresponding languages and package managers
  README.adoc
Labels: approved, size/M

#2678 Add machine output documentation
  docs/dev/machine-output.adoc
  scripts/generate-machineooutput-doc.sh
Labels: approved, lgtm, size/L

#2713 Updates release notes
  docs/dev/development.adoc
Labels: approved, kind/documentation, lgtm, size/XS

#2692 Fixes watch unit tests for windows
  pkg/component/watch_test.go
Labels: approved, kind/bug, lgtm, size/XS

#2667 Fake filesystem changes to devfile parser
  pkg/devfile/parser/apiVersion.go
  pkg/devfile/parser/apiVersion_test.go
  pkg/devfile/parser/content.go
  pkg/devfile/parser/content_test.go
Labels: approved, lgtm, size/L

#2720 Update labeling for GitHub issues
  .github/ISSUE_TEMPLATE/Feature.md
  .github/ISSUE_TEMPLATE/UserStory.md
Labels: approved, kind/documentation, lgtm, size/XS

#2702 Fixes debug info test for windows
  pkg/debug/info_test.go
Labels: approved, kind/flake, lgtm, size/S

#2708 add app and project in the create service equivalent command template
  pkg/odo/cli/service/create.go
  pkg/odo/cli/service/create_test.go
Labels: approved, kind/bug, lgtm, size/M

#2714 Add additional information to pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, kind/documentation, lgtm, size/XS

#2627 Adds event information when waiting for a pod
  pkg/log/fidget/spinner.go
  pkg/log/status.go
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/odo/util/cmdutils.go
Labels: approved, kind/feature, lgtm, size/L

#2330 Fixes wait for project creation
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/project/project.go
  pkg/project/project_test.go
  tests/integration/project/cmd_project_test.go
Labels: approved, kind/bug, lgtm, size/L

#2679 create services together with deployment during devfile push
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/kclient/deployments_test.go
  pkg/kclient/generators.go
  pkg/kclient/generators_test.go
  pkg/kclient/services.go
  pkg/kclient/services_test.go
  tests/examples/source/devfiles/nodejs-multicontainer/devfile.yaml
  tests/examples/source/devfiles/nodejs/devfile.yaml
  tests/helper/helper_filesystem.go
  tests/integration/cmd_devfile_push_test.go
Labels: approved, kind/feature, lgtm, ok-to-test, size/L

#2599 Speeds up integration test for deletion of owned resources
  tests/helper/helper_oc.go
  tests/integration/component.go
Labels: approved, kind/code-refactoring, lgtm, size/S

#2694 Add support for url describe command
  pkg/occlient/occlient.go
  pkg/odo/cli/url/describe.go
  pkg/odo/cli/url/url.go
  pkg/url/url.go
  tests/integration/cmd_url_test.go
Labels: approved, kind/feature, lgtm, ok-to-test, size/L

#2674 Removes the annotation 'app.openshift.io/vcs-uri' for local and binary components
  docs/dev/machine-output.adoc
  pkg/component/component.go
  pkg/devfile/versions/1.0.0/devfileJsonSchema100.go
  pkg/devfile/versions/common/types.go
  pkg/occlient/occlient_test.go
  pkg/odo/cli/component/list.go
  tests/integration/cmd_app_test.go
  tests/integration/component.go
Labels: approved, lgtm, release-note, size/M

#2491 Delete services belonging to an application during 'odo app delete'
  pkg/application/application.go
  pkg/application/labels/labels.go
  pkg/component/labels/labels.go
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/odo/cli/application/application.go
  tests/helper/helper_generic.go
  tests/integration/servicecatalog/cmd_service_test.go
Labels: approved, kind/bug, lgtm, size/M

#2731 Wait for rollout
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/kclient/deployments.go
  tests/examples/source/devfiles/nodejs/devfile.yaml
  tests/helper/helper_filesystem.go
  tests/integration/cmd_devfile_push_test.go
Labels: approved, area/devfile, kind/bug, lgtm

#2760 Error checking was removed for WaitAndGetPod
  pkg/occlient/occlient.go
Labels: approved, kind/bug, lgtm

#2699 Devfile support for odo create
  .travis.yml
  Makefile
  pkg/catalog/catalog.go
  pkg/catalog/types.go
  pkg/envinfo/envinfo.go
  pkg/envinfo/envinfo_test.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/ui/ui.go
  pkg/util/config_util.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/integration/cmd_devfile_create_test.go
Labels: approved, kind/feature, lgtm, ok-to-test, size/L

#2749 List devfile component without connecting cluster if experimental flag is enabled
  pkg/odo/cli/catalog/list/components.go
Labels: approved, kind/bug, lgtm

#2759 Add tests for --help / -h / help
  tests/integration/cmd_pref_config_test.go
Labels: approved, kind/test, lgtm

#2764 Fixed get service command flake
  tests/integration/servicecatalog/cmd_service_test.go
Labels: approved, kind/flake, lgtm

#2736 Odo catalog list components format
  .travis.yml
  Makefile
  pkg/odo/cli/catalog/list/components.go
  tests/integration/cmd_devfile_catalog_test.go
Labels: approved, kind/feature, lgtm, ok-to-test

#2767 Fixing app delete flake in service test file
  tests/integration/servicecatalog/cmd_service_test.go
Labels: approved, kind/bug, lgtm

#2747 If clonePath is set, sync to it
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
Labels: approved, kind/bug, lgtm

#2750 Fixes storage owner references.
  pkg/occlient/volumes.go
  pkg/occlient/volumes_test.go
  tests/helper/helper_oc.go
  tests/integration/component.go
Labels: approved, kind/bug, lgtm

#2772 Fixes hardcoded directory strings with env variables
  tests/integration/cmd_push_test.go
Labels: approved, kind/code-refactoring, lgtm
