Repository redhat-developer/odo, pull requests merged in 2020-08, with the labels that each got.

#3649 make odo delete work on s2i components in experimental mode
  pkg/odo/cli/url/delete.go
Labels: approved, lgtm

#3666 Fixes GetRunningPodNameByComponent for the CLI runners
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
Labels: approved, kind/bug, lgtm

#3674 increase ResponseHeaderTimeout
  pkg/util/util.go
Labels: approved, kind/flake, lgtm

#3662 Make the file sync destination more consistent
  docs/public/debugging-using-devfile.adoc
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/common/utils_test.go
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/sync/adapter.go
  pkg/sync/adapter_test.go
  tests/examples/source/devfiles/nodejs/devfile-no-endpoints.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-debugrun.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-multiple-defaults.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-parent.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-post-start.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-restart.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-sparseCheckoutDir.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-testgroup.yaml
  tests/examples/source/devfiles/nodejs/devfile-without-devbuild.yaml
  tests/examples/source/devfiles/nodejs/devfile-without-devinit.yaml
  tests/examples/source/devfiles/nodejs/devfile.yaml
  tests/examples/source/devfiles/nodejs/devfileCompositeCommands.yaml
  tests/examples/source/devfiles/nodejs/devfileCompositeCommandsParallel.yaml
  tests/examples/source/devfiles/nodejs/devfileCompositeNonExistent.yaml
  tests/examples/source/devfiles/nodejs/devfileCompositeRun.yaml
  tests/examples/source/devfiles/nodejs/devfileIndirectNesting.yaml
  tests/examples/source/devfiles/nodejs/devfileNestedCompCommands.yaml
  tests/examples/source/devfiles/springboot/devfile-with-metadataname-foobar.yaml
  tests/examples/source/devfiles/springboot/devfile.yaml
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/cmd_devfile_test_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_test_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, kind/cleanup, lgtm

#3669 make odo catalog list components work outside of experimental mode
  pkg/catalog/catalog.go
  pkg/odo/cli/catalog/list/components.go
Labels: approved, kind/feature, lgtm

#3658 Validate exec subcommands in a composite
  pkg/devfile/adapters/common/command.go
  pkg/devfile/adapters/common/command_test.go
  tests/examples/source/devfiles/nodejs/devfileCompositeInvalidComponent.yaml
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, kind/bug, lgtm

#3688 Update to 1.1.5 image
  pkg/devfile/adapters/common/utils.go
Labels: approved, kind/feature, lgtm

#3689 Release 1.2.5
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, kind/feature

#3696 Add installation documentation
  docs/public/installing-odo.adoc
Labels: kind/documentation

#3647 add Kubernetes namespace support
  .travis.yml
  pkg/kclient/namespace.go
  pkg/kclient/namespace_test.go
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/odo/cli/component/common_push.go
  pkg/odo/cli/project/create.go
  pkg/odo/cli/project/delete.go
  pkg/odo/cli/project/list.go
  pkg/odo/cli/project/project.go
  pkg/odo/cli/project/set.go
  pkg/odo/cli/service/create_test.go
  pkg/odo/cli/service/service_test.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/genericclioptions/fakecontext.go
  pkg/odo/util/completion/completionhandlers_test.go
  pkg/project/project.go
  pkg/project/project_test.go
  pkg/testingutil/projects.go
Labels: approved, lgtm

#3694 Fix typo when setting PROJECTS_ROOT env on docker
  pkg/devfile/adapters/docker/component/utils.go
Labels: approved, kind/bug, lgtm

#3682 Update golangci-lint to latest version and fix some linting errors
  Makefile
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/parser/context/schema.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/service/create.go
  tests/integration/cmd_url_test.go
Labels: approved, lgtm

#3545 feature #3403 : Added --s2i flag for 'odo create' command
  docs/dev/experimental-mode.adoc
  pkg/component/types.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/push.go
  tests/integration/component.go
  tests/integration/devfile/cmd_devfile_catalog_test.go
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, kind/feature, lgtm

#3631 PreStop Event Feature
  pkg/devfile/adapters/common/command.go
  pkg/devfile/adapters/common/command_test.go
  pkg/devfile/adapters/common/interface.go
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/docker/adapter.go
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/docker/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/validate/errors.go
  pkg/devfile/validate/events.go
  pkg/devfile/validate/events_test.go
  pkg/devfile/validate/validate.go
  pkg/kclient/errors.go
  pkg/kclient/pods.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/devfile.go
  pkg/testingutil/devfile.go
  pkg/testingutil/pods.go
  tests/examples/source/devfiles/nodejs/devfile-with-valid-events.yaml
  tests/integration/devfile/cmd_devfile_delete_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/cmd_devfile_test_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
Labels: approved, kind/feature, lgtm

#3648 Add Json output for registry output
  pkg/machineoutput/registry.go
  pkg/odo/cli/registry/list.go
  tests/integration/devfile/cmd_devfile_registry_test.go
Labels: approved, lgtm

#3628 Fix project unzip function on Windows
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, kind/bug, lgtm, ok-to-test

#3654 Fixes odo watch when delay is set to 0
  pkg/watch/watch.go
  tests/helper/helper_generic.go
  tests/integration/devfile/cmd_devfile_watch_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, kind/bug, lgtm

#3596 refactor: simplify execution of devfile commands
  pkg/component/component.go
  pkg/devfile/adapters/common/command.go
  pkg/devfile/adapters/common/command_composite.go
  pkg/devfile/adapters/common/command_parallel_composite.go
  pkg/devfile/adapters/common/command_simple.go
  pkg/devfile/adapters/common/command_supervisor.go
  pkg/devfile/adapters/common/exec.go
  pkg/devfile/adapters/common/executor.go
  pkg/devfile/adapters/common/generic.go
  pkg/devfile/adapters/common/generic_test.go
  pkg/devfile/adapters/common/interface.go
  pkg/devfile/adapters/common/types.go
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/docker/adapter.go
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/docker/component/adapter_test.go
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/docker/component/utils_test.go
  pkg/devfile/adapters/interface.go
  pkg/devfile/adapters/kubernetes/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/exec/devfile.go
  pkg/log/status.go
  pkg/machineoutput/event_logging.go
  pkg/machineoutput/services.go
  pkg/odo/cli/catalog/list/services.go
  pkg/sync/adapter.go
  pkg/testingutil/devfile.go
  tests/helper/helper_docker.go
  tests/integration/devfile/docker/cmd_docker_devfile_test_test.go
Labels: approved, kind/code-refactoring, lgtm

#3719 Remove docker tests
  .travis.yml
Labels: approved, lgtm

#3715 Skiping s2iItem check on kubernetes cluster
  tests/integration/devfile/cmd_devfile_catalog_test.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, kind/bug, kind/cleanup, kind/code-refactoring, kind/failing-test, lgtm

#3723 Get only project name
  tests/integration/project/cmd_project_test.go
Labels: approved, lgtm

#3706 Removing the unsupported ruby image test
  tests/integration/component.go
Labels: approved, kind/bug, lgtm

#3643 CI support for ODO on IBM P
  Makefile
  docs/dev/test-architecture-ppc64le.adoc
  scripts/configure-installer-tests-cluster-ppc64le.sh
  scripts/openshiftci-presubmit-all-tests.sh
Labels: approved, area/System-PZ, lgtm, ok-to-test

#3730 Docker test target clean up
  .travis.yml
Labels: approved, kind/cleanup, lgtm

#3642 Removing duplicates from devfile catalog test
  tests/integration/devfile/cmd_devfile_catalog_test.go
Labels: approved, kind/cleanup, lgtm

#3716 Update integration testcases and e2e testcases for S390x support
  scripts/configure-installer-tests-cluster-s390x.sh
  scripts/openshiftci-presubmit-all-tests.sh
  tests/e2escenarios/e2e_java_test.go
  tests/e2escenarios/e2e_source_test.go
  tests/integration/component.go
Labels: approved, area/System-PZ, kind/feature, lgtm, ok-to-test

#3616 Implement `odo env`
  .travis.yml
  Makefile
  pkg/envinfo/envinfo.go
  pkg/envinfo/envinfo_test.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/env/env.go
  pkg/odo/cli/env/env_test.go
  pkg/odo/cli/env/set.go
  pkg/odo/cli/env/unset.go
  pkg/odo/cli/env/view.go
  tests/integration/devfile/cmd_devfile_env_test.go
Labels: approved, area/devfile, kind/feature, lgtm

#3737 Applying secret to namespace for authenticated registry
  scripts/configure-installer-tests-cluster.sh
  tests/e2escenarios/e2e_images_test.go
Labels: approved, kind/bug, kind/feature, lgtm

#3746 Fixing cluster service version issue for operators on 4.6 cluster
  scripts/setup-operators.sh
Labels: approved, kind/bug, kind/feature, lgtm

#3748 add caching to version check
  pkg/notify/notify.go
Labels: approved, lgtm

#3740 Stop other commands in case of restart false
  pkg/devfile/adapters/common/generic.go
Labels: approved, lgtm

#3665 create url during push with infomation defined in devfile endpoint
  pkg/component/component.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/parser/data/2.0.0/types.go
  pkg/devfile/parser/data/common/types.go
  pkg/devfile/parser/types_test.go
  pkg/kclient/generators.go
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/odo/cli/component/common_push.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/describe.go
  pkg/testingutil/routes.go
  pkg/url/types.go
  pkg/url/url.go
  pkg/url/url_test.go
  tests/examples/source/devfiles/nodejs/devfile-with-multiple-endpoints.yaml
  tests/integration/cmd_url_test.go
  tests/integration/component.go
  tests/integration/devfile/cmd_devfile_url_test.go
Labels: approved, area/devfile, area/url, lgtm

#3626 Adds storage create and delete commands for devfiles.
  .travis.yml
  Makefile
  pkg/devfile/adapters/common/utils_test.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/storage/utils.go
  pkg/devfile/adapters/kubernetes/storage/utils_test.go
  pkg/devfile/parser/context/context.go
  pkg/devfile/parser/context/fake.go
  pkg/devfile/parser/data/1.0.0/components.go
  pkg/devfile/parser/data/2.0.0/components.go
  pkg/devfile/parser/data/2.0.0/components_test.go
  pkg/devfile/parser/data/common/errors.go
  pkg/devfile/parser/data/common/types.go
  pkg/devfile/parser/data/interface.go
  pkg/devfile/parser/writer.go
  pkg/devfile/parser/writer_test.go
  pkg/kclient/volumes.go
  pkg/odo/cli/storage/create.go
  pkg/odo/cli/storage/delete.go
  pkg/storage/labels/labels.go
  pkg/storage/storage.go
  pkg/testingutil/devfile.go
  tests/helper/helper_cli.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/cmd_storage_test.go
  tests/integration/devfile/cmd_devfile_storage_test.go
Labels: approved, kind/feature, lgtm

#3586 Watch command should better handle file synchronization/error reporting when push command is invoked before/after the watch
  pkg/devfile/adapters/common/types.go
  pkg/odo/cli/component/watch.go
  pkg/sync/adapter.go
  pkg/sync/adapter_test.go
  pkg/util/file_indexer.go
  pkg/util/file_indexer_test.go
  pkg/watch/watch.go
  pkg/watch/watch_test.go
  tests/helper/helper_cli.go
  tests/helper/helper_filesystem.go
  tests/helper/helper_generic.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/helper/helper_run.go
  tests/integration/devfile/cmd_devfile_watch_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, lgtm, ok-to-test

#3739 Updates the integration test for parent support.
  pkg/testingutil/httputils.go
  tests/examples/source/devfiles/openliberty/devfile-with-multi-layer-parent.yaml
  tests/examples/source/devfiles/openliberty/devfile-with-parent.yaml
  tests/examples/source/devfiles/openliberty/project/pom.xml
  tests/examples/source/devfiles/openliberty/project/src/main/java/dev/appsody/starter/StarterApplication.java
  tests/examples/source/devfiles/openliberty/project/src/main/java/dev/appsody/starter/StarterResource.java
  tests/examples/source/devfiles/openliberty/project/src/main/java/dev/appsody/starter/health/StarterLivenessCheck.java
  tests/examples/source/devfiles/openliberty/project/src/main/java/dev/appsody/starter/health/StarterReadinessCheck.java
  tests/examples/source/devfiles/openliberty/project/src/main/liberty/config/server.xml
  tests/examples/source/devfiles/openliberty/project/src/main/webapp/WEB-INF/beans.xml
  tests/examples/source/devfiles/openliberty/project/src/main/webapp/index.html
  tests/examples/source/devfiles/openliberty/project/src/test/java/it/dev/appsody/starter/HealthEndpointTest.java
  tests/examples/source/devfiles/parentSupport/devfile-middle-layer.yaml
  tests/examples/source/devfiles/parentSupport/devfile-with-multi-layer-parent.yaml
  tests/examples/source/devfiles/parentSupport/devfile-with-parent.yaml
  tests/examples/source/devfiles/parentSupport/devfile.yaml
  tests/helper/helper_http.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, kind/failing-test, lgtm

#3744 Update e2e supported images test to support s390x arch.
  README.adoc
  scripts/configure-installer-tests-cluster-s390x.sh
  scripts/openshiftci-presubmit-all-tests.sh
  tests/e2escenarios/e2e_images_test.go
Labels: approved, area/System-PZ, area/testing, lgtm, ok-to-test

#3760 Updates test for printSupportedParameters to fix flake
  pkg/odo/cli/env/env_test.go
Labels: approved, kind/failing-test, lgtm

#3733 Fix odo log flake
  tests/helper/helper_generic.go
  tests/integration/devfile/cmd_devfile_log_test.go
Labels: approved, kind/flake, lgtm

#3673 Implement Starter Projects for devfile
  pkg/devfile/parser/data/1.0.0/components.go
  pkg/devfile/parser/data/2.0.0/components.go
  pkg/devfile/parser/data/2.0.0/components_test.go
  pkg/devfile/parser/data/2.0.0/types.go
  pkg/devfile/parser/data/common/types.go
  pkg/devfile/parser/data/interface.go
  pkg/devfile/parser/parse.go
  pkg/devfile/parser/parse_test.go
  pkg/devfile/parser/types.go
  pkg/devfile/parser/types_test.go
  pkg/odo/cli/catalog/describe/component.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/ui/ui.go
  pkg/testingutil/devfile.go
  tests/examples/source/devfiles/nodejs/devfile-no-endpoints.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-debugrun.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-invalid-volmount.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-multiple-defaults.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-restart.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-sparseCheckoutDir.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-testgroup.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-valid-events.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-volume-components.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-volumes.yaml
  tests/examples/source/devfiles/nodejs/devfile-without-devbuild.yaml
  tests/examples/source/devfiles/nodejs/devfile-without-devinit.yaml
  tests/examples/source/devfiles/nodejs/devfile.yaml
  tests/examples/source/devfiles/nodejs/devfileCompositeCommands.yaml
  tests/examples/source/devfiles/nodejs/devfileCompositeCommandsParallel.yaml
  tests/examples/source/devfiles/nodejs/devfileCompositeNonExistent.yaml
  tests/examples/source/devfiles/nodejs/devfileCompositeRun.yaml
  tests/examples/source/devfiles/nodejs/devfileIndirectNesting.yaml
  tests/examples/source/devfiles/nodejs/devfileNestedCompCommands.yaml
  tests/examples/source/devfiles/nodejs/devfileSourceMapping.yaml
  tests/examples/source/devfiles/springboot/devfile-with-metadataname-foobar.yaml
  tests/examples/source/devfiles/springboot/devfile.yaml
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, lgtm

#3712 Add json format output to project get
  pkg/odo/cli/project/get.go
  tests/integration/project/cmd_project_test.go
Labels: approved, lgtm

#3765 Fix the make test-coverage for s390x arch
  scripts/generate-coverage.sh
Labels: approved, area/System-PZ, area/testing, lgtm, ok-to-test

#3726 Test guidelines updated to write proper tests and avoid duplicates
  .github/PULL_REQUEST_TEMPLATE.md
  docs/dev/test-architecture.adoc
  tests/template/template_cleantest_test.go
Labels: approved, kind/documentation, lgtm

#3777 Prevent v1 devfiles from being used
  pkg/devfile/validate/validate.go
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, kind/cleanup, lgtm

#3795 wrong commands in the odo.dev docs
  docs/creating-a-multicomponent-application-with-odo.md
  docs/creating-an-application-with-a-database.md
Labels: kind/documentation, lgtm

#3780 Update documents for s390x arch.
  docs/public/understanding-odo.adoc
Labels: approved, area/System-PZ, kind/documentation, lgtm, ok-to-test

#3619 Sync operation within the Push command does not remove deleted/renamed files
  pkg/devfile/adapters/common/exec.go
  pkg/devfile/adapters/common/exec_test.go
  pkg/sync/adapter.go
  pkg/sync/adapter_test.go
  tests/helper/helper_generic.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/utils/cmd_devfile_push_test_utils.go
Labels: approved, kind/bug, lgtm, ok-to-test

#3728 Fixes odo url list for s2i components
  pkg/odo/cli/url/list.go
  tests/integration/devfile/cmd_devfile_url_test.go
Labels: approved, kind/bug, lgtm

#3732 Docker test container for travis login
  openshift-ci/build-root/Dockerfile.travislogin
Labels: approved, kind/feature, lgtm

#3787 Adding plugin handler test makefile target
  .travis.yml
  Makefile
Labels: approved, kind/feature, lgtm

#3790 Fix describe to print out linked components list
  pkg/component/component_full_description.go
Labels: approved, kind/bug, lgtm, ok-to-test

#3793 clean up devfile env tests and uses dns supported component name
  tests/integration/devfile/cmd_devfile_env_test.go
Labels: approved, kind/cleanup, lgtm

#3802 Applying secret to namespace for authenticated registry for s390x
  scripts/configure-installer-tests-cluster-s390x.sh
Labels: approved, area/System-PZ, area/testing, kind/feature, lgtm, needs-ok-to-test

#3804 Fix odo describe for component with linked services
  pkg/component/component_full_description.go
Labels: approved, kind/bug, lgtm, ok-to-test

#3805 remove showing help twice for incorrect commands
  pkg/odo/cli/cli.go
  tests/integration/generic_test.go
Labels: approved, kind/bug, lgtm

#3806 add json output test for preference view
  tests/integration/cmd_pref_config_test.go
Labels: approved, lgtm

#3813 Fixing rvm error and Docker file format for travis login
  openshift-ci/build-root/Dockerfile.travislogin
Labels: approved, kind/bug, lgtm

#3820 Replace unstable mongodb-enterprise operator subscription with percona-server-mongodb-operator
  scripts/setup-operators.sh
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/failing-test, kind/feature, lgtm

#3651 Add support for unlinking component from service
  pkg/envinfo/envinfo.go
  pkg/odo/cli/component/common_link.go
  pkg/service/service.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, lgtm

#3702 odo config for devfile
  .travis.yml
  Makefile
  pkg/config/config.go
  pkg/config/env_var.go
  pkg/config/storage.go
  pkg/devfile/parser/configurables.go
  pkg/devfile/parser/configurables_test.go
  pkg/devfile/parser/data/2.0.0/components.go
  pkg/devfile/parser/representation.go
  pkg/envinfo/envinfo.go
  pkg/odo/cli/config/config.go
  pkg/odo/cli/config/set.go
  pkg/odo/cli/config/unset.go
  pkg/odo/cli/config/view.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/genericclioptions/context_flags.go
  pkg/preference/preference.go
  pkg/preference/preference_test.go
  tests/integration/cmd_pref_config_test.go
  tests/integration/devfile/cmd_devfile_config_test.go
Labels: approved, lgtm

#3848 Bumping odo version to 1.2.5 -> 1.2.6
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#3835 consolidated some integration tests
  tests/integration/devfile/cmd_devfile_test_test.go
Labels: approved, lgtm

#3837 Add odo push to link/unlink tests
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, lgtm

#3860 Fix #3841 - odo watch redeploys component during first push
  pkg/odo/cli/component/watch.go
Labels: approved, kind/bug, lgtm, ok-to-test

#3854 fix: remove requirement for URL to end with .zip
  pkg/util/util.go
Labels: approved, kind/bug, lgtm

#3856 remove unnecessary unit tests
  pkg/config/config_test.go
  pkg/config/fakeConfig.go
  pkg/envinfo/envinfo_test.go
  pkg/odo/cli/env/env_test.go
  pkg/preference/preference_test.go
Labels: approved, lgtm

#3858 Update the help usage for odo create and odo url create
  docs/public/deploying-a-devfile-using-odo.adoc
  pkg/odo/cli/component/create.go
  pkg/odo/cli/url/create.go
Labels: approved, kind/cleanup, kind/documentation, lgtm

#3839 not provide %s for namespaces in logs
  pkg/odo/genericclioptions/context.go
Labels: approved, lgtm

#3844 Fixing os.GetWd() usage for getting component name
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/test.go
Labels: approved, kind/code-refactoring, lgtm

#3770 Update doc for starter project
  docs/file-reference/index.md
Labels: approved, lgtm

#3785 Add support for hot reload commands
  pkg/devfile/adapters/common/command_simple.go
  pkg/devfile/adapters/common/command_supervisor.go
  pkg/devfile/adapters/common/generic.go
  pkg/devfile/adapters/common/types.go
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/parser/data/2.0.0/devfileJsonSchema200.go
  pkg/devfile/parser/data/2.0.0/types.go
  pkg/devfile/parser/data/common/types.go
  tests/examples/source/devfiles/nodejs/devfile-with-hotReload.yaml
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, lgtm

#3788 Adds list command of storage for devfile v2
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/common/utils_test.go
  pkg/odo/cli/storage/create.go
  pkg/odo/cli/storage/list.go
  pkg/odo/cli/storage/list_test.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  pkg/storage/types.go
  pkg/testingutil/containers.go
  pkg/testingutil/devfile.go
  pkg/testingutil/pods.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/cmd_devfile_storage_test.go
Labels: approved, kind/feature, lgtm

#3821 Run missing debug command against 4.x cluster
  .travis.yml
  Makefile
Labels: approved, area/testing, kind/cleanup, lgtm

#3855 Remove experimental mode from docs
  docs/public/debugging-using-devfile.adoc
  docs/public/deploying-a-devfile-using-odo.adoc
  docs/public/operator-hub.adoc
Labels: approved, kind/documentation

#3762 Remove unnecessary devfile flag and update tests
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/exec.go
  pkg/odo/cli/debug/debug.go
  pkg/odo/cli/debug/info.go
  pkg/odo/cli/debug/portforward.go
  pkg/odo/cli/url/delete.go
  tests/integration/devfile/cmd_devfile_debug_test.go
  tests/integration/devfile/cmd_devfile_delete_test.go
  tests/integration/devfile/cmd_devfile_exec_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/cmd_devfile_test_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
  tests/integration/devfile/cmd_devfile_watch_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, kind/bug, kind/cleanup, lgtm

#3864 Updating cross-compile script to produce stripped binaries
  scripts/cross-compile.sh
Labels: approved, lgtm
