Repository redhat-developer/odo, pull requests merged in 2020-10, with the labels that each got.

#3890 Fix deletion of files and folders created during watch
  pkg/sync/adapter.go
  pkg/watch/watch.go
  tests/integration/devfile/utils/utils.go
Labels: approved, kind/bug, lgtm

#4064 Fixing typo and cleanup unused code
  pkg/odo/cli/component/common_link.go
Labels: approved, kind/cleanup, lgtm

#4066 Fixes message indicating no build when run mode is switched
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/sync/adapter.go
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, kind/bug, lgtm

#4086 Update vendor-update makefile target
  Makefile
Labels: approved, kind/bug, lgtm

#3959 add container name validation during creation and push
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/validate/validate.go
  pkg/devfile/validate/validate_test.go
  pkg/odo/cli/component/create.go
  tests/integration/devfile/cmd_devfile_env_test.go
Labels: approved, area/devfile, kind/bug, lgtm

#4054 Update configure-installer-tests-cluster-s390x.sh script to import right imagestream for tests.
  scripts/configure-installer-tests-cluster-s390x.sh
Labels: approved, area/System-PZ, lgtm

#4065 Update configure-installer-tests-cluster-ppc64le.sh script to import right imagestream for tests.
  scripts/configure-installer-tests-cluster-ppc64le.sh
Labels: approved, area/System-PZ, kind/bug, lgtm, ok-to-test

#4068 read s2i paths from both Config and ContainerConfig
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
Labels: approved, kind/bug, kind/failing-test, lgtm

#4043 feat: Allow composite commands to be overridden
  pkg/devfile/parser/data/2.0.0/components.go
  pkg/devfile/parser/types.go
  pkg/devfile/parser/types_test.go
  tests/examples/source/devfiles/parentSupport/devfile-with-parent-composite.yaml
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, area/devfile, kind/feature, lgtm

#4100 Fix link to Devfile documentation
  _posts/2020-09-24-odo-200-ga-release.md
Labels: approved, lgtm

#4007 Adds app commands for devfile components
  .gitignore
  Makefile
  pkg/application/application.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/pushed_component.go
  pkg/component/types.go
  pkg/kclient/deployments.go
  pkg/kclient/fake/ingress.go
  pkg/kclient/kclient.go
  pkg/occlient/fakeclient.go
  pkg/odo/cli/application/application.go
  pkg/odo/cli/application/delete.go
  pkg/odo/cli/application/describe.go
  pkg/odo/cli/application/list.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/url/list.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/util/cmdutils.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  pkg/testingutil/deployments.go
  pkg/url/url.go
  pkg/url/url_test.go
  tests/helper/helper_generic.go
  tests/integration/cmd_app_test.go
  tests/integration/component.go
  tests/integration/devfile/cmd_devfile_app_test.go
Labels: approved, kind/feature, lgtm

#4045 Default vol mount path to vol name if absent
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/common/utils_test.go
  pkg/odo/cli/storage/create.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  tests/examples/source/devfiles/nodejs/devfile-with-volume-components.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-volumes.yaml
  tests/integration/cmd_storage_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/cmd_devfile_storage_test.go
Labels: approved, kind/bug, lgtm

#4085 Refactor validate pkg for generic and odo validation
  pkg/devfile/adapters/common/command.go
  pkg/devfile/adapters/common/command_simple.go
  pkg/devfile/adapters/common/command_test.go
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/common/utils_test.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/parse.go
  pkg/devfile/parser/data/2.0.0/components.go
  pkg/devfile/parser/data/common/command_helper.go
  pkg/devfile/parser/data/common/command_helper_test.go
  pkg/devfile/parser/data/common/component_helper.go
  pkg/devfile/parser/data/common/component_helper_test.go
  pkg/devfile/validate/commands.go
  pkg/devfile/validate/commands_test.go
  pkg/devfile/validate/components.go
  pkg/devfile/validate/components_test.go
  pkg/devfile/validate/errors.go
  pkg/devfile/validate/events.go
  pkg/devfile/validate/events_test.go
  pkg/devfile/validate/generic/commands.go
  pkg/devfile/validate/generic/commands_test.go
  pkg/devfile/validate/generic/components.go
  pkg/devfile/validate/generic/components_test.go
  pkg/devfile/validate/generic/errors.go
  pkg/devfile/validate/generic/events.go
  pkg/devfile/validate/generic/events_test.go
  pkg/devfile/validate/generic/validate.go
  pkg/devfile/validate/validate_test.go
  pkg/testingutil/devfile.go
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, kind/cleanup, kind/code-refactoring, lgtm

#4099 Update secure registry documentation
  docs/public/secure-registry.adoc
Labels: approved, kind/documentation, lgtm

#4067 Added odo watch test with debug flag
  tests/helper/helper_filesystem.go
  tests/integration/devfile/cmd_devfile_watch_test.go
Labels: approved, kind/cleanup, lgtm

#4092 Add warning for default namespace during odo create
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/ui/ui.go
Labels: approved, lgtm

#4111 nit: dont show url as :// in odo url list
  pkg/url/url.go
  pkg/url/url_test.go
  tests/integration/cmd_url_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
Labels: approved, kind/bug, lgtm

#4127 Removing mongo db operator
  scripts/setup-operators.sh
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/cleanup, kind/failing-test, lgtm

#4121 Updating golang version to 1.15
  Dockerfile.rhel
  openshift-ci/build-root/Dockerfile
  openshift-ci/build-root/Dockerfile.travislogin
  scripts/rpm-prepare.sh
Labels: approved, area/release-eng, lgtm

#4128 Add links to new Kubernetes Slack
  README.adoc
  docs/public/community.adoc
Labels: approved, kind/documentation, lgtm

#4122 Ignore lifecycle/rotten labels when generating changelog
  scripts/changelog-script.sh
Labels: approved, kind/cleanup, lgtm

#4132 Revert "Updating golang version to 1.15"
  Dockerfile.rhel
  openshift-ci/build-root/Dockerfile
  openshift-ci/build-root/Dockerfile.travislogin
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#3431 Status support: Event notification support for build and application status for IDE integration for devfile scenarios
  .travis.yml
  Makefile
  pkg/devfile/adapters/common/generic.go
  pkg/devfile/adapters/common/interface.go
  pkg/devfile/adapters/docker/adapter.go
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/docker/component/status.go
  pkg/devfile/adapters/docker/utils/utils.go
  pkg/devfile/adapters/kubernetes/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/podwatcher.go
  pkg/devfile/adapters/kubernetes/component/podwatcher_test.go
  pkg/devfile/adapters/kubernetes/component/status.go
  pkg/devfile/adapters/kubernetes/component/status_test.go
  pkg/lclient/containers.go
  pkg/lclient/containers_test.go
  pkg/machineoutput/event_logging.go
  pkg/machineoutput/types_event_logging.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/component/component.go
  pkg/odo/cli/component/status.go
  pkg/url/status.go
  pkg/url/status_test.go
  tests/helper/helper_cli.go
  tests/helper/helper_docker.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/helper/helper_run.go
  tests/integration/devfile/cmd_devfile_status_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_status_test.go
  tests/integration/devfile/utils/cmd_devfile_event_test_utils.go
Labels: approved, kind/feature, lgtm, ok-to-test

#4075 Refactor: fix s2i flag for odo create
  pkg/odo/cli/component/create.go
  tests/integration/component.go
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, kind/bug, kind/code-refactoring, lgtm

#4133 Update deploying a devfile documentation
  docs/public/deploying-a-devfile-using-odo.adoc
Labels: approved, kind/documentation, lgtm

#4152 Release 2.0.1 of odo
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: kind/feature

#4143 renamed Openshift to S2I in odo to remove confusion
  docs/dev/experimental-mode.adoc
  docs/public/deploying-a-devfile-using-odo.adoc
  docs/public/s2i-to-devfile.adoc
  pkg/odo/cli/catalog/list/components.go
  pkg/odo/cli/component/list.go
  tests/integration/devfile/docker/cmd_docker_devfile_catalog_test.go
Labels: approved, lgtm

#4154 Add 2.0.1 changelog blog post
  docs/blog/2020-09-24-odo-200-ga-release.md
  docs/blog/2020-10-28-odo-201-release.md
Labels: kind/documentation

#4161 Publish blog post
  docs/blog/2020-10-28-odo-201-release.md
Labels: kind/documentation

#4164 Fix blog post
  docs/blog/2020-10-28-odo-201-release.md
Labels: kind/documentation

#4166 Updates build version to 2.0.1
  build/VERSION
Labels: kind/code-refactoring

#4167 Changes headings for deploying your first devfile
  docs/public/deploying-a-devfile-using-odo.adoc
Labels: kind/documentation

#4158 fix: typos [skip-ci]
  README.adoc
  docs/dev/experimental-mode.adoc
  docs/dev/logging.adoc
  docs/proposals/devfile.md
  docs/proposals/event-notification.md
  pkg/auth/login.go
  pkg/catalog/catalog_test.go
  pkg/component/component.go
  pkg/component/component_full_description.go
  pkg/component/types.go
  pkg/config/config.go
  pkg/config/env_var.go
  pkg/debug/info.go
  pkg/devfile/adapters/common/types.go
  pkg/devfile/adapters/docker/storage/adapter.go
  pkg/devfile/adapters/kubernetes/storage/adapter.go
  pkg/devfile/parser/configurables.go
  pkg/devfile/parser/context/schema.go
  pkg/devfile/parser/data/common/types.go
  pkg/devfile/parser/parse.go
  pkg/devfile/parser/types.go
  pkg/envinfo/envinfo.go
  pkg/kclient/generators.go
  pkg/kclient/kclient.go
  pkg/kclient/services.go
  pkg/kclient/supervisord.go
  pkg/log/status.go
  pkg/machineoutput/types_event_logging.go
  pkg/occlient/occlient.go
  pkg/occlient/templates.go
  pkg/odo/cli/component/common_push.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/exec.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/component/log.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/component/status.go
  pkg/odo/cli/component/watch.go
  pkg/odo/cli/project/create.go
  pkg/odo/cli/project/project.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/genericclioptions/runnable.go
  pkg/sync/adapter.go
  tests/examples/source/openjdk/src/main/java/AnotherMessageProducer.java
  tests/helper/helper_configValidate.go
  tests/helper/helper_filesystem.go
  tests/helper/helper_generic.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/component.go
Labels: approved, kind/documentation, lgtm

#4151 Debug travis
  .travis.yml
Labels: approved, kind/flake, lgtm

#4150 Trunicate longer devfile description
  pkg/component/component.go
  pkg/devfile/adapters/kubernetes/storage/utils.go
  pkg/odo/cli/catalog/list/components.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, kind/feature, lgtm

#4148 fix odo catalog list service erroring out when no service templates / CSVs are present
  pkg/odo/cli/catalog/list/services.go
  pkg/odo/cli/component/list.go
Labels: approved, lgtm

#4178 Update release notes
  docs/dev/development.adoc
Labels: approved, kind/documentation, lgtm

#3969 Enable link unlink target for 311 servicecatalog test
  .travis.yml
  Makefile
Labels: approved, lgtm
