Repository redhat-developer/odo, pull requests merged in 2020-06, with the labels that each got.

#3160 add state to ingress list and describe
  pkg/kclient/fake/ingress.go
  pkg/odo/cli/url/describe.go
  pkg/odo/cli/url/list.go
  pkg/url/types.go
  pkg/url/url.go
  pkg/url/url_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_url_test.go
Labels: approved, area/devfile, area/url, kind/feature, lgtm

#3248 Don't prompt for namespace if pushtarget is Docker
  pkg/odo/cli/component/create.go
Labels: approved, area/devfile, area/local, kind/bug, lgtm

#3252 Fix windows incompatibility with /tmp
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/bug, lgtm

#3281 Fix checkForImageStream to return correct result.
  tests/helper/helper_oc.go
Labels: approved, kind/bug, lgtm, ok-to-test

#3041 devfile push Integration test on kubernetes cluster
  .travis.yml
  tests/helper/helper_cli.go
  tests/helper/helper_generic.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/helper/kubernetes_utils.go
  tests/integration/devfile/cmd_devfile_catalog_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/cmd_devfile_registry_test.go
  tests/integration/devfile/cmd_devfile_watch_test.go
Labels: approved, area/devfile, kind/test, lgtm

#3294 Release 1.2.2 of odo
  Dockerfile.rhel
  pkg/version/version.go
  scripts/installer.sh
  scripts/rpm-prepare.sh
Labels: kind/feature

#3269 Fixes list and describe of secure URLs for not pushed components
  pkg/url/url.go
  tests/integration/cmd_url_test.go
Labels: approved, kind/bug, lgtm

#3265 Don't show imagestreams error on experimental mode
  pkg/occlient/occlient.go
  pkg/odo/cli/component/create.go
Labels: approved, kind/cleanup, lgtm

#3301 remove openshift logo from readme
  README.adoc
  docs/img/openshift.png
Labels: approved, kind/documentation, lgtm

#3287 Remove unnecessary preference set
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, kind/bug, kind/cleanup, lgtm

#2927 return error if app not found
  pkg/odo/cli/component/watch.go
  tests/integration/cmd_watch_test.go
Labels: approved, kind/bug, lgtm

#3306 Update build/VERSION to 1.2.2
  build/VERSION
Labels: kind/feature

#3318 Fix failing CI tests due to Open Liberty devfile rename
  tests/integration/devfile/cmd_devfile_catalog_test.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_catalog_test.go
Labels: approved, area/testing, kind/bug, lgtm

#3202 Removing install script and update other references
  docs/dev/development.adoc
  pkg/notify/notify.go
  scripts/bump-version.sh
  scripts/installer.sh
  scripts/test-installer.sh
Labels: approved, lgtm

#3290 Removing unused secret directory
  openshift-ci/build-root/Dockerfile
Labels: approved, kind/bug, kind/cleanup, lgtm

#2913 devfile delete Integration test on kubernetes cluster
  .travis.yml
  tests/integration/devfile/cmd_devfile_delete_test.go
Labels: approved, kind/test, lgtm

#3321 Fix namespace issue for url create --now
  pkg/odo/cli/component/devfile.go
Labels: approved, kind/bug, kind/failing-test, kind/flake, lgtm

#3118 Add --devfile flag support
  docs/dev/experimental-mode.adoc
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/component/watch.go
  pkg/odo/cli/url/create.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/helper/helper_filesystem.go
  tests/helper/kubernetes_utils.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/cmd_devfile_delete_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
  tests/integration/devfile/cmd_devfile_watch_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_delete_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_url_pushtarget_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_url_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_watch_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, area/devfile, kind/feature, lgtm, triage/ready

#3068 Updating travis env variable and adding docker version info
  .travis.yml
  scripts/oc-cluster.sh
Labels: approved, kind/cleanup, lgtm

#3322 use a more specific error message for when image is not found
  pkg/occlient/occlient.go
  pkg/odo/cli/component/create.go
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, lgtm

#2884 devfile create Interation test on kubernetes cluster using travis CI
  .travis.yml
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, kind/test, lgtm

#3139 Updating url delete to apply `--now` on devfile
  pkg/odo/cli/component/push.go
  pkg/odo/cli/url/delete.go
  tests/integration/devfile/cmd_devfile_url_test.go
Labels: approved, kind/feature, lgtm

#3264 list devfile components catalog in json format
  pkg/catalog/catalog.go
  pkg/odo/cli/catalog/list/components.go
  tests/integration/component.go
  tests/integration/devfile/cmd_devfile_catalog_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_catalog_test.go
Labels: approved, area/devfile, kind/bug, lgtm

#3310 Fix unsafe data race in ExecuteCommand
  pkg/exec/exec.go
Labels: approved, kind/bug, lgtm

#3129 Fix Docker Supervisord Vol Initialization
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/docker/component/adapter_test.go
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/docker/component/utils_test.go
  pkg/devfile/adapters/docker/utils/utils.go
  pkg/devfile/adapters/docker/utils/utils_test.go
  pkg/lclient/containers.go
  pkg/lclient/containers_test.go
  pkg/lclient/fakeclient.go
  tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
Labels: approved, kind/bug, kind/cleanup, lgtm

#3279 Converts v1 devfiles to v2
  tests/examples/source/devfiles/nodejs/devfile-no-endpoints.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-restart.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-volumes.yaml
  tests/examples/source/devfiles/nodejs/devfile-without-devbuild.yaml
  tests/examples/source/devfiles/nodejs/devfile-without-devinit.yaml
  tests/examples/source/devfiles/nodejs/devfile.yaml
  tests/examples/source/devfiles/springboot/devfile.yaml
  tests/examples/source/devfilesV1/springboot/devfile-init-without-build.yaml
  tests/examples/source/devfilesV1/springboot/devfile-init.yaml
  tests/examples/source/devfilesV2/nodejs/devfile.yaml
  tests/examples/source/devfilesV2/springboot/devfile.yaml
  tests/helper/helper_filesystem.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, kind/code-refactoring, lgtm

#3351 Adding oc to bin path for multistage testing
  openshift-ci/build-root/Dockerfile
Labels: approved, kind/feature, lgtm

#3358 resolved the gosec issue failing unit tests
  pkg/util/util.go
  tests/helper/helper_generic.go
Labels: approved, lgtm

#2941 warn --app and --all-apps coexist
  pkg/odo/cli/component/list.go
Labels: approved, lgtm

#3305 url list routes and ingress
  pkg/odo/cli/url/describe.go
  pkg/odo/cli/url/list.go
  pkg/url/types.go
  pkg/url/url.go
  pkg/url/url_test.go
  tests/integration/cmd_url_test.go
  tests/integration/component.go
  tests/integration/devfile/cmd_devfile_url_test.go
Labels: approved, area/devfile, area/url, kind/bug, lgtm

#3326 Fix 'odo version' integration test.
  tests/integration/generic_test.go
Labels: approved, kind/bug, lgtm, ok-to-test

#3349 Validate application exist before describe it
  pkg/odo/cli/application/describe.go
  tests/integration/cmd_app_test.go
Labels: approved, lgtm

#3370 Update events
  docs/public/community.adoc
Labels: kind/documentation

#3352 Updates the v2 schema to the latest
  pkg/devfile/adapters/docker/component/adapter_test.go
  pkg/devfile/adapters/docker/component/utils_test.go
  pkg/devfile/adapters/docker/storage/adapter_test.go
  pkg/devfile/adapters/docker/utils/utils_test.go
  pkg/devfile/adapters/helper_test.go
  pkg/devfile/parser/data/2.0.0/devfileJsonSchema200.go
  pkg/devfile/parser/data/2.0.0/types.go
  pkg/devfile/parser/data/common/types.go
  pkg/devfile/validate/components_test.go
  pkg/sync/adapter_test.go
Labels: approved, kind/code-refactoring, lgtm

#3365 fix: properly check that odo version contains the server URL
  tests/helper/helper_oc.go
  tests/integration/generic_test.go
Labels: approved, kind/bug, lgtm

#3376 Create periodic script for odo periodic job
  scripts/openshiftci-periodic-tests.sh
Labels: approved, kind/feature, lgtm

#3339 Show error message if no registries are configured
  pkg/odo/cli/registry/list.go
  pkg/odo/cli/url/list.go
  tests/integration/devfile/cmd_devfile_registry_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
Labels: approved, area/devfile, kind/bug, lgtm

#3315 Added few supported container images to e2e image test
  tests/e2escenarios/e2e_images_test.go
Labels: approved, kind/feature, lgtm

#3341 Fix multiple registry related issues
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/registry/add.go
  pkg/preference/preference.go
  tests/integration/devfile/cmd_devfile_catalog_test.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_catalog_test.go
Labels: approved, area/devfile, kind/bug, lgtm

#3003 Push support: Event notification support for build and application status for IDE integration for devfile scenarios
  pkg/component/component.go
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/exec/devfile.go
  pkg/exec/exec.go
  pkg/machineoutput/event_logging.go
  pkg/machineoutput/types.go
  pkg/machineoutput/types_event_logging.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/push.go
  pkg/sync/adapter.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
  tests/integration/devfile/utils/cmd_devfile_push_test_utils.go
Labels: approved, area/devfile, kind/feature, lgtm, need/docs, ok-to-test

#3362 Adding oc binary to bin path for multi stage test infra
  openshift-ci/build-root/multistage/Dockerfile
  openshift-ci/build-root/multistage/check-oc.sh
Labels: approved, kind/feature, lgtm

#3408 Update devfile log levels from 3 to 4 to be consistent
  pkg/devfile/adapters/common/command.go
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/docker/storage/utils.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/storage/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
Labels: approved, kind/cleanup, lgtm

#3329 Design proposal: secure registry support
  docs/proposals/secure-registry.md
Labels: approved, kind/documentation, lgtm

#3368 Proposal for odo deploy
  docs/proposals/odo-deploy.md
Labels: approved, kind/design, lgtm, ok-to-test

#3412 Updating script path in Dockerfile for multistage test
  openshift-ci/build-root/multistage/Dockerfile
Labels: approved, kind/feature, lgtm

#3327 Invalid ANSI colouring on Windows when doing devfile push
  pkg/log/status.go
Labels: approved, kind/bug, lgtm, ok-to-test

#3399 catalog list component -o json should be shown as before with experimental mode disabled
  pkg/odo/cli/catalog/list/components.go
Labels: approved, kind/bug, lgtm

#3414 removed deprecated and nodejs 8 images from e2e tests and README
  README.adoc
  tests/e2escenarios/e2e_images_test.go
Labels: approved, lgtm

#3421 Update changelog script
  scripts/changelog-script.sh
Labels: kind/code-refactoring

#3422 Release 1.2.3
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, kind/feature, lgtm

#3404 fix 'Timeout out' typo and fix formatting
  tests/helper/helper_generic.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
Labels: approved, kind/cleanup, kind/test, lgtm

#3173 Add command to provide starter project information
  pkg/devfile/parse.go
  pkg/devfile/parser/context/content.go
  pkg/devfile/parser/context/content_test.go
  pkg/devfile/parser/context/context.go
  pkg/devfile/parser/context/context_test.go
  pkg/devfile/parser/parse.go
  pkg/odo/cli/catalog/catalog.go
  pkg/odo/cli/catalog/describe/component.go
  pkg/odo/cli/catalog/describe/describe.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/integration/devfile/cmd_devfile_catalog_test.go
Labels: approved, kind/feature, lgtm, ok-to-test

#3374 Build progress does not show correctly when the command line is too long
  pkg/log/status.go
Labels: approved, kind/bug, lgtm, ok-to-test

#3291 Devfile v2 command group impl + Odo catalog list components
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  pkg/catalog/types.go
  pkg/devfile/adapters/common/command.go
  pkg/devfile/adapters/common/command_test.go
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/common/utils_test.go
  pkg/devfile/parse.go
  pkg/devfile/parser/data/2.0.0/components.go
  pkg/devfile/parser/parse.go
  pkg/odo/cli/catalog/describe/component.go
  pkg/odo/cli/catalog/list/components.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/watch.go
  pkg/odo/cli/url/create.go
  pkg/preference/preference.go
  pkg/testingutil/devfile.go
  pkg/util/util_test.go
  tests/examples/source/devfiles/nodejs/devfile-with-multiple-defaults.yaml
  tests/examples/source/devfiles/springboot/devfile.yaml
  tests/integration/devfile/cmd_devfile_catalog_test.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/cmd_devfile_registry_test.go
  tests/integration/devfile/cmd_devfile_watch_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_catalog_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_watch_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, kind/feature, lgtm

#3391 Ignore .odo/env folder for devfile
  pkg/envinfo/envinfo.go
  pkg/envinfo/envinfo_test.go
  pkg/odo/cli/component/create.go
  pkg/util/file_indexer.go
  pkg/util/util.go
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, kind/bug, lgtm

#3418 Adding oc from build to container image in multistage
  openshift-ci/build-root/multistage/Dockerfile
  openshift-ci/build-root/multistage/check-oc.sh
  openshift-ci/build-root/source-image/Dockerfile
Labels: approved, kind/feature, lgtm
