Repository redhat-developer/odo, pull requests merged in 2020-02, with the labels that each got.

#2548 Swapped out StringSliceVarP for StringArrayVarP to parse cli parameter…
  pkg/odo/cli/service/create.go
Labels: approved, kind/bug, lgtm, ok-to-test, size/XS

#2374 Fix README.adoc text about supported versions
  README.adoc
Labels: approved, kind/documentation, lgtm, size/M

#2533 Deletes storage on component deletion
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/occlient/volumes.go
  pkg/occlient/volumes_test.go
  tests/helper/helper_oc.go
  tests/integration/component.go
Labels: approved, kind/bug, lgtm, size/L

#2549 Running Unit test on macOS
  .travis.yml
Labels: approved, lgtm, size/M

#2520 add devfile proposal
  docs/proposals/devfile.md
Labels: approved, lgtm, size/M

#2482 Enabling now flag for remaining operations
  pkg/odo/cli/component/common_push.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/component/update.go
  pkg/odo/cli/config/set.go
  pkg/odo/cli/config/unset.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/delete.go
  tests/helper/helper_oc.go
  tests/integration/cmd_pref_config_test.go
  tests/integration/cmd_url_test.go
Labels: approved, kind/api-change, kind/feature, lgtm, size/L

#2556 add new reviewers to top level OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#2587 Update changelog script
  scripts/changelog-script.sh
Labels: approved, lgtm, size/XS

#2564 Odo Push Show Error to User from Openshift
  pkg/odo/cli/component/common_push.go
  pkg/odo/util/cmdutils.go
Labels: approved, lgtm, size/XS

#2560 Add support for experimental mode feature
  docs/dev/experimental-mode.adoc
  pkg/odo/cli/cli.go
  pkg/odo/cli/preference/set.go
  pkg/odo/cli/preference/unset.go
  pkg/odo/cli/preference/view.go
  pkg/odo/util/experimental/experimental.go
  pkg/odo/util/experimental/experimental_test.go
  pkg/preference/preference.go
  pkg/preference/preference_test.go
Labels: approved, lgtm, size/L

#2558 Fix Panic: When odo app describe run out of component folder
  pkg/odo/cli/application/describe.go
  pkg/odo/util/cmdutils.go
  tests/integration/cmd_app_test.go
Labels: approved, kind/bug, lgtm, size/M

#2402 E2E test for every supported images
  .travis.yml
  Makefile
  tests/e2escenarios/e2e_images_test.go
  tests/helper/helper_generic.go
  tests/helper/helper_oc.go
Labels: approved, kind/test, lgtm, size/L

#2572 Use env variable for unit test verbose mode
  Makefile
  docs/dev/development.adoc
Labels: approved, lgtm, size/S

#2597 update README: add info about odo calls
  README.adoc
Labels: approved, kind/documentation, lgtm, size/S

#2518 Adds the debug info command
  pkg/debug/info.go
  pkg/debug/info_test.go
  pkg/odo/cli/debug/debug.go
  pkg/odo/cli/debug/info.go
  pkg/odo/cli/debug/portforward.go
  pkg/testingutil/fileutils.go
  tests/helper/helper_http.go
  tests/helper/helper_run.go
  tests/integration/cmd_debug_test.go
Labels: approved, kind/feature, lgtm, size/XL

#2584 Add State to Odo Storage List
  pkg/config/fakeConfig.go
  pkg/odo/cli/storage/list.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  pkg/storage/types.go
  tests/integration/cmd_storage_test.go
Labels: approved, lgtm, size/L

#2568 Adds HTTPs support for URL
  pkg/component/component.go
  pkg/config/config.go
  pkg/occlient/occlient.go
  pkg/occlient/occlient_test.go
  pkg/odo/cli/url/create.go
  pkg/url/url.go
  pkg/url/url_test.go
  tests/helper/helper_http.go
  tests/helper/odo_utils.go
  tests/integration/cmd_url_test.go
Labels: approved, kind/feature, lgtm, size/L

#2595 Exports ODO_LOG_LEVEL env variable in integration tests
  .travis.yml
  Makefile
  cmd/odo/odo.go
Labels: approved, kind/code-refactoring, lgtm, size/S

#2598 Remove devfile push cmd
  pkg/odo/cli/cli.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/push.go
Labels: approved, lgtm, size/L

#2546 Add kclient functions for creating volumes
  pkg/kclient/deployments.go
  pkg/kclient/deployments_test.go
  pkg/kclient/generators.go
  pkg/kclient/generators_test.go
  pkg/kclient/kclient.go
  pkg/kclient/volumes.go
  pkg/kclient/volumes_test.go
Labels: approved, kind/feature, lgtm, ok-to-test, size/XL

#2633 Updating nodejs:8 to nodejs:latest for source example run on openshift 4.*
  tests/e2escenarios/e2e_images_test.go
  tests/integration/cmd_debug_test.go
  tests/integration/cmd_push_test.go
  tests/integration/component.go
Labels: approved, kind/bug, lgtm, size/M

#2589 Create deployment based on Devfile
  pkg/devfile/adapters/common/interface.go
  pkg/devfile/adapters/common/types.go
  pkg/devfile/adapters/helper.go
  pkg/devfile/adapters/helper_test.go
  pkg/devfile/adapters/interface.go
  pkg/devfile/adapters/kubernetes/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/versions/1.0.0/components.go
  pkg/devfile/versions/interface.go
  pkg/kclient/deployments.go
  pkg/kclient/deployments_test.go
  pkg/kclient/generators.go
  pkg/kclient/generators_test.go
  pkg/kclient/volumes_test.go
  pkg/odo/cli/component/devfile.go
  pkg/testingutil/devfile.go
Labels: approved, kind/feature, lgtm, size/XL

#2634 possible fix: index out of bound error on `odo catalog list compoments` when registry url and namespace are not present
  pkg/catalog/catalog.go
Labels: approved, kind/bug, lgtm, size/S

#2629 Removing odo specific checks from devfile parser
  pkg/devfile/parse.go
  pkg/devfile/versions/1.0.0/validate.go
  pkg/devfile/versions/common/commands.go
  pkg/devfile/versions/common/commands_test.go
  pkg/devfile/versions/common/components.go
  pkg/devfile/versions/common/components_test.go
  pkg/devfile/versions/common/projects.go
  pkg/devfile/versions/common/projects_test.go
  pkg/devfile/versions/interface.go
Labels: approved, lgtm, size/L
