Repository redhat-developer/odo, pull requests merged in 2021-11, with the labels that each got.

#5191 Document for URL creation using odo
  docs/website/docs/using-odo/create-url.md
Labels: approved, lgtm, kind/documentation

#5192 odo build-images command
  docs/website/docs/command-reference/build-images.md
  docs/website/docs/command-reference/catalog.md
  docs/website/docs/command-reference/create.md
  docs/website/docs/command-reference/service.md
  pkg/devfile/image/docker_compatible.go
  pkg/devfile/image/docker_compatible_test.go
  pkg/devfile/image/image.go
  pkg/devfile/image/image_test.go
  pkg/devfile/image/mock_Backend.go
  pkg/kclient/mock_Client.go
  pkg/odo/cli/build_images/build_images.go
  pkg/odo/cli/cli.go
  scripts/mockgen.sh
  tests/examples/source/devfiles/nodejs/devfile-outerloop-args.yaml
  tests/examples/source/devfiles/nodejs/devfile-outerloop.yaml
  tests/examples/source/nodejs/Dockerfile
  tests/helper/helper_cmd_wrapper.go
  tests/integration/devfile/cmd_devfile_build_images_test.go
Labels: approved, lgtm, kind/feature

#5208 Remove metadata.namespace from ALM Examples
  pkg/service/service.go
  pkg/service/service_test.go
Labels: kind/bug, approved, lgtm

#5199 Fix odo overwrites devfile with flattened/resolved devfile and refactor component creation
  pkg/devfile/devfile.go
  pkg/odo/cli/catalog/describe/component.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/create_methods.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/errors.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/component/status.go
  pkg/odo/cli/component/test.go
  pkg/odo/cli/component/watch.go
  pkg/odo/genericclioptions/context.go
  pkg/util/file_indexer.go
  pkg/util/file_indexer_test.go
  tests/examples/source/devfiles/nodejs/devfile-with-parent.yaml
  tests/helper/odo_utils.go
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, lgtm, kind/cleanup

#5218 Bumping odo version v2.4.1 -> v2.4.2
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm, kind/feature

#5205 Refactoring test
  tests/integration/devfile/cmd_devfile_status_test.go
Labels: approved, lgtm

#5196 Scripts for IBM Pipelines
  .ibm/pipelines/functions.sh
  .ibm/pipelines/kubernetes-tests.sh
  .ibm/pipelines/openshift-tests.sh
  .ibm/pipelines/unit-tests.sh
Labels: approved, lgtm, kind/tests

#5225 Add starter project name in doc
  docs/website/docs/using-odo/create-component.md
Labels: kind/bug, approved, lgtm, kind/documentation

#5227 Fix help for `odo link`
  pkg/odo/cli/component/link.go
Labels: approved, lgtm, kind/documentation

#5223 Catalog describe service displays info about []object fields
  pkg/odo/cli/catalog/describe/operator_backend.go
Labels: kind/bug, approved, lgtm

#5216 add tests for .devfile.yaml support
  tests/integration/devfile/cmd_dot_devfile_test.go
Labels: approved, lgtm

#5198 Refactor genericclioptions.Context
  pkg/localConfigProvider/localConfigProvider.go
  pkg/odo/cli/application/delete.go
  pkg/odo/cli/application/describe.go
  pkg/odo/cli/application/list.go
  pkg/odo/cli/build_images/build_images.go
  pkg/odo/cli/catalog/describe/component.go
  pkg/odo/cli/catalog/describe/service.go
  pkg/odo/cli/catalog/list/components.go
  pkg/odo/cli/catalog/list/services.go
  pkg/odo/cli/catalog/search/component.go
  pkg/odo/cli/catalog/search/service.go
  pkg/odo/cli/component/common_link.go
  pkg/odo/cli/component/component.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/create_helpers.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/describe.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/exec.go
  pkg/odo/cli/component/get.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/component/log.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/component/status.go
  pkg/odo/cli/component/test.go
  pkg/odo/cli/component/watch.go
  pkg/odo/cli/config/set.go
  pkg/odo/cli/config/unset.go
  pkg/odo/cli/debug/info.go
  pkg/odo/cli/debug/portforward.go
  pkg/odo/cli/logout/logout.go
  pkg/odo/cli/project/create.go
  pkg/odo/cli/project/delete.go
  pkg/odo/cli/project/get.go
  pkg/odo/cli/project/list.go
  pkg/odo/cli/project/set.go
  pkg/odo/cli/service/create.go
  pkg/odo/cli/service/delete.go
  pkg/odo/cli/service/describe.go
  pkg/odo/cli/service/list.go
  pkg/odo/cli/storage/create.go
  pkg/odo/cli/storage/delete.go
  pkg/odo/cli/storage/list.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/delete.go
  pkg/odo/cli/url/list.go
  pkg/odo/genericclioptions/client.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/genericclioptions/fakecontext.go
  pkg/odo/genericclioptions/resolve.go
  pkg/odo/genericclioptions/util.go
  pkg/odo/util/completion/completionhandlers.go
Labels: approved, lgtm, kind/cleanup

#5229 Corrects service creation help message
  pkg/odo/cli/service/create.go
Labels: kind/bug, approved, lgtm

#5234 Fix odo config view
  pkg/odo/cli/config/view.go
  tests/integration/cmd_pref_config_test.go
Labels: kind/bug, approved, lgtm

#5244 Incorporated feedback about When statements
  tests/integration/devfile/cmd_devfile_watch_test.go
Labels: approved, lgtm, kind/tests

#5261 Bump odo to 2.4.3
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm
