Repository redhat-developer/odo, pull requests merged in 2021-02, with the labels that each got.

#4399 $ARTIFACTS_DIR is set by platform
  scripts/openshiftci-periodic-tests.sh
  scripts/openshiftci-presubmit-all-tests.sh
  scripts/openshiftci-presubmit-unittests.sh
Labels: approved, kind/bug, lgtm

#4325 Validation spinners refactor
  pkg/odo/cli/component/create.go
Labels: approved, kind/cleanup, kind/code-refactoring, lgtm

#4395 Refactors storage List() to use Storage Client.
  pkg/component/component_full_description.go
  pkg/config/config.go
  pkg/envinfo/envinfo.go
  pkg/localConfigProvider/localConfigProvider.go
  pkg/localConfigProvider/mock_localConfigProvider.go
  pkg/odo/cli/storage/list.go
  pkg/odo/cli/storage/list_test.go
  pkg/storage/kubernetes.go
  pkg/storage/kubernetes_test.go
  pkg/storage/s2i.go
  pkg/storage/s2i_test.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
Labels: approved, kind/code-refactoring, lgtm

#4366 Refactors url List() to use URL Client
  pkg/component/component.go
  pkg/component/component_full_description.go
  pkg/config/url.go
  pkg/devfile/adapters/docker/component/utils_test.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/envinfo/url.go
  pkg/envinfo/url_test.go
  pkg/odo/cli/component/common_push.go
  pkg/odo/cli/component/status.go
  pkg/odo/cli/url/list.go
  pkg/odo/genericclioptions/context.go
  pkg/testingutil/devfile.go
  pkg/url/kubernetes.go
  pkg/url/kubernetes_test.go
  pkg/url/mock_Client.go
  pkg/url/s2i.go
  pkg/url/status.go
  pkg/url/status_test.go
  pkg/url/url.go
  pkg/url/url_test.go
Labels: approved, lgtm

#4381 Adds debug-command flag to odo watch
  docs/public/deploying-a-devfile-using-odo.adoc
  pkg/odo/cli/component/watch.go
  pkg/watch/watch.go
  pkg/watch/watch_test.go
  tests/examples/source/devfiles/nodejs/devfile-with-debugrun.yaml
  tests/integration/devfile/cmd_devfile_watch_test.go
Labels: approved, kind/feature, lgtm

#4411 Adding psi prow script placeholder.
  scripts/openshiftci-e2e-4x-psi-tests.sh
Labels: approved, lgtm

#4375 Elaborate on minikube, ingress, nip.io setup
  docs/public/deploying-a-devfile-using-odo.adoc
Labels: approved, kind/documentation, lgtm, ok-to-test

#4063 Setting up baseline POC of internal CI
  go.mod
  go.sum
  pkg/util/util.go
  scripts/openshiftci-presubmit-all-tests-old.sh
  scripts/openshiftci-presubmit-all-tests.sh
  scripts/run_all_tests.sh
  tests/e2escenarios/e2e_images_test.go
  tests/helper/helper_oc.go
  tests/integration/cmd_push_test.go
  tests/integration/loginlogout/cmd_login_logout_test.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, lgtm

#4415 Fix release script link
  docs/dev/development.adoc
Labels: approved, kind/documentation, lgtm

#4417 Updates to 'odo watch' and Operator docs
  docs/debugging-applications-in-odo.md
  docs/deploying-a-devfile-using-odo.md
  docs/operator-hub.md
Labels: approved, kind/documentation

#4416 Fixing wrong project passed to the component
  tests/e2escenarios/e2e_images_test.go
Labels: approved, kind/failing-test, lgtm

#4396 adding project resource check before warning about default project usage
  pkg/odo/cli/component/create.go
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, kind/bug, lgtm

#4418 Buming odo version for release
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#4427 Added java-maven to the list of components to be tested
  tests/e2escenarios/e2e_devfile_test.go
Labels: approved, kind/feature, lgtm

#4419 Renaming entrypoint scripts to use new job
  scripts/openshiftci-e2e-4x-psi-tests.sh
  scripts/openshiftci-presubmit-all-tests.sh
Labels: approved, lgtm

#4425 Make starter project download work with custom context directory
  pkg/component/starter_project.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/create_helpers.go
  tests/helper/helper_filesystem.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/template/template_cleantest_test.go
Labels: approved, kind/bug, lgtm

#4433 Adds Parthvi to reviewers of odo
  OWNERS
Labels: approved, lgtm

#4430 Fixes no default build command error.
  pkg/devfile/adapters/common/command.go
  pkg/devfile/adapters/common/command_test.go
  pkg/devfile/adapters/common/errors.go
Labels: approved, kind/bug, lgtm

#4434 Adding link to Connector extension on Open VSX
  README.adoc
Labels: approved, kind/documentation, lgtm, ok-to-test

#4394 Remove external nodejs dependency of Git
  docs/dev/test-architecture.adoc
  tests/integration/cmd_push_test.go
  tests/integration/generic_test.go
Labels: approved, kind/failing-test, lgtm

#4450 Document how to enable OLM on Kubernetes
  docs/public/install-service-binding-operator.adoc
Labels: approved, kind/documentation, lgtm

#4452 Fixes the URL name cropping issue.
  pkg/url/kubernetes.go
  pkg/url/url.go
  tests/integration/devfile/cmd_devfile_url_test.go
Labels: approved, kind/bug, lgtm

#4436 Modifies odo create for devfile components to not require a cluster access.
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/push.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/genericclioptions/util.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/cmd_devfile_env_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, kind/bug, lgtm
