Repository redhat-developer/odo, pull requests merged in 2021-05, with the labels that each got.

#4565 Make Telemetry upload faster
  pkg/odo/cli/cli.go
  pkg/odo/cli/telemetry/telemetry.go
  pkg/odo/genericclioptions/runnable.go
  pkg/segment/segment.go
  pkg/segment/segment_test.go
Labels: approved, kind/feature, lgtm, release-good-to-have

#4682 Bumping odo version v2.1.0 -> v2.2.0
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#4683 add breaking changes in odo 2.2 doc
  docs/public/breaking-changes-in-odo-2.2.adoc
Labels: approved, kind/documentation, lgtm

#4684 Adds Priti to OWNERS
  OWNERS
Labels: approved, lgtm

#4686 Add changelog and github issue template
  .github/PULL_REQUEST_TEMPLATE.md
  Changelog.md
Labels: approved, lgtm

#4671 odo catalog describe service for operators
  pkg/odo/cli/catalog/describe/interface.go
  pkg/odo/cli/catalog/describe/operator_backend.go
  pkg/odo/cli/catalog/describe/service.go
  pkg/odo/cli/catalog/describe/service_catalog_backend.go
  pkg/service/cr_description.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/feature, lgtm

#4460 Automate psi ci for mac and windows
  Makefile
  scripts/openshiftci-e2e-4x-psi-tests.sh
  scripts/openshiftci-unit-psi-tests_win_mac.sh
  scripts/run_script_unit.sh
  scripts/setup_script_unit.sh
Labels: approved, kind/feature, lgtm

#4691 typo in breaking changes doc
  docs/public/breaking-changes-in-odo-2.2.adoc
Labels: approved, lgtm

#4692 Fix some typos in development doc
  docs/dev/development.adoc
Labels: approved, kind/documentation, lgtm, ok-to-test

#4689 fixing ci-firewall command
  scripts/openshiftci-e2e-4x-psi-tests.sh
Labels: approved, lgtm

#4697 Resolve broken links in main doc
  docs/public/operator-hub.adoc
Labels: approved, kind/documentation, lgtm

#4695 Add make help
  Makefile
Labels: approved, kind/documentation, lgtm

#4696 fix doc instruction readme, add some helpers and built breaking-changes-2.2 doc
  README.md
  chosen-docs/upstream/breaking-changes-in-odo-2.2.md
  docs/breaking-changes-in-odo-2.2.md
  docs/operator-hub.md
  docs/sample-applications.md
  index.md
Labels: approved, kind/documentation, lgtm

#4698 Update changelog script
  scripts/changelog-script.sh
Labels: approved, lgtm

#4700 Update test script to use main branch for PSI test
  scripts/openshiftci-e2e-4x-psi-tests.sh
Labels: approved, area/testing, lgtm

#4670 follow devfile like conventions in generated url name to keep url short for --s2i
  pkg/devfile/convert/convert.go
  tests/integration/component.go
Labels: approved, lgtm

#4679 Update devfile tests with OCI-based registry
  tests/integration/devfile/cmd_devfile_catalog_test.go
  tests/integration/devfile/cmd_devfile_registry_test.go
Labels: approved, lgtm

#4706 fix typo in unit-test job name for windows
  scripts/openshiftci-unit-psi-tests_win_mac.sh
Labels: approved, lgtm

#4709 Updating latest build/VERSION
  build/VERSION
Labels: approved, lgtm

#4702 Fix OCI-based registry migration
  pkg/preference/preference.go
Labels: approved, kind/bug, lgtm

#4588 Adds dev.odo.push.path attribute support for pushing only mentioned files
  pkg/component/component.go
  pkg/devfile/adapters/common/types.go
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/sync/adapter.go
  pkg/sync/adapter_test.go
  pkg/sync/sync.go
  pkg/sync/sync_test.go
  pkg/util/file_indexer.go
  pkg/util/file_indexer_test.go
  tests/examples/source/devfiles/nodejs/devfile-with-remote-attributes.yaml
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, lgtm

#4714 Fix SB annotations since '.' no longer converted to '_'
  docs/public/deploying-java-app-with-database.adoc
Labels: approved, kind/documentation, lgtm, ok-to-test

#4718 Fix SB annotations (#4714)
  docs/deploying-java-app-with-database.md
Labels: approved, kind/documentation, lgtm

#4716 add --jenkinsProject in PSI test script
  scripts/minici-presubmit-all-tests.sh
  scripts/openshiftci-e2e-4x-psi-tests.sh
  scripts/openshiftci-unit-psi-tests_win_mac.sh
Labels: approved, lgtm

#4567 Removes invalid endpoints from the devfile on triggering url create.
  pkg/config/url.go
  pkg/envinfo/envinfo.go
  pkg/envinfo/url.go
  pkg/envinfo/url_test.go
  pkg/odo/cli/url/create.go
  pkg/odo/genericclioptions/context.go
  pkg/util/url_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
Labels: approved, kind/bug, lgtm

#4721 [skip ci] Update links to devfile registry in readme
  README.adoc
Labels: approved, kind/documentation, lgtm

#4715 Remove devfile images needs image pull from docker
  tests/e2escenarios/e2e_devfile_test.go
Labels: approved, kind/failing-test, lgtm

#4705 Modify minikube script for long running cluster
  scripts/minikube-minishift-all-tests.sh
  scripts/minikube-minishift-setup-env.sh
Labels: approved, area/testing, kind/feature, lgtm

#4681 Adds a document regarding the odo.dev.push.path attributes in the devfile
  docs/public/using-devfile-odo.dev.push.path-attribute.adoc
Labels: approved, kind/documentation, lgtm

#4713 Use ServiceBinding types instead of unstructured.Unstructured
  go.mod
  go.sum
  pkg/odo/cli/component/common_link.go
  pkg/odo/cli/component/link.go
  vendor/github.com/redhat-developer/service-binding-operator/LICENSE
  vendor/github.com/redhat-developer/service-binding-operator/api/v1alpha1/conditions.go
  vendor/github.com/redhat-developer/service-binding-operator/api/v1alpha1/groupversion_info.go
  vendor/github.com/redhat-developer/service-binding-operator/api/v1alpha1/servicebinding_types.go
  vendor/github.com/redhat-developer/service-binding-operator/api/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm

#4707 Adding deprecation warning for git based registries
  Changelog.md
  docs/public/git-registry-deprecation.adoc
  pkg/log/status.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/registry/add.go
  pkg/odo/cli/registry/list.go
  pkg/odo/cli/registry/update.go
  pkg/odo/cli/registry/util/util.go
  pkg/odo/cli/registry/util/util_test.go
  tests/integration/devfile/cmd_devfile_registry_test.go
Labels: approved, lgtm

#4712 Adding wait support to component deletion for devfile
  pkg/devfile/adapters/common/interface.go
  pkg/devfile/adapters/docker/adapter.go
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/docker/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/kclient/fakeclient.go
  pkg/kclient/kclient.go
  pkg/odo/cli/component/devfile.go
  tests/helper/helper_cli.go
  tests/helper/helper_generic.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/component.go
  tests/integration/devfile/cmd_devfile_delete_test.go
Labels: approved, kind/bug, lgtm

#4722 Fix Operatorhub test to use CreateNewContext()
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, lgtm

#4723 Remove duplicity and make tests verbose
  tests/integration/cmd_pref_config_test.go
Labels: approved, kind/cleanup, lgtm

#4740 Updates the Changelog.md with the mention of PR https://github.com/openshift/odo/pull/4588
  Changelog.md
Labels: approved, kind/documentation, lgtm

#4732 Adding container based filtering for get ports
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/config/url.go
  pkg/devfile/convert/convert.go
  pkg/envinfo/url.go
  pkg/envinfo/url_test.go
  pkg/localConfigProvider/localConfigProvider.go
  pkg/localConfigProvider/mock_localConfigProvider.go
  pkg/odo/cli/component/create.go
  tests/integration/devfile/cmd_devfile_url_test.go
Labels: approved, kind/bug, lgtm

#4746 Release v2.2.1
  Changelog.md
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#4749 Adds docs for dev.push.path attribute
  .gitignore
  chosen-docs/upstream/using-devfile-odo.dev.push.path-attribute.md
  docs/sample-applications.md
  docs/using-devfile-odo.dev.push.path-attribute.md
  index.md
Labels: approved, kind/documentation, lgtm

#4724 Add doc to introduce using devfiles on IBM Z & Power.
  docs/public/deploying-a-devfile-using-odo-on-IBM-Z-and-Power.adoc
Labels: approved, lgtm

#4753 Adding tempdir close defer to prevent unclosed tmpdir
  pkg/util/util.go
Labels: approved, kind/bug, lgtm

#4736 Debug flaky test
  tests/helper/helper_cli.go
  tests/helper/helper_generic.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/devfile/cmd_devfile_delete_test.go
Labels: approved, lgtm

#4759 Update VERSION
  build/VERSION
Labels: approved, lgtm

#4762 Update README.adoc - remove travis-ci badge
  README.adoc
Labels: approved, kind/documentation, lgtm
