Repository redhat-developer/odo, pull requests merged in 2021-08, with the labels that each got.

#4943 Do not cancel the whole execution if one of the test suite fails
  scripts/openshiftci-periodic-tests.sh
Labels: approved, kind/feature, lgtm

#4954 Test storage + link
  tests/integration/operatorhub/cmd_link_test.go
Labels: approved, kind/bug, lgtm

#4947 Remove unused Docker code
  pkg/devfile/adapters/docker/adapter.go
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/docker/component/adapter_test.go
  pkg/devfile/adapters/docker/component/status.go
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/docker/component/utils_test.go
  pkg/devfile/adapters/docker/storage/utils.go
  pkg/devfile/adapters/docker/storage/utils_test.go
  pkg/devfile/adapters/docker/utils/utils.go
  pkg/devfile/adapters/docker/utils/utils_test.go
  pkg/lclient/client.go
  pkg/lclient/containers.go
  pkg/lclient/containers_test.go
  pkg/lclient/fakeclient.go
  pkg/lclient/generators.go
  pkg/lclient/generators_test.go
  pkg/lclient/images.go
  pkg/lclient/images_test.go
  pkg/lclient/mock_client.go
  pkg/lclient/storage.go
  pkg/lclient/storage_test.go
Labels: approved, kind/cleanup, lgtm

#4958 Nightly CI and Operator Setup script
  Changelog.md
  scripts/configure-cluster/common/setup-operators.sh
  scripts/openshiftci-Nightly-SBO-tests.sh
Labels: approved, area/testing, kind/feature, lgtm

#4966 Bumping odo version before release
  Changelog.md
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#4962 Adds a column in odo list output to indicate components created by odo
  Changelog.md
  Makefile
  pkg/odo/cli/component/list.go
  tests/integration/component.go
  tests/integration/devfile/cmd_devfile_list_test.go
Labels: approved, kind/feature, lgtm

#4930 odo link: fix command description
  Changelog.md
  pkg/odo/cli/component/link.go
  tests/integration/cmd_link_unlink_test.go
Labels: approved, lgtm, kind/cleanup

#4972 Fix reports directory for operatorhub nightly tests
  scripts/openshiftci-Nightly-SBO-tests.sh
  scripts/openshiftci-periodic-tests.sh
  scripts/openshiftci-presubmit-all-tests.sh
Labels: approved, lgtm, kind/failing-test

#4977 Updated npm modules for Dependabot warnings
  website/package-lock.json
  website/package.json
Labels: approved, lgtm

#4967 Add deprecation warnings for s2i components
  Changelog.md
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/push.go
  tests/integration/component.go
Labels: approved, lgtm, kind/cleanup

#4983 Adds missing # to a Changelog entry
  Changelog.md
Labels: approved, lgtm

#4982 Documents steps for component creation
  Changelog.md
  website/OWNERS
  website/docs/command-reference/catalog.md
  website/docs/command-reference/component.md
  website/docs/command-reference/env.md
  website/docs/command-reference/login.md
  website/docs/command-reference/storage.md
  website/docs/command-reference/url.md
  website/docs/using-odo/create-component.md
Labels: approved, lgtm, kind/documentation

#4986 Remove empty docs; add when ready
  website/docs/architecture/devfile.md
  website/docs/architecture/odo-init-image.md
  website/docs/architecture/overview.md
  website/docs/architecture/service-binding.md
  website/docs/contributing/code.md
  website/docs/contributing/proposals/_category_.json
  website/docs/contributing/proposals/feature-1.md
  website/docs/getting-started/basics.md
  website/docs/getting-started/cluster-setup/development-clusters.md
  website/docs/getting-started/cluster-setup/kubernetes.md
  website/docs/getting-started/cluster-setup/openshift.md
  website/docs/getting-started/cluster-setup/operators.md
  website/docs/getting-started/features.md
  website/docs/getting-started/import-applications.md
  website/docs/getting-started/quickstart.md
  website/docs/using-odo/continuous-development.md
  website/docs/using-odo/create-url.md
  website/docs/using-odo/debug-application.md
  website/docs/using-odo/environment-variables.md
  website/docs/using-odo/lifecycle-events.md
  website/docs/using-odo/persistent-storage.md
  website/docs/using-odo/push-specific-files.md
  website/docs/using-odo/services.md
  website/docusaurus.config.js
Labels: approved, lgtm, kind/documentation

#5003 Updating pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm

#5005 Updating automatic changelog generation script
  scripts/changelog-script.sh
Labels: approved, lgtm, kind/cleanup

#4906 Dropping support for service catalog based services
  Changelog.md
  Makefile
  pkg/application/application.go
  pkg/application/doc.go
  pkg/odo/cli/application/application.go
  pkg/odo/cli/catalog/describe/service.go
  pkg/odo/cli/catalog/describe/service_catalog_backend.go
  pkg/odo/cli/catalog/list/services.go
  pkg/odo/cli/catalog/search/service.go
  pkg/odo/cli/catalog/util/util_test.go
  pkg/odo/cli/component/link.go
  pkg/odo/cli/component/unlink.go
  pkg/odo/cli/service/create.go
  pkg/odo/cli/service/create_test.go
  pkg/odo/cli/service/delete.go
  pkg/odo/cli/service/list.go
  pkg/odo/cli/service/service.go
  pkg/odo/cli/service/service_catalog_backend.go
  pkg/odo/cli/service/service_test.go
  pkg/odo/cli/service/types.go
  pkg/odo/cli/service/ui/ui.go
  pkg/odo/cli/service/ui/ui_test.go
  pkg/odo/cli/service/utils.go
  pkg/odo/util/completion/completionhandlers.go
  pkg/odo/util/completion/completionhandlers_test.go
  pkg/service/service.go
  pkg/service/service_test.go
  tests/integration/cmd_link_unlink_test.go
  tests/integration/servicecatalog/cmd_link_unlink_test.go
  tests/integration/servicecatalog/cmd_service_test.go
  tests/integration/servicecatalog/servicecatalog_suite_test.go
Labels: approved, lgtm, points/1, kind/code-refactoring

#5002 Bumping odo version v2.2.4 -> v2.3.0
  Changelog.md
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#4974 Fixes the usage of service create command with parameters and dry-run flag
  pkg/odo/cli/service/operator_backend.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: kind/bug, approved, lgtm

#5009 Removed QE members from top-level reviewers
  OWNERS
  tests/OWNERS
Labels: approved, lgtm, kind/cleanup

#4970 Uses the deployment while listing storage from the cluster
  pkg/storage/kubernetes.go
  pkg/storage/kubernetes_test.go
  pkg/testingutil/deployments.go
Labels: kind/bug, approved, lgtm, kind/design

#4973 Add Cluster Setup documentation
  Changelog.md
  website/docs/getting-started/cluster-setup/kubernetes.md
  website/docs/getting-started/cluster-setup/openshift.md
  website/docs/getting-started/features.md
Labels: approved, lgtm, kind/documentation

#4934 Add Tutorials section to doc website
  website/docs/architecture/_category_.json
  website/docs/architecture/secure-registry.md
  website/docs/contributing/_category_.json
  website/docs/tutorials/_category_.json
  website/docs/tutorials/deploying-a-devfile-using-odo-on-IBM-Z-and-Power.md
  website/docs/tutorials/deploying-java-app-with-database.md
Labels: approved, lgtm, kind/documentation

#4963 Send telemetry data on user interrupt
  pkg/odo/genericclioptions/runnable.go
  pkg/segment/context/context.go
  pkg/util/util.go
Labels: approved, lgtm, kind/feature

#5017 Add sonar rule to ignore 'duplicated string literals' error on test files
  sonar-project.properties
Labels: approved, lgtm, kind/cleanup

#5018 Fix typo when there are no services
  pkg/odo/cli/service/list.go
Labels: kind/bug, approved, lgtm

#4979 Fixes ephemeral storage mount issue
  Changelog.md
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/component/status_test.go
  tests/helper/helper_cli.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/helper/helper_run.go
  tests/integration/devfile/cmd_devfile_storage_test.go
Labels: kind/bug, approved, lgtm
