Repository redhat-developer/odo, pull requests merged in 2021-12, with the labels that each got.

#5265 setup minikube before env setup
  scripts/minikube-minishift-setup-env.sh
Labels: approved, lgtm, kind/tests

#5237 Adds mapping support to odo link
  docs/website/docs/command-reference/link.md
  pkg/odo/cli/component/common_link.go
  pkg/odo/cli/component/link.go
  pkg/odo/cli/service/create.go
  pkg/odo/util/cmdutils.go
  pkg/odo/util/cmdutils_test.go
  tests/examples/operators/redis.yaml
  tests/integration/operatorhub/cmd_link_test.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, lgtm, kind/feature

#5238 Use adler32 into URL name
  pkg/kclient/fake/ingress.go
  pkg/url/kubernetes.go
  pkg/url/kubernetes_test.go
  pkg/url/url.go
  pkg/url/utils.go
  pkg/util/util.go
Labels: approved, lgtm, kind/feature

#5260 Devfile telemetry
  go.mod
  go.sum
  pkg/catalog/catalog.go
  pkg/odo/cli/component/create_methods.go
  pkg/segment/integrations.go
  pkg/segment/integrations_test.go
  pkg/segment/segment.go
  vendor/github.com/devfile/registry-support/index/generator/LICENSE
  vendor/github.com/devfile/registry-support/registry-library/library/library.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, kind/feature, area/telemetry

#5270 Default to Y when asking to opt in for telemetry
  pkg/odo/genericclioptions/runnable.go
Labels: approved, lgtm, kind/feature

#5269 Use an image with pre-installed oc/kubectl/ibmcloud for IBM Pipelines
  .ibm/images/Dockerfile
  .ibm/pipelines/functions.sh
  .ibm/pipelines/kubernetes-tests.sh
  .ibm/pipelines/openshift-tests.sh
  .ibm/pipelines/unit-tests.sh
  Makefile
Labels: approved, lgtm, kind/tests

#5272 Fixes done by `goimports -l -w pkg`
  pkg/catalog/catalog.go
  pkg/devfile/adapters/kubernetes/component/podwatcher_test.go
  pkg/devfile/adapters/kubernetes/component/status_test.go
  pkg/envinfo/storage.go
  pkg/kclient/events_test.go
  pkg/kclient/ingress.go
  pkg/kclient/ingress_test.go
  pkg/kclient/pods_test.go
  pkg/odo/cli/catalog/list/list.go
  pkg/odo/cli/catalog/search/search.go
  pkg/odo/cli/component/create_methods.go
  pkg/odo/cli/registry/add.go
  pkg/odo/cli/ui/common.go
  pkg/odo/util/validation/validation_test.go
  pkg/odogenerator/ingressgenerator.go
  pkg/secret/secret.go
  pkg/secret/secret_test.go
  pkg/segment/integrations_test.go
  pkg/sync/adapter_test.go
  pkg/sync/mock/sync.go
  pkg/testingutil/fileutils.go
  pkg/unions/kubernetes_ingress.go
Labels: approved, lgtm, kind/cleanup

#5252 Add suppport for cpuLimit, cpuRequest and memoryRequest
  go.mod
  go.sum
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/kclient/deployments_test.go
  pkg/occlient/routes.go
  pkg/testingutil/routes.go
  pkg/unions/kubernetes_ingress.go
  tests/examples/source/devfiles/nodejs/devfile-with-MR-CL-CR.yaml
  tests/integration/devfile/cmd_devfile_push_test.go
  vendor/github.com/devfile/api/v2/pkg/validation/components.go
  vendor/github.com/devfile/api/v2/pkg/validation/errors.go
  vendor/github.com/devfile/api/v2/pkg/validation/validation-rule.md
  vendor/github.com/devfile/library/pkg/devfile/generator/generators.go
  vendor/github.com/devfile/library/pkg/devfile/generator/utils.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/2.2.0/devfileJsonSchema220.go
  vendor/github.com/devfile/library/pkg/devfile/parser/parse.go
  vendor/github.com/devfile/library/pkg/testingutil/devfile.go
  vendor/github.com/hashicorp/go-version/CHANGELOG.md
  vendor/github.com/hashicorp/go-version/LICENSE
  vendor/github.com/hashicorp/go-version/README.md
  vendor/github.com/hashicorp/go-version/constraint.go
  vendor/github.com/hashicorp/go-version/go.mod
  vendor/github.com/hashicorp/go-version/version.go
  vendor/github.com/hashicorp/go-version/version_collection.go
  vendor/modules.txt
Labels: approved, lgtm

#5233 Segregate Docs
  docs/dev/ci-reference.adoc
  docs/dev/completion-architecture.adoc
  docs/dev/development.adoc
  docs/dev/logging.adoc
  docs/dev/machine-output.adoc
  docs/dev/test-architecture-ppc64le.adoc
  docs/dev/test-architecture-s390x.adoc
  docs/dev/test-architecture.adoc
  docs/dev/usage-data.adoc
  docs/dev/validation-architecture.adoc
  docs/public/breaking-changes-in-odo-2.2.adoc
  docs/public/community.adoc
  docs/public/debugging-using-devfile.adoc
  docs/public/using-storage.adoc
  docs/website/blog/breaking-changes-in-odo-2.2.md
  docs/website/docs/command-reference/storage.md
  docs/website/docs/contributing/_category_.json
  docs/website/docs/contributing/docs.md
  docs/website/docs/contribution.md
  docs/website/docs/getting-started/quickstart.md
  docs/website/docs/tutorials/debugging-using-devfile.md
  docs/website/docs/tutorials/using-devfile-lifecycle-events.md
  docs/website/docs/tutorials/using-devfile-odo.dev.push.path-attribute.md
  docs/website/docusaurus.config.js
Labels: approved, lgtm, kind/cleanup, kind/documentation

#5236 Add support for tracking people visiting odo.dev
  docs/website/docusaurus-odo-plugin-segment/README.md
  docs/website/docusaurus-odo-plugin-segment/index.js
  docs/website/docusaurus-odo-plugin-segment/package-lock.json
  docs/website/docusaurus-odo-plugin-segment/package.json
  docs/website/docusaurus-odo-plugin-segment/segment.js
  docs/website/docusaurus.config.js
  docs/website/package-lock.json
  docs/website/package.json
Labels: approved, lgtm, kind/feature

#5273 refactor devfile-registry tests
  tests/integration/devfile/cmd_devfile_registry_test.go
Labels: approved, lgtm, kind/code-refactoring, kind/tests

#5280 Add sucess and failure for ibmcloud tests comments
  .ibm/pipelines/functions.sh
  .ibm/pipelines/kubernetes-tests.sh
  .ibm/pipelines/openshift-tests.sh
  .ibm/pipelines/unit-tests.sh
Labels: approved, lgtm, kind/tests

#5275 refactor devfile storage test
  tests/integration/devfile/cmd_devfile_storage_test.go
Labels: approved, lgtm, kind/code-refactoring, kind/tests

#5287 Use odo-init-image v1.1.11
  pkg/devfile/adapters/common/utils.go
Labels: approved, lgtm, kind/feature

#5277 Refactor cmd_devfile_log_tests.go
  tests/integration/devfile/cmd_devfile_log_test.go
Labels: approved, lgtm

#5290 add blog post about v2.4.3
  docs/website/blog/2021-05-04-breaking-changes-in-odo-2.2.md
  docs/website/blog/2021-12-14-odo-v2.4.3.md
Labels: approved, lgtm, kind/documentation

#5291 update gjson version
  go.mod
  go.sum
  vendor/github.com/openshift/client-go/build/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/build.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/build_client.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/buildconfig.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/doc.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/fake/doc.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/fake/fake_build.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/fake/fake_build_client.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/fake/fake_buildconfig.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/doc.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/doc.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/fake_image.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/fake_image_client.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/fake_imagesignature.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/fake_imagestream.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/fake_imagestreamimage.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/fake_imagestreamimport.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/fake_imagestreammapping.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/fake_imagestreamtag.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/fake/fake_imagetag.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/image.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/image_client.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagesignature.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestream.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestreamimage.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestreamimport.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestreammapping.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagestreamtag.go
  vendor/github.com/openshift/client-go/image/clientset/versioned/typed/image/v1/imagetag.go
  vendor/github.com/tidwall/gjson/README.md
  vendor/github.com/tidwall/gjson/SYNTAX.md
  vendor/github.com/tidwall/gjson/gjson.go
  vendor/github.com/tidwall/gjson/go.mod
  vendor/github.com/tidwall/gjson/go.sum
  vendor/github.com/tidwall/match/match.go
  vendor/github.com/tidwall/pretty/README.md
  vendor/github.com/tidwall/pretty/go.mod
  vendor/github.com/tidwall/pretty/pretty.go
  vendor/modules.txt
Labels: approved, lgtm, kind/cleanup

#5281 Windows tests on Ibm pipeline
  .ibm/images/Dockerfile
  .ibm/pipelines/windows-test-script.ps1
  .ibm/pipelines/windows-test.sh
  tests/integration/devfile/cmd_devfile_build_images_test.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/cmd_devfile_deploy_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, lgtm, kind/tests

#5292 Cleanup tests namespaces before to run tests
  .ibm/pipelines/functions.sh
  .ibm/pipelines/kubernetes-tests.sh
  .ibm/pipelines/openshift-tests.sh
Labels: approved, lgtm, kind/tests

#5276 Delete outerloop resources with undeploy
  docs/website/docs/command-reference/create.md
  docs/website/docs/command-reference/delete.md
  docs/website/docs/command-reference/flags.md
  pkg/devfile/adapters/common/apply.go
  pkg/devfile/adapters/common/command.go
  pkg/devfile/adapters/common/command_apply.go
  pkg/devfile/adapters/common/command_composite.go
  pkg/devfile/adapters/common/command_parallel_composite.go
  pkg/devfile/adapters/common/command_simple.go
  pkg/devfile/adapters/common/command_supervisor.go
  pkg/devfile/adapters/common/generic.go
  pkg/devfile/adapters/common/interface.go
  pkg/devfile/adapters/kubernetes/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/component.go
  pkg/devfile/adapters/kubernetes/component/component_image.go
  pkg/devfile/adapters/kubernetes/component/component_kubernetes.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/devfile.go
  pkg/service/service.go
  tests/integration/devfile/cmd_devfile_delete_test.go
  tests/integration/devfile/cmd_devfile_deploy_test.go
Labels: approved, lgtm, kind/feature

#5286 Fix panic with interactive odo create when talking to a disconnected cluster
  pkg/odo/cli/component/create_methods.go
Labels: kind/bug, approved, lgtm

#5288 add ansible script to create a Win VM
  scripts/ansible/kubernetes-cluster/create-vm.yml
  scripts/ansible/kubernetes-cluster/vars.yml
Labels: approved, lgtm, kind/tests

#5279 Handle ephemeral field on Volumes
  docs/website/docs/command-reference/flags.md
  docs/website/docs/command-reference/storage.md
  pkg/component/component_full_description.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/storage/utils.go
  pkg/devfile/adapters/kubernetes/storage/utils_test.go
  pkg/envinfo/storage.go
  pkg/localConfigProvider/localConfigProvider.go
  pkg/odo/cli/storage/create.go
  pkg/odo/cli/storage/list_test.go
  pkg/odo/util/completion/completionhandlers.go
  pkg/storage/kubernetes.go
  pkg/storage/kubernetes_test.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  pkg/storage/types.go
  pkg/storage/types_test.go
  pkg/storage/utils.go
  tests/examples/source/devfiles/nodejs/devfile-2.1.0.yaml
  tests/integration/devfile/cmd_devfile_storage_test.go
Labels: approved, lgtm, kind/feature

#5302 Use odo-robot to post logs to PR
  .ibm/images/Dockerfile
  .ibm/pipelines/functions.sh
Labels: approved, lgtm, kind/tests

#5306 Update to install OLM for K8S tests
  scripts/ansible/kubernetes-cluster/README.md
Labels: approved, lgtm

#5307 Run Operator Hub integration tests on IBMKubernetes cluster
  .ibm/pipelines/kubernetes-tests.sh
Labels: approved, lgtm, kind/tests

#5308 `s/openshift/redhat-developer` in changelog script
  scripts/changelog-script.sh
Labels: kind/bug, approved, lgtm

#5284 Add release-bit-verification script
  scripts/release-bit-verification.sh
Labels: approved, lgtm, kind/tests
