Repository redhat-developer/odo, pull requests merged in 2021-04, with the labels that each got.

#4573 Swap login/logout calls from using odo to oc directly
  scripts/openshiftci-periodic-tests.sh
  scripts/openshiftci-presubmit-all-tests-old.sh
  scripts/openshiftci-presubmit-all-tests.sh
Labels: approved, kind/failing-test, lgtm, ok-to-test

#4563 Modifies newKubernetesAdapter() and others
  pkg/component/component.go
  pkg/devfile/adapters/helper.go
  pkg/devfile/adapters/helper_test.go
  pkg/devfile/adapters/kubernetes/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/component/podwatcher.go
  pkg/devfile/adapters/kubernetes/component/podwatcher_test.go
  pkg/devfile/adapters/kubernetes/component/status.go
  pkg/devfile/adapters/kubernetes/component/status_test.go
  pkg/odo/cli/component/common_push.go
  pkg/url/url.go
  pkg/url/url_test.go
Labels: approved, kind/failing-test, lgtm

#4557 Decide GVR based on underlying cluster
  pkg/kclient/deployments.go
  pkg/odo/cli/component/common_link.go
Labels: approved, kind/bug, lgtm

#4572 Disable test sending out telemetry
  tests/integration/cmd_pref_config_test.go
Labels: approved, lgtm

#4576 Use UserId instead of AnonymousId while sending telemetry data
  pkg/segment/segment.go
  pkg/segment/segment_test.go
Labels: approved, kind/code-refactoring, lgtm

#4585 Updating segment variable= dev key as default overrideable with ldflags
  Makefile
  pkg/segment/segment.go
Labels: approved, lgtm

#4578 Separate out openshift specific tests
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, kind/failing-test, lgtm

#4560 Update documentation for SBO installation
  docs/public/install-service-binding-operator.adoc
Labels: approved, lgtm

#4580 introduce ODO_DISABLE_TELEMETRY and skip telemetry question when there is no tty
  USAGE_DATA.adoc
  pkg/odo/genericclioptions/runnable.go
  tests/e2escenarios/e2escenarios_suite_test.go
  tests/helper/helper_generic.go
  tests/integration/cmd_pref_config_test.go
  tests/integration/debug/debug_suite_test.go
  tests/integration/devfile/debug/debug_suite_test.go
  tests/integration/devfile/devfile_suite_test.go
  tests/integration/integration_suite_test.go
  tests/integration/loginlogout/loginlogout_suite_test.go
  tests/integration/operatorhub/operatorhub_suite_test.go
  tests/integration/project/project_suite_test.go
  tests/integration/servicecatalog/servicecatalog_suite_test.go
  tests/template/template_suite_test.go
Labels: approved, kind/cleanup, kind/code-refactoring, lgtm, release-blocker

#4599 Revert Java:8 image import to default
  tests/e2escenarios/e2e_images_test.go
  tests/helper/helper_oc.go
Labels: approved, kind/failing-test, lgtm

#4564 Cleanup context in devfile integration tests
  .github/PULL_REQUEST_TEMPLATE.md
  tests/integration/devfile/cmd_devfile_app_test.go
  tests/integration/devfile/cmd_devfile_debug_test.go
  tests/integration/devfile/cmd_devfile_delete_test.go
  tests/integration/devfile/cmd_devfile_describe_test.go
  tests/integration/devfile/cmd_devfile_log_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/cmd_devfile_test_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
  tests/integration/devfile/cmd_devfile_watch_test.go
Labels: approved, lgtm

#4601 add operator-hub tests to ci for s390x platform
  scripts/configure-installer-tests-cluster-s390x.sh
  scripts/openshiftci-presubmit-all-tests.sh
Labels: approved, area/System-PZ, lgtm, needs-ok-to-test

#4602 update java image import for s390x platform
  scripts/configure-installer-tests-cluster-s390x.sh
Labels: approved, area/System-PZ, lgtm, ok-to-test

#4608 Bumping odo version to v2.1.0
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#4610 Fixes kClient namespace in createKubernetesAdapter()
  pkg/devfile/adapters/helper.go
Labels: approved, kind/bug, lgtm

#4611 SBO 0.6.0 and minor fixes
  docs/creating-a-multicomponent-application-with-odo.md
  docs/install-service-binding-operator.md
  docs/odo-architecture.md
  docs/sample-applications.md
Labels: approved

#4605 Adding exchange for minikube and minishift
  scripts/minici-presubmit-all-tests.sh
  scripts/minikube-minishift-setup-env.sh
Labels: approved, kind/failing-test, lgtm

#4613 fix odo compatibility with SBO 0.7.0
  go.mod
  go.sum
  pkg/kclient/deployments.go
  pkg/odo/cli/component/common_link.go
  pkg/odo/cli/component/link.go
  vendor/github.com/openshift/custom-resource-status/LICENSE
  vendor/github.com/openshift/custom-resource-status/conditions/v1/conditions.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/doc.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/types.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/zz_generated.deepcopy.go
  vendor/github.com/redhat-developer/service-binding-operator/LICENSE
  vendor/github.com/redhat-developer/service-binding-operator/pkg/apis/operators/v1alpha1/doc.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/apis/operators/v1alpha1/register.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/apis/operators/v1alpha1/servicebinding_types.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/apis/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/apis/operators/v1alpha1/zz_generated.openapi.go
  vendor/modules.txt
Labels: approved, kind/bug, lgtm, release-blocker

#4619 add Application in the odo env view standard output
  pkg/odo/cli/env/view.go
  tests/integration/devfile/cmd_devfile_env_test.go
Labels: approved, kind/bug, lgtm

#4586 Sanitize file-path from telemetry data
  pkg/segment/segment.go
  pkg/segment/segment_test.go
Labels: approved, kind/cleanup, lgtm

#4625 Upgrade ci-firewall version to v0.1.1
  scripts/minici-presubmit-all-tests.sh
Labels: approved, kind/failing-test, kind/flake, lgtm

#4633 Increase Run time for minikube job
  scripts/minici-presubmit-all-tests.sh
Labels: approved, kind/failing-test, lgtm

#4628 Removes travis & codecov configuration
  .codecov.yml
  .travis.yml
Labels: approved, kind/cleanup, lgtm

#4629 Use ParseDevfileAndValidate instead of ParseAndValidate
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/component/status.go
  pkg/odo/cli/component/test.go
  pkg/odo/cli/component/watch.go
  pkg/odo/genericclioptions/context.go
Labels: approved, kind/cleanup, lgtm

#4634 Removes docker related code
  pkg/devfile/adapters/helper.go
  pkg/localConfigProvider/localConfigProvider.go
  pkg/odo/cli/catalog/describe/component.go
  pkg/odo/cli/catalog/list/components.go
  pkg/odo/cli/component/common_push.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/exec.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/component/status.go
  pkg/odo/cli/component/watch.go
  pkg/odo/cli/preference/set.go
  pkg/odo/cli/preference/unset.go
  pkg/odo/cli/preference/view.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/util/pushtarget/pushtarget.go
  pkg/odo/util/pushtarget/pushtarget_test.go
  pkg/preference/machine_output.go
  pkg/preference/preference.go
  pkg/preference/preference_test.go
  pkg/url/status.go
  pkg/url/url.go
  tests/integration/cmd_pref_config_test.go
Labels: approved, kind/cleanup, lgtm

#4627 Refactor Kubernetes storage utils for devfile/library migration
  pkg/devfile/adapters/common/types.go
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/common/utils_test.go
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/docker/storage/adapter.go
  pkg/devfile/adapters/docker/storage/adapter_test.go
  pkg/devfile/adapters/docker/storage/utils.go
  pkg/devfile/adapters/docker/storage/utils_test.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/storage/utils.go
  pkg/devfile/adapters/kubernetes/storage/utils_test.go
  pkg/envinfo/storage.go
Labels: approved, kind/cleanup, kind/code-refactoring, lgtm

#4638 Adding inseucre skip to cluster configure commands
  scripts/configure-cluster/common/auth.sh
  scripts/configure-cluster/common/kubeconfigandadmin.sh
Labels: approved, lgtm

#4632 Upgrading ci-firewall version for linix
  scripts/openshiftci-e2e-4x-psi-tests.sh
Labels: approved, kind/failing-test, lgtm

#4630 Revert java import changes for s390x
  scripts/configure-installer-tests-cluster-s390x.sh
Labels: approved, kind/failing-test, lgtm

#4518 implement devfile conversion ( with --now support) on --s2i without --git flag
  Makefile
  pkg/config/config.go
  pkg/devfile/convert/convert.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/create_helpers.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/devfile.go
  tests/e2escenarios/e2e_beta_test.go
  tests/e2escenarios/e2e_devfile_test.go
  tests/e2escenarios/e2e_images_test.go
  tests/e2escenarios/e2e_source_test.go
  tests/helper/helper_cli.go
  tests/helper/helper_configValidate.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/helper/odo_utils.go
  tests/integration/cmd_app_test.go
  tests/integration/cmd_debug_test.go
  tests/integration/cmd_pref_config_test.go
  tests/integration/cmd_push_test.go
  tests/integration/cmd_storage_test.go
  tests/integration/cmd_url_test.go
  tests/integration/component.go
  tests/integration/debug/cmd_debug_test.go
  tests/integration/devfile/utils/utils.go
  tests/integration/generic_test.go
  tests/template/template_cleantest_test.go
Labels: approved, kind/feature, lgtm

#4595 Adding container flag for storage and fixing code to work with it
  docs/public/using-storage.adoc
  pkg/envinfo/storage.go
  pkg/localConfigProvider/localConfigProvider.go
  pkg/odo/cli/storage/create.go
  tests/integration/devfile/cmd_devfile_storage_test.go
Labels: approved, kind/feature, lgtm

#4636 OCI-based devfile reigstry support patch
  pkg/odo/cli/component/create.go
Labels: approved, kind/bug, lgtm

#4647 Remove Dockerfile.travislogin as its not being used anywhere
  openshift-ci/build-root/Dockerfile.travislogin
Labels: approved, lgtm

#4650 Creates service on cluster upon "odo push"
  go.mod
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/service/create.go
  pkg/odo/cli/service/operator_backend.go
  pkg/service/service.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/feature, lgtm

#4652 Require "Epic" for a user story
  .github/ISSUE_TEMPLATE/UserStory.md
Labels: approved, lgtm

#4657 Updating main-branch
  scripts/minici-presubmit-all-tests.sh
  scripts/openshiftci-e2e-4x-psi-tests.sh
Labels: approved, lgtm

#4656 Adds component labels to Operator backed services
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/service/service.go
Labels: approved, kind/feature, lgtm

#4471 Refactor help examples to use go templates
  pkg/odo/cli/preference/set.go
  pkg/odo/cli/preference/unset.go
Labels: approved, kind/code-refactoring, lgtm

#4665 Adds Parthvi to top level OWNERS
  OWNERS
Labels: approved, lgtm

#4663 Fix filename
  docs/public/installing-and-configuring-minikube-environment.adoc
Labels: approved, kind/documentation, lgtm, ok-to-test

#4653 Enabling operator-hub test for Power.
  scripts/configure-installer-tests-cluster-ppc64le.sh
  scripts/openshiftci-presubmit-all-tests.sh
Labels: approved, lgtm, ok-to-test

#4667 Adjust SBO link and fix broken relative links to other articles
  docs/public/operator-hub.adoc
  docs/public/operators-on-minikube.adoc
Labels: approved, kind/documentation, lgtm, ok-to-test

#4659 skip centos7 image test on s390x
  tests/e2escenarios/e2e_images_test.go
Labels: approved, area/System-PZ, lgtm, ok-to-test

#4672 Adjust SBO link and fix broken relative links to other articles
  chosen-docs/upstream/installing-and-configuring-minikube-environment.md
  docs/installing-and-configuring-minikube-environment.md
  docs/operator-hub.md
  docs/operators-on-minikube.md
  docs/using-storage.md
  index.md
Labels: approved, kind/documentation, lgtm

#4669 Adds a check to ignore pods which are marked for deletion
  pkg/kclient/pods.go
  pkg/kclient/pods_test.go
  tests/integration/devfile/cmd_devfile_storage_test.go
Labels: approved, kind/bug, lgtm

#4676 Adds Parthvi to OWNERS of gh-pages branch
  OWNERS
Labels: approved, lgtm

#4660 invalidate the cache if there is an error
  pkg/catalog/catalog.go
  pkg/util/httpcache.go
  pkg/util/httpcache_test.go
Labels: approved, kind/bug, lgtm

#4677 Fixes the storage list integration test for kubernetes clusters
  tests/helper/helper_cli.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/helper/helper_run.go
  tests/integration/devfile/cmd_devfile_storage_test.go
Labels: approved, kind/failing-test, lgtm
