Repository redhat-developer/odo, pull requests merged in 2021-06, with the labels that each got.

#4757 add feloy as top-level approver and anandrkskd as reviewer and tests approver
  OWNERS
  tests/OWNERS
Labels: approved, lgtm

#4743 Updating docs and changelog script for updated release process
  docs/dev/development.adoc
  scripts/changelog-script.sh
Labels: approved, lgtm

#4756 Adding KUBECONFIG checks in odo catalog list components
  Changelog.md
  pkg/odo/cli/catalog/list/components.go
  pkg/util/util.go
  tests/integration/devfile/cmd_devfile_catalog_test.go
Labels: approved, kind/bug, lgtm

#4708 Adding wrapper functions in tests helper lib
  tests/helper/helper_cmd_wrapper.go
  tests/integration/devfile/cmd_devfile_watch_test.go
Labels: approved, kind/code-refactoring, lgtm

#4765 use filepath Join instead of / while constructing kubeconfig path
  Changelog.md
  pkg/util/util.go
Labels: approved, kind/bug, lgtm

#4766 Adds the annotation app.openshift.io/vcs-uri to deployments
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/odo/cli/component/devfile.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/helper/helper_cli.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/helper/helper_run.go
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, kind/feature, lgtm

#4767 [skip ci] Fixed README typo for nodejs devfile version
  README.adoc
Labels: approved, kind/documentation, lgtm

#4729 Custom link names and bindAsFiles option for SB
  Changelog.md
  pkg/envinfo/envinfo.go
  pkg/envinfo/envinfo_test.go
  pkg/odo/cli/component/common_link.go
  pkg/odo/cli/component/link.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, lgtm

#4752 Use staging devfile registry for integration tests
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/debug/debug_suite_test.go
  tests/integration/devfile/devfile_suite_test.go
Labels: approved, kind/cleanup, lgtm

#4775 Use staging registry for devfile debug suite test
  tests/integration/devfile/debug/debug_suite_test.go
Labels: approved, lgtm

#4758 Sanitize Telemetry data
  pkg/segment/segment.go
  pkg/segment/segment_test.go
Labels: approved, kind/bug, lgtm

#4774 Enhance usage data documentation
  README.adoc
  USAGE_DATA.adoc
  docs/dev/ci-reference.adoc
  docs/dev/development.adoc
  docs/dev/test-architecture-ppc64le.adoc
  docs/dev/test-architecture-s390x.adoc
  docs/dev/test-architecture.adoc
  docs/dev/usage-data.adoc
Labels: approved, kind/documentation, lgtm

#4791 Reducing timeout for windows and macOS unit test to 20m
  scripts/openshiftci-e2e-4x-psi-tests.sh
  scripts/openshiftci-unit-psi-tests_win_mac.sh
Labels: approved, kind/failing-test, lgtm

#4772 odo push can deploy new services when some services are already deployed
  Changelog.md
  pkg/service/service.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/bug, lgtm

#4787 ginkgo checksum error on CI
  Makefile
Labels: approved, lgtm

#4785 change debugport in container if its different from env_info
  Changelog.md
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils_test.go
  pkg/devfile/convert/convert.go
  tests/integration/cmd_debug_test.go
Labels: approved, kind/bug, lgtm

#4770 Refactor OperatorHub integration tests
  tests/helper/helper_oc.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/code-refactoring, lgtm

#4793 Refactor devfile delete tests and add validity checks for delete command
  pkg/odo/genericclioptions/runnable.go
  tests/e2escenarios/e2e_java_test.go
  tests/integration/component.go
  tests/integration/devfile/cmd_devfile_delete_test.go
Labels: approved, kind/cleanup, kind/code-refactoring, lgtm

#4742 List components from other sources
  pkg/application/application_test.go
  pkg/application/labels/labels.go
  pkg/application/labels/labels_test.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/labels/labels_test.go
  pkg/component/pushed_component.go
  pkg/component/types.go
  pkg/kclient/deployments.go
  pkg/kclient/fake/ingress.go
  pkg/odo/cli/application/application.go
  pkg/odo/cli/application/describe.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/project/project.go
  pkg/odo/util/completion/completionhandlers.go
  pkg/project/labels.go
  pkg/storage/labels/labels_test.go
  pkg/storage/storage_test.go
  pkg/testingutil/deploymentconfigs.go
  pkg/testingutil/deployments.go
  pkg/testingutil/routes.go
  pkg/url/labels/labels_test.go
  pkg/url/url_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/examples/manifests/dc-label.yaml
  tests/examples/manifests/deployment-app-label.yaml
  tests/examples/manifests/deployment-httpd-label.yaml
  tests/helper/helper_cli.go
  tests/helper/helper_filesystem.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/cmd_cmp_sub_test.go
  tests/integration/component.go
Labels: approved, kind/code-refactoring, kind/feature, lgtm

#4803 Bumping odo version
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#4804 Add changelogs
  Changelog.md
Labels: approved, kind/documentation, lgtm

#4777 Adds ability to link one devfile component to another
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/kclient/services.go
  pkg/odo/cli/component/common_link.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/feature, lgtm

#4761 Only delete service from devfile
  Changelog.md
  docs/public/deploying-java-app-with-database.adoc
  docs/public/operator-hub.adoc
  go.sum
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/odo/cli/service/create.go
  pkg/odo/cli/service/delete.go
  pkg/odo/cli/service/interface.go
  pkg/odo/cli/service/list.go
  pkg/odo/cli/service/list_operator.go
  pkg/odo/cli/service/list_operator_test.go
  pkg/odo/cli/service/operator_backend.go
  pkg/odo/cli/service/service_catalog_backend.go
  pkg/service/service.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, lgtm

#4751 Revised Proposal to param based operator service creation
  docs/proposals/improved-schema-for-services.md
Labels: approved, kind/design, kind/documentation, lgtm

#4735 Changes the route and ingress names to include the app name
  pkg/component/component.go
  pkg/kclient/ingress.go
  pkg/occlient/routes.go
  pkg/url/kubernetes.go
  pkg/url/kubernetes_test.go
  pkg/url/mock_Client.go
  pkg/url/s2i.go
  pkg/url/url.go
  pkg/url/url_test.go
  tests/integration/devfile/cmd_devfile_delete_test.go
Labels: approved, kind/bug, kind/cleanup, kind/code-refactoring, lgtm

#4809 remove getInitContainer from odo
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils_test.go
Labels: approved, lgtm

#4823 Fix kubeconfig issue when minikube already running on VM
  scripts/minikube-minishift-setup-env.sh
Labels: approved, kind/failing-test, lgtm

#4831 Fixes push when csv support is not present on the cluster
  pkg/service/service.go
Labels: approved, kind/bug, lgtm

#4832 Updating CI Firewall version to v0.1.2
  scripts/minici-presubmit-all-tests.sh
  scripts/openshiftci-e2e-4x-psi-tests.sh
Labels: approved, kind/code-refactoring, lgtm

#4825 Fix URL and typos with install-operator-on-minikube doc
  docs/public/operators-on-minikube.adoc
Labels: approved, kind/documentation, lgtm

#4788 Implement runner function on test
  tests/e2escenarios/e2e_devfile_test.go
  tests/e2escenarios/e2e_images_test.go
  tests/e2escenarios/e2e_java_test.go
  tests/e2escenarios/e2e_source_test.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/helper/odo_utils.go
  tests/integration/cmd_app_test.go
  tests/integration/cmd_debug_test.go
  tests/integration/cmd_link_unlink_test.go
  tests/integration/cmd_pref_config_test.go
  tests/integration/cmd_push_test.go
  tests/integration/cmd_storage_test.go
  tests/integration/cmd_url_test.go
  tests/integration/cmd_watch_test.go
  tests/integration/component.go
  tests/integration/debug/cmd_debug_test.go
  tests/integration/devfile/cmd_devfile_app_test.go
  tests/integration/devfile/cmd_devfile_catalog_test.go
  tests/integration/devfile/cmd_devfile_config_test.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/cmd_devfile_debug_test.go
  tests/integration/devfile/cmd_devfile_delete_test.go
  tests/integration/devfile/cmd_devfile_describe_test.go
  tests/integration/devfile/cmd_devfile_env_test.go
  tests/integration/devfile/cmd_devfile_log_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/cmd_devfile_registry_test.go
  tests/integration/devfile/cmd_devfile_status_test.go
  tests/integration/devfile/cmd_devfile_storage_test.go
  tests/integration/devfile/cmd_devfile_test_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
  tests/integration/devfile/cmd_devfile_watch_test.go
  tests/integration/devfile/debug/cmd_devfile_debug_test.go
  tests/integration/devfile/utils/utils.go
  tests/integration/generic_test.go
  tests/integration/loginlogout/cmd_login_logout_test.go
  tests/integration/servicecatalog/cmd_link_unlink_test.go
  tests/integration/servicecatalog/cmd_service_test.go
  tests/template/template_cleantest_test.go
Labels: approved, lgtm

#4795 Fixing GOPATH and GOBIN in minikube and minishift scripts
  scripts/minikube-minishift-setup-env.sh
Labels: approved, lgtm

#4834 Fix minikube tests if kubelet gets stopped
  scripts/minikube-minishift-setup-env.sh
Labels: approved, kind/failing-test, lgtm

#4821 odo catalog describe service <operator> --example
  pkg/odo/cli/catalog/describe/operator_backend.go
  pkg/odo/cli/catalog/describe/service.go
  pkg/service/types.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/feature, lgtm

#4829 Fixes the unexpected deletion of ingress URLs with default tls secret
  pkg/kclient/fake/ingress.go
  pkg/testingutil/routes.go
  pkg/url/kubernetes.go
  pkg/url/kubernetes_test.go
  pkg/url/status_test.go
  pkg/url/url.go
  pkg/url/url_test.go
Labels: approved, kind/bug, lgtm

#4837 Fix minikube failures on pr
  scripts/minikube-minishift-setup-env.sh
Labels: approved, kind/failing-test, lgtm

#4835 Remove cmd helper functions
  docs/dev/test-architecture.adoc
  tests/helper/helper_run.go
  tests/integration/devfile/debug/debug_suite_test.go
  tests/integration/devfile/devfile_suite_test.go
  tests/integration/operatorhub/cmd_service_test.go
  tests/integration/project/cmd_project_test.go
Labels: approved, kind/code-refactoring, lgtm

#4811 Set 4 nodes for ginkgo tests
  Makefile
Labels: approved, kind/code-refactoring, lgtm

#4820 add integration tests for devfile 2.1.0 and refactor devfile push tests
  pkg/devfile/devfile.go
  tests/examples/source/devfiles/nodejs/devfile-variables.yaml
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/cmd_devfile_list_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, area/testing, lgtm

#4704 param based odo service create for operator backed services
  docs/dev/test-architecture.adoc
  go.mod
  go.sum
  pkg/kclient/operators.go
  pkg/odo/cli/service/create.go
  pkg/odo/cli/service/operator_backend.go
  pkg/odo/cli/service/service_catalog_backend.go
  pkg/service/crd_builder.go
  pkg/service/crd_builder_test.go
  pkg/service/crd_spec_builder.go
  pkg/service/crd_spec_builder_test.go
  pkg/service/service.go
  scripts/configure-cluster/common/setup-operators.sh
  scripts/configure-cluster/common/setup-postgres-operator.sh
  scripts/configure-installer-tests-cluster.sh
  scripts/run_all_tests.sh
  tests/helper/helper_cli.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/operatorhub/cmd_service_test.go
  vendor/github.com/tidwall/gjson/README.md
  vendor/github.com/tidwall/gjson/SYNTAX.md
  vendor/github.com/tidwall/gjson/gjson.go
  vendor/github.com/tidwall/sjson/LICENSE
  vendor/github.com/tidwall/sjson/README.md
  vendor/github.com/tidwall/sjson/go.mod
  vendor/github.com/tidwall/sjson/go.sum
  vendor/github.com/tidwall/sjson/logo.png
  vendor/github.com/tidwall/sjson/sjson.go
  vendor/modules.txt
Labels: approved, kind/feature, lgtm

#4846 Run operator hub tests in parallel
  Makefile
Labels: approved, kind/code-refactoring, lgtm

#4807 Remove nesting levels in operatorhub integration tests
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/code-refactoring, lgtm

#4806 app tests refactored
  tests/integration/cmd_app_test.go
Labels: approved, kind/code-refactoring, lgtm

#4848 update changelog with `odo service create` feature changes
  Changelog.md
Labels: approved, kind/documentation, lgtm

#4661 Moving to creating n/w.k8s.io/v1beta1 ingress with fallback
  pkg/component/pushed_component.go
  pkg/kclient/fake/discovery.go
  pkg/kclient/fake/ingress.go
  pkg/kclient/fakeclient.go
  pkg/kclient/ingress.go
  pkg/kclient/ingress_test.go
  pkg/kclient/kclient.go
  pkg/kclient/secrets_test.go
  pkg/occlient/fakeclient.go
  pkg/odo/cli/url/list.go
  pkg/odogenerator/ingressgenerator.go
  pkg/unions/kubernetes_ingress.go
  pkg/url/kubernetes.go
  pkg/url/kubernetes_test.go
  pkg/url/s2i.go
  pkg/url/status.go
  pkg/url/status_test.go
  pkg/url/types.go
  pkg/url/url.go
  pkg/url/url_test.go
  tests/integration/cmd_url_test.go
Labels: approved, kind/task, lgtm

#4852 Update go 1.15
  Dockerfile.rhel
  docs/dev/development.adoc
  go.mod
  go.sum
  openshift-ci/build-root/Dockerfile
  scripts/rpm-prepare.sh
  vendor/modules.txt
Labels: approved, kind/task, lgtm

#4859 disable rpm-build test from unit test
  scripts/openshiftci-presubmit-unittests.sh
Labels: approved, kind/failing-test, lgtm

#4812 format service parameters as a table
  pkg/odo/cli/catalog/describe/operator_backend.go
Labels: approved, area/UX, kind/design, lgtm

#4763 Add cluster type to telemetry
  pkg/kclient/fake/discovery.go
  pkg/occlient/fakeclient.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/create_helpers.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/project/create.go
  pkg/odo/cli/project/set.go
  pkg/segment/context/context.go
  pkg/segment/context/context_test.go
  pkg/segment/segment.go
Labels: approved, kind/feature, lgtm
