Repository redhat-developer/odo, pull requests merged in 2021-07, with the labels that each got.

#4864 Correct ioutil.WriteFile comment about os.Create
  pkg/util/file_indexer.go
Labels: approved, kind/documentation, lgtm

#4819 `odo link` and `odo unlink` write to devfile without deploying to cluster
  Changelog.md
  Makefile
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/envinfo/envinfo.go
  pkg/envinfo/envinfo_test.go
  pkg/kclient/deployments.go
  pkg/kclient/deployments_test.go
  pkg/odo/cli/component/common_link.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/link.go
  pkg/odo/cli/component/unlink.go
  pkg/service/service.go
  pkg/storage/kubernetes.go
  tests/examples/source/devfiles/nodejs/devfile-with-link.yaml
  tests/integration/operatorhub/cmd_link_test.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/feature, lgtm

#4868 Some doc on app / project packages
  pkg/application/application.go
  pkg/application/doc.go
  pkg/project/doc.go
  pkg/project/project.go
Labels: approved, kind/documentation, lgtm

#4849 Refactor project command tests
  Makefile
  tests/integration/project/cmd_project_test.go
Labels: approved, kind/code-refactoring, lgtm

#4863 Refactor component tests
  tests/integration/component.go
Labels: approved, kind/code-refactoring, lgtm

#4853 Updating create, delete and get to newer networking v1 extension v1 union functions
  Changelog.md
  pkg/kclient/fakeclient.go
  pkg/kclient/ingress.go
  pkg/kclient/ingress_test.go
  pkg/kclient/kclient.go
  pkg/odogenerator/ingressgenerator.go
  pkg/unions/kubernetes_ingress.go
  pkg/url/kubernetes.go
  pkg/url/types.go
  pkg/url/url.go
Labels: approved, kind/task, lgtm

#4720 Update URL in doc
  docs/public/deploying-a-devfile-using-odo.adoc
Labels: approved, lgtm

#4860 refactor cmd-storage test
  tests/integration/cmd_storage_test.go
Labels: approved, kind/code-refactoring, lgtm

#4866 Add linked service information in odo describe
  Changelog.md
  pkg/component/component.go
  pkg/component/component_full_description.go
  pkg/component/component_test.go
  pkg/component/pushed_component.go
  pkg/component/types.go
  pkg/kclient/deployments.go
  pkg/odo/cli/component/delete.go
  pkg/odo/util/cmdutils.go
  pkg/odo/util/completion/completionhandlers.go
  pkg/service/service.go
  tests/integration/operatorhub/cmd_link_test.go
Labels: approved, kind/feature, lgtm

#4870 Add telemetry contextual properties if it is enabled
  Changelog.md
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/project/create.go
  pkg/odo/cli/project/set.go
  pkg/odo/genericclioptions/runnable.go
  pkg/segment/context/context.go
  pkg/segment/context/context_test.go
  pkg/segment/segment.go
  pkg/segment/segment_test.go
Labels: approved, kind/cleanup, lgtm

#4881 Fix Changelog
  Changelog.md
Labels: approved, kind/documentation, lgtm

#4754 Enable olm and Run operatorhub tests on kubernetes cluster
  scripts/configure-cluster/common/setup-operators.sh
  scripts/configure-installer-tests-cluster.sh
  scripts/minikube-minishift-all-tests.sh
  scripts/minikube-minishift-setup-env.sh
  tests/examples/operators/redis.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-link.yaml
  tests/helper/helper_cli.go
  tests/helper/helper_filesystem.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/operatorhub/cmd_link_test.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, area/testing, kind/failing-test, kind/feature, lgtm

#4880 Bumping version of odo for release
  Changelog.md
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#4858 Renames the service name to include the app name
  pkg/component/pushed_component.go
  pkg/debug/portforward.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/kclient/errors.go
  pkg/kclient/fake/ingress.go
  pkg/kclient/pods.go
  pkg/kclient/services.go
  pkg/kclient/services_test.go
  pkg/odo/cli/component/common_link.go
  pkg/odo/cli/component/devfile.go
  pkg/storage/kubernetes.go
  pkg/storage/kubernetes_test.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  pkg/testingutil/pods.go
  pkg/testingutil/services.go
  pkg/url/kubernetes.go
  pkg/url/kubernetes_test.go
  pkg/url/url.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/integration/devfile/cmd_devfile_app_test.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/bug, kind/design, lgtm

#4882 Fixing now implementation for config set and unset in devfile
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/config/set.go
  pkg/odo/cli/config/unset.go
  pkg/odo/genericclioptions/context.go
  tests/integration/cmd_pref_config_test.go
Labels: approved, kind/bug, lgtm

#4887 delete dangling dir created by unit-tests
  pkg/testingutil/configs.go
Labels: approved, lgtm

#4873 Tests/fix for test on ibmc
  tests/integration/cmd_push_test.go
  tests/integration/component.go
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, kind/failing-test, lgtm

#4869 Limits memory requests to deploy more components
  tests/examples/source/devfiles/nodejs/devfile-with-link.yaml
  tests/integration/operatorhub/cmd_link_test.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/flake, lgtm

#4902 Migrating URL unit tests to use networking v1 ingress
  pkg/kclient/fake/ingress.go
  pkg/url/kubernetes_test.go
  pkg/url/status_test.go
  pkg/url/types.go
  pkg/url/url.go
  pkg/url/url_test.go
Labels: approved, kind/task, lgtm

#4912 Updating dependencies to address dependabot alerts
  README.adoc
  website/README.md
  website/package-lock.json
  website/package.json
  website/src/pages/markdown-page.md
  website/yarn.lock
Labels: approved, kind/cleanup, lgtm

#4904 Update component create and delete help examples
  Changelog.md
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/delete.go
Labels: approved, kind/bug, kind/documentation, lgtm

#4888 Enabling override of required golang in rpm
  rpms/openshift-odo.spec
Labels: approved, lgtm

#4914 Add Getting Started > Basics documentation
  website/docs/getting-started/basics.md
  website/docs/getting-started/installation.md
Labels: approved, kind/documentation, lgtm

#4900 Add Sonar Cloud config file: sonar-project.properties
  sonar-project.properties
Labels: approved, kind/feature, lgtm

#4926 Removes Girish from OWNERS files
  OWNERS
  docs/OWNERS
  pkg/debug/OWNERS
  pkg/devfile/OWNERS
Labels: approved, lgtm

#4919 Do not display "Waiting for component to start" twice
  Changelog.md
  pkg/kclient/pods.go
Labels: approved, kind/bug, lgtm

#4909 preStart events support
  Changelog.md
  go.mod
  go.sum
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/storage/utils.go
  pkg/devfile/adapters/kubernetes/storage/utils_test.go
  pkg/devfile/validate/commands.go
  pkg/devfile/validate/events.go
  pkg/devfile/validate/events_test.go
  pkg/devfile/validate/validate.go
  vendor/github.com/devfile/library/pkg/devfile/generator/generators.go
  vendor/github.com/devfile/library/pkg/devfile/generator/utils.go
  vendor/github.com/devfile/library/pkg/devfile/parser/context/content.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/interface.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/mock_interface.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/2.2.0/devfileJsonSchema220.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/versions.go
  vendor/github.com/devfile/library/pkg/devfile/parser/writer.go
  vendor/github.com/devfile/library/pkg/util/util.go
  vendor/modules.txt
Labels: approved, kind/feature, lgtm

#4935 Modifies the error message to list the available starters
  pkg/component/starter_project.go
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, kind/bug, lgtm

#4915 Refactor devfile catalog and config integration tests
  tests/integration/devfile/cmd_devfile_catalog_test.go
  tests/integration/devfile/cmd_devfile_config_test.go
Labels: approved, kind/code-refactoring, lgtm

#4911 Add language and projectType metadata in devfile for s2i components
  pkg/devfile/convert/convert.go
  tests/integration/component.go
Labels: approved, kind/bug, lgtm

#4921 Add documentation for global configuration
  pkg/preference/preference.go
  website/docs/getting-started/configure.md
Labels: approved, kind/documentation, lgtm

#4923 Add odo installation docs
  website/docs/getting-started/installation.md
Labels: approved, kind/documentation, lgtm
