Repository redhat-developer/odo, pull requests merged in 2021-03, with the labels that each got.

#4329 Ci reference test docs
  docs/dev/ci-reference.adoc
Labels: approved, kind/documentation, lgtm

#4464 Bumping odo version v2.0.5 -> v2.0.6
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#4484 Change API & Operator version for Serice Binding Operator
  go.sum
  pkg/kclient/operators.go
  pkg/odo/cli/component/common_link.go
  scripts/configure-cluster/common/setup-operators.sh
Labels: approved, kind/failing-test, lgtm

#4478 Preserve permissions when extracting zip files
  pkg/util/util.go
Labels: approved, kind/bug, lgtm

#4487 Fix install URL link
  scripts/changelog-script.sh
Labels: approved, kind/documentation, lgtm, ok-to-test

#4489 Bumping version to v2.0.7
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#4456 Add telemetry consent to preference
  pkg/odo/cli/preference/set.go
  pkg/odo/cli/preference/unset.go
  pkg/odo/cli/preference/view.go
  pkg/preference/machine_output.go
  pkg/preference/preference.go
  pkg/preference/preference_test.go
  tests/integration/cmd_pref_config_test.go
Labels: approved, lgtm

#4466 Refactoring convert code so it can be used outside utils package
  pkg/devfile/convert/convert.go
  pkg/odo/cli/utils/convert.go
Labels: approved, kind/code-refactoring, lgtm

#4495 fixed odo create allowed to run multiple times in same dir
  pkg/odo/cli/component/create.go
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, kind/bug, lgtm

#4496 resolve project not being set in offline context creation
  pkg/odo/genericclioptions/context.go
Labels: approved, kind/bug, lgtm

#4472 odo create -o json for devfile also work towards making odo describe work without cluster connection
  pkg/component/component_full_description.go
  pkg/odo/cli/application/delete.go
  pkg/odo/cli/application/describe.go
  pkg/odo/cli/application/list.go
  pkg/odo/cli/catalog/describe/component.go
  pkg/odo/cli/catalog/describe/service.go
  pkg/odo/cli/catalog/list/components.go
  pkg/odo/cli/catalog/list/services.go
  pkg/odo/cli/catalog/search/component.go
  pkg/odo/cli/catalog/search/service.go
  pkg/odo/cli/component/common_link.go
  pkg/odo/cli/component/component.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/exec.go
  pkg/odo/cli/component/get.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/component/log.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/component/status.go
  pkg/odo/cli/component/test.go
  pkg/odo/cli/component/update.go
  pkg/odo/cli/component/watch.go
  pkg/odo/cli/config/set.go
  pkg/odo/cli/config/unset.go
  pkg/odo/cli/debug/info.go
  pkg/odo/cli/debug/portforward.go
  pkg/odo/cli/logout/logout.go
  pkg/odo/cli/project/create.go
  pkg/odo/cli/project/delete.go
  pkg/odo/cli/project/get.go
  pkg/odo/cli/project/list.go
  pkg/odo/cli/project/set.go
  pkg/odo/cli/service/create.go
  pkg/odo/cli/service/delete.go
  pkg/odo/cli/service/list.go
  pkg/odo/cli/storage/mount.go
  pkg/odo/cli/storage/unmount.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/utils/convert.go
  pkg/odo/genericclioptions/client.go
  pkg/odo/genericclioptions/context.go
  pkg/storage/kubernetes.go
  pkg/url/kubernetes.go
  tests/helper/helper_cmd_wrapper.go
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, lgtm

#4486 Java+DB docs [skip ci]
  docs/public/deploying-java-app-with-database.adoc
  docs/public/installing-and-onfiguring-minikube-environment.adoc
Labels: approved, kind/documentation, lgtm

#4406 Scripts for PSI minishift tests
  scripts/minici-presubmit-all-tests.sh
  scripts/minikube-minishift-all-tests.sh
  scripts/minikube-minishift-setup-env.sh
  scripts/minishift-start-if-required.sh
Labels: approved, kind/feature, lgtm

#4511 Updating build/VERSION to latest released version
  build/VERSION
Labels: approved, lgtm

#4407 Adds storage Push() for devfile components.
  pkg/component/component.go
  pkg/devfile/adapters/common/interface.go
  pkg/devfile/adapters/docker/component/utils.go
  pkg/devfile/adapters/docker/storage/adapter.go
  pkg/devfile/adapters/docker/storage/adapter_test.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/storage/adapter.go
  pkg/devfile/adapters/kubernetes/storage/utils.go
  pkg/devfile/adapters/kubernetes/storage/utils_test.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils_test.go
  pkg/kclient/volumes.go
  pkg/kclient/volumes_test.go
  pkg/occlient/occlient.go
  pkg/occlient/volumes.go
  pkg/occlient/volumes_test.go
  pkg/storage/kubernetes.go
  pkg/storage/kubernetes_test.go
  pkg/storage/mock_Client.go
  pkg/storage/s2i.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
Labels: approved, lgtm

#4512 Replaces generic validation package with validation from devfile library and api.
  pkg/devfile/adapters/common/command.go
  pkg/devfile/adapters/common/command_test.go
  pkg/devfile/validate/generic/commands.go
  pkg/devfile/validate/generic/commands_test.go
  pkg/devfile/validate/generic/components.go
  pkg/devfile/validate/generic/components_test.go
  pkg/devfile/validate/generic/errors.go
  pkg/devfile/validate/generic/events.go
  pkg/devfile/validate/generic/events_test.go
  pkg/devfile/validate/generic/validate.go
  pkg/devfile/validate/validate.go
Labels: approved, kind/code-refactoring, lgtm

#4513 Add docs for java+database example
  chosen-docs/upstream/deploying-java-app-with-database.md
  chosen-docs/upstream/install-service-binding-operator.md
  chosen-docs/upstream/installing-and-onfiguring-minikube-environment.md
  docs/deploying-java-app-with-database.md
  docs/install-service-binding-operator.md
  docs/installing-and-onfiguring-minikube-environment.md
  docs/odo-cli-reference.md
  index.md
Labels: approved, kind/documentation, lgtm

#4508 Fixes odo create when cluster access is limited
  pkg/component/component_full_description.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/describe.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/component/watch.go
  pkg/odo/cli/url/create.go
  pkg/odo/genericclioptions/client.go
  pkg/odo/genericclioptions/context.go
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, kind/bug, lgtm

#4506 fix json in describe component
  pkg/odo/cli/catalog/describe/component.go
  tests/integration/devfile/cmd_devfile_catalog_test.go
Labels: approved, kind/bug, lgtm

#4516 Adding file permission to run minikube job
  scripts/minici-presubmit-all-tests.sh
  scripts/minikube-minishift-all-tests.sh
  scripts/minikube-minishift-setup-env.sh
  scripts/minishift-start-if-required.sh
Labels: approved, kind/failing-test, lgtm

#4521 Removal of docker tests and related helper code
  Makefile
  tests/helper/helper_cli.go
  tests/helper/helper_docker.go
  tests/integration/devfile/docker/cmd_docker_devfile_catalog_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_delete_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_exec_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_push_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_status_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_test_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_url_pushtarget_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_url_test.go
  tests/integration/devfile/docker/cmd_docker_devfile_watch_test.go
  tests/integration/devfile/docker/docker_suite_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, kind/code-refactoring, lgtm

#4524 Removes occurrence of docker from utils.go
  tests/integration/devfile/utils/utils.go
Labels: approved, kind/cleanup, lgtm

#4501 describe works offline without need for connection to a cluster
  pkg/odo/cli/component/component.go
  pkg/odo/cli/component/describe.go
  tests/integration/devfile/cmd_devfile_describe_test.go
Labels: approved, kind/bug, lgtm

#4519 use default component name if user doesn't provide one in devfile mode
  pkg/odo/cli/component/create.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/feature, lgtm

#4526 Add test-integration-devfile tests for ppc64le
  scripts/openshiftci-presubmit-all-tests.sh
Labels: approved, lgtm, ok-to-test

#4514 Add test-integration-devfile tests for s390x
  scripts/openshiftci-presubmit-all-tests.sh
Labels: approved, area/System-PZ, lgtm, ok-to-test

#4509 Changes to prefix projectNames with test_file_name and line number
  tests/helper/helper_generic.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/helper/odo_utils.go
  tests/integration/devfile/cmd_devfile_debug_test.go
Labels: approved, lgtm

#4530 Passing minikube and minishift parameter using env
  scripts/minici-presubmit-all-tests.sh
  scripts/minikube-minishift-all-tests.sh
  scripts/minikube-minishift-setup-env.sh
Labels: approved, kind/bug, lgtm

#4528 show in all project commands help that a push is not required
  pkg/odo/cli/project/create.go
  pkg/odo/cli/project/delete.go
  pkg/odo/cli/project/set.go
Labels: approved, kind/feature, lgtm

#4541 Make preference commands errors pretty and fix typos with test
  pkg/preference/preference.go
  pkg/preference/preference_test.go
Labels: approved, kind/cleanup, lgtm

#4546 add rnapoles-rh as a reviewer
  OWNERS
Labels: approved, lgtm

#4497 Adds a check to error out if the run command didn't start properly.
  pkg/devfile/adapters/common/interface.go
  pkg/devfile/adapters/docker/adapter.go
  pkg/devfile/adapters/docker/component/adapter.go
  pkg/devfile/adapters/kubernetes/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/occlient/deploymentConfigs.go
  pkg/odo/cli/component/devfile.go
  pkg/util/util.go
  tests/integration/devfile/cmd_devfile_debug_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, kind/bug, lgtm

#4551 Fixing golang image pull error
  openshift-ci/build-root/Dockerfile
Labels: approved, kind/failing-test, lgtm

#4552 Fixing argument issue on minikube and minishift psi tests
  scripts/minici-presubmit-all-tests.sh
  scripts/minikube-minishift-all-tests.sh
  scripts/minikube-minishift-setup-env.sh
Labels: approved, lgtm

#4558 Bumping odo version v2.0.7 -> v2.0.8
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#4554 Get SB secret name from SB
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/kclient/deployments.go
  pkg/odo/cli/component/common_link.go
Labels: approved, kind/bug, lgtm

#4569 Fixing latest image import issue for java 8
  tests/e2escenarios/e2e_images_test.go
  tests/helper/helper_oc.go
Labels: approved, kind/failing-test, lgtm
