Repository redhat-developer/odo, pull requests merged in 2021-09, with the labels that each got.

#5028 Replace "nightly" tag with "next" in some integration tests devfiles
  tests/e2escenarios/e2e_devfile_test.go
  tests/examples/source/devfiles/nodejs/devfile-with-invalid-events.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-invalid-volmount.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-preStart.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-valid-events.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-volume-components.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-volumes.yaml
  tests/examples/source/devfiles/nodejs/devfile-without-devinit.yaml
  tests/examples/source/devfiles/nodejs/devfileSourceMapping.yaml
  tests/examples/source/devfiles/springboot/devfile-with-metadataname-foobar.yaml
  tests/examples/source/devfiles/springboot/devfile-with-subDir.yaml
  tests/examples/source/devfiles/springboot/devfile.yaml
  tests/helper/helper_generic.go
  tests/integration/devfile/cmd_devfile_app_test.go
  tests/integration/devfile/cmd_devfile_catalog_test.go
  tests/integration/devfile/cmd_devfile_config_test.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/cmd_devfile_debug_test.go
  tests/integration/devfile/cmd_devfile_delete_test.go
  tests/integration/devfile/cmd_devfile_describe_test.go
  tests/integration/devfile/cmd_devfile_env_test.go
  tests/integration/devfile/cmd_devfile_exec_test.go
  tests/integration/devfile/cmd_devfile_list_test.go
  tests/integration/devfile/cmd_devfile_log_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/cmd_devfile_registry_test.go
  tests/integration/devfile/cmd_devfile_status_test.go
  tests/integration/devfile/cmd_devfile_storage_test.go
  tests/integration/devfile/cmd_devfile_test_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
  tests/integration/devfile/cmd_devfile_watch_test.go
  tests/integration/devfile/debug/debug_suite_test.go
  tests/integration/devfile/devfile_suite_test.go
Labels: kind/bug, approved, lgtm

#4975 Updating config cmds and tests for logged out senario
  Changelog.md
  pkg/odo/cli/catalog/list/components.go
  pkg/odo/cli/config/set.go
  pkg/odo/cli/config/unset.go
  pkg/odo/genericclioptions/context.go
  pkg/util/util.go
  tests/helper/helper_oc.go
  tests/integration/cmd_pref_config_test.go
Labels: kind/bug, approved, lgtm

#4948 Refactor machine output code
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/types.go
  pkg/debug/info.go
  pkg/debug/info_test.go
  pkg/envinfo/envinfo.go
  pkg/envinfo/types.go
  pkg/machineoutput/types.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/debug/info.go
  pkg/odo/cli/env/view.go
  pkg/odo/cli/project/create.go
  pkg/odo/cli/project/delete.go
  pkg/odo/cli/project/get.go
  pkg/odo/cli/project/list.go
  pkg/odo/cli/storage/create.go
  pkg/odo/cli/storage/delete.go
  pkg/odo/cli/storage/list_test.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/list.go
  pkg/odo/util/cmdutils.go
  pkg/project/project.go
  pkg/project/project_test.go
  pkg/project/types.go
  pkg/storage/kubernetes.go
  pkg/storage/kubernetes_test.go
  pkg/storage/s2i.go
  pkg/storage/s2i_test.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  pkg/storage/types.go
  pkg/url/kubernetes.go
  pkg/url/kubernetes_test.go
  pkg/url/s2i.go
  pkg/url/types.go
  pkg/url/url.go
  pkg/url/url_test.go
  tests/helper/helper_generic.go
  tests/integration/cmd_storage_test.go
  tests/integration/cmd_url_test.go
  tests/integration/devfile/cmd_devfile_debug_test.go
  tests/integration/devfile/cmd_devfile_env_test.go
  tests/integration/devfile/cmd_devfile_list_test.go
  tests/integration/devfile/cmd_devfile_storage_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
  tests/integration/generic_test.go
  tests/integration/project/cmd_project_test.go
  website/docs/command-reference/json-output.md
Labels: approved, lgtm, kind/feature

#5026 Display default project value while creating a component interactively
  pkg/odo/cli/component/create.go
Labels: approved, lgtm

#5025 List all services in JSON output
  pkg/odo/cli/service/list_operator.go
  pkg/odo/cli/service/list_operator_test.go
  pkg/service/service.go
  pkg/service/service_test.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: kind/bug, approved, lgtm

#4985 Cleanup namespaces
  scripts/clean-old-namespace-from-cluster.sh
  tests/e2escenarios/e2e_images_test.go
  tests/e2escenarios/e2e_java_test.go
  tests/e2escenarios/e2e_source_test.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
Labels: approved, lgtm, kind/cleanup

#5021 Removes code related to s2i storage
  pkg/component/component.go
  pkg/component/pushed_component.go
  pkg/odo/cli/component/component.go
  pkg/odo/cli/storage/list.go
  pkg/odo/cli/storage/mount.go
  pkg/odo/cli/storage/storage.go
  pkg/odo/cli/storage/storage_test.go
  pkg/odo/cli/storage/unmount.go
  pkg/odo/util/completion/completionhandlers.go
  pkg/storage/kubernetes.go
  pkg/storage/s2i.go
  pkg/storage/s2i_test.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  pkg/storage/types_test.go
  pkg/storage/utils.go
  pkg/storage/utils_test.go
Labels: approved, lgtm, kind/cleanup

#5035 Increasing timeout from 1min to 5min for PodsShuouldBeRunning
  tests/helper/helper_oc.go
Labels: area/testing, approved, lgtm, kind/failing-test

#4946 add PSI and IBM cloud to the script for test
  scripts/openshiftci-e2e-4x-psi-tests_win_mac.sh
  scripts/run_script_e2e.sh
  scripts/setup_script_e2e.sh
Labels: approved, lgtm

#5040 Send Identify event with every Track event
  pkg/segment/segment.go
Labels: kind/bug, approved, lgtm

#5032 Fix clusterwide permission issues with odo link and run K8s tests with a developer user
  pkg/service/link.go
  pkg/service/service_binding_builder.go
  scripts/minikube-minishift-setup-env.sh
Labels: kind/bug, approved, lgtm

#5046 release v2.3.1
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#5047 fix Filepath to use / for odo describe --context /path for windows
  pkg/component/component_full_description.go
Labels: kind/bug, approved, lgtm

#5022 Modifies and adds scripts to run K8S tests on IBM Cloud cluster
  Makefile
  scripts/k8sibmc-all-tests.sh
  scripts/k8sibmc-setup-env.sh
  scripts/minici-presubmit-all-tests.sh
Labels: approved, lgtm, kind/tests

#5048 add logic to run github_changelog_generator in container
  scripts/changelog-script.sh
Labels: approved, lgtm, kind/cleanup

#5039 odo service create/describe -o json
  pkg/odo/cli/service/create.go
  pkg/odo/cli/service/delete.go
  pkg/odo/cli/service/describe.go
  pkg/odo/cli/service/interface.go
  pkg/odo/cli/service/list_operator.go
  pkg/odo/cli/service/list_operator_test.go
  pkg/odo/cli/service/operator_backend.go
  pkg/odo/cli/service/service.go
  pkg/odo/cli/service/utils.go
  tests/integration/operatorhub/cmd_service_test.go
  website/docs/command-reference/json-output.md
Labels: approved, lgtm, kind/feature

#5038 Debug test file cleanup left over
  tests/integration/devfile/cmd_devfile_debug_test.go
Labels: approved, lgtm, kind/tests

#4918 Mount persistent volumes for S2I images
  pkg/devfile/convert/convert.go
  pkg/storage/kubernetes.go
  pkg/storage/kubernetes_test.go
  pkg/storage/storage.go
  pkg/testingutil/deployments.go
  tests/integration/cmd_create_s2i_test.go
  tests/integration/cmd_storage_test.go
Labels: kind/bug, approved, lgtm

#5033 Removing remaining service catalog references
  pkg/application/application.go
  pkg/catalog/catalog.go
  pkg/kclient/serviceCatalog.go
  pkg/kclient/serviceCatalog_test.go
  pkg/odo/cli/application/describe.go
  pkg/odo/cli/catalog/search/service.go
  pkg/odo/cli/catalog/util/util.go
  pkg/odo/cli/component/common_link.go
  pkg/odo/cli/component/link.go
  pkg/service/service.go
  pkg/service/types.go
  tests/integration/cmd_link_unlink_test.go
Labels: approved, lgtm, kind/cleanup

#5058 repeated check for deleted dir in odo watch test
  tests/integration/devfile/utils/utils.go
Labels: approved, lgtm, kind/flake

#5068 update timeout to 8mins
  scripts/clean-old-namespace-from-cluster.sh
  scripts/openshiftci-e2e-4x-psi-tests_win_mac.sh
  tests/helper/helper_oc.go
Labels: approved, lgtm, kind/flake

#5057 Set odo to use staging registry in `CommonBeforeEach`
  tests/e2escenarios/e2e_devfile_test.go
  tests/helper/helper_generic.go
  tests/integration/devfile/cmd_devfile_app_test.go
  tests/integration/devfile/cmd_devfile_catalog_test.go
  tests/integration/devfile/cmd_devfile_config_test.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/cmd_devfile_debug_test.go
  tests/integration/devfile/cmd_devfile_delete_test.go
  tests/integration/devfile/cmd_devfile_describe_test.go
  tests/integration/devfile/cmd_devfile_env_test.go
  tests/integration/devfile/cmd_devfile_exec_test.go
  tests/integration/devfile/cmd_devfile_list_test.go
  tests/integration/devfile/cmd_devfile_log_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/cmd_devfile_registry_test.go
  tests/integration/devfile/cmd_devfile_status_test.go
  tests/integration/devfile/cmd_devfile_storage_test.go
  tests/integration/devfile/cmd_devfile_test_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
  tests/integration/devfile/cmd_devfile_watch_test.go
  tests/integration/devfile/debug/debug_suite_test.go
Labels: approved, lgtm, kind/tests

#5069 resolve CI job script error
  scripts/openshiftci-e2e-4x-psi-tests_win_mac.sh
  scripts/run_script_e2e.sh
Labels: approved, lgtm

#5076 cleanup website node packages
  website/package-lock.json
  website/package.json
  website/yarn.lock
Labels: approved, lgtm, kind/documentation

#5031 Modifies the usage of service create, link and unlink by using separate files for Kubernetes resources
  docs/public/operator-hub.adoc
  pkg/component/component_full_description.go
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/common/utils_test.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/odo/cli/component/common_link.go
  pkg/odo/cli/component/create_helpers.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/describe.go
  pkg/odo/cli/component/link.go
  pkg/odo/cli/service/create.go
  pkg/odo/cli/service/list_operator.go
  pkg/odo/cli/service/operator_backend.go
  pkg/service/link.go
  pkg/service/service.go
  pkg/service/service_test.go
  tests/integration/operatorhub/cmd_link_test.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, lgtm, kind/feature

#5077 fixed JOB_NAME
  scripts/minici-presubmit-all-tests.sh
Labels: approved, lgtm

#5062 Delete devfile when creation fails
  pkg/odo/cli/component/create.go
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: kind/bug, approved, lgtm

#5070 Removing unused flags in link command
  pkg/odo/cli/component/common_link.go
  pkg/odo/cli/component/link.go
  pkg/odo/cli/component/unlink.go
Labels: approved, lgtm, kind/cleanup

#5023 Removes the s2i flag from the create file
  Makefile
  docs/dev/test-architecture.adoc
  pkg/odo/cli/cli.go
  pkg/odo/cli/component/common_push.go
  pkg/odo/cli/component/component.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/create_helpers.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/exec.go
  pkg/odo/cli/component/interactive_create.go
  pkg/odo/cli/component/log.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/component/update.go
  pkg/odo/cli/component/watch.go
  pkg/odo/cli/utils/convert.go
  pkg/odo/genericclioptions/localprovider.go
  scripts/minikube-minishift-all-tests.sh
  tests/e2escenarios/e2e_images_test.go
  tests/e2escenarios/e2e_java_test.go
  tests/e2escenarios/e2e_source_test.go
  tests/integration/cmd_app_test.go
  tests/integration/cmd_cmp_sub_test.go
  tests/integration/cmd_cmp_test.go
  tests/integration/cmd_create_s2i_test.go
  tests/integration/cmd_debug_test.go
  tests/integration/cmd_pref_config_test.go
  tests/integration/cmd_push_test.go
  tests/integration/cmd_storage_test.go
  tests/integration/cmd_url_test.go
  tests/integration/cmd_watch_test.go
  tests/integration/component.go
  tests/integration/debug/cmd_debug_test.go
  tests/integration/debug/debug_suite_test.go
  tests/integration/devfile/cmd_devfile_app_test.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
  tests/integration/devfile/cmd_devfile_watch_test.go
  tests/integration/devfile/utils/utils.go
  tests/integration/generic_test.go
Labels: approved, lgtm, kind/cleanup

#5075 Update Readme.adoc
  README.adoc
Labels: approved, lgtm, kind/documentation

#5067 Add timezone information to Telemetry data
  pkg/segment/segment.go
Labels: approved, lgtm, kind/feature

#5016 Removes code related to s2i based URLs
  pkg/component/component_test.go
  pkg/component/pushed_component.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/odo/util/completion/completionhandlers.go
  pkg/url/kubernetes.go
  pkg/url/s2i.go
  pkg/url/status_test.go
  pkg/url/url.go
  pkg/url/url_test.go
  pkg/url/utils.go
  pkg/url/utils_test.go
Labels: approved, lgtm, kind/cleanup

#5065 Use interface for kclient
  pkg/application/application.go
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  pkg/component/component.go
  pkg/debug/portforward.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/storage/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils_test.go
  pkg/kclient/interface.go
  pkg/kclient/kclient.go
  pkg/kclient/mock_Client.go
  pkg/kclient/namespace.go
  pkg/localConfigProvider/mock_localConfigProvider.go
  pkg/odo/cli/application/application.go
  pkg/odo/cli/application/delete.go
  pkg/odo/cli/application/describe.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/exec.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/component/status.go
  pkg/odo/cli/component/watch.go
  pkg/odo/cli/service/list_operator.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/genericclioptions/fakecontext.go
  pkg/odo/genericclioptions/resolve.go
  pkg/service/link.go
  pkg/service/service.go
  pkg/storage/mock_Client.go
  pkg/url/mock_Client.go
  pkg/url/status.go
  scripts/mockgen.sh
Labels: approved, lgtm, kind/cleanup

#5081 Restart command when stopped on odo push
  pkg/devfile/adapters/common/interface.go
  pkg/devfile/adapters/kubernetes/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: kind/bug, approved, lgtm

#5103 Update DefaultDevfileRegistry link in IBM-Z and Power doc
  website/docs/tutorials/deploying-a-devfile-using-odo-on-IBM-Z-and-Power.md
Labels: approved, lgtm, needs-ok-to-test, kind/documentation, area/System-PZ
