Repository redhat-developer/odo, pull requests merged in 2021-01, with the labels that each got.

#4341 remove aditi from gh-pages
  OWNERS
Labels: approved, kind/cleanup, lgtm

#4339 Removes Aditi from the OWNERS files
  OWNERS
  pkg/devfile/OWNERS
Labels: approved, lgtm

#4348 Revert centos nodejs tags to older version
  tests/e2escenarios/e2e_images_test.go
Labels: approved, kind/failing-test, lgtm

#4345 Separates test into its own spec
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/failing-test, lgtm

#4333 sanitize dir name before using it on odo push
  go.mod
  go.sum
  pkg/url/url.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/integration/component.go
  vendor/github.com/gosimple/slug/.gitignore
  vendor/github.com/gosimple/slug/.travis.yml
  vendor/github.com/gosimple/slug/LICENSE
  vendor/github.com/gosimple/slug/README.md
  vendor/github.com/gosimple/slug/doc.go
  vendor/github.com/gosimple/slug/go.mod
  vendor/github.com/gosimple/slug/go.sum
  vendor/github.com/gosimple/slug/languages_substitution.go
  vendor/github.com/gosimple/slug/slug.go
  vendor/github.com/rainycape/unidecode/.gitignore
  vendor/github.com/rainycape/unidecode/LICENSE
  vendor/github.com/rainycape/unidecode/README.md
  vendor/github.com/rainycape/unidecode/decode.go
  vendor/github.com/rainycape/unidecode/make_table.go
  vendor/github.com/rainycape/unidecode/table.go
  vendor/github.com/rainycape/unidecode/table.txt
  vendor/github.com/rainycape/unidecode/unidecode.go
  vendor/modules.txt
Labels: approved, do-not-merge/hold, lgtm

#4336 Output service name when creating Operator backed service
  pkg/odo/cli/service/create.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/bug, lgtm

#4358 Fixes panic while collecting events from the pod.
  pkg/component/component.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/kclient/pods.go
  pkg/kclient/pods_test.go
  pkg/odo/cli/component/common_link.go
Labels: approved, kind/bug, lgtm

#4292 Configure-installer script refactor part 2
  scripts/configure-cluster/common/auth.sh
  scripts/configure-cluster/common/kubeconfigandadmin.sh
  scripts/configure-cluster/common/kubeconfigreset.sh
  scripts/configure-cluster/common/test-htpasswd
  scripts/configure-installer-tests-cluster-ppc64le.sh
  scripts/configure-installer-tests-cluster-s390x.sh
  scripts/configure-installer-tests-cluster.sh
Labels: approved, lgtm

#4359 Doc Typo
  docs/public/operator-hub.adoc
Labels: approved, lgtm, ok-to-test

#4353 set UserCreatedDevfile: true in envInfo and check on delete --all
  pkg/envinfo/envinfo.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/delete.go
  tests/integration/devfile/cmd_devfile_delete_test.go
Labels: approved, lgtm

#4349 Add centos7 nodejs latest as supported
  pkg/catalog/catalog.go
  pkg/devfile/adapters/common/utils.go
  tests/e2escenarios/e2e_images_test.go
Labels: approved, kind/failing-test, kind/feature, lgtm, release-blocker

#4360 Change default value for ephemral preference
  pkg/preference/preference.go
  tests/integration/devfile/cmd_devfile_storage_test.go
Labels: approved, lgtm, release-blocker

#4352 Bumping odo version from v2.0.3 to v2.0.4
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm, release-blocker

#4317 Some fix for configure script of s390x.
  scripts/configure-installer-tests-cluster-s390x.sh
Labels: approved, area/System-PZ, kind/failing-test, lgtm

#4338 Refactor catalog list services
  pkg/catalog/catalog.go
  pkg/odo/cli/catalog/list/services.go
  pkg/odo/cli/catalog/util/util.go
  tests/integration/operatorhub/cmd_service_test.go
Labels: approved, kind/code-refactoring, lgtm

#4380 removing information on mandate to clone go in GOPATH
  docs/dev/development.adoc
Labels: approved, lgtm

#4384 Fixes test for checking no starter project found
  tests/examples/source/devfiles/nodejs/devfile-with-no-starterProject.yaml
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, kind/failing-test, lgtm

#4378 Fix configure script run locally
  scripts/configure-cluster/common/kubeconfigandadmin.sh
Labels: approved, kind/failing-test, lgtm

#4377 Fixes catalog list services for minishift
  pkg/catalog/catalog.go
  pkg/odo/cli/catalog/list/services.go
Labels: approved, kind/bug, lgtm

#4391 Export tags and language for Devfile components
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  pkg/catalog/types.go
Labels: approved, kind/feature, lgtm

#4344 Refactors storage code for localConfigProvider.
  pkg/component/component.go
  pkg/component/component_full_description.go
  pkg/component/component_test.go
  pkg/config/config.go
  pkg/config/fakeConfig.go
  pkg/config/storage.go
  pkg/config/storage_test.go
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/common/utils_test.go
  pkg/envinfo/storage.go
  pkg/envinfo/storage_test.go
  pkg/localConfigProvider/localConfigProvider.go
  pkg/localConfigProvider/mock_localConfigProvider.go
  pkg/odo/cli/storage/create.go
  pkg/odo/cli/storage/delete.go
  pkg/odo/cli/utils/convert.go
  pkg/odo/util/cmdutils.go
  pkg/odo/util/completion/completionhandlers.go
  pkg/storage/storage.go
  tests/integration/devfile/cmd_devfile_storage_test.go
Labels: approved, lgtm

#4390 Remove the unused step in configure-installer-tests-cluster-s390x.sh.
  scripts/configure-installer-tests-cluster-s390x.sh
Labels: approved, lgtm

#4369 refactor: extracted starter project code from create options
  pkg/component/starter_project.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/create_helpers.go
Labels: approved, kind/code-refactoring, lgtm

#4388 Keeping the current active project/namespace when re-logging in
  pkg/auth/login.go
Labels: approved, kind/bug, lgtm, ok-to-test

#4304 Adding ubi8/nodejs-14 image as supported
  pkg/catalog/catalog.go
  pkg/devfile/adapters/common/utils.go
  scripts/configure-installer-tests-cluster.sh
  tests/e2escenarios/e2e_images_test.go
Labels: approved, kind/failing-test, kind/feature, lgtm
