Repository redhat-developer/odo, pull requests merged in 2022-05, with the labels that each got.

#5703 odo dev store information about currently forwarded ports
  .ibm/images/Dockerfile
  docs/website/versioned_docs/version-3.0.0/command-reference/dev.md
  pkg/api/component.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/dev/writer.go
  pkg/odo/cli/dev/writer_test.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/state/const.go
  pkg/state/doc.go
  pkg/state/interface.go
  pkg/state/state.go
  pkg/state/state_test.go
  pkg/state/types.go
  pkg/watch/watch.go
  tests/helper/helper_generic.go
  tests/integration/devfile/cmd_alizer_test.go
  tests/integration/devfile/cmd_dev_test.go
  tests/integration/devfile/cmd_devfile_init_test.go
Labels: approved, lgtm, kind/feature

#5710 Blog post for v3-alpha1
  docs/website/blog/2022-05-02-odo-v3-alpha1.md
Labels: approved, lgtm, kind/documentation

#5711 Fix issue with variables not substituted in `uri`-referenced manifests (#5451)
  pkg/deploy/deploy.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/libdevfile/command_apply.go
  pkg/libdevfile/component_kubernetes_utils.go
  pkg/libdevfile/errors.go
  pkg/libdevfile/libdevfile.go
  pkg/libdevfile/libdevfile_test.go
  pkg/service/link.go
  pkg/service/service.go
  tests/examples/source/devfiles/nodejs/devfile-deploy-with-k8s-uri.yaml
  tests/examples/source/devfiles/nodejs/project/kubernetes/outerloop-deployment.yaml
  tests/integration/devfile/cmd_devfile_deploy_test.go
Labels: kind/bug, approved, lgtm

#5714 update image path, fix test
  tests/examples/source/devfiles/nodejs/devfile-with-pod.yaml
Labels: approved, lgtm, v2, kind/tests

#5708 Removing support for github based registries
  pkg/init/backend/flags.go
  pkg/odo/cli/preference/registry/add.go
  pkg/odo/cli/preference/registry/list.go
  pkg/odo/cli/preference/registry/update.go
  pkg/odo/cli/preference/registry/util/util.go
  pkg/odo/cli/preference/registry/util/util_test.go
  pkg/registry/registry.go
  pkg/registry/registry_test.go
  tests/integration/devfile/cmd_devfile_registry_test.go
Labels: approved, lgtm, kind/task

#5721 Fix issue preventing URI-referenced Kubernetes components from being gathered for deletion
  pkg/component/delete/delete.go
  pkg/component/delete/delete_test.go
  tests/examples/source/devfiles/nodejs/devfile-deploy-with-k8s-uri.yaml
  tests/examples/source/devfiles/nodejs/devfile-deploy-with-multiple-resources-and-k8s-uri.yaml
  tests/examples/source/devfiles/nodejs/kubernetes/devfile-deploy-with-k8s-uri/outerloop-deployment.yaml
  tests/examples/source/devfiles/nodejs/kubernetes/devfile-deploy-with-multiple-resources-and-k8s-uri/outerloop-deploy-2.yaml
  tests/examples/source/devfiles/nodejs/kubernetes/devfile-deploy-with-multiple-resources-and-k8s-uri/outerloop-deploy.yaml
  tests/integration/devfile/cmd_delete_test.go
  tests/integration/devfile/cmd_devfile_deploy_test.go
Labels: kind/bug, approved, lgtm

#5720 odo describe component -o json
  docs/website/versioned_docs/version-3.0.0/command-reference/describe.md
  docs/website/versioned_docs/version-3.0.0/command-reference/json-output.md
  pkg/api/component.go
  pkg/api/error.go
  pkg/api/utils.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/errors.go
  pkg/component/types.go
  pkg/machineoutput/types.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/describe/component.go
  pkg/odo/cli/describe/describe.go
  pkg/odo/cli/init/init.go
  pkg/odo/util/cmdutils.go
  pkg/state/interface.go
  pkg/state/state.go
  pkg/state/state_test.go
  tests/integration/devfile/cmd_describe_test.go
Labels: approved, lgtm, kind/feature

#5717 Fix error when opening file in windows OS
  tests/helper/helper_generic.go
Labels: approved, lgtm, kind/tests

#5667 Adds odo registry command
  pkg/alizer/alizer.go
  pkg/alizer/alizer_test.go
  pkg/init/backend/interactive.go
  pkg/init/backend/interactive_test.go
  pkg/log/status.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/registry/registry.go
  pkg/registry/interface.go
  pkg/registry/mock.go
  pkg/registry/registry.go
  pkg/registry/registry_test.go
  pkg/registry/types.go
  tests/integration/devfile/cmd_devfile_registry_test.go
Labels: approved, lgtm, kind/feature

#5735 Remove old docs
  docs/website/versioned_docs/version-3.0.0/using-odo/_category_.json
  docs/website/versioned_docs/version-3.0.0/using-odo/create-component.md
Labels: approved, lgtm, kind/documentation

#5736 Update the site configuration to expand sidebars
  docs/website/.gitignore
  docs/website/docusaurus.config.js
Labels: approved, lgtm, kind/documentation

#5725 odo describe component
  docs/website/versioned_docs/version-3.0.0/command-reference/describe.md
  pkg/api/component.go
  pkg/api/devfile-data.go
  pkg/api/utils.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/log/status.go
  pkg/odo/cli/describe/component.go
  pkg/registry/registry.go
  tests/integration/devfile/cmd_describe_test.go
Labels: approved, lgtm, kind/feature

#5734 Small update to cluster setup docs
  docs/website/versioned_docs/version-3.0.0/getting-started/cluster-setup/kubernetes.md
  docs/website/versioned_docs/version-3.0.0/getting-started/cluster-setup/openshift.md
Labels: approved, lgtm, kind/documentation

#5737 Rename alizer command to analyze
  docs/website/versioned_docs/version-3.0.0/command-reference/json-output.md
  pkg/odo/cli/alizer/alizer.go
  tests/integration/devfile/cmd_analyze_test.go
Labels: approved, lgtm, kind/feature

#5641 Create binding between devfile component and existing service
  pkg/binding/asker/interface.go
  pkg/binding/asker/survey_asker.go
  pkg/binding/backend/flags.go
  pkg/binding/backend/interactive.go
  pkg/binding/backend/interface.go
  pkg/binding/backend/mock.go
  pkg/binding/binding.go
  pkg/binding/interface.go
  pkg/binding/mock.go
  pkg/kclient/binding.go
  pkg/kclient/interface.go
  pkg/kclient/kclient.go
  pkg/kclient/mock_Client.go
  pkg/kclient/operators.go
  pkg/kclient/utils.go
  pkg/libdevfile/component_kubernetes_utils.go
  pkg/odo/cli/add/add.go
  pkg/odo/cli/add/binding/binding.go
  pkg/odo/cli/cli.go
  pkg/odo/genericclioptions/clientset/clientset.go
  scripts/ansible/kubernetes-cluster/operators.yml
  scripts/configure-cluster/common/setup-operators.sh
  scripts/mockgen.sh
  tests/examples/manifests/bindablekind-instance.yaml
  tests/helper/helper_cli.go
  tests/helper/helper_dev.go
  tests/helper/helper_filesystem.go
  tests/helper/helper_generic.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/helper/odo_utils.go
  tests/integration/devfile/cmd_add_binding_test.go
Labels: approved, lgtm, kind/feature

#5724 odo create namespace
  docs/website/versioned_docs/version-3.0.0/command-reference/create-namespace.md
  pkg/odo/cli/cli.go
  pkg/odo/cli/create/create.go
  pkg/odo/cli/create/namespace/namespace.go
  tests/helper/helper_cli.go
  tests/helper/helper_generic.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/cmd_namespace_test.go
Labels: approved, lgtm, kind/feature

#5730 odo add binding documentation
  docs/website/versioned_docs/version-3.0.0/command-reference/add-binding.md
Labels: approved, lgtm, kind/documentation

#5731 odo list -o json
  docs/website/versioned_docs/version-3.0.0/command-reference/json-output.md
  docs/website/versioned_docs/version-3.0.0/command-reference/list.md
  pkg/api/component-abstract.go
  pkg/api/component.go
  pkg/api/list.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/pushed_component.go
  pkg/component/types.go
  pkg/odo/cli/list/list.go
  tests/integration/devfile/cmd_devfile_list_test.go
Labels: approved, lgtm, kind/feature

#5743 Implement `odo delete namespace/project`
  docs/website/versioned_docs/version-3.0.0/command-reference/delete-component.md
  docs/website/versioned_docs/version-3.0.0/command-reference/delete-namespace.md
  pkg/odo/cli/delete/component/component.go
  pkg/odo/cli/delete/component/component_test.go
  pkg/odo/cli/delete/delete.go
  pkg/odo/cli/delete/namespace/namespace.go
  tests/helper/helper_cli.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/cmd_namespace_test.go
Labels: approved, lgtm, kind/feature

#5740 Minor update to odo dev reference
  docs/website/versioned_docs/version-3.0.0/command-reference/dev.md
Labels: approved, lgtm, kind/documentation

#5739 odo registry -o json
  docs/website/versioned_docs/version-3.0.0/command-reference/json-output.md
  docs/website/versioned_docs/version-3.0.0/command-reference/registry.md
  pkg/alizer/alizer.go
  pkg/alizer/alizer_test.go
  pkg/alizer/interface.go
  pkg/alizer/mock.go
  pkg/api/registry.go
  pkg/binding/backend/mock.go
  pkg/binding/mock.go
  pkg/dev/mock.go
  pkg/init/asker/asker.go
  pkg/init/asker/interface.go
  pkg/init/asker/mock.go
  pkg/init/backend/alizer_test.go
  pkg/init/backend/interactive.go
  pkg/init/backend/interactive_test.go
  pkg/kclient/mock_Client.go
  pkg/odo/cli/registry/registry.go
  pkg/registry/devfile_component_type_list.go
  pkg/registry/devfile_component_type_list_test.go
  pkg/registry/interface.go
  pkg/registry/mock.go
  pkg/registry/registry.go
  pkg/registry/registry_test.go
  pkg/registry/types.go
  pkg/registry/types_with_details.go
  pkg/registry/types_with_details_test.go
  tests/helper/helper_generic.go
  tests/integration/devfile/cmd_devfile_init_test.go
  tests/integration/devfile/cmd_devfile_registry_test.go
Labels: approved, lgtm, kind/feature

#5745 Bumping odo version to v3.0.0-alpha2
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm, kind/task

#5744 Implement `odo set namespace/project`
  docs/website/versioned_docs/version-3.0.0/command-reference/set-namespace.md
  pkg/odo/cli/cli.go
  pkg/odo/cli/set/namespace/namespace.go
  pkg/odo/cli/set/set.go
  tests/helper/helper_cli.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/cmd_namespace_test.go
Labels: approved, lgtm, kind/feature

#5722 Redo the quickstart guide to odo 3.0.0
  docs/website/versioned_docs/version-3.0.0/getting-started/quickstart.md
Labels: approved, lgtm, kind/documentation

#5729 odo list namespace
  docs/website/versioned_docs/version-3.0.0/command-reference/list-namespace.md
  pkg/odo/cli/cli.go
  pkg/odo/cli/list/list.go
  pkg/odo/cli/list/namespace/namespace.go
  tests/integration/cmd_namespace_test.go
Labels: approved, lgtm, kind/feature

#5741 Reorganize documentation to specific folders
  docs/website/versioned_docs/version-3.0.0/command-reference/dev.md
  docs/website/versioned_docs/version-3.0.0/command-reference/preference.md
  docs/website/versioned_docs/version-3.0.0/development/_category_.json
  docs/website/versioned_docs/version-3.0.0/development/contribution.md
  docs/website/versioned_docs/version-3.0.0/getting-started/_category_.json
  docs/website/versioned_docs/version-3.0.0/overview/_category_.json
  docs/website/versioned_docs/version-3.0.0/overview/basics.md
  docs/website/versioned_docs/version-3.0.0/overview/cluster-setup/_category_.json
  docs/website/versioned_docs/version-3.0.0/overview/cluster-setup/kubernetes.md
  docs/website/versioned_docs/version-3.0.0/overview/cluster-setup/openshift.md
  docs/website/versioned_docs/version-3.0.0/overview/configure.md
  docs/website/versioned_docs/version-3.0.0/overview/features.md
  docs/website/versioned_docs/version-3.0.0/overview/installation.md
  docs/website/versioned_docs/version-3.0.0/overview/intro.md
  docs/website/versioned_docs/version-3.0.0/tutorials/_category_.json
  docs/website/versioned_docs/version-3.0.0/user-guides/_category_.json
  docs/website/versioned_docs/version-3.0.0/user-guides/advanced/_category_.json
  docs/website/versioned_docs/version-3.0.0/user-guides/advanced/deploying-on-ibm-z-and-power.md
  docs/website/versioned_docs/version-3.0.0/user-guides/advanced/pushing-specific-files.md
  docs/website/versioned_docs/version-3.0.0/user-guides/advanced/using-devfile-lifecycle-events.md
  docs/website/versioned_docs/version-3.0.0/user-guides/quickstart.md
Labels: approved, lgtm, kind/documentation

#5758 Removing unused examples/yaml files
  tests/examples/source/devfiles/nodejs/devfile-2.1.0.yaml
  tests/examples/source/devfiles/nodejs/devfile-deploy-with-multiple-resources.yaml
  tests/examples/source/devfiles/nodejs/devfile-no-endpoints.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-hotReload.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-invalid-events.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-invalid-volmount.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-link.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-multiple-defaults.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-no-default.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-no-group-kind.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-pod.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-testgroup.yaml
  tests/examples/source/devfiles/nodejs/devfile-without-devbuild.yaml
  tests/examples/source/devfiles/nodejs/devfile-without-devinit.yaml
  tests/examples/source/devfiles/nodejs/devfileCompositeInvalidComponent.yaml
  tests/examples/source/devfiles/nodejs/devfileCompositeNonExistent.yaml
  tests/examples/source/devfiles/nodejs/devfileIndirectNesting.yaml
  tests/examples/source/devfiles/parentSupport/devfile-middle-layer.yaml
  tests/examples/source/devfiles/parentSupport/devfile-with-composite.yaml
  tests/examples/source/devfiles/parentSupport/devfile-with-multi-layer-parent.yaml
  tests/examples/source/devfiles/parentSupport/devfile-with-parent-composite.yaml
  tests/examples/source/devfiles/parentSupport/devfile-with-parent.yaml
  tests/examples/source/devfiles/parentSupport/devfile.yaml
  tests/examples/source/devfiles/springboot/devfile-with-metadataname-foobar.yaml
  tests/examples/source/openjdk-sb-postgresql/.gitignore
  tests/examples/source/openjdk-sb-postgresql/pom.xml
  tests/examples/source/openjdk-sb-postgresql/src/main/java/com/example/demo/CrudApplication.java
  tests/examples/source/openjdk-sb-postgresql/src/main/java/com/example/demo/exception/NotFoundException.java
  tests/examples/source/openjdk-sb-postgresql/src/main/java/com/example/demo/exception/UnprocessableEntityException.java
  tests/examples/source/openjdk-sb-postgresql/src/main/java/com/example/demo/exception/UnsupportedMediaTypeException.java
  tests/examples/source/openjdk-sb-postgresql/src/main/java/com/example/demo/service/Fruit.java
  tests/examples/source/openjdk-sb-postgresql/src/main/java/com/example/demo/service/FruitController.java
  tests/examples/source/openjdk-sb-postgresql/src/main/java/com/example/demo/service/FruitRepository.java
  tests/examples/source/openjdk-sb-postgresql/src/main/resources/application.properties
  tests/examples/source/openjdk-sb-postgresql/src/main/resources/import.sql
  tests/examples/source/openjdk-sb-postgresql/src/main/resources/static/index.html
  tests/examples/source/web-nodejs-sample/.gitignore
  tests/examples/source/web-nodejs-sample/app/app.js
  tests/examples/source/web-nodejs-sample/package-lock.json
  tests/examples/source/web-nodejs-sample/package.json
Labels: approved, lgtm

#5763 Update quickstart guide
  docs/website/versioned_docs/version-3.0.0/user-guides/quickstart.md
Labels: approved, lgtm, kind/documentation

#5769 Speed up tests on K8s by not blocking until test namespace is gone
  tests/helper/helper_cli.go
  tests/helper/helper_generic.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/cmd_namespace_test.go
  tests/integration/devfile/cmd_delete_test.go
  tests/integration/devfile/cmd_dev_test.go
  tests/integration/devfile/cmd_devfile_deploy_test.go
Labels: area/testing, approved, lgtm, kind/tests

#5767 Fix ordering of command reference docs
  docs/website/versioned_docs/version-3.0.0/command-reference/add-binding.md
  docs/website/versioned_docs/version-3.0.0/command-reference/build-images.md
  docs/website/versioned_docs/version-3.0.0/command-reference/create-namespace.md
  docs/website/versioned_docs/version-3.0.0/command-reference/delete-component.md
  docs/website/versioned_docs/version-3.0.0/command-reference/delete-namespace.md
  docs/website/versioned_docs/version-3.0.0/command-reference/deploy.md
  docs/website/versioned_docs/version-3.0.0/command-reference/describe.md
  docs/website/versioned_docs/version-3.0.0/command-reference/dev.md
  docs/website/versioned_docs/version-3.0.0/command-reference/init.md
  docs/website/versioned_docs/version-3.0.0/command-reference/json-output.md
  docs/website/versioned_docs/version-3.0.0/command-reference/list-namespace.md
  docs/website/versioned_docs/version-3.0.0/command-reference/list.md
  docs/website/versioned_docs/version-3.0.0/command-reference/preference.md
  docs/website/versioned_docs/version-3.0.0/command-reference/registry.md
  docs/website/versioned_docs/version-3.0.0/command-reference/set-namespace.md
Labels: approved, lgtm, kind/documentation
