Repository redhat-developer/odo, pull requests merged in 2022-07, with the labels that each got.

#5902 adding Threat Model and corresponding md file
  .threatmodel/THREAT_MODELING.md
  .threatmodel/odo-model.json
Labels: approved, lgtm, kind/documentation

#5856 Fixes terminal completion command for odo
  pkg/odo/cli/cli.go
  pkg/odo/cli/completion/completion.go
  pkg/odo/cli/utils/terminal.go
  pkg/odo/cli/utils/terminal_test.go
  pkg/odo/cli/utils/utils.go
  pkg/odo/util/cmdutils.go
Labels: approved, lgtm

#5885 odo dev: handle port forwarding after pod restart
  pkg/binding/mock.go
  pkg/dev/dev.go
  pkg/dev/interface.go
  pkg/dev/mock.go
  pkg/devfile/adapters/helper.go
  pkg/devfile/adapters/helper_test.go
  pkg/devfile/adapters/kubernetes/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/kclient/interface.go
  pkg/kclient/mock_Client.go
  pkg/kclient/port_forwarding.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/portForward/interface.go
  pkg/portForward/portForward.go
  pkg/portForward/writer.go
  pkg/portForward/writer_test.go
  tests/e2escenarios/e2e-test.go
  tests/examples/source/devfiles/nodejs/project-with-multiple-endpoints/server.js
  tests/helper/helper_dev.go
  tests/integration/devfile/cmd_dev_test.go
Labels: approved, lgtm, kind/feature

#5908 Use cached discovery client
  docs/website/docs/command-reference/list.md
  pkg/kclient/all.go
  pkg/kclient/kclient.go
Labels: approved, lgtm

#5915 Blog: Connecting to a service without SBO
  docs/website/blog/2022-06-30-binding-database-service-without-sbo.md
Labels: approved, lgtm, kind/documentation

#5919 Bump odo version in installation docs
  docs/website/docs/overview/installation.md
  docs/website/docusaurus.config.js
  docs/website/versioned_docs/version-2.5.0/getting-started/installation.md
Labels: approved, lgtm, kind/documentation

#5931 reduce test make targets, organize test file structure
  .ibm/pipelines/kubernetes-tests.sh
  .ibm/pipelines/openshift-tests.sh
  .ibm/pipelines/windows-test-script.ps1
  Makefile
  scripts/openshiftci-Nightly-SBO-tests.sh
  scripts/openshiftci-periodic-tests.sh
  scripts/openshiftci-presubmit-all-tests-old.sh
  scripts/openshiftci-presubmit-all-tests.sh
  tests/helper/odo_utils.go
  tests/integration/cmd_add_binding_test.go
  tests/integration/cmd_analyze_test.go
  tests/integration/cmd_delete_test.go
  tests/integration/cmd_describe_component_test.go
  tests/integration/cmd_describe_list_binding_test.go
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
  tests/integration/cmd_devfile_build_images_test.go
  tests/integration/cmd_devfile_deploy_test.go
  tests/integration/cmd_devfile_init_test.go
  tests/integration/cmd_devfile_list_test.go
  tests/integration/cmd_devfile_registry_test.go
  tests/integration/cmd_logs_test.go
  tests/integration/cmd_remove_binding_test.go
  tests/integration/devfile/debug/debug_suite_test.go
  tests/integration/devfile/devfile_suite_test.go
  tests/integration/devfile/utils/utils.go
  tests/integration/interactive_add_binding_test.go
  tests/integration/interactive_deploy_test.go
  tests/integration/interactive_dev_test.go
  tests/integration/interactive_init_test.go
  tests/integration/project/cmd_project_test.go
  tests/integration/project/project_suite_test.go
  tests/interactive/interactive_suit_test.go
Labels: area/testing, approved, lgtm, area/refactoring

#5944 Remove unused functions: ComponentExist, PushedComponent
  pkg/component/component.go
  pkg/component/pushed_component.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/utils/utils_test.go
  pkg/storage/kubernetes.go
  pkg/storage/kubernetes_test.go
  pkg/storage/mock_Client.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
Labels: approved, lgtm, [deprecated] kind/cleanup

#5945 Cleanup test to skip setup cluster steps if needed
  tests/e2escenarios/e2e-test.go
  tests/e2escenarios/e2e_devfile_test.go
  tests/helper/helper_generic.go
  tests/integration/cmd_add_binding_test.go
  tests/integration/cmd_analyze_test.go
  tests/integration/cmd_delete_test.go
  tests/integration/cmd_describe_component_test.go
  tests/integration/cmd_describe_list_binding_test.go
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
  tests/integration/cmd_devfile_build_images_test.go
  tests/integration/cmd_devfile_deploy_test.go
  tests/integration/cmd_devfile_init_test.go
  tests/integration/cmd_devfile_list_test.go
  tests/integration/cmd_devfile_registry_test.go
  tests/integration/cmd_logs_test.go
  tests/integration/cmd_namespace_test.go
  tests/integration/cmd_pref_config_test.go
  tests/integration/cmd_remove_binding_test.go
  tests/integration/generic_test.go
  tests/integration/interactive_add_binding_test.go
  tests/integration/interactive_deploy_test.go
  tests/integration/interactive_dev_test.go
  tests/integration/interactive_init_test.go
Labels: approved, lgtm, kind/tests

#5859 update documentation issue template
  .github/ISSUE_TEMPLATE/Documentation.md
Labels: approved, lgtm, area/documentation

#5934 download golangci-lint binary with test script
  Makefile
Labels: area/testing, approved, lgtm

#5952 Bump version to v3.0.0-beta2
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#5942 Grab pod logs concurrently
  pkg/logs/interface.go
  pkg/logs/logs.go
  pkg/odo/cli/logs/logs.go
Labels: kind/bug, approved, lgtm

#5956 Add blog post for v3.0.0-beta1 release
  docs/website/blog/2022-07-01-odo-v3-beta1.md
Labels: approved, lgtm, kind/documentation

#5961 Use sync/atomic to keep tab on go routines
  pkg/logs/logs.go
  pkg/odo/cli/logs/logs.go
  tests/integration/cmd_logs_test.go
Labels: kind/bug, approved, lgtm

#5936 Allow binding to services from other namespaces
  docs/website/docs/command-reference/add-binding.md
  docs/website/docs/command-reference/describe-binding.md
  docs/website/docs/command-reference/json-output.md
  docs/website/docs/command-reference/list-binding.md
  pkg/binding/add.go
  pkg/binding/asker/interface.go
  pkg/binding/asker/survey_asker.go
  pkg/binding/backend/flags.go
  pkg/binding/backend/interactive.go
  pkg/binding/backend/interface.go
  pkg/binding/backend/mock.go
  pkg/binding/binding.go
  pkg/binding/binding_test.go
  pkg/binding/interface.go
  pkg/binding/list_test.go
  pkg/binding/mock.go
  pkg/kclient/binding.go
  pkg/kclient/dynamic.go
  pkg/kclient/interface.go
  pkg/kclient/mock_Client.go
  pkg/odo/cli/add/binding/binding.go
  pkg/odo/cli/describe/binding.go
  pkg/odo/cli/list/binding/binding.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/service/service.go
  tests/integration/cmd_add_binding_test.go
  tests/integration/cmd_describe_list_binding_test.go
  tests/integration/interactive_add_binding_test.go
Labels: approved, lgtm, kind/feature

#5968 Update Dependabot configuration
  .github/dependabot.yml
Labels: approved, lgtm, kind/task

#5970 Update Alizer version
  go.mod
  go.sum
  scripts/generate-mod.sh
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/dotnet_enricher.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/enricher.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/framework/dotnet/dotnet_detector.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/framework/go/beego_detector.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/framework/go/echo_detector.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/framework/go/fasthttp_detector.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/framework/go/gin_detector.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/framework/go/gofiber_detector.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/framework/go/mux_detector.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/framework/java/micronaut_detector.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/framework/java/openliberty_detector.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/framework/java/quarkus_detector.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/framework/java/spring_detector.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/framework/java/vertx_detector.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/framework/javascript/nodejs/express_detector.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/framework/javascript/nodejs/reactjs_detector.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/framework/python/django_detector.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/go_enricher.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/java_enricher.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/javascript_enricher.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/python_enricher.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/model/model.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/component_recognizer.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/devfile_recognizer.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/language_recognizer.go
  vendor/github.com/redhat-developer/alizer/go/pkg/schema/languages.go
  vendor/github.com/redhat-developer/alizer/go/pkg/schema/package_json.go
  vendor/github.com/redhat-developer/alizer/go/pkg/schema/pom_xml.go
  vendor/github.com/redhat-developer/alizer/go/pkg/utils/detector.go
  vendor/github.com/redhat-developer/alizer/go/pkg/utils/langfiles/languages_file_handler.go
  vendor/github.com/redhat-developer/alizer/go/pkg/utils/langfiles/resources/languages-customization.yml
  vendor/modules.txt
Labels: approved, lgtm, kind/task

#5965 Improve --help page by separating commands to management commands
  pkg/odo/cli/add/add.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/create/create.go
  pkg/odo/cli/delete/delete.go
  pkg/odo/cli/describe/describe.go
  pkg/odo/cli/list/list.go
  pkg/odo/cli/remove/remove.go
  pkg/odo/cli/set/set.go
Labels: approved, lgtm

#5966 Add blog post for `v3.0.0-beta2` release and update installation doc
  docs/website/blog/2022-07-21-odo-v3-beta2.md
  docs/website/docs/overview/installation.md
  docs/website/docusaurus.config.js
Labels: approved, lgtm, kind/documentation

#5963 Refactor color througout interactive mode and dev
  pkg/init/backend/interactive.go
  pkg/log/status.go
  pkg/portForward/writer.go
Labels: approved, lgtm

#5975 Limit the total number of Dependabot PRs to 2
  .github/dependabot.yml
Labels: approved, lgtm, kind/task

#5978 Increase timeout by 60sec devEnv check
  Makefile
  tests/e2escenarios/e2e_test.go
Labels: approved, lgtm, kind/tests

#5852 Do not save component name in env.yaml
  pkg/component/pushed_component.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/cli/dev/dev.go
  pkg/storage/storage.go
  tests/helper/helper_filesystem.go
  tests/integration/cmd_dev_test.go
Labels: kind/bug, approved, lgtm
