Repository redhat-developer/odo, pull requests merged in 2022-09, with the labels that each got.

#6074 Blog post for v3.0.0-rc1 release
  docs/website/blog/2022-09-01-odo-v3-rc1.md
  docs/website/docs/overview/installation.md
  docs/website/docusaurus.config.js
Labels: approved, lgtm, kind/documentation

#6093 [flaky test] Move DetectName to method in alizer package
  pkg/alizer/alizer.go
  pkg/alizer/alizer_test.go
  pkg/alizer/interface.go
  pkg/alizer/mock.go
  pkg/component/component.go
  pkg/init/backend/alizer.go
  pkg/init/backend/interactive.go
  pkg/init/backend/interactive_test.go
  pkg/init/init.go
Labels: kind/bug, approved, lgtm

#6088 (odo init): Add input validation for component name
  docs/website/docs/command-reference/init.md
  pkg/init/asker/asker.go
  pkg/init/backend/flags.go
  pkg/init/backend/flags_test.go
  pkg/init/backend/interactive.go
  pkg/init/backend/interactive_test.go
  pkg/init/init_test.go
  pkg/odo/cli/init/init.go
  tests/integration/cmd_devfile_init_test.go
  tests/integration/interactive_init_test.go
Labels: kind/bug, approved, lgtm

#6094 Use map for runningIn instead of array in JSON output
  docs/website/docs/command-reference/json-output.md
  pkg/api/binding.go
  pkg/api/component-abstract.go
  pkg/api/component.go
  pkg/api/component_test.go
  pkg/binding/list.go
  pkg/binding/list_test.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/odo/cli/init/init.go
  tests/integration/cmd_describe_component_test.go
  tests/integration/cmd_devfile_list_test.go
Labels: kind/bug, approved, lgtm

#6078 Fix: (odo list) Empty parenthesis for odo version if component is not on the cluster
  pkg/odo/cli/list/component/list.go
Labels: kind/bug, approved, lgtm

#6096 Remove skip for k8s from `odo dev` integration tests
  tests/integration/cmd_dev_test.go
Labels: approved, lgtm, kind/tests

#6100 Display "Interactive mode enabled" only when running `odo init` interactively
  pkg/log/status.go
  pkg/odo/cli/init/init.go
  pkg/odo/cli/messages/messages.go
  tests/integration/cmd_devfile_init_test.go
  tests/integration/interactive_init_test.go
Labels: kind/bug, approved, lgtm

#6081 Remove cluster setup
  docs/website/blog/2022-06-14-binding-external-service.md
  docs/website/docs/command-reference/add-binding.md
  docs/website/docs/overview/cluster-setup/_category_.json
  docs/website/docs/overview/cluster-setup/kubernetes.md
  docs/website/docs/overview/cluster-setup/openshift.md
  docs/website/docs/user-guides/quickstart.md
Labels: approved, lgtm, kind/documentation

#6086 Reorganizes installation document
  docs/website/docs/overview/installation.md
Labels: approved, lgtm, kind/documentation

#6071 Reorganize and separate language / framework tutorials.
  docs/website/docs/_version.mdx
  docs/website/docs/user-guides/advanced/_category_.json
  docs/website/docs/user-guides/deploy/_category_.json
  docs/website/docs/user-guides/deploy/_delete_resources.mdx
  docs/website/docs/user-guides/deploy/_editing_devfile.mdx
  docs/website/docs/user-guides/deploy/_overview.mdx
  docs/website/docs/user-guides/deploy/_prerequisites.mdx
  docs/website/docs/user-guides/deploy/_running_deploy.mdx
  docs/website/docs/user-guides/deploy/deploy.md
  docs/website/docs/user-guides/deploy/dotnet.md
  docs/website/docs/user-guides/deploy/go.md
  docs/website/docs/user-guides/deploy/java.md
  docs/website/docs/user-guides/deploy/nodejs.md
  docs/website/docs/user-guides/quickstart.md
  docs/website/docs/user-guides/quickstart/_category_.json
  docs/website/docs/user-guides/quickstart/_connecting_to_cluster.mdx
  docs/website/docs/user-guides/quickstart/_creating_app.mdx
  docs/website/docs/user-guides/quickstart/_initial_source_code.mdx
  docs/website/docs/user-guides/quickstart/_running_command.mdx
  docs/website/docs/user-guides/quickstart/dotnet.md
  docs/website/docs/user-guides/quickstart/go.md
  docs/website/docs/user-guides/quickstart/java.md
  docs/website/docs/user-guides/quickstart/nodejs.md
  docs/website/docs/user-guides/quickstart/quickstart.md
  docs/website/src/pages/index.tsx
Labels: approved, lgtm, kind/documentation

#6105 JSON output for preference view
  docs/website/docs/command-reference/json-output.md
  pkg/api/preference.go
  pkg/odo/cli/preference/view.go
  pkg/odo/cli/preference/view_test.go
  pkg/preference/implem.go
  pkg/preference/machine_output.go
  tests/integration/cmd_pref_config_test.go
Labels: approved, lgtm, kind/feature

#6089 Manual sync of files pressing p
  .ibm/pipelines/windows-test-script.ps1
  docs/website/docs/command-reference/dev.md
  go.mod
  pkg/watch/file_watcher.go
  pkg/watch/key_watcher.go
  pkg/watch/key_watcher_unix.go
  pkg/watch/key_watcher_windows.go
  pkg/watch/term_unix_bsd.go
  pkg/watch/term_unix_other.go
  pkg/watch/watch.go
  pkg/watch/watch_test.go
  tests/helper/helper_dev.go
  tests/helper/helper_interactive.go
  tests/integration/cmd_add_binding_test.go
  tests/integration/cmd_delete_test.go
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
  tests/integration/interactive_dev_test.go
  vendor/github.com/hinshun/vt10x/.travis.yml
  vendor/github.com/hinshun/vt10x/LICENSE
  vendor/github.com/hinshun/vt10x/README.md
  vendor/github.com/hinshun/vt10x/color.go
  vendor/github.com/hinshun/vt10x/csi.go
  vendor/github.com/hinshun/vt10x/doc.go
  vendor/github.com/hinshun/vt10x/ioctl_other.go
  vendor/github.com/hinshun/vt10x/ioctl_posix.go
  vendor/github.com/hinshun/vt10x/parse.go
  vendor/github.com/hinshun/vt10x/state.go
  vendor/github.com/hinshun/vt10x/str.go
  vendor/github.com/hinshun/vt10x/vt.go
  vendor/github.com/hinshun/vt10x/vt_other.go
  vendor/github.com/hinshun/vt10x/vt_posix.go
  vendor/modules.txt
Labels: approved, lgtm, kind/feature

#6116 Do not display message when using no-watch flag
  pkg/watch/watch.go
  tests/helper/helper_dev.go
Labels: kind/bug, approved, lgtm

#6117 Fix broken links to installation guide
  docs/website/docs/command-reference/add-binding.md
  pkg/binding/binding.go
  scripts/changelog-script.sh
Labels: kind/bug, approved, lgtm, area/documentation

#6115 Adds tabs for podman/docker docs and OS differences
  docs/website/docs/user-guides/deploy/_prerequisites.mdx
Labels: approved, lgtm, kind/documentation

#6119 Port-forward all endpoints regardless of exposure
  pkg/libdevfile/libdevfile.go
  pkg/libdevfile/libdevfile_test.go
  pkg/odo/cli/dev/dev.go
  tests/integration/cmd_dev_test.go
Labels: kind/bug, approved, lgtm

#6112 Add runtime label based on metadata:language/projectType
  pkg/component/component.go
  pkg/component/delete/delete_test.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/commandhandler.go
  pkg/labels/constants.go
  pkg/labels/labels.go
  pkg/storage/kubernetes.go
  pkg/storage/kubernetes_test.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  pkg/testingutil/pods.go
  pkg/testingutil/services.go
  tests/examples/source/devfiles/nodejs/devfile-with-metadata-language.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-metadata-no-language-project-type.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-metadata-project-type.yaml
  tests/helper/helper_cli.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/cmd_dev_test.go
Labels: approved, lgtm, kind/feature

#6121 fix login failure error: x509
  scripts/openshiftci-presubmit-all-tests.sh
Labels: approved, lgtm, kind/tests

#6109 Show Kubernetes cluster version in odo version
  pkg/kclient/oc_server.go
  pkg/odo/cli/version/version.go
  tests/integration/generic_test.go
  tests/integration/loginlogout/cmd_login_logout_test.go
Labels: kind/bug, approved, lgtm

#6123 upgrade to docusaurus 2.1 and fix version mismatch
  docs/website/docusaurus.config.js
  docs/website/package.json
  docs/website/yarn.lock
Labels: approved, lgtm, kind/documentation

#6104 Update README.md with logo & updated text
  README.md
  docs/website/static/img/logo_small.png
Labels: approved, lgtm, kind/documentation

#6095 Guide for migrating from v2 to v3
  docs/website/docs/user-guides/v3-migration-guide.md
Labels: approved, lgtm, kind/documentation

#6128 Fix broken links to devfile.io
  docs/website/docs/command-reference/deploy.md
  docs/website/docs/command-reference/dev.md
  docs/website/docs/development/devfile.md
  docs/website/versioned_docs/version-2.5.0/command-reference/deploy.md
Labels: approved, lgtm, kind/documentation, area/documentation

#6124 docs: move deploying to advanced usage
  docs/website/docs/user-guides/advanced/deploy/_category_.json
  docs/website/docs/user-guides/advanced/deploy/_delete_resources.mdx
  docs/website/docs/user-guides/advanced/deploy/_editing_devfile.mdx
  docs/website/docs/user-guides/advanced/deploy/_overview.mdx
  docs/website/docs/user-guides/advanced/deploy/_prerequisites.mdx
  docs/website/docs/user-guides/advanced/deploy/_running_deploy.mdx
  docs/website/docs/user-guides/advanced/deploy/deploy.md
  docs/website/docs/user-guides/advanced/deploy/dotnet.md
  docs/website/docs/user-guides/advanced/deploy/go.md
  docs/website/docs/user-guides/advanced/deploy/java.md
  docs/website/docs/user-guides/advanced/deploy/nodejs.md
  docs/website/docs/user-guides/advanced/deploying-on-ibm-z-and-power.md
  docs/website/docs/user-guides/advanced/pushing-specific-files.md
  docs/website/docs/user-guides/advanced/using-devfile-lifecycle-events.md
  docs/website/docs/user-guides/deploy/_category_.json
Labels: approved, lgtm, kind/documentation

#6118 Adds support for odo list services
  docs/website/docs/command-reference/json-output.md
  docs/website/docs/command-reference/list-services.md
  go.mod
  go.sum
  pkg/api/bindable_service.go
  pkg/api/list.go
  pkg/binding/binding.go
  pkg/dev/dev.go
  pkg/odo/cli/list/binding/binding.go
  pkg/odo/cli/list/component/list.go
  pkg/odo/cli/list/list.go
  pkg/odo/cli/list/namespace/namespace.go
  pkg/odo/cli/list/services/services.go
  tests/integration/cmd_list_services_test.go
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/internal/dbg/dbg.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/modules.txt
Labels: approved, lgtm, kind/feature

#6108 check if namespace is created instead of project
  tests/helper/helper_cli.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/interactive_add_binding_test.go
Labels: approved, lgtm, kind/tests

#6133 Fix typo in README
  README.md
Labels: approved, lgtm, kind/documentation, area/documentation

#6130 Try to reload config when disconnected from the cluster
  pkg/kclient/interface.go
  pkg/kclient/mock_Client.go
  pkg/kclient/refresh.go
  pkg/watch/watch.go
Labels: kind/bug, approved, lgtm

#6140 Update devfile data in integration tests
  tests/integration/cmd_devfile_init_test.go
  tests/integration/cmd_devfile_registry_test.go
  tests/integration/interactive_deploy_test.go
  tests/integration/interactive_dev_test.go
  tests/integration/interactive_init_test.go
Labels: area/testing, approved, lgtm, kind/tests

#6137 Bump odo to v3.0.0-rc2
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#6114 Add documentation on connecting to a service
  docs/website/docs/user-guides/advanced/_create-mongodb-service.mdx
  docs/website/docs/user-guides/advanced/_delete-mongodb-service.mdx
  docs/website/docs/user-guides/advanced/connecting-a-service.md
Labels: approved, lgtm, kind/documentation, area/documentation

#6126 Make command reference docs consistent
  docs/website/docs/command-reference/add-binding.md
  docs/website/docs/command-reference/build-images.md
  docs/website/docs/command-reference/create-namespace.md
  docs/website/docs/command-reference/delete-component.md
  docs/website/docs/command-reference/delete-namespace.md
  docs/website/docs/command-reference/deploy.md
  docs/website/docs/command-reference/describe-binding.md
  docs/website/docs/command-reference/describe-component.md
  docs/website/docs/command-reference/dev.md
  docs/website/docs/command-reference/init.md
  docs/website/docs/command-reference/list-binding.md
  docs/website/docs/command-reference/list-component.md
  docs/website/docs/command-reference/list-namespace.md
  docs/website/docs/command-reference/list.md
  docs/website/docs/command-reference/logs.md
  docs/website/docs/command-reference/registry.md
  docs/website/docs/command-reference/remove-binding.md
  docs/website/docs/command-reference/set-namespace.md
Labels: approved, lgtm, kind/documentation, area/documentation

#6144 Use Deploying an Application not Deploying application
  docs/website/docs/user-guides/advanced/deploy/deploy.md
Labels: approved, lgtm, kind/documentation

#6136 Fix panic when component name is long but not app
  pkg/util/util.go
  pkg/util/util_test.go
Labels: kind/bug, approved, lgtm

#6148 Add CLI images / information on index page of odo.dev
  docs/website/src/pages/index.module.css
  docs/website/src/pages/index.tsx
  docs/website/static/img/deploy.png
  docs/website/static/img/init.png
Labels: approved, lgtm, kind/documentation

#6120 Create document highlighting dev and deploy
  docs/website/docs/overview/concepts.md
  docs/website/docs/overview/dev_and_deploy.md
Labels: approved, lgtm, kind/documentation

#6145 Document how `odo` translates `container` component into Kubernetes resources
  docs/website/docs/development/architecture/_category_.json
  docs/website/docs/development/architecture/how-odo-works.md
  docs/website/src/css/custom.css
Labels: approved, lgtm, kind/documentation, area/documentation

#6141 Refacto odo dev
  pkg/dev/dev.go
  pkg/dev/interface.go
  pkg/dev/mock.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/genericclioptions/clientset/clientset.go
Labels: approved, lgtm

#6154 Fix message for interactive odo delete project
  pkg/odo/cli/delete/namespace/namespace.go
Labels: kind/bug, area/UX, approved, lgtm

#6164 Revert devfile python ID
  tests/integration/cmd_devfile_registry_test.go
  tests/integration/interactive_deploy_test.go
  tests/integration/interactive_dev_test.go
  tests/integration/interactive_init_test.go
Labels: area/testing, approved, lgtm, kind/tests

#6153 Make command reference docs consistent (2)
  docs/website/docs/command-reference/add-binding.md
  docs/website/docs/command-reference/build-images.md
  docs/website/docs/command-reference/delete-namespace.md
  docs/website/docs/command-reference/describe-binding.md
  docs/website/docs/command-reference/init.md
  docs/website/docs/command-reference/list-component.md
  docs/website/docs/command-reference/list-namespace.md
  docs/website/docs/command-reference/logs.md
  docs/website/docs/command-reference/remove-binding.md
  docs/website/docs/command-reference/set-namespace.md
  docs/website/docs/overview/configure.md
Labels: approved, lgtm, kind/documentation, area/documentation

#6156 Adjust sidebars on odo.dev website
  docs/website/docs/overview/_category_.json
  docs/website/docs/user-guides/_category_.json
  docs/website/docs/user-guides/advanced/_category_.json
  docs/website/docs/user-guides/advanced/connecting-a-service.md
  docs/website/docs/user-guides/advanced/deploy/_category_.json
  docs/website/docs/user-guides/quickstart/_category_.json
  docs/website/docusaurus.config.js
Labels: approved, lgtm, kind/documentation, area/documentation

#6127 Add extra output when init project using odo dev or deploy
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/messages/messages.go
  tests/integration/interactive_deploy_test.go
  tests/integration/interactive_dev_test.go
Labels: approved, lgtm

#6163 Refacto sync pkg
  pkg/dev/dev.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/component/commandhandler.go
  pkg/devfile/adapters/kubernetes/component/push.go
  pkg/devfile/adapters/types.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/sync/adapter.go
  pkg/sync/adapter_test.go
  pkg/sync/copy.go
  pkg/sync/copy_test.go
  pkg/sync/interface.go
  pkg/sync/mock/sync.go
  pkg/sync/sync.go
  pkg/sync/sync_test.go
  pkg/watch/watch.go
  scripts/mockgen.sh
Labels: approved, lgtm

#6169 Refactor remotecmd
  pkg/component/delete/delete.go
  pkg/component/delete/delete_test.go
  pkg/component/exec_handler.go
  pkg/dev/dev.go
  pkg/dev/mock.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/component/commandhandler.go
  pkg/exec/exec.go
  pkg/exec/exec_test.go
  pkg/exec/interface.go
  pkg/exec/mock.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/remotecmd/doc.go
  pkg/remotecmd/interface.go
  pkg/remotecmd/kubeexec.go
  pkg/remotecmd/kubexec_test.go
  pkg/sync/sync.go
  pkg/sync/sync_test.go
  scripts/mockgen.sh
Labels: approved, lgtm
