Repository redhat-developer/odo, pull requests merged in 2022-06, with the labels that each got.

#5783 Execute tar with --no-same-owner
  pkg/kclient/pods.go
Labels: kind/bug, approved, lgtm

#5773 odo describe binding
  docs/website/versioned_docs/version-3.0.0/command-reference/describe-binding.md
  docs/website/versioned_docs/version-3.0.0/command-reference/describe-component.md
  docs/website/versioned_docs/version-3.0.0/command-reference/json-output.md
  pkg/api/binding.go
  pkg/binding/binding.go
  pkg/binding/interface.go
  pkg/binding/mock.go
  pkg/kclient/binding.go
  pkg/kclient/interface.go
  pkg/kclient/mock_Client.go
  pkg/kclient/operators.go
  pkg/odo/cli/describe/binding.go
  pkg/odo/cli/describe/describe.go
  tests/examples/source/devfiles/nodejs/devfile-with-service-binding-envvars.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-service-binding-files.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-spec-service-binding-envvars.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-spec-service-binding.yaml
  tests/integration/devfile/cmd_describe_binding_test.go
  tests/integration/devfile/cmd_describe_component_test.go
Labels: approved, lgtm, kind/feature

#5762 Adds documentation to Devfile reference page
  docs/website/versioned_docs/version-3.0.0/command-reference/dev.md
  docs/website/versioned_docs/version-3.0.0/development/devfile.md
Labels: approved, lgtm, kind/documentation

#5786 Adds Java Spring Boot example to quickstart guide
  docs/website/versioned_docs/version-3.0.0/user-guides/quickstart.md
Labels: approved, lgtm, kind/documentation

#5726 move alizer command from gui to utility group
  pkg/odo/cli/alizer/alizer.go
  pkg/odo/cli/cli.go
Labels: approved, lgtm

#5788 Add Golang to the quickstart guide
  docs/website/versioned_docs/version-3.0.0/user-guides/quickstart.md
Labels: approved, lgtm, kind/documentation

#5790 Add unit test for odo add binding
  pkg/binding/binding.go
  pkg/binding/binding_test.go
  pkg/binding/interface.go
  pkg/binding/mock.go
  pkg/kclient/binding.go
  pkg/kclient/deployments.go
  pkg/kclient/interface.go
  pkg/kclient/mock_Client.go
  pkg/odo/cli/add/binding/binding.go
  pkg/testingutil/devfile.go
Labels: approved, lgtm, kind/tests

#5787 odo remove binding
  docs/website/versioned_docs/version-3.0.0/command-reference/remove-binding.md
  pkg/binding/add.go
  pkg/binding/binding.go
  pkg/binding/interface.go
  pkg/binding/mock.go
  pkg/binding/remove.go
  pkg/binding/remove_binding_test.go
  pkg/odo/cli/add/add.go
  pkg/odo/cli/add/binding/binding.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/remove/binding/binding.go
  pkg/odo/cli/remove/remove.go
  tests/integration/devfile/cmd_remove_binding_test.go
Labels: approved, lgtm, kind/feature

#5804 Use latest alizer library version, including .net detection
  docs/website/versioned_docs/version-3.0.0/user-guides/quickstart.md
  go.mod
  go.sum
  pkg/alizer/alizer.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/go_enricher.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/component_recognizer.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/devfile_recognizer.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/language_recognizer.go
  vendor/github.com/redhat-developer/alizer/go/pkg/schema/languages.go
  vendor/github.com/redhat-developer/alizer/go/pkg/utils/langfiles/languages_file_handler.go
  vendor/modules.txt
Labels: approved, lgtm, kind/feature

#5778 add e2e tests
  Makefile
  tests/e2escenarios/e2e-test.go
Labels: approved, lgtm, kind/tests

#5760 Add `odo logs`
  docs/website/versioned_docs/version-3.0.0/command-reference/logs.md
  pkg/binding/mock.go
  pkg/component/component.go
  pkg/kclient/binding.go
  pkg/kclient/interface.go
  pkg/kclient/mock_Client.go
  pkg/kclient/pods.go
  pkg/log/status.go
  pkg/logs/interface.go
  pkg/logs/logs.go
  pkg/logs/logs_test.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/logs/logs.go
  pkg/odo/genericclioptions/clientset/clientset.go
  tests/integration/devfile/cmd_logs_test.go
Labels: approved, lgtm, kind/feature

#5808 Update OWNERS files
  OWNERS
  openshift-ci/build-root/OWNERS
  scripts/OWNERS
  tests/OWNERS
Labels: approved, lgtm, kind/tests

#5749 Substituting variables into the devfile from the CLI
  docs/website/versioned_docs/version-3.0.0/command-reference/deploy.md
  docs/website/versioned_docs/version-3.0.0/command-reference/dev.md
  go.mod
  go.sum
  pkg/dev/dev.go
  pkg/dev/interface.go
  pkg/dev/mock.go
  pkg/devfile/devfile.go
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/genericclioptions/context.go
  pkg/vars/doc.go
  pkg/vars/errors.go
  pkg/vars/vars.go
  pkg/vars/vars_test.go
  pkg/watch/watch.go
  tests/integration/devfile/cmd_dev_test.go
  vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/import_reference.go
  vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/zz_generated.parent_overrides.go
  vendor/github.com/devfile/library/pkg/devfile/parse.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/2.2.0/devfileJsonSchema220.go
  vendor/github.com/devfile/library/pkg/devfile/parser/parse.go
  vendor/github.com/devfile/library/pkg/util/util.go
  vendor/modules.txt
Labels: approved, lgtm, kind/feature

#5815 ignore dynamic resource when not found
  pkg/kclient/dynamic.go
Labels: kind/bug, approved, lgtm, ok-to-test

#5807 Fix: configuration shows volumes as containers
  pkg/init/backend/interactive.go
  pkg/init/backend/interactive_test.go
Labels: kind/bug, approved, lgtm

#5785 Wait for deployment rollout only when binding created / modified
  pkg/kclient/dynamic.go
  pkg/kclient/interface.go
  pkg/kclient/mock_Client.go
  pkg/service/link.go
  pkg/service/service.go
  tests/integration/devfile/cmd_dev_test.go
Labels: kind/bug, approved, lgtm

#5817 odo add binding - Bind as files UI update
  docs/website/versioned_docs/version-3.0.0/command-reference/add-binding.md
  pkg/binding/asker/survey_asker.go
  pkg/odo/cli/add/binding/binding.go
  tests/integration/cmd_namespace_test.go
  tests/interactive/cmd_add_binding_test.go
Labels: approved, lgtm, kind/feature

#5810 Add 3.0.0 link to homepage, and fix alpha title
  docs/website/docusaurus.config.js
  docs/website/src/pages/index.tsx
Labels: approved, lgtm, kind/documentation

#5835 Update README.md
  README.md
Labels: kind/bug, approved, lgtm, area/documentation

#5812 Add Homebrew installation details
  docs/website/docs/getting-started/installation.md
  docs/website/versioned_docs/version-3.0.0/overview/installation.md
Labels: approved, lgtm, kind/documentation

#5768 Add support for `command`/`args` fields in `container` components
  docs/website/versioned_docs/version-3.0.0/command-reference/dev.md
  pkg/component/delete/delete.go
  pkg/component/exec_handler.go
  pkg/devfile/adapters/common/command.go
  pkg/devfile/adapters/common/command_composite.go
  pkg/devfile/adapters/common/command_parallel_composite.go
  pkg/devfile/adapters/common/command_simple.go
  pkg/devfile/adapters/common/command_supervisor.go
  pkg/devfile/adapters/common/command_test.go
  pkg/devfile/adapters/common/errors.go
  pkg/devfile/adapters/common/exec.go
  pkg/devfile/adapters/common/exec_test.go
  pkg/devfile/adapters/common/executor.go
  pkg/devfile/adapters/common/generic.go
  pkg/devfile/adapters/common/interface.go
  pkg/devfile/adapters/common/utils.go
  pkg/devfile/adapters/common/utils_test.go
  pkg/devfile/adapters/kubernetes/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/component/commandhandler.go
  pkg/devfile/adapters/kubernetes/component/status.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils_test.go
  pkg/kclient/supervisord.go
  pkg/libdevfile/errors.go
  pkg/libdevfile/libdevfile.go
  pkg/libdevfile/libdevfile_test.go
  pkg/machineoutput/event_logging.go
  pkg/machineoutput/types_event_logging.go
  pkg/remotecmd/doc.go
  pkg/remotecmd/interface.go
  pkg/remotecmd/kubeexec.go
  pkg/remotecmd/kubexec_test.go
  pkg/remotecmd/remotecmd.go
  pkg/remotecmd/remotecmd_test.go
  pkg/remotecmd/types.go
  pkg/storage/kubernetes.go
  pkg/storage/kubernetes_test.go
  pkg/storage/storage.go
  pkg/sync/adapter.go
  pkg/sync/adapter_test.go
  pkg/sync/mock/sync.go
  pkg/sync/sync.go
  pkg/task/retry.go
  pkg/task/retry_test.go
  pkg/util/util.go
  tests/integration/devfile/cmd_dev_test.go
Labels: kind/bug, approved, lgtm

#5825 Adds odo logs for Deploy mode
  docs/website/versioned_docs/version-3.0.0/command-reference/logs.md
  pkg/logs/errors.go
  pkg/logs/interface.go
  pkg/logs/logs.go
  pkg/odo/cli/logs/logs.go
  tests/examples/source/devfiles/nodejs/devfile-deploy-functional-pods.yaml
  tests/integration/devfile/cmd_logs_test.go
Labels: approved, lgtm, kind/feature

#5828 Add blog post about binding an external service
  docs/website/blog/2022-06-14-binding-external-service.md
Labels: approved, lgtm, kind/documentation

#5826 Fix parametrized integration tests
  tests/examples/source/devfiles/nodejs/devfile-deploy-with-multiple-resources.yaml
  tests/integration/cmd_namespace_test.go
  tests/integration/devfile/cmd_delete_test.go
  tests/integration/devfile/cmd_describe_binding_test.go
  tests/integration/devfile/cmd_devfile_build_images_test.go
  tests/integration/devfile/cmd_devfile_deploy_test.go
Labels: approved, lgtm, kind/tests

#5845 Fix flaky `kubeexec` unit test case with env vars
  pkg/devfile/adapters/kubernetes/component/commandhandler.go
  pkg/remotecmd/kubeexec.go
  pkg/remotecmd/kubexec_test.go
  pkg/remotecmd/types.go
Labels: area/testing, approved, lgtm, kind/tests

#5849 Fix CLI info regarding Springboot quickstart
  docs/website/versioned_docs/version-3.0.0/user-guides/quickstart.md
Labels: approved, lgtm, kind/documentation

#5823 odo list binding
  docs/website/versioned_docs/version-3.0.0/command-reference/json-output.md
  docs/website/versioned_docs/version-3.0.0/command-reference/list-binding.md
  pkg/api/binding.go
  pkg/api/list.go
  pkg/binding/add.go
  pkg/binding/binding.go
  pkg/binding/binding_test.go
  pkg/binding/interface.go
  pkg/binding/list.go
  pkg/binding/list_test.go
  pkg/binding/mock.go
  pkg/kclient/binding.go
  pkg/kclient/interface.go
  pkg/kclient/mock_Client.go
  pkg/kclient/operators.go
  pkg/odo/cli/list/binding/binding.go
  pkg/odo/cli/list/list.go
  pkg/odo/cli/ui/table.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/genericclioptions/context_test.go
  pkg/odo/genericclioptions/errors.go
  tests/examples/source/devfiles/nodejs/devfile-with-service-binding-files.yaml
  tests/integration/devfile/cmd_describe_binding_test.go
  tests/integration/devfile/cmd_describe_list_binding_test.go
Labels: approved, lgtm, kind/feature

#5813 When typing odo foobar --help should error out with invalid command
  pkg/odo/cli/cli.go
  tests/integration/generic_test.go
Labels: kind/bug, approved, lgtm

#5851 Check if all Pods are running in odo logs tests
  tests/integration/devfile/cmd_logs_test.go
Labels: approved, lgtm, kind/tests

#5853 Remove odo preference registry update command
  docs/website/versioned_docs/version-3.0.0/overview/configure.md
  pkg/odo/cli/preference/registry/registry.go
  pkg/odo/cli/preference/registry/update.go
  pkg/registry/registry.go
  tests/helper/helper_generic.go
  tests/integration/devfile/cmd_devfile_registry_test.go
Labels: approved, lgtm

#5861 Install script for operators on Kubernetes + Activate tests with operatoes on Kubernetes
  scripts/ansible/kubernetes-cluster/README.md
  scripts/ansible/kubernetes-cluster/operators-kubernetes.yml
  scripts/ansible/kubernetes-cluster/operators-openshift.yml
  tests/integration/devfile/cmd_add_binding_test.go
  tests/integration/devfile/cmd_describe_list_binding_test.go
Labels: approved, lgtm, kind/feature

#5864 Add DCO documentation
  CONTRIBUTING.md
  DCO
Labels: approved, lgtm

#5822 Preference cleanup (1/n)
  go.mod
  go.sum
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/kclient/pods_test.go
  pkg/odo/cli/preference/set.go
  pkg/odo/cli/preference/unset.go
  pkg/odo/cli/preference/unset_test.go
  pkg/odo/cli/preference/view_test.go
  pkg/odo/cli/version/version.go
  pkg/preference/errors.go
  pkg/preference/implem.go
  pkg/preference/implem_test.go
  pkg/preference/mock.go
  pkg/preference/preference.go
  pkg/preference/variables.go
  pkg/util/defaults.go
  tests/helper/helper_filesystem.go
  tests/integration/cmd_pref_config_test.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/modules.txt
Labels: approved, lgtm

#5855 Add missing documentation on SBO installation
  docs/website/versioned_docs/version-3.0.0/command-reference/add-binding.md
  docs/website/versioned_docs/version-3.0.0/overview/cluster-setup/kubernetes.md
  docs/website/versioned_docs/version-3.0.0/overview/cluster-setup/openshift.md
Labels: approved, lgtm, kind/documentation

#5858 odo add binding without devfile.yaml
  docs/website/versioned_docs/version-3.0.0/command-reference/add-binding.md
  pkg/binding/add.go
  pkg/binding/asker/interface.go
  pkg/binding/asker/survey_asker.go
  pkg/binding/backend/flags.go
  pkg/binding/backend/interactive.go
  pkg/binding/backend/interface.go
  pkg/binding/backend/mock.go
  pkg/binding/binding.go
  pkg/binding/binding_test.go
  pkg/binding/interface.go
  pkg/binding/list_test.go
  pkg/binding/mock.go
  pkg/kclient/binding.go
  pkg/kclient/deployments.go
  pkg/kclient/interface.go
  pkg/kclient/kclient.go
  pkg/kclient/mock_Client.go
  pkg/kclient/operators.go
  pkg/odo/cli/add/binding/binding.go
  pkg/preference/mock.go
  pkg/service/link.go
  tests/integration/devfile/cmd_add_binding_test.go
  tests/interactive/cmd_add_binding_test.go
Labels: approved, lgtm, kind/feature

#5850 Update preference view to show list of devfile registries
  docs/website/versioned_docs/version-3.0.0/command-reference/registry.md
  pkg/odo/cli/init/init.go
  pkg/odo/cli/preference/registry/list.go
  pkg/odo/cli/preference/registry/registry.go
  pkg/odo/cli/preference/view.go
  pkg/odo/cli/preference/view_test.go
  tests/helper/odo_utils.go
  tests/integration/devfile/cmd_devfile_registry_test.go
Labels: approved, lgtm, kind/feature

#5878 Add `run-command` flag to `odo dev` to run non-default Run command
  docs/website/docs/command-reference/dev.md
  pkg/dev/dev.go
  pkg/dev/interface.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/libdevfile/errors.go
  pkg/libdevfile/libdevfile.go
  pkg/libdevfile/libdevfile_test.go
  pkg/odo/cli/dev/dev.go
  tests/examples/source/devfiles/nodejs/devfile-with-two-run-commands.yaml
  tests/helper/helper_dev.go
  tests/integration/devfile/cmd_dev_test.go
  tests/interactive/cmd_deploy_test.go
Labels: approved, lgtm, kind/feature, area/dev

#5837 Eventually list namespaces for test
  tests/integration/cmd_namespace_test.go
Labels: approved, lgtm, kind/tests

#5891 Add `build-command` flag to `odo dev` to run non-default Build command
  docs/website/docs/command-reference/dev.md
  pkg/dev/dev.go
  pkg/dev/interface.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/libdevfile/libdevfile.go
  pkg/libdevfile/libdevfile_test.go
  pkg/odo/cli/dev/dev.go
  tests/examples/source/devfiles/nodejs/devfile-with-alternative-commands.yaml
  tests/integration/devfile/cmd_dev_test.go
Labels: approved, lgtm, kind/feature, area/dev

#5887 Fix misleading add binding error message
  pkg/binding/binding.go
  pkg/binding/binding_test.go
  pkg/kclient/binding.go
Labels: kind/bug, approved, lgtm

#5827 Enable Dependabot
  .github/dependabot.yml
Labels: approved, lgtm, area/dependency

#5903 Bump to version v3.0.0-beta1
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm
