Repository redhat-developer/odo, pull requests merged in 2022-01, with the labels that each got.

#5309 refactor devfile test test
  tests/integration/devfile/cmd_devfile_test_test.go
Labels: approved, lgtm, kind/cleanup, kind/tests

#5293 Separate layers - Application + Project
  pkg/application/application.go
  pkg/application/application_test.go
  pkg/application/kubernetes.go
  pkg/application/kubernetes_test.go
  pkg/application/mock.go
  pkg/application/types.go
  pkg/kclient/deployments_test.go
  pkg/kclient/kclient_test.go
  pkg/odo/cli/application/application.go
  pkg/odo/cli/application/delete.go
  pkg/odo/cli/application/delete_test.go
  pkg/odo/cli/application/describe.go
  pkg/odo/cli/application/describe_test.go
  pkg/odo/cli/application/list.go
  pkg/odo/cli/application/list_test.go
  pkg/odo/cli/component/common_push.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/config/set.go
  pkg/odo/cli/config/unset.go
  pkg/odo/cli/project/create.go
  pkg/odo/cli/project/create_test.go
  pkg/odo/cli/project/delete.go
  pkg/odo/cli/project/delete_test.go
  pkg/odo/cli/project/list.go
  pkg/odo/cli/project/set.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/delete.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/genericclioptions/context_test.go
  pkg/odo/util/completion/completionhandlers.go
  pkg/odo/util/flag.go
  pkg/project/kubernetes.go
  pkg/project/kubernetes_test.go
  pkg/project/mock.go
  pkg/project/project.go
  pkg/util/util.go
  pkg/util/util_test.go
  scripts/mockgen.sh
Labels: approved, lgtm, kind/cleanup

#5295 Remove scripts which are no longer in use
  scripts/create-packages.sh
  scripts/k8sibmc-all-tests.sh
  scripts/k8sibmc-setup-env.sh
  scripts/minici-presubmit-all-tests.sh
  scripts/minikube-minishift-all-tests.sh
  scripts/minikube-minishift-setup-env.sh
  scripts/minishift-start-if-required.sh
  scripts/oc-cluster.sh
  scripts/run_all_tests.sh
  scripts/supported-311-is.sh
  scripts/sync-docs.sh
  scripts/travis-check-pods.sh
  scripts/upload-packages.sh
  tests/integration/project/cmd_project_test.go
Labels: approved, lgtm, kind/cleanup

#5294 Allow odo deploy without envfile
  pkg/odo/cli/component/common_push.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/cmdline/cobra.go
  tests/integration/devfile/cmd_devfile_deploy_test.go
Labels: kind/bug, approved, lgtm

#5296 Separate layers : Preference
  cmd/odo/odo.go
  go.mod
  pkg/catalog/catalog.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/devfile/adapters/helper.go
  pkg/devfile/adapters/helper_test.go
  pkg/devfile/adapters/kubernetes/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/component/podwatcher_test.go
  pkg/devfile/adapters/kubernetes/component/status_test.go
  pkg/devfile/adapters/kubernetes/storage/utils.go
  pkg/kclient/interface.go
  pkg/kclient/mock_Client.go
  pkg/kclient/oc_server.go
  pkg/kclient/pods.go
  pkg/kclient/pods_test.go
  pkg/odo/cli/component/common_push.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/create_methods.go
  pkg/odo/cli/component/push.go
  pkg/odo/cli/config/set.go
  pkg/odo/cli/config/unset.go
  pkg/odo/cli/preference/set.go
  pkg/odo/cli/preference/set_test.go
  pkg/odo/cli/preference/unset.go
  pkg/odo/cli/preference/unset_test.go
  pkg/odo/cli/preference/view.go
  pkg/odo/cli/preference/view_test.go
  pkg/odo/cli/registry/add.go
  pkg/odo/cli/registry/delete.go
  pkg/odo/cli/registry/list.go
  pkg/odo/cli/registry/update.go
  pkg/odo/cli/registry/util/util.go
  pkg/odo/cli/registry/util/util_test.go
  pkg/odo/cli/telemetry/telemetry.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/delete.go
  pkg/odo/cli/version/version.go
  pkg/odo/genericclioptions/runnable.go
  pkg/preference/implem.go
  pkg/preference/implem_test.go
  pkg/preference/machine_output.go
  pkg/preference/mock.go
  pkg/preference/preference.go
  pkg/preference/variables.go
  pkg/segment/integrations.go
  pkg/segment/integrations_test.go
  pkg/segment/segment.go
  pkg/segment/segment_test.go
  pkg/testingutil/configs.go
  pkg/testingutil/configs_test.go
  scripts/mockgen.sh
  tests/helper/helper_generic.go
  vendor/modules.txt
Labels: approved, lgtm, kind/cleanup

#5326 bump to v2.5.0
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#5327 fix wrong path in rpm SPEC
  rpms/openshift-odo.spec
Labels: approved, lgtm

#5349 add blog post about 2.5.0 release
  docs/website/blog/2022-01-14-odo-v2.5.0.md
Labels: kind/documentation

#5351 Add myself to OWNERS group
  OWNERS
  docs/OWNERS
  docs/website/OWNERS
Labels: approved, lgtm, kind/documentation

#5352 Updates .github/PULL_REQUEST_TEMPLATE.md with new information
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, kind/documentation

#5353 Updates incorrect link
  docs/website/README.md
Labels: approved, lgtm, kind/documentation

#5350 fix typos and style in 2.5.0 blog post
  docs/website/blog/2022-01-14-odo-v2.5.0.md
Labels: approved, lgtm, kind/documentation

#5354 add namespace in configure-installer-tests-cluster-s390x.sh
  scripts/configure-installer-tests-cluster-s390x.sh
Labels: approved, lgtm, needs-ok-to-test, area/System-PZ

#5315 odo push recreates the pod if scaled to 0
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/kclient/pods.go
  tests/helper/helper_cli.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: kind/bug, approved, lgtm

#5356 blog post for 2.5.0 - add video recording
  docs/website/blog/2022-01-14-odo-v2.5.0.md
Labels: approved, lgtm

#5342 Move envvar to specific package
  pkg/component/devfile_repr.go
  pkg/config/env_var.go
  pkg/config/env_var_test.go
  pkg/envvar/env_var.go
  pkg/envvar/env_var_test.go
  pkg/odo/cli/config/set.go
  tests/integration/cmd_pref_config_test.go
Labels: approved, lgtm, kind/cleanup

#5340 Add more verbosity to undeploy
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/component_kubernetes.go
  pkg/devfile/adapters/kubernetes/component/errors.go
  pkg/log/status.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/service/create.go
  tests/integration/devfile/cmd_devfile_delete_test.go
Labels: kind/bug, approved, lgtm

#5365 [v2 cherrypicking] Undeploy error
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/component_kubernetes.go
  pkg/devfile/adapters/kubernetes/component/errors.go
  pkg/log/status.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/service/create.go
  tests/integration/devfile/cmd_devfile_delete_test.go
Labels: kind/bug

#5364 odo.dev: reorder getting-started section
  docs/website/docs/getting-started/basics.md
  docs/website/docs/getting-started/features.md
  docs/website/docs/getting-started/installation.md
  docs/website/docs/getting-started/quickstart.md
Labels: approved, lgtm, kind/documentation

#5367 Updates blog posts
  docs/website/blog/2020-09-24-odo-v2.0.0-ga-release.md
  docs/website/blog/2020-10-28-odo-v2.0.1-release.md
  docs/website/blog/2021-05-04-odo-v2.2.0-breaking-changes.md
  docs/website/blog/2021-12-14-odo-v2.4.3.md
  docs/website/blog/2022-01-14-odo-v2.5.0.md
Labels: approved, lgtm, kind/documentation

#5369 Update concept page
  docs/website/docs/getting-started/basics.md
Labels: approved, lgtm, kind/documentation

#5373 Updates logo for odo
  docs/website/docusaurus.config.js
  docs/website/src/pages/index.module.css
  docs/website/static/img/docusaurus.png
  docs/website/static/img/favicon.ico
  docs/website/static/img/logo.
  docs/website/static/img/logo.png
  docs/website/static/img/logo.svg
  docs/website/static/img/logo_dark.png
  docs/website/static/img/logo_final.png
  docs/website/static/img/tutorial/docsVersionDropdown.png
  docs/website/static/img/tutorial/localeDropdown.png
  docs/website/static/img/undraw_docusaurus_mountain.svg
  docs/website/static/img/undraw_docusaurus_react.svg
  docs/website/static/img/undraw_docusaurus_tree.svg
Labels: approved

#5372 Update Cluster Setup documentation
  docs/website/docs/getting-started/cluster-setup/kubernetes.md
  docs/website/docs/getting-started/cluster-setup/openshift.md
Labels: approved, lgtm, kind/documentation

#5355 split unit test into unit test and validate test
  .ibm/pipelines/unit-tests.sh
  .ibm/pipelines/validate.sh
Labels: approved, lgtm, kind/tests

#5371 Update installation page
  docs/website/docs/getting-started/installation.md
Labels: approved, lgtm, kind/documentation

#5374 odo init reference doc
  docs/website/docs/command-reference/delete.md
  docs/website/docs/command-reference/deploy.md
  docs/website/docs/command-reference/init.md
  docs/website/docs/command-reference/link.md
  docs/website/docs/command-reference/registry.md
  docs/website/docs/command-reference/service.md
  docs/website/docs/command-reference/storage.md
Labels: approved, lgtm, kind/documentation

#5323 Refactor test-cmd-devfile-debug
  tests/integration/devfile/cmd_devfile_debug_test.go
Labels: approved, lgtm, kind/tests

#5381 update website dependencies
  docs/website/package-lock.json
Labels: approved, lgtm, kind/cleanup

#5368 Updates introduction documentation
  docs/website/docs/getting-started/features.md
  docs/website/docs/intro.md
Labels: approved, lgtm, kind/documentation

#5398 Updated node-forge from 0.10.0 to 1.0.0
  docs/website/package-lock.json
  docs/website/package.json
Labels: approved, lgtm

#5394 Add --hostname alias to odo url create
  pkg/odo/cli/url/create.go
Labels: approved, lgtm, kind/feature

#5378 Fix sonarcloud
  .github/workflows/build.yml
  sonar-project.properties
Labels: approved, lgtm, kind/tests

#5363 Add server flag to odo login
  pkg/auth/interface.go
  pkg/auth/login.go
  pkg/auth/mock.go
  pkg/odo/cli/login/login.go
  pkg/odo/cli/login/login_test.go
  scripts/mockgen.sh
Labels: kind/bug, approved, lgtm

#5404 Fix odo describe panic without the context directory
  pkg/component/component_full_description.go
  pkg/envinfo/storage.go
  pkg/storage/kubernetes.go
  pkg/storage/kubernetes_test.go
  pkg/url/kubernetes.go
  pkg/url/kubernetes_test.go
  pkg/url/status_test.go
  tests/integration/devfile/cmd_devfile_describe_test.go
Labels: kind/bug, approved, lgtm
