Repository redhat-developer/odo, pull requests merged in 2022-11, with the labels that each got.

#6251 Make 'pkg/logs' platform-agnostic
  pkg/component/component.go
  pkg/component/exec_handler.go
  pkg/exec/exec_test.go
  pkg/kclient/all.go
  pkg/kclient/deployments.go
  pkg/kclient/interface.go
  pkg/kclient/mock_Client.go
  pkg/kclient/pods.go
  pkg/kclient/pods_test.go
  pkg/logs/logs.go
  pkg/logs/logs_test.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/platform/doc.go
  pkg/platform/interface.go
Labels: approved, lgtm, kind/code-refactoring, kind/task

#6265 display equivalent odo init command for odo init interactive
  pkg/init/init.go
  pkg/init/interface.go
  pkg/init/mock.go
  pkg/odo/cli/init/init.go
  tests/integration/interactive_init_test.go
Labels: approved, lgtm, kind/feature

#6266 resolve inconsistent order of registries in preference view
  pkg/odo/cli/preference/view.go
  pkg/preference/implem.go
  pkg/registry/registry_test.go
  tests/integration/cmd_devfile_registry_test.go
Labels: kind/bug, approved, lgtm

#6290 Disable loading a single branch when getting git starter project
  pkg/registry/starter_project.go
  tests/examples/source/devfiles/java/devfile-with-git-main-branch.yaml
  tests/integration/cmd_devfile_init_test.go
Labels: kind/bug, approved, lgtm

#6292 Change expecations to match reality
  tests/integration/cmd_devfile_init_test.go
Labels: approved, lgtm, kind/tests

#6166 Update odo to use go 1.18
  .ibm/images/Dockerfile
  Dockerfile.rhel
  Makefile
  go.mod
  go.sum
  openshift-ci/build-root/Dockerfile
  pkg/api/component.go
  pkg/devfile/image/docker_compatible.go
  pkg/devfile/location/location.go
  pkg/kclient/fakeclient.go
  pkg/libdevfile/libdevfile.go
  pkg/log/status.go
  pkg/odo/cli/create/namespace/namespace.go
  pkg/odo/cli/delete/namespace/namespace.go
  pkg/odo/util/cmdutils.go
  pkg/storage/storage.go
  pkg/util/util_test.go
  scripts/rpm-prepare.sh
  tests/helper/helper_telemetry.go
  tests/integration/cmd_namespace_test.go
  vendor/golang.org/x/text/cases/cases.go
  vendor/golang.org/x/text/cases/context.go
  vendor/golang.org/x/text/cases/fold.go
  vendor/golang.org/x/text/cases/icu.go
  vendor/golang.org/x/text/cases/info.go
  vendor/golang.org/x/text/cases/map.go
  vendor/golang.org/x/text/cases/tables10.0.0.go
  vendor/golang.org/x/text/cases/tables11.0.0.go
  vendor/golang.org/x/text/cases/tables12.0.0.go
  vendor/golang.org/x/text/cases/tables13.0.0.go
  vendor/golang.org/x/text/cases/tables9.0.0.go
  vendor/golang.org/x/text/cases/trieval.go
  vendor/golang.org/x/text/internal/internal.go
  vendor/golang.org/x/text/internal/match.go
  vendor/modules.txt
Labels: approved, lgtm, kind/feature

#6288 fix login failure on interop tests with error: x509
  scripts/openshiftci-Nightly-SBO-tests.sh
  scripts/openshiftci-periodic-tests.sh
  scripts/openshiftci-presubmit-all-tests.sh
Labels: kind/bug, approved, lgtm, kind/tests

#6306 Add YouTube link to docs footer
  docs/website/docusaurus.config.js
Labels: approved, lgtm, area/documentation

#6300 Add support for an experimental mode
  docs/website/docs/overview/configure.md
  docs/website/docs/user-guides/advanced/experimental-mode.md
  pkg/log/status.go
  pkg/odo/cli/feature/doc.go
  pkg/odo/cli/feature/experimental.go
  pkg/odo/cli/feature/features.go
  pkg/odo/cli/feature/features_test.go
  pkg/odo/commonflags/main_test.go
  pkg/odo/commonflags/run_on.go
  tests/helper/helper_experimental.go
  tests/integration/generic_test.go
Labels: approved, lgtm, kind/feature

#6311 Debug validate errors on IBM Cloud
  Makefile
Labels: approved, lgtm

#6309 Build and push .ibm/images/Dockerfile image
  .github/workflows/build-push-ibm-image.yaml
  .ibm/images/README
Labels: area/testing, approved, lgtm, kind/tests

#6285 Remove localconfigLocalConfigProvider abstraction
  pkg/dev/dev.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/types.go
  pkg/envinfo/envinfo.go
  pkg/localConfigProvider/localConfigProvider.go
  pkg/localConfigProvider/mock_localConfigProvider.go
  pkg/odo/cli/delete/component/component_test.go
  pkg/odo/genericclioptions/localprovider.go
  pkg/storage/kubernetes_test.go
  pkg/storage/list.go
  pkg/storage/list_test.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  pkg/storage/utils.go
  pkg/watch/watch.go
  scripts/mockgen.sh
Labels: approved, lgtm, kind/code-refactoring, area/odo-on-podman

#6289 fix to prioritize newly added registry
  pkg/init/backend/flags.go
  pkg/init/backend/flags_test.go
  pkg/init/init.go
  pkg/init/init_test.go
  pkg/odo/cli/preference/view.go
  pkg/odo/cli/preference/view_test.go
  pkg/preference/implem.go
  pkg/preference/mock.go
  pkg/preference/preference.go
  pkg/registry/registry.go
  pkg/registry/registry_test.go
  pkg/registry/utils.go
Labels: kind/bug, approved, lgtm

#6307 InterOP: enable test report generation for tests
  .gitignore
  Makefile
  scripts/openshiftci-presubmit-all-tests.sh
Labels: approved, lgtm, kind/tests

#6295 Adds ability to list namespaces in JSON format
  docs/website/docs/command-reference/json-output.md
  pkg/api/list.go
  pkg/api/project.go
  pkg/odo/cli/list/namespace/namespace.go
  tests/integration/cmd_namespace_test.go
Labels: approved, lgtm, kind/feature

#6244 List Routes/Ingresses created by `odo deploy` in `odo describe component`
  docs/website/docs/command-reference/describe-component.md
  docs/website/docs/command-reference/json-output.md
  pkg/alizer/alizer_test.go
  pkg/api/component.go
  pkg/binding/backend/interactive.go
  pkg/binding/binding.go
  pkg/binding/binding_test.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/kclient/binding.go
  pkg/kclient/dynamic.go
  pkg/kclient/ingress_routes.go
  pkg/kclient/interface.go
  pkg/kclient/mock_Client.go
  pkg/odo/cli/describe/component.go
  pkg/service/service.go
  tests/e2escenarios/e2e_test.go
  tests/examples/source/devfiles/nodejs/devfile-deploy-defaultBackend-ingress.yaml
  tests/examples/source/devfiles/nodejs/devfile-deploy-ingress.yaml
  tests/examples/source/devfiles/nodejs/devfile-deploy-route.yaml
  tests/integration/cmd_describe_component_test.go
Labels: approved, lgtm, kind/feature

#6189 `odo dev` deletes remote resources not present in the Devfile
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/component/push.go
  pkg/devfile/components.go
  pkg/devfile/components_test.go
  pkg/kclient/secrets.go
  pkg/labels/labels.go
  pkg/service/link.go
  pkg/service/service.go
  tests/examples/source/devfiles/nodejs/devfile-with-k8s-resource.yaml
  tests/integration/cmd_add_binding_test.go
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
  tests/integration/cmd_remove_binding_test.go
Labels: kind/bug, approved, lgtm, area/dev

#6320 Remove Dharmit from OWNERS files across the repo
  OWNERS
  docs/OWNERS
  docs/website/OWNERS
  pkg/service/OWNERS
  tests/OWNERS
Labels: approved, lgtm

#6183 Podman dev
  docs/website/docs/user-guides/advanced/experimental-mode.md
  pkg/dev/common/common.go
  pkg/dev/common/common_test.go
  pkg/dev/interface.go
  pkg/dev/kubedev/cleanup.go
  pkg/dev/kubedev/kubedev.go
  pkg/dev/mock.go
  pkg/dev/podmandev/cleanup.go
  pkg/dev/podmandev/command.go
  pkg/dev/podmandev/pod.go
  pkg/dev/podmandev/pod_test.go
  pkg/dev/podmandev/podmandev.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/podman/exec.go
  pkg/podman/interface.go
  pkg/podman/logs.go
  pkg/podman/mock.go
  pkg/podman/podman.go
  pkg/podman/pods.go
  pkg/state/state.go
  pkg/sync/copy.go
  pkg/watch/interface.go
  pkg/watch/mock.go
  pkg/watch/watch.go
  scripts/mockgen.sh
Labels: approved, lgtm, kind/feature

#6323 Update odo describe output in docs
  docs/website/docs/user-guides/advanced/deploy/_accessing_application.mdx
  docs/website/docs/user-guides/advanced/deploy/_editing_devfile.mdx
  docs/website/docs/user-guides/advanced/deploy/_running_deploy.mdx
  docs/website/docs/user-guides/advanced/deploy/dotnet.md
  docs/website/docs/user-guides/advanced/deploy/go.md
  docs/website/docs/user-guides/advanced/deploy/java.md
  docs/website/docs/user-guides/advanced/deploy/nodejs.md
Labels: approved, lgtm, area/documentation

#6303 More tests without cluster
  .ibm/pipelines/windows-test-script.ps1
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/odo/cli/describe/component.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/list/component/list.go
  tests/e2escenarios/e2e_devfile_test.go
  tests/e2escenarios/e2e_test.go
  tests/helper/helper_generic.go
  tests/helper/labels.go
  tests/integration/cmd_add_binding_test.go
  tests/integration/cmd_analyze_test.go
  tests/integration/cmd_delete_test.go
  tests/integration/cmd_describe_component_test.go
  tests/integration/cmd_describe_list_binding_test.go
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
  tests/integration/cmd_devfile_build_images_test.go
  tests/integration/cmd_devfile_deploy_test.go
  tests/integration/cmd_devfile_init_test.go
  tests/integration/cmd_devfile_list_test.go
  tests/integration/cmd_devfile_registry_test.go
  tests/integration/cmd_list_services_test.go
  tests/integration/cmd_logs_test.go
  tests/integration/cmd_namespace_test.go
  tests/integration/cmd_pref_config_test.go
  tests/integration/cmd_remove_binding_test.go
  tests/integration/generic_test.go
  tests/integration/interactive_add_binding_test.go
  tests/integration/interactive_deploy_test.go
  tests/integration/interactive_dev_test.go
  tests/integration/interactive_init_test.go
Labels: approved, lgtm, kind/tests

#6310 check if bindable-kind instance is up before test
  tests/helper/helper_cli.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/cmd_add_binding_test.go
  tests/integration/cmd_describe_list_binding_test.go
  tests/integration/cmd_dev_test.go
  tests/integration/cmd_devfile_deploy_test.go
  tests/integration/cmd_list_services_test.go
  tests/integration/interactive_add_binding_test.go
Labels: area/testing, approved, lgtm, kind/tests

#6255 Implement `odo delete component --files` to delete files generated by `odo`
  docs/website/docs/command-reference/delete-component.md
  pkg/odo/cli/delete/component/component.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/files/files.go
  pkg/odo/cli/files/files_test.go
  pkg/odo/cli/init/init.go
  pkg/odo/genericclioptions/init.go
  pkg/util/file_indexer.go
  pkg/util/file_indexer_test.go
  pkg/util/util_test.go
  tests/integration/cmd_delete_test.go
  tests/integration/cmd_devfile_init_test.go
  tests/integration/interactive_init_test.go
Labels: approved, lgtm, kind/feature, area/component

#6325 Bump odo version to v3.3.0
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#6326 add anand to owner file as reviewer and approver
  OWNERS
Labels: approved, lgtm

#6329 Set labels for component on podman
  pkg/dev/podmandev/pod.go
  pkg/dev/podmandev/pod_test.go
Labels: approved, lgtm, kind/feature

#6324 Make remaining Quickstart docs consistent
  docs/website/docs/user-guides/quickstart/dotnet.md
  docs/website/docs/user-guides/quickstart/go.md
  docs/website/docs/user-guides/quickstart/nodejs.md
Labels: approved, lgtm, ok-to-test, kind/documentation, area/documentation

#6328 odo dev on podman: Add support for devfile volume
  pkg/dev/podmandev/pod.go
  pkg/dev/podmandev/pod_test.go
  pkg/libdevfile/generator/component.go
Labels: approved, lgtm, kind/feature

#6341 Disable flaky test on Windows
  tests/integration/interactive_init_test.go
Labels: approved, lgtm, kind/tests

#6344 Fix potential unit tests failures caused by envconfig relying on the system environment
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/segment/segment_test.go
Labels: kind/bug, area/testing, approved, lgtm

#6332 Integration tests for odo dev running on podman
  Makefile
  tests/e2escenarios/e2e_devfile_test.go
  tests/e2escenarios/e2e_test.go
  tests/helper/helper_dev.go
  tests/helper/labels.go
  tests/integration/cmd_add_binding_test.go
  tests/integration/cmd_delete_test.go
  tests/integration/cmd_describe_component_test.go
  tests/integration/cmd_describe_list_binding_test.go
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
  tests/integration/cmd_devfile_deploy_test.go
  tests/integration/cmd_devfile_list_test.go
  tests/integration/cmd_logs_test.go
  tests/integration/cmd_remove_binding_test.go
Labels: approved, lgtm, kind/tests

#6345 fix: add exit code check for no-cluster tests
  .ibm/pipelines/windows-test-script.ps1
Labels: kind/bug, approved, lgtm, kind/tests

#6346 Downloading wrong starter project when using `odo init`
  pkg/init/asker/asker.go
  pkg/init/backend/interactive.go
  tests/integration/interactive_init_test.go
Labels: kind/bug, approved, lgtm, area/init

#6073 E2e scenario 3
  Makefile
  tests/e2escenarios/e2e_test.go
  tests/examples/source/devfiles/go/cluster.yaml
  tests/examples/source/devfiles/go/go.mod
  tests/examples/source/devfiles/go/go.sum
  tests/examples/source/devfiles/go/main.go
  tests/examples/source/devfiles/go/middleware/handlers.go
  tests/examples/source/devfiles/go/models/models.go
  tests/examples/source/devfiles/go/router/router.go
Labels: approved, lgtm, kind/tests

#6356 Integration tests: Declare devfile volumes as ephemeral
  .ibm/pipelines/kubernetes-tests.sh
  tests/examples/source/devfiles/nodejs/devfile-with-volumes.yaml
  tests/examples/source/devfiles/springboot/devfile-registry.yaml
  tests/examples/source/devfiles/springboot/devfile-with-missing-projectType-and-language-metadata.yaml
  tests/examples/source/devfiles/springboot/devfile-with-missing-projectType-metadata.yaml
  tests/examples/source/devfiles/springboot/devfile.yaml
  tests/examples/source/java-quarkus/devfile.yaml
  tests/integration/cmd_dev_test.go
Labels: approved, lgtm, kind/tests

#6355 Fix flaky behavior with "list namespaces/projects -o json" integration tests
  tests/integration/cmd_namespace_test.go
Labels: kind/bug, area/testing, approved, lgtm

#6354 Fix completion error when command is empty
  pkg/odo/cli/list/namespace/namespace.go
Labels: kind/bug, approved, lgtm

#6359 Update build version and release blog post for v3.3.0
  build/VERSION
  docs/website/blog/2022-11-29-odo-v3.3.0.md
Labels: approved, lgtm, kind/feature, area/documentation

#6361 Update OWNERS
  OWNERS
Labels: lgtm

#6352 Do not call LogErrorAndExit but return err in GenericRun
  pkg/odo/cli/add/binding/binding.go
  pkg/odo/cli/alizer/alizer.go
  pkg/odo/cli/build_images/build_images.go
  pkg/odo/cli/create/namespace/namespace.go
  pkg/odo/cli/delete/component/component.go
  pkg/odo/cli/delete/namespace/namespace.go
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/cli/describe/binding.go
  pkg/odo/cli/describe/component.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/init/init.go
  pkg/odo/cli/list/binding/binding.go
  pkg/odo/cli/list/component/list.go
  pkg/odo/cli/list/list.go
  pkg/odo/cli/list/namespace/namespace.go
  pkg/odo/cli/list/services/services.go
  pkg/odo/cli/login/login.go
  pkg/odo/cli/logout/logout.go
  pkg/odo/cli/logs/logs.go
  pkg/odo/cli/preference/add/registry.go
  pkg/odo/cli/preference/remove/registry.go
  pkg/odo/cli/preference/set.go
  pkg/odo/cli/preference/unset.go
  pkg/odo/cli/preference/view.go
  pkg/odo/cli/registry/registry.go
  pkg/odo/cli/remove/binding/binding.go
  pkg/odo/cli/set/namespace/namespace.go
  pkg/odo/cli/telemetry/telemetry.go
  pkg/odo/cli/version/version.go
  pkg/odo/genericclioptions/runnable.go
Labels: approved, lgtm, kind/code-refactoring

#6360 Lower log level for kclient.GetAllResourcesFromSelector
  pkg/kclient/all.go
Labels: kind/bug, approved, lgtm

#6348 Sync files on Podman
  pkg/dev/kubedev/kubedev.go
  pkg/dev/podmandev/cleanup.go
  pkg/dev/podmandev/podmandev.go
  pkg/dev/podmandev/reconcile.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/watch/noop_watcher.go
  pkg/watch/watch.go
  tests/integration/cmd_dev_test.go
Labels: lgtm, kind/feature

#6358 Replace group by apiVersion in odo list services output
  docs/website/docs/command-reference/json-output.md
  docs/website/docs/command-reference/list-services.md
  pkg/api/bindable_service.go
  pkg/odo/cli/list/services/services.go
  tests/integration/cmd_list_services_test.go
Labels: kind/bug, approved, lgtm, release-note-action-required
