Repository redhat-developer/odo, pull requests merged in 2022-08, with the labels that each got.

#5976 Allow using remote Dockerfiles (HTTP(S) only) for building images
  docs/website/docs/command-reference/build-images.md
  docs/website/docs/command-reference/deploy.md
  pkg/deploy/deploy.go
  pkg/deploy/interface.go
  pkg/deploy/mock.go
  pkg/devfile/image/docker_compatible.go
  pkg/devfile/image/docker_compatible_test.go
  pkg/devfile/image/image.go
  pkg/devfile/image/image_test.go
  pkg/devfile/image/mock_Backend.go
  pkg/odo/cli/build_images/build_images.go
  pkg/odo/cli/deploy/deploy.go
  tests/integration/cmd_devfile_build_images_test.go
  tests/integration/cmd_devfile_deploy_test.go
Labels: approved, lgtm, kind/feature

#5992 update quickstart
  docs/website/docs/user-guides/quickstart.md
Labels: approved, lgtm, kind/documentation

#5686 add documenation for env variables used by odo
  docs/website/docs/overview/configure.md
Labels: approved, lgtm, kind/documentation

#5979 Remove $ symbol from some commands
  docs/website/docs/command-reference/create-namespace.md
  docs/website/docs/command-reference/delete-namespace.md
  docs/website/docs/command-reference/describe-binding.md
  docs/website/docs/command-reference/dev.md
  docs/website/docs/command-reference/init.md
  docs/website/docs/command-reference/json-output.md
  docs/website/docs/command-reference/list-binding.md
  docs/website/docs/command-reference/list-namespace.md
  docs/website/docs/command-reference/registry.md
  docs/website/docs/command-reference/remove-binding.md
  docs/website/docs/command-reference/set-namespace.md
  docs/website/docs/user-guides/quickstart.md
Labels: approved, lgtm, kind/documentation

#6001 Add more checks to check-fit.sh
  scripts/check-fit.sh
Labels: approved, lgtm, kind/tests

#6003 Adds link to inner loop to the Quickstart guide
  docs/website/docs/user-guides/quickstart.md
Labels: approved, lgtm, kind/documentation

#5995 Use devfile proxy for odo init --devfile-registry
  docs/website/docs/overview/configure.md
  tests/integration/cmd_devfile_registry_test.go
Labels: approved, lgtm, kind/tests

#6005 Use oceanicNext dark theme for website
  docs/website/docusaurus.config.js
Labels: approved, lgtm, kind/documentation, area/documentation

#5973 Fetch pods first; use channel instead of slice
  pkg/kclient/all.go
  pkg/kclient/deployments.go
  pkg/kclient/interface.go
  pkg/kclient/mock_Client.go
  pkg/kclient/pods.go
  pkg/logs/logs.go
  pkg/storage/mock_Client.go
Labels: kind/bug, approved, lgtm

#5933 odo dev: react to changes as soon as possible
  pkg/binding/binding.go
  pkg/binding/interface.go
  pkg/binding/mock.go
  pkg/component/component.go
  pkg/component/delete/delete.go
  pkg/component/delete/delete_test.go
  pkg/dev/dev.go
  pkg/dev/interface.go
  pkg/dev/mock.go
  pkg/devfile/adapters/errors.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/component/commandhandler.go
  pkg/devfile/adapters/kubernetes/component/interface.go
  pkg/devfile/adapters/kubernetes/component/push.go
  pkg/devfile/adapters/kubernetes/storage/utils.go
  pkg/devfile/adapters/types.go
  pkg/kclient/binding.go
  pkg/kclient/deployments.go
  pkg/kclient/dynamic.go
  pkg/kclient/events.go
  pkg/kclient/events_test.go
  pkg/kclient/interface.go
  pkg/kclient/mock_Client.go
  pkg/kclient/pods.go
  pkg/kclient/pods_test.go
  pkg/kclient/volumes.go
  pkg/kclient/volumes_test.go
  pkg/log/status.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/portForward/interface.go
  pkg/portForward/portForward.go
  pkg/service/link.go
  pkg/service/service.go
  pkg/util/file_indexer.go
  pkg/util/util.go
  pkg/watch/backo.go
  pkg/watch/interface.go
  pkg/watch/mock.go
  pkg/watch/pod_phases.go
  pkg/watch/status.go
  pkg/watch/watch.go
  pkg/watch/watch_test.go
  tests/examples/source/devfiles/nodejs/devfile-deploy-functional-pods.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-volume-components.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-volumes.yaml
  tests/helper/helper_dev.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_run.go
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
  tests/integration/cmd_logs_test.go
Labels: approved, lgtm, kind/feature

#6016 Bump odo version to v3.0.0-beta3
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#6006 Enhance error message when user runs from a non-component directory
  pkg/odo/genericclioptions/context_test.go
  pkg/odo/genericclioptions/localprovider.go
  tests/integration/cmd_delete_test.go
Labels: kind/bug, approved, lgtm

#6009 Document how odo works with projects/namespaces
  docs/website/docs/command-reference/create-namespace.md
  docs/website/docs/command-reference/delete-namespace.md
  docs/website/docs/command-reference/deploy.md
  docs/website/docs/command-reference/dev.md
  docs/website/docs/command-reference/set-namespace.md
  pkg/odo/cli/create/namespace/namespace.go
Labels: approved, lgtm, kind/documentation, area/documentation

#5923 `odo dev`: Add support for non-exec commands part of a composite run or debug command
  pkg/binding/binding.go
  pkg/component/component.go
  pkg/component/delete/delete.go
  pkg/component/delete/delete_test.go
  pkg/component/delete/interface.go
  pkg/deploy/deploy.go
  pkg/dev/dev.go
  pkg/dev/interface.go
  pkg/dev/mock.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/component/commandhandler.go
  pkg/devfile/adapters/kubernetes/component/push.go
  pkg/devfile/adapters/kubernetes/component/utils.go
  pkg/kclient/deployments.go
  pkg/kclient/deployments_test.go
  pkg/kclient/interface.go
  pkg/kclient/mock_Client.go
  pkg/kclient/services.go
  pkg/kclient/services_test.go
  pkg/kclient/volumes_test.go
  pkg/labels/constants.go
  pkg/labels/labels.go
  pkg/labels/labels_test.go
  pkg/logs/logs.go
  pkg/odo/cli/dev/dev.go
  pkg/service/link.go
  pkg/service/service.go
  pkg/storage/kubernetes.go
  pkg/storage/kubernetes_test.go
  pkg/storage/storage_test.go
  pkg/testingutil/deployments.go
  pkg/testingutil/pods.go
  pkg/testingutil/services.go
  pkg/watch/watch.go
  tests/e2escenarios/e2e_devfile_test.go
  tests/e2escenarios/e2e_test.go
  tests/examples/source/devfiles/nodejs/devfile-composite-apply-commands.yaml
  tests/helper/helper_dev.go
  tests/integration/cmd_add_binding_test.go
  tests/integration/cmd_delete_test.go
  tests/integration/cmd_describe_component_test.go
  tests/integration/cmd_describe_list_binding_test.go
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
  tests/integration/cmd_devfile_deploy_test.go
  tests/integration/cmd_devfile_list_test.go
  tests/integration/cmd_logs_test.go
Labels: approved, lgtm, kind/feature

#6008 Remove command: odo project
  pkg/auth/login.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/list/namespace/namespace.go
  pkg/odo/cli/project/create.go
  pkg/odo/cli/project/create_test.go
  pkg/odo/cli/project/delete.go
  pkg/odo/cli/project/delete_test.go
  pkg/odo/cli/project/get.go
  pkg/odo/cli/project/list.go
  pkg/odo/cli/project/project.go
  pkg/odo/cli/project/set.go
  pkg/segment/segment_test.go
  tests/helper/helper_oc.go
  tests/helper/odo_utils.go
  tests/integration/cmd_dev_test.go
  tests/integration/loginlogout/cmd_login_logout_test.go
Labels: kind/bug, approved, lgtm

#6013 Restart port forwarding on failure
  pkg/portForward/portForward.go
  tests/examples/source/devfiles/nodejs/devfile-composite-apply-commands.yaml
  tests/helper/helper_cli.go
  tests/helper/helper_dev.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/cmd_dev_test.go
Labels: kind/bug, approved, lgtm

#5972 Allow specifying message to end the spinner with
  pkg/devfile/adapters/kubernetes/component/commandhandler.go
  pkg/log/status.go
Labels: kind/bug, approved, lgtm

#6021 Fix: Non odo components not reported
  pkg/component/component.go
  pkg/component/component_test.go
  tests/examples/manifests/deployment-app-label.yaml
  tests/examples/manifests/deployment-without-managed-by-label.yaml
  tests/integration/cmd_devfile_list_test.go
Labels: kind/bug, approved, lgtm

#6024 odo dev: Cleanup after displaying the error
  pkg/odo/cli/dev/dev.go
  pkg/odo/genericclioptions/runnable.go
  pkg/odo/util/cmdutils.go
  pkg/watch/watch.go
  pkg/watch/watch_test.go
  tests/integration/cmd_dev_test.go
Labels: kind/bug, approved, lgtm

#6020 Watch for devfile dependencies
  pkg/libdevfile/generator/component.go
  pkg/libdevfile/testdata/child-devfile-commands-only.yaml
  pkg/libdevfile/testdata/child-devfile-complete.yaml
  pkg/libdevfile/testdata/child-devfile-components-only.yaml
  pkg/libdevfile/testdata/child-devfile.yaml
  pkg/libdevfile/testdata/parent/parent-devfile-commands-only.yaml
  pkg/libdevfile/testdata/parent/parent-devfile-components-only.yaml
  pkg/libdevfile/testdata/parent/parent-devfile-empty.yaml
  pkg/libdevfile/testdata/parent/parent-devfile.yaml
  pkg/libdevfile/uris.go
  pkg/libdevfile/uris_test.go
  pkg/watch/watch.go
  tests/examples/source/devfiles/nodejs/devfile-child.yaml
  tests/examples/source/devfiles/nodejs/devfile-parent.yaml
  tests/helper/helper_filesystem.go
  tests/integration/cmd_dev_test.go
Labels: kind/bug, approved, lgtm

#6019 Add blog post for v3.0.0-beta3 and update installation docs
  docs/website/blog/2022-08-18-odo-v3-beta3.md
  docs/website/docs/overview/installation.md
  docs/website/docusaurus.config.js
Labels: do-not-merge/hold, approved, lgtm, kind/documentation, area/documentation

#6035 Update site index page with lighter font
  docs/website/src/css/custom.css
Labels: approved, lgtm, kind/documentation

#6038 Troubleshoot IBM Cloud Windows tests failing
  tests/helper/helper_cmd_wrapper.go
Labels: approved, lgtm

#6037 test: use `T.Setenv` to set env vars in tests
  pkg/envinfo/envinfo_test.go
  pkg/odo/genericclioptions/context_test.go
  pkg/preference/implem_test.go
  pkg/registry/registry_test.go
  pkg/registry/utils_test.go
  pkg/segment/integrations_test.go
  pkg/segment/segment_test.go
Labels: approved, lgtm, ok-to-test

#6025 Do not get project from env.yaml file
  docs/website/docs/command-reference/create-namespace.md
  docs/website/docs/command-reference/delete-namespace.md
  docs/website/docs/command-reference/deploy.md
  docs/website/docs/command-reference/dev.md
  docs/website/docs/command-reference/set-namespace.md
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/envinfo/envinfo.go
  pkg/localConfigProvider/localConfigProvider.go
  pkg/odo/cli/delete/component/component.go
  pkg/odo/cli/delete/component/component_test.go
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/set/namespace/namespace.go
  pkg/odo/cmdline/cmdline.go
  pkg/odo/cmdline/cobra.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/genericclioptions/context_test.go
  pkg/odo/genericclioptions/errors.go
  pkg/odo/genericclioptions/localprovider.go
  pkg/odo/genericclioptions/resolve.go
  tests/integration/cmd_delete_test.go
  tests/integration/cmd_describe_component_test.go
  tests/integration/cmd_dev_test.go
  tests/integration/cmd_devfile_build_images_test.go
  tests/integration/cmd_devfile_deploy_test.go
  tests/integration/cmd_namespace_test.go
Labels: approved, lgtm, kind/feature

#6032 Add blog post for v3.0.0-beta3 and update installation docs
  docs/website/blog/2022-08-18-odo-v3-beta3.md
  docs/website/docs/overview/installation.md
Labels: approved, lgtm, kind/documentation, area/documentation

#5989 Autodetect project name via Alizer
  pkg/alizer/alizer.go
  pkg/alizer/alizer_test.go
  pkg/init/backend/alizer.go
  pkg/init/backend/interactive.go
  pkg/init/backend/interactive_test.go
  pkg/init/init.go
  tests/integration/interactive_init_test.go
Labels: approved, lgtm, kind/feature

#6031 Do not send userId to registry when ODO_DEBUG_TELEMETRY_FILE is set
  pkg/segment/integrations.go
  pkg/segment/integrations_test.go
Labels: kind/bug, approved, lgtm

#6048 deploymentExists different from component running
  pkg/devfile/adapters/kubernetes/component/adapter.go
  tests/examples/source/java-quarkus/.dockerignore
  tests/examples/source/java-quarkus/.gitignore
  tests/examples/source/java-quarkus/.mvn/wrapper/.gitignore
  tests/examples/source/java-quarkus/.mvn/wrapper/MavenWrapperDownloader.java
  tests/examples/source/java-quarkus/.mvn/wrapper/maven-wrapper.properties
  tests/examples/source/java-quarkus/README.md
  tests/examples/source/java-quarkus/devfile.yaml
  tests/examples/source/java-quarkus/mvnw
  tests/examples/source/java-quarkus/mvnw.cmd
  tests/examples/source/java-quarkus/pom.xml
  tests/examples/source/java-quarkus/src/main/docker/Dockerfile.jvm
  tests/examples/source/java-quarkus/src/main/docker/Dockerfile.legacy-jar
  tests/examples/source/java-quarkus/src/main/docker/Dockerfile.native
  tests/examples/source/java-quarkus/src/main/docker/Dockerfile.native-micro
  tests/examples/source/java-quarkus/src/main/java/org/acme/GreetingResource.java
  tests/examples/source/java-quarkus/src/main/java/org/acme/MyLivenessCheck.java
  tests/examples/source/java-quarkus/src/main/resources/META-INF/resources/index.html
  tests/examples/source/java-quarkus/src/main/resources/application.properties
  tests/examples/source/java-quarkus/src/test/java/org/acme/GreetingResourceIT.java
  tests/examples/source/java-quarkus/src/test/java/org/acme/GreetingResourceTest.java
  tests/helper/helper_dev.go
  tests/integration/cmd_dev_test.go
Labels: kind/bug, approved, lgtm

#6029 Fix: ServiceBinding resources are not deployed with odo deploy
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/commandhandler.go
  pkg/devfile/adapters/kubernetes/component/push.go
  pkg/service/link.go
  pkg/service/service.go
  tests/examples/source/devfiles/nodejs/devfile-deploy-with-SB.yaml
  tests/integration/cmd_devfile_deploy_test.go
Labels: kind/bug, approved, lgtm

#6055 Ignore notfound error on delete
  pkg/component/delete/delete.go
Labels: kind/bug, approved, lgtm

#6059 Update errors.go
  pkg/odo/genericclioptions/errors.go
Labels: kind/bug, approved, lgtm, ok-to-test

#6057 Do not use env.yaml file anymore
  docs/website/docs/command-reference/dev.md
  pkg/component/component.go
  pkg/dev/dev.go
  pkg/dev/mock.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils_test.go
  pkg/devfile/adapters/types.go
  pkg/envinfo/envinfo.go
  pkg/envinfo/envinfo_test.go
  pkg/envinfo/fake.go
  pkg/envinfo/types.go
  pkg/kclient/mock_Client.go
  pkg/localConfigProvider/localConfigProvider.go
  pkg/localConfigProvider/mock_localConfigProvider.go
  pkg/odo/cli/add/binding/binding.go
  pkg/odo/cli/delete/component/component_test.go
  pkg/odo/cli/describe/binding.go
  pkg/odo/cli/describe/component.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/list/binding/binding.go
  pkg/odo/cli/remove/binding/binding.go
  pkg/odo/cmdline/mock.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/genericclioptions/context_test.go
  pkg/odo/genericclioptions/resolve.go
  pkg/odo/util/flag.go
  pkg/storage/kubernetes_test.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  pkg/util/file_indexer.go
  pkg/util/file_indexer_test.go
  pkg/watch/watch.go
  tests/examples/source/devfiles/nodejs/devfile-composite-apply-commands.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-debugrun.yaml
  tests/examples/source/devfiles/nodejs/devfileCompositeBuildRunDebugInMultiContainersAndSharedVolume.yaml
  tests/examples/source/devfiles/nodejs/devfileCompositeRunAndDebug.yaml
  tests/examples/source/devfiles/nodejs/project/package.json
  tests/integration/cmd_delete_test.go
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
  tests/integration/cmd_namespace_test.go
Labels: kind/bug, approved, lgtm

#6004 fix flake and use operatorhub to install EDB
  .ibm/pipelines/windows-test-script.ps1
  .ibm/pipelines/windows-test.sh
  Makefile
  scripts/configure-cluster/common/setup-operators.sh
  scripts/openshiftci-presubmit-all-tests.sh
  tests/helper/helper_oc.go
  tests/integration/interactive_add_binding_test.go
Labels: approved, lgtm, kind/tests

#6015 Make odo work if optional `metadata.name` field is missing in Devfile
  pkg/binding/add.go
  pkg/binding/binding_test.go
  pkg/binding/interface.go
  pkg/binding/mock.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/delete/delete.go
  pkg/component/delete/delete_test.go
  pkg/component/delete/interface.go
  pkg/component/delete/mock.go
  pkg/deploy/deploy.go
  pkg/deploy/interface.go
  pkg/deploy/mock.go
  pkg/dev/dev.go
  pkg/dev/interface.go
  pkg/dev/mock.go
  pkg/devfile/adapters/kubernetes/component/commandhandler.go
  pkg/odo/cli/add/binding/binding.go
  pkg/odo/cli/delete/component/component.go
  pkg/odo/cli/delete/component/component_test.go
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/cli/describe/component.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/list/component/list.go
  pkg/odo/cli/list/list.go
  pkg/odo/cli/logs/logs.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/genericclioptions/context_test.go
  pkg/registry/registry.go
  pkg/registry/starter_project.go
  pkg/watch/interface.go
  pkg/watch/mock.go
  pkg/watch/watch.go
  tests/examples/source/devfiles/nodejs/devfile-no-metadata-name.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-service-binding-files.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-volume-components.yaml
  tests/helper/helper_filesystem.go
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
Labels: approved, lgtm, kind/feature

#6063 Update script to support alpha/beta/rc versions
  scripts/bump-version.sh
Labels: approved, lgtm

#6064 Bump to version 3.0.0-rc1
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm
