Repository redhat-developer/odo, pull requests merged in 2022-02, with the labels that each got.

#5400 Updates the quickstart and cluster setup guides
  docs/website/docs/getting-started/cluster-setup/kubernetes.md
  docs/website/docs/getting-started/cluster-setup/openshift.md
  docs/website/docs/getting-started/quickstart.md
  docs/website/src/pages/index.tsx
Labels: approved, lgtm

#5415 remove github action for sonar cloud
  .github/workflows/build.yml
Labels: approved, lgtm

#5414 More inline help for odo init
  pkg/odo/cli/init/init.go
  pkg/odo/cli/init/params/types.go
Labels: kind/bug, approved, lgtm

#5426 Fix quickstart link on the site
  docs/website/src/pages/index.tsx
Labels: approved, lgtm, kind/documentation

#5318 Preserving devfile provided by starter project
  docs/website/docs/command-reference/create.md
  pkg/odo/cli/component/create.go
  tests/examples/source/devfiles/nodejs/devfile-with-starter-with-devfile.yaml
  tests/integration/devfile/cmd_devfile_create_test.go
Labels: approved, lgtm, kind/feature

#5429 Fix odo running OC specific tests in K8s env
  tests/integration/cmd_pref_config_test.go
Labels: kind/bug, approved, lgtm, kind/tests

#5431 Adds ASCII logo to --help / removes oc references
  pkg/odo/cli/cli.go
Labels: approved, lgtm, kind/cleanup

#5436 Fix main branch
  build/VERSION
Labels: approved, lgtm

#5437 Move sonar-project.properties to .sonarcloud.properties
  .sonarcloud.properties
Labels: approved, lgtm, kind/cleanup

#5440 minor changes to use service IDs and clusters in the Developer QE account
  .ibm/pipelines/kubernetes-tests.sh
  .ibm/pipelines/openshift-tests.sh
Labels: approved, lgtm, kind/tests

#5443 Corrects `VersionFetchURL` variable and `build/VERSION` file
  build/VERSION
  pkg/odo/cli/version/notify.go
Labels: kind/bug, approved, lgtm

#5407 Add duplicate port validation, update devfile libraries, and add tests to check port name matches endpoint name
  go.mod
  go.sum
  pkg/envinfo/url.go
  pkg/envinfo/url_test.go
  tests/integration/devfile/cmd_devfile_delete_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
  vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/commands.go
  vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/component_image.go
  vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/component_kubernetes_like.go
  vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/devfile.go
  vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/endpoint.go
  vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/zz_generated.deepcopy.go
  vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/zz_generated.getters.go
  vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/zz_generated.parent_overrides.go
  vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/zz_generated.plugin_overrides.go
  vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/zz_generated.union_definitions.go
  vendor/github.com/devfile/api/v2/pkg/validation/endpoints.go
  vendor/github.com/devfile/api/v2/pkg/validation/errors.go
  vendor/github.com/devfile/api/v2/pkg/validation/validation-rule.md
  vendor/github.com/devfile/library/pkg/devfile/generator/utils.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/2.2.0/devfileJsonSchema220.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/commands.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/common/options.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/components.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/projects.go
  vendor/github.com/devfile/library/pkg/devfile/parser/parse.go
  vendor/github.com/devfile/library/pkg/testingutil/devfile.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm

#5417 fix comment override for windows test
  .ibm/pipelines/windows-test.sh
Labels: approved, lgtm, kind/tests

#5428 Odo v3: Move odo registry to odo preference registry, remove unused pref. settings
  USAGE_DATA.md
  docs/website/docs/getting-started/configure.md
  docs/website/docs/tutorials/deploying-java-app-with-database.md
  pkg/catalog/catalog.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/starter_project.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/create_methods.go
  pkg/odo/cli/preference/preference.go
  pkg/odo/cli/preference/registry/add.go
  pkg/odo/cli/preference/registry/consts/consts.go
  pkg/odo/cli/preference/registry/delete.go
  pkg/odo/cli/preference/registry/list.go
  pkg/odo/cli/preference/registry/registry.go
  pkg/odo/cli/preference/registry/update.go
  pkg/odo/cli/preference/registry/util/util.go
  pkg/odo/cli/preference/registry/util/util_test.go
  pkg/odo/cli/preference/set.go
  pkg/odo/cli/preference/unset.go
  pkg/odo/cli/preference/view.go
  pkg/odo/cli/preference/view_test.go
  pkg/preference/implem.go
  pkg/preference/implem_test.go
  pkg/preference/machine_output.go
  pkg/preference/mock.go
  pkg/preference/preference.go
  pkg/preference/variables.go
  pkg/segment/integrations.go
  tests/helper/helper_generic.go
  tests/integration/cmd_pref_config_test.go
  tests/integration/devfile/cmd_devfile_catalog_test.go
  tests/integration/devfile/cmd_devfile_registry_test.go
Labels: approved, lgtm, kind/feature

#5434 Refactor odo init to make parts reusable by odo dev/deploy
  pkg/catalog/catalog.go
  pkg/catalog/interface.go
  pkg/catalog/mock_catalog.go
  pkg/init/asker/asker.go
  pkg/init/asker/interface.go
  pkg/init/asker/mock.go
  pkg/init/backend/flags.go
  pkg/init/backend/flags_test.go
  pkg/init/backend/interactive.go
  pkg/init/backend/interactive_test.go
  pkg/init/backend/interface.go
  pkg/init/backend/mock.go
  pkg/init/backend/types.go
  pkg/init/init.go
  pkg/init/init_test.go
  pkg/init/interface.go
  pkg/init/mock.go
  pkg/init/registry/interface.go
  pkg/init/registry/registry.go
  pkg/odo/cli/init/asker/interface.go
  pkg/odo/cli/init/init.go
  pkg/odo/cli/init/init_test.go
  pkg/odo/cli/init/params/flags.go
  pkg/odo/cli/init/params/flags_test.go
  pkg/odo/cli/init/params/interactive.go
  pkg/odo/cli/init/params/interactive_test.go
  pkg/odo/cli/init/params/interface.go
  pkg/odo/cli/init/params/mock.go
  pkg/odo/cli/init/params/types.go
  pkg/odo/cli/init/params/types_test.go
  scripts/mockgen.sh
Labels: approved, lgtm, kind/cleanup

#5457 Use functions from devfile library
  go.mod
  pkg/catalog/catalog.go
  pkg/component/component.go
  pkg/devfile/adapters/common/command_test.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/storage/utils.go
  pkg/envinfo/envinfo.go
  pkg/envinfo/storage.go
  pkg/envinfo/storage_test.go
  pkg/init/backend/flags.go
  pkg/init/init.go
  pkg/init/registry/interface.go
  pkg/init/registry/mock.go
  pkg/init/registry/registry.go
  pkg/kclient/oc_server.go
  pkg/odo/cli/component/common_push.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/create_methods.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/component/watch.go
  pkg/odo/cli/preference/registry/add.go
  pkg/odo/cli/preference/registry/delete.go
  pkg/odo/cli/preference/registry/update.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/utils/terminal.go
  pkg/odo/cli/version/notify.go
  pkg/odo/cmdline/cobra.go
  pkg/odo/genericclioptions/util.go
  pkg/odo/util/validation/validators.go
  pkg/preference/implem.go
  pkg/segment/context/context.go
  pkg/service/service.go
  pkg/sync/adapter.go
  pkg/sync/sync.go
  pkg/url/kubernetes.go
  pkg/util/file_indexer.go
  pkg/util/httpcache.go
  pkg/util/httpcache_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  pkg/watch/watch.go
  pkg/watch/watch_test.go
  tests/helper/helper_filesystem.go
  tests/helper/helper_generic.go
  tests/helper/kubernetes_utils.go
  tests/integration/devfile/utils/utils.go
  vendor/modules.txt
Labels: approved, lgtm, kind/cleanup

#5413 Set replicas using devfile library
  go.mod
  go.sum
  pkg/devfile/adapters/kubernetes/component/adapter.go
  vendor/github.com/devfile/library/pkg/devfile/generator/generators.go
  vendor/github.com/devfile/library/pkg/devfile/generator/utils.go
  vendor/modules.txt
Labels: approved, lgtm, kind/cleanup

#5462 Update devfiles images document for s390x
  docs/website/docs/tutorials/deploying-a-devfile-using-odo-on-IBM-Z-and-Power.md
Labels: approved, lgtm, needs-ok-to-test, area/System-PZ

#5472 Remove registry command from top level commands
  pkg/odo/cli/cli.go
Labels: approved, lgtm

#5467 Personalize devfile
  go.mod
  go.sum
  pkg/init/asker/asker.go
  pkg/init/asker/interface.go
  pkg/init/asker/mock.go
  pkg/init/backend/alizer.go
  pkg/init/backend/flags.go
  pkg/init/backend/interactive.go
  pkg/init/backend/interactive_test.go
  pkg/init/backend/interface.go
  pkg/init/backend/mock.go
  pkg/init/init.go
  pkg/init/interface.go
  pkg/init/mock.go
  pkg/init/registry/mock.go
  pkg/odo/cli/init/init.go
  vendor/github.com/devfile/library/pkg/devfile/parser/configurables.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/interface.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/mock_interface.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/containers.go
  vendor/github.com/devfile/library/pkg/testingutil/filesystem/default_fs.go
  vendor/github.com/devfile/library/pkg/testingutil/filesystem/fake_fs.go
  vendor/github.com/devfile/library/pkg/testingutil/filesystem/filesystem.go
  vendor/github.com/devfile/library/pkg/testingutil/filesystem/singleton.go
  vendor/github.com/devfile/library/pkg/testingutil/filesystem/watcher.go
  vendor/modules.txt
Labels: approved, lgtm, kind/feature

#5490 update yaml URL when install postgreSQL on IBM Z and Power
  docs/website/docs/tutorials/deploying-java-app-with-database.md
Labels: approved, lgtm, ok-to-test

#5492 Add test for personalization options
  pkg/init/asker/asker_test.go
Labels: approved, lgtm, kind/tests

#5481 Non-default deploy commands do not break running the default one
  pkg/devfile/adapters/kubernetes/component/adapter.go
  tests/examples/source/devfiles/nodejs/devfile-with-two-deploy-commands.yaml
  tests/integration/devfile/cmd_devfile_deploy_test.go
Labels: kind/bug, approved, lgtm, v2

#5448 Pipeline changes to use clusters in QE account
  .ibm/pipelines/windows-test-script.ps1
Labels: area/testing, approved, lgtm, ok-to-test

#5498 Skeleton for odo delete component command
  pkg/odo/cli/cli.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/delete/component.go
  pkg/odo/cli/delete/delete.go
  pkg/odo/genericclioptions/resolve.go
  pkg/odo/genericclioptions/runnable.go
  pkg/odo/genericclioptions/util.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/cmd_devfile_delete_test.go
  tests/integration/devfile/cmd_devfile_deploy_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, lgtm, kind/feature
