Repository redhat-developer/odo, pull requests merged in 2022-12, with the labels that each got.

#6369 replacing timeout with time interval
  tests/integration/cmd_namespace_test.go
Labels: lgtm, kind/tests

#6367 Fix: Panic when running odo list namespaces without an active Kubernetes context
  pkg/odo/genericclioptions/clientset/clientset.go
  tests/integration/cmd_namespace_test.go
Labels: kind/bug, lgtm

#6365 Support Alizer-based automatic port detection with odo init interactive mode
  docs/website/docs/command-reference/init.md
  docs/website/docs/command-reference/json-output.md
  docs/website/docs/user-guides/quickstart/_creating_app.mdx
  pkg/alizer/alizer.go
  pkg/alizer/interface.go
  pkg/alizer/mock.go
  pkg/api/analyze.go
  pkg/init/backend/alizer.go
  pkg/init/backend/alizer_test.go
  pkg/init/backend/applicationports.go
  pkg/init/backend/applicationports_test.go
  pkg/init/backend/flags.go
  pkg/init/backend/flags_test.go
  pkg/init/backend/interactive.go
  pkg/init/backend/interactive_test.go
  pkg/init/backend/interface.go
  pkg/init/backend/mock.go
  pkg/init/init.go
  pkg/init/init_test.go
  pkg/init/interface.go
  pkg/init/mock.go
  pkg/libdevfile/libdevfile.go
  pkg/libdevfile/libdevfile_test.go
  pkg/odo/cli/alizer/alizer.go
  pkg/odo/cli/init/init.go
  pkg/testingutil/devfile.go
  tests/integration/interactive_init_test.go
Labels: lgtm, kind/feature, area/init

#6363 updating bindable kind instance
  scripts/ansible/kubernetes-cluster/operators-kubernetes.yml
  scripts/ansible/kubernetes-cluster/operators-openshift.yml
  scripts/configure-cluster/common/setup-operators.sh
  tests/examples/manifests/bindablekind-instance.yaml
  tests/examples/source/devfiles/go/cluster.yaml
Labels: lgtm, kind/tests

#6375 Delay the display of warnings related to experimental features
  pkg/odo/cli/feature/doc.go
  pkg/odo/cli/feature/features.go
  pkg/odo/genericclioptions/runnable.go
Labels: kind/bug, lgtm

#6383 Improve confirmation message for namespace/project deletion
  docs/website/docs/command-reference/delete-namespace.md
  pkg/odo/cli/delete/namespace/namespace.go
  tests/helper/helper_oc.go
  tests/helper/odo_utils.go
  tests/integration/cmd_namespace_test.go
Labels: kind/bug, lgtm

#6388 Add complete devfiles to advanced guides
  docs/website/docs/user-guides/advanced/deploy/dotnet.md
  docs/website/docs/user-guides/advanced/deploy/go.md
  docs/website/docs/user-guides/advanced/deploy/java.md
  docs/website/docs/user-guides/advanced/deploy/nodejs.md
Labels: lgtm, kind/feature, area/documentation

#6377 Get next free port when forwarding ports on podman
  pkg/dev/podmandev/pod.go
  pkg/dev/podmandev/pod_test.go
  pkg/dev/podmandev/podmandev.go
  pkg/dev/podmandev/reconcile.go
  pkg/portForward/portForward.go
  pkg/util/util.go
Labels: lgtm, kind/feature

#6395 Test with OpenShift cluster non authenticated
  .ibm/pipelines/openshift-unauth-tests.sh
  Makefile
  tests/helper/helper_cli.go
  tests/helper/helper_generic.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/helper/labels.go
  tests/integration/cmd_analyze_test.go
  tests/integration/cmd_describe_component_test.go
  tests/integration/cmd_devfile_build_images_test.go
  tests/integration/cmd_devfile_init_test.go
  tests/integration/cmd_devfile_list_test.go
  tests/integration/cmd_devfile_registry_test.go
  tests/integration/cmd_namespace_test.go
  tests/integration/cmd_pref_config_test.go
  tests/integration/cmd_remove_binding_test.go
  tests/integration/generic_test.go
  tests/integration/interactive_init_test.go
Labels: area/testing, lgtm, kind/tests

#6384 Display a warning when connection to cluster fails
  pkg/odo/cli/describe/component.go
  pkg/odo/cli/errors/errors.go
  tests/integration/cmd_describe_component_test.go
Labels: kind/bug, lgtm

#6391 Flake odo add binding in interactive doest show namespace recently created
  tests/integration/interactive_add_binding_test.go
Labels: lgtm, kind/tests

#6397 Show Devfile Stack versions in "odo registry" output
  docs/website/docs/command-reference/json-output.md
  docs/website/docs/command-reference/registry.md
  docs/website/docs/user-guides/quickstart/quickstart.md
  pkg/api/registry.go
  pkg/odo/cli/registry/registry.go
  pkg/registry/registry.go
  pkg/registry/registry_test.go
  tests/integration/cmd_devfile_registry_test.go
Labels: lgtm, kind/feature, area/registry

#6393 update env name for ODO_ROBOT_KEY
  .ibm/pipelines/functions.sh
Labels: kind/bug, lgtm, kind/tests

#6400 Set Priority field in GitHub Project item based on the 'priority/*' label on the issue
  .github/workflows/issue-management.yaml
Labels: lgtm, kind/feature

#6402 copy aritifacts only if ARTIFACT_DIR var is exposed
  scripts/openshiftci-presubmit-all-tests.sh
Labels: lgtm

#6404 Bump version to 3.4.0
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: lgtm, area/release-eng

#6403 Automate release process (GitHub part)
  .github/workflow-data/release-management/blog-post-footer.tpl.md
  .github/workflow-data/release-management/blog-post-header.tpl.md
  .github/workflow-data/release-management/pr.tpl.md
  .github/workflows/issue-management.yaml
  .github/workflows/release-management.yaml
Labels: lgtm, kind/feature, area/release-eng

#6410 Fallback to interactive mode if there is no match from Alizer when initializing a component
  pkg/init/init.go
  tests/integration/interactive_deploy_test.go
  tests/integration/interactive_dev_test.go
  tests/integration/interactive_init_test.go
Labels: kind/bug, lgtm, area/init

#6406 Enable use of ImageStreams on OpenShift
  docs/website/docs/development/architecture/how-odo-works.md
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/labels/labels.go
  tests/integration/cmd_dev_test.go
Labels: lgtm, kind/feature

#6415 Fix preference not taken into account for `odo version`
  cmd/odo/help_test.go
  pkg/odo/cli/add/add.go
  pkg/odo/cli/alizer/alizer.go
  pkg/odo/cli/build_images/build_images.go
  pkg/odo/cli/completion/completion.go
  pkg/odo/cli/create/create.go
  pkg/odo/cli/create/namespace/namespace.go
  pkg/odo/cli/delete/delete.go
  pkg/odo/cli/delete/namespace/namespace.go
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/cli/describe/describe.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/init/init.go
  pkg/odo/cli/list/component/list.go
  pkg/odo/cli/list/list.go
  pkg/odo/cli/login/login.go
  pkg/odo/cli/logout/logout.go
  pkg/odo/cli/logs/logs.go
  pkg/odo/cli/preference/add/add.go
  pkg/odo/cli/preference/preference.go
  pkg/odo/cli/preference/remove/remove.go
  pkg/odo/cli/registry/registry.go
  pkg/odo/cli/remove/remove.go
  pkg/odo/cli/set/namespace/namespace.go
  pkg/odo/cli/set/set.go
  pkg/odo/cli/version/version.go
  pkg/odo/util/cmdutils.go
Labels: kind/bug, lgtm

#6428 Do not use same log file for openshift tests auth/noauth
  .ibm/pipelines/openshift-unauth-tests.sh
Labels: lgtm

#6427 Add more tests for Podman + write Component abstraction for integration tests
  tests/helper/component_cluster.go
  tests/helper/component_interface.go
  tests/helper/component_podman.go
  tests/helper/helper_dev.go
  tests/integration/cmd_dev_test.go
Labels: lgtm, kind/tests

#6426 Display a generic Experimental mode warning message when this mode is enabled
  docs/website/docs/user-guides/advanced/experimental-mode.md
  pkg/log/status.go
  pkg/odo/cli/feature/doc.go
  pkg/odo/cli/feature/experimental.go
  pkg/odo/cli/feature/features.go
  pkg/odo/cli/feature/features_test.go
  pkg/odo/genericclioptions/runnable.go
  tests/helper/helper_experimental.go
  tests/integration/generic_test.go
Labels: lgtm, kind/code-refactoring

#6429 Allow fetching specific devfile stack version
  docs/website/docs/command-reference/init.md
  pkg/alizer/alizer.go
  pkg/alizer/alizer_test.go
  pkg/alizer/interface.go
  pkg/alizer/mock.go
  pkg/api/analyze.go
  pkg/init/asker/asker.go
  pkg/init/asker/interface.go
  pkg/init/asker/mock.go
  pkg/init/backend/alizer.go
  pkg/init/backend/alizer_test.go
  pkg/init/backend/flags.go
  pkg/init/backend/interactive.go
  pkg/init/init.go
  pkg/odo/cli/alizer/alizer.go
  pkg/odo/cli/init/init.go
  pkg/registry/registry.go
  tests/integration/cmd_devfile_init_test.go
  tests/integration/interactive_deploy_test.go
  tests/integration/interactive_dev_test.go
  tests/integration/interactive_init_test.go
Labels: lgtm, kind/feature

#6436 Add missing example to init command reference doc
  docs/website/docs/command-reference/init.md
Labels: kind/bug, lgtm, area/documentation

#6418 odo delete component deletes components running on podman
  pkg/component/delete/delete.go
  pkg/component/delete/delete_test.go
  pkg/component/delete/interface.go
  pkg/component/delete/mock.go
  pkg/dev/kubedev/cleanup.go
  pkg/dev/podmandev/cleanup.go
  pkg/kclient/mock_Client.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/delete/component/component.go
  pkg/odo/cli/delete/component/component_test.go
  pkg/odo/cli/delete/delete.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/podman/interface.go
  pkg/podman/mock.go
  pkg/podman/podman.go
  tests/helper/component_cluster.go
  tests/helper/component_interface.go
  tests/helper/component_podman.go
  tests/integration/cmd_delete_test.go
  tests/integration/cmd_dev_test.go
Labels: lgtm, kind/feature

#6439 Make remaining docs consistent
  docs/website/docs/command-reference/list-services.md
  docs/website/docs/command-reference/set-namespace.md
  docs/website/docs/user-guides/advanced/experimental-mode.md
Labels: lgtm, ok-to-test, kind/documentation, area/documentation
