Repository redhat-developer/odo, pull requests merged in 2022-03, with the labels that each got.

#5499 [v2] Add duplicate port validation, update devfile libraries, and add tests to check port name matches endpoint name
  go.mod
  go.sum
  pkg/envinfo/url.go
  pkg/envinfo/url_test.go
  tests/integration/cmd_link_unlink_test.go
  tests/integration/devfile/cmd_devfile_app_test.go
  tests/integration/devfile/cmd_devfile_delete_test.go
  tests/integration/devfile/cmd_devfile_status_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
  vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/commands.go
  vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/component_image.go
  vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/component_kubernetes_like.go
  vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/devfile.go
  vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/endpoint.go
  vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/zz_generated.deepcopy.go
  vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/zz_generated.getters.go
  vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/zz_generated.parent_overrides.go
  vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/zz_generated.plugin_overrides.go
  vendor/github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2/zz_generated.union_definitions.go
  vendor/github.com/devfile/api/v2/pkg/validation/endpoints.go
  vendor/github.com/devfile/api/v2/pkg/validation/errors.go
  vendor/github.com/devfile/api/v2/pkg/validation/validation-rule.md
  vendor/github.com/devfile/library/pkg/devfile/generator/utils.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/2.2.0/devfileJsonSchema220.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/commands.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/common/options.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/components.go
  vendor/github.com/devfile/library/pkg/devfile/parser/data/v2/projects.go
  vendor/github.com/devfile/library/pkg/devfile/parser/parse.go
  vendor/github.com/devfile/library/pkg/testingutil/devfile.go
  vendor/modules.txt
Labels: approved, lgtm

#5314 [v3] update to SBO library to 1.0
  go.mod
  go.sum
  pkg/kclient/operators.go
  pkg/service/link.go
  pkg/service/service.go
  pkg/service/service_binding_builder.go
  vendor/github.com/redhat-developer/service-binding-operator/apis/binding/v1alpha1/bindablekinds_types.go
  vendor/github.com/redhat-developer/service-binding-operator/apis/binding/v1alpha1/servicebinding_types.go
  vendor/github.com/redhat-developer/service-binding-operator/apis/binding/v1alpha1/servicebinding_webhook.go
  vendor/github.com/redhat-developer/service-binding-operator/apis/binding/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/redhat-developer/service-binding-operator/apis/common.go
  vendor/github.com/redhat-developer/service-binding-operator/apis/conditions.go
  vendor/github.com/redhat-developer/service-binding-operator/apis/spec/v1alpha3/groupversion_info.go
  vendor/github.com/redhat-developer/service-binding-operator/apis/spec/v1alpha3/servicebinding_types.go
  vendor/github.com/redhat-developer/service-binding-operator/apis/spec/v1alpha3/servicebinding_webhook.go
  vendor/github.com/redhat-developer/service-binding-operator/apis/spec/v1alpha3/zz_generated.deepcopy.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/binding/annotationmapper.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/binding/definition.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/binding/jsonpath.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/binding/model.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/binding/registry/registry.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/client/kubernetes/resource_lookup.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/client/kubernetes/whoami.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/api.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/builder/pipeline.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/context/impl.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/context/service.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/context/service/service.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/context/spec_binding_impl.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/crddescription.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/handler/collect/impl.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/handler/project/impl.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/util/util.go
  vendor/modules.txt
Labels: approved, lgtm, v3

#5446 [v2] update to SBO library to 1.0
  go.mod
  go.sum
  pkg/kclient/operators.go
  pkg/odo/cli/service/operator_backend.go
  pkg/service/link.go
  pkg/service/service.go
  pkg/service/service_binding_builder.go
  tests/integration/devfile/cmd_dot_devfile_test.go
  tests/integration/operatorhub/cmd_link_test.go
  tests/integration/operatorhub/cmd_service_test.go
  vendor/github.com/redhat-developer/service-binding-operator/apis/binding/v1alpha1/bindablekinds_types.go
  vendor/github.com/redhat-developer/service-binding-operator/apis/binding/v1alpha1/servicebinding_types.go
  vendor/github.com/redhat-developer/service-binding-operator/apis/binding/v1alpha1/servicebinding_webhook.go
  vendor/github.com/redhat-developer/service-binding-operator/apis/binding/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/redhat-developer/service-binding-operator/apis/common.go
  vendor/github.com/redhat-developer/service-binding-operator/apis/conditions.go
  vendor/github.com/redhat-developer/service-binding-operator/apis/spec/v1alpha3/groupversion_info.go
  vendor/github.com/redhat-developer/service-binding-operator/apis/spec/v1alpha3/servicebinding_types.go
  vendor/github.com/redhat-developer/service-binding-operator/apis/spec/v1alpha3/servicebinding_webhook.go
  vendor/github.com/redhat-developer/service-binding-operator/apis/spec/v1alpha3/zz_generated.deepcopy.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/binding/annotationmapper.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/binding/definition.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/binding/jsonpath.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/binding/model.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/binding/registry/registry.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/client/kubernetes/resource_lookup.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/client/kubernetes/whoami.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/api.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/builder/pipeline.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/context/impl.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/context/service.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/context/service/service.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/context/spec_binding_impl.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/crddescription.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/handler/collect/impl.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/reconcile/pipeline/handler/project/impl.go
  vendor/github.com/redhat-developer/service-binding-operator/pkg/util/util.go
  vendor/modules.txt
Labels: approved, lgtm, v2

#5510 GetAllResourcesFromSelector to retrieve resources of all kinds
  pkg/kclient/all.go
  pkg/kclient/interface.go
  pkg/kclient/mock_Client.go
Labels: approved, lgtm, kind/feature

#5466 POC for odo interactive testing
  .ibm/pipelines/kubernetes-tests.sh
  .ibm/pipelines/openshift-tests.sh
  Makefile
  go.mod
  go.sum
  pkg/testingutil/survey_ui.go
  scripts/openshiftci-periodic-tests.sh
  scripts/openshiftci-presubmit-all-tests.sh
  scripts/tools.go
  tests/helper/helper_interactive.go
  tests/integration/interactive/cmd_init_test.go
  tests/integration/interactive/interactive_suit_test.go
  vendor/github.com/hinshun/vt10x/Gopkg.lock
  vendor/github.com/hinshun/vt10x/Gopkg.toml
  vendor/github.com/hinshun/vt10x/color.go
  vendor/github.com/hinshun/vt10x/csi.go
  vendor/github.com/hinshun/vt10x/expect.go
  vendor/github.com/hinshun/vt10x/go.mod
  vendor/github.com/hinshun/vt10x/parse.go
  vendor/github.com/hinshun/vt10x/state.go
  vendor/github.com/hinshun/vt10x/str.go
  vendor/github.com/hinshun/vt10x/vt.go
  vendor/github.com/hinshun/vt10x/vt_other.go
  vendor/github.com/hinshun/vt10x/vt_posix.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: approved, lgtm, kind/tests

#5469 Modify periodic test script for v2 branch
  scripts/openshiftci-periodic-tests.sh
  tests/examples/source/devfiles/nodejs/devfile-registry.yaml
  tests/examples/source/devfiles/python/devfile-registry.yaml
  tests/examples/source/devfiles/springboot/devfile-registry.yaml
Labels: approved, lgtm, kind/tests

#5509 Syncs documentation for 2.5.0
  docs/website/docs/command-reference/create.md
  docs/website/docs/command-reference/delete.md
  docs/website/docs/command-reference/deploy.md
  docs/website/docs/command-reference/link.md
  docs/website/docs/command-reference/registry.md
  docs/website/docs/command-reference/service.md
  docs/website/docs/command-reference/storage.md
  docs/website/docs/getting-started/basics.md
  docs/website/docs/getting-started/cluster-setup/kubernetes.md
  docs/website/docs/getting-started/cluster-setup/openshift.md
  docs/website/docs/getting-started/configure.md
  docs/website/docs/getting-started/features.md
  docs/website/docs/getting-started/installation.md
  docs/website/docs/getting-started/quickstart.md
  docs/website/docs/intro.md
  docs/website/docs/tutorials/deploying-a-devfile-using-odo-on-IBM-Z-and-Power.md
  docs/website/docs/tutorials/deploying-java-app-with-database.md
Labels: approved, lgtm, kind/documentation

#5515 Do not fail on no right to list some resource
  pkg/kclient/all.go
Labels: kind/bug, approved, lgtm

#5518 Set timeout for interactive tests Expects
  tests/helper/helper_interactive.go
Labels: kind/bug, approved, lgtm

#5519 Fix typos and invalid URLs in documentation
  .github/PULL_REQUEST_TEMPLATE.md
  docs/website/README.md
  docs/website/docs/command-reference/flags.md
  docs/website/docs/contribution.md
  docs/website/docs/getting-started/features.md
  docs/website/docs/intro.md
  docs/website/docs/using-odo/create-component.md
  docs/website/docusaurus.config.js
  docs/website/src/pages/index.tsx
  docs/website/versioned_docs/version-3.0.0/command-reference/flags.md
  docs/website/versioned_docs/version-3.0.0/contribution.md
  docs/website/versioned_docs/version-3.0.0/getting-started/features.md
  docs/website/versioned_docs/version-3.0.0/intro.md
  docs/website/versioned_docs/version-3.0.0/using-odo/create-component.md
Labels: approved, lgtm, kind/documentation

#5516 Use callback and implement watch handler at CLI level
  pkg/dev/dev.go
  pkg/dev/interface.go
  pkg/odo/cli/dev/dev.go
Labels: approved, lgtm

#5528 Increase the QPS and Burst constants of the Kubernetes REST client
  pkg/kclient/kclient.go
Labels: approved, lgtm, kind/feature

#5531 Initialize devfile on odo dev/deploy without devfile
  pkg/init/init.go
  pkg/init/interface.go
  pkg/init/mock.go
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/init/init.go
  tests/helper/helper_interactive.go
  tests/integration/devfile/cmd_dev_test.go
  tests/integration/devfile/cmd_devfile_deploy_test.go
  tests/integration/interactive/cmd_deploy_test.go
  tests/integration/interactive/cmd_dev_test.go
  tests/integration/interactive/cmd_init_test.go
Labels: approved, lgtm, kind/feature

#5449 Save test results for each test spec to improve test results reporting
  tests/helper/helper_generic.go
Labels: area/testing, approved, lgtm

#5511 odo delete component without a devfile
  pkg/component/delete/delete.go
  pkg/component/delete/delete_test.go
  pkg/component/delete/interface.go
  pkg/component/delete/mock.go
  pkg/component/delete/mock_handler.go
  pkg/component/labels/labels.go
  pkg/deploy/deploy.go
  pkg/odo/cli/delete/component.go
  pkg/odo/cli/delete/component_test.go
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/service/service.go
  scripts/mockgen.sh
  tests/integration/devfile/cmd_delete_test.go
Labels: approved, lgtm, kind/feature

#5538 Make sure Makefile targets for both integration and E2E tests depend on the 'install' target
  Makefile
Labels: approved, lgtm, kind/tests

#5541 Fix panic with odo init when non-existent devfile path is provided
  pkg/odo/cli/init/init.go
  tests/integration/devfile/cmd_devfile_init_test.go
Labels: kind/bug, approved, lgtm

#5543 Remove information about resource cleanup from odo dev exit message
  pkg/watch/watch.go
Labels: kind/bug, approved, lgtm

#5545 Test and fix using namespace from env file
  pkg/odo/cli/deploy/deploy.go
  tests/integration/devfile/cmd_dev_test.go
  tests/integration/devfile/cmd_devfile_deploy_test.go
  tests/integration/devfile/cmd_devfile_init_test.go
Labels: kind/bug, approved, lgtm, kind/tests

#5530 fix openshift login failure
  .ibm/pipelines/openshift-tests.sh
  .ibm/pipelines/windows-test-script.ps1
  .ibm/pipelines/windows-test.sh
Labels: approved, lgtm, kind/tests

#5542 condition odo deploy information in odo init output
  pkg/odo/cli/init/init.go
  tests/integration/devfile/cmd_devfile_init_test.go
Labels: approved, lgtm, kind/feature

#5537 Reorganized test file directory structure
  .ibm/pipelines/kubernetes-tests.sh
  .ibm/pipelines/openshift-tests.sh
  Makefile
  scripts/openshiftci-periodic-tests.sh
  scripts/openshiftci-presubmit-all-tests.sh
  tests/interactive/cmd_deploy_test.go
  tests/interactive/cmd_dev_test.go
  tests/interactive/cmd_init_test.go
  tests/interactive/interactive_suit_test.go
Labels: approved, lgtm, kind/tests

#5181 Moving to use gitignore library go-gitignore
  go.mod
  go.sum
  pkg/sync/adapter.go
  pkg/util/file_indexer.go
  pkg/util/file_indexer_test.go
  vendor/github.com/sabhiram/go-gitignore/.gitignore
  vendor/github.com/sabhiram/go-gitignore/LICENSE
  vendor/github.com/sabhiram/go-gitignore/README.md
  vendor/github.com/sabhiram/go-gitignore/go.mod
  vendor/github.com/sabhiram/go-gitignore/go.sum
  vendor/github.com/sabhiram/go-gitignore/ignore.go
  vendor/github.com/sabhiram/go-gitignore/version_gen.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm

#5551 Add Dev and Project labeling / refactoring labeling and annotations
  pkg/component/component.go
  pkg/component/component_full_description.go
  pkg/component/component_test.go
  pkg/component/labels/labels.go
  pkg/component/labels/labels_test.go
  pkg/component/pushed_component.go
  pkg/component/types.go
  pkg/deploy/deploy.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/storage/utils.go
  pkg/kclient/deployments.go
  pkg/kclient/fake/ingress.go
  pkg/service/link.go
  pkg/service/service.go
  pkg/storage/labels/labels_test.go
  pkg/storage/storage.go
  pkg/testingutil/deployments.go
  pkg/testingutil/routes.go
  pkg/url/labels/labels_test.go
  pkg/url/url.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/helper/helper_run.go
Labels: approved, lgtm, kind/feature

#5558 Remove nanoseconds from spinner
  pkg/log/fidget/spinner.go
  pkg/log/status.go
Labels: approved, lgtm, kind/feature

#5556 Make `odo dev` and `odo deploy` display welcoming messages too before running Alizer detection, just like `odo init`
  pkg/init/init.go
  pkg/init/interface.go
  pkg/init/mock.go
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/cli/dev/dev.go
  tests/interactive/cmd_deploy_test.go
  tests/interactive/cmd_dev_test.go
Labels: area/UX, approved, lgtm, kind/feature

#5500 Delete with devfile.yaml
  pkg/component/component.go
  pkg/component/delete/delete.go
  pkg/component/delete/delete_test.go
  pkg/component/delete/interface.go
  pkg/component/delete/mock.go
  pkg/component/delete/mock_handler.go
  pkg/deploy/deploy.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/kclient/deployments.go
  pkg/kclient/utils.go
  pkg/libdevfile/component_kubernetes_utils.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/cli/delete/component.go
  pkg/odo/cli/delete/component_test.go
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/genericclioptions/context_test.go
  pkg/odo/genericclioptions/localprovider.go
  pkg/service/link.go
  pkg/service/service.go
  pkg/testingutil/deployments.go
  pkg/testingutil/devfile.go
  pkg/util/util.go
  tests/examples/source/devfiles/nodejs/devfile-deploy-with-multiple-resources.yaml
  tests/helper/helper_cli.go
  tests/helper/helper_generic.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/helper/helper_run.go
  tests/integration/devfile/cmd_delete_test.go
  tests/integration/devfile/cmd_dev_test.go
  tests/integration/devfile/cmd_devfile_deploy_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
Labels: approved, lgtm, kind/feature

#5547 fix failing v2 periodic tests
  scripts/openshiftci-periodic-tests.sh
Labels: approved, lgtm, kind/tests

#5574 v2 Delete cleanup
  pkg/component/component.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/component/component.go
  pkg/odo/cli/component/delete.go
  pkg/odo/cli/component/devfile.go
  pkg/odo/genericclioptions/resolve.go
  pkg/odo/genericclioptions/runnable.go
  pkg/odo/genericclioptions/util.go
  tests/integration/devfile/cmd_delete_test.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/cmd_devfile_delete_test.go
  tests/integration/devfile/cmd_devfile_deploy_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: approved, lgtm

#5569 Create DevSession for integration tests
  tests/helper/helper_dev.go
  tests/integration/devfile/cmd_delete_test.go
  tests/integration/devfile/cmd_dev_test.go
  tests/integration/devfile/cmd_devfile_list_test.go
Labels: approved, lgtm, kind/tests

#5580 Remove v2delete reference from Makefile
  Makefile
Labels: approved, lgtm

#5539 Updates the UX/UI experience of odo deploy and odo dev
  pkg/deploy/deploy.go
  pkg/dev/dev.go
  pkg/devfile/image/docker_compatible.go
  pkg/devfile/image/image.go
  pkg/log/status.go
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/cli/dev/dev.go
  pkg/service/service.go
  pkg/watch/watch.go
Labels: approved, lgtm

#5577 remove odo catalog command
  Makefile
  docs/website/versioned_docs/version-3.0.0/command-reference/catalog.md
  docs/website/versioned_docs/version-3.0.0/command-reference/init.md
  pkg/catalog/interface.go
  pkg/catalog/mock_catalog.go
  pkg/component/component.go
  pkg/component/delete/mock.go
  pkg/init/asker/asker.go
  pkg/init/asker/interface.go
  pkg/init/asker/mock.go
  pkg/init/backend/alizer.go
  pkg/init/backend/alizer_test.go
  pkg/init/backend/interactive.go
  pkg/init/backend/interactive_test.go
  pkg/init/init.go
  pkg/init/init_test.go
  pkg/init/registry/registry.go
  pkg/odo/cli/catalog/catalog.go
  pkg/odo/cli/catalog/describe/component.go
  pkg/odo/cli/catalog/describe/describe.go
  pkg/odo/cli/catalog/list/components.go
  pkg/odo/cli/catalog/list/list.go
  pkg/odo/cli/catalog/search/component.go
  pkg/odo/cli/catalog/search/search.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/create_methods.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/component/ui/ui.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/odo/util/completion/completionhandlers.go
  pkg/registry/devfile_component_type_list.go
  pkg/registry/devfile_component_type_list_test.go
  pkg/registry/interface.go
  pkg/registry/mock.go
  pkg/registry/registry.go
  pkg/registry/registry_test.go
  pkg/registry/types.go
  pkg/registry/types_with_details.go
  pkg/registry/types_with_details_test.go
  scripts/mockgen.sh
  tests/integration/devfile/cmd_devfile_catalog_test.go
  tests/integration/devfile/utils/utils.go
  tests/integration/generic_test.go
Labels: approved, lgtm

#5582 Update odo delete component doc
  docs/website/versioned_docs/version-3.0.0/command-reference/delete.md
  pkg/odo/cli/delete/component.go
Labels: approved, lgtm, kind/documentation

#5553 Interactive mode — Ask all questions first
  pkg/init/backend/alizer.go
  pkg/init/backend/flags.go
  pkg/init/backend/flags_test.go
  pkg/init/backend/interactive.go
  pkg/init/backend/interactive_test.go
  pkg/init/backend/interface.go
  pkg/init/backend/mock.go
  pkg/init/init.go
  pkg/init/interface.go
  pkg/init/mock.go
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/init/init.go
  tests/helper/helper_generic.go
  tests/integration/devfile/cmd_devfile_init_test.go
  tests/interactive/cmd_init_test.go
Labels: area/UX, approved, lgtm, kind/feature

#5590 docs: update prismjs
  docs/website/package.json
  docs/website/yarn.lock
Labels: approved, lgtm

#5586 Fix some flaky tests
  tests/integration/devfile/cmd_delete_test.go
  tests/integration/devfile/cmd_dev_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: kind/bug, approved, lgtm

#5589 Create cleanup
  Makefile
  docs/website/versioned_docs/version-3.0.0/command-reference/create.md
  pkg/component/component.go
  pkg/component/component_full_description.go
  pkg/component/component_test.go
  pkg/component/starter_project.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/component/component.go
  pkg/odo/cli/component/create.go
  pkg/odo/cli/component/create_helpers.go
  pkg/odo/cli/component/create_methods.go
  pkg/odo/cli/component/interactive_create.go
  tests/e2escenarios/e2e_devfile_test.go
  tests/examples/source/devfiles/nodejs/devfile-with-subDir.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-tag.yaml
  tests/helper/helper_configValidate.go
  tests/helper/helper_filesystem.go
  tests/helper/helper_generic.go
  tests/integration/cmd_pref_config_test.go
  tests/integration/devfile/cmd_delete_test.go
  tests/integration/devfile/cmd_dev_test.go
  tests/integration/devfile/cmd_devfile_build_images_test.go
  tests/integration/devfile/cmd_devfile_create_test.go
  tests/integration/devfile/cmd_devfile_init_test.go
  tests/integration/devfile/cmd_devfile_list_test.go
  tests/integration/devfile/cmd_devfile_push_test.go
  tests/integration/devfile/cmd_devfile_registry_test.go
  tests/integration/devfile/cmd_devfile_url_test.go
  tests/integration/devfile/cmd_dot_devfile_test.go
Labels: approved, lgtm, kind/code-refactoring

#5526 Implements port forwarding for odo dev
  pkg/dev/dev.go
  pkg/dev/interface.go
  pkg/dev/mock.go
  pkg/kclient/interface.go
  pkg/kclient/mock_Client.go
  pkg/kclient/operators.go
  pkg/kclient/port_forwarding.go
  pkg/libdevfile/errors.go
  pkg/libdevfile/libdevfile.go
  pkg/libdevfile/libdevfile_test.go
  pkg/odo/cli/dev/dev.go
  pkg/util/util.go
  pkg/watch/watch.go
  scripts/mockgen.sh
  tests/examples/source/devfiles/nodejs/devfile-with-multiple-endpoints.yaml
  tests/examples/source/devfiles/nodejs/project-with-multiple-endpoints/package.json
  tests/examples/source/devfiles/nodejs/project-with-multiple-endpoints/server.js
  tests/examples/source/devfiles/nodejs/project-with-multiple-endpoints/test/test.js
  tests/helper/helper_dev.go
  tests/helper/helper_run.go
  tests/integration/devfile/cmd_delete_test.go
  tests/integration/devfile/cmd_dev_test.go
  tests/integration/devfile/cmd_devfile_list_test.go
  vendor/k8s.io/client-go/tools/portforward/doc.go
  vendor/k8s.io/client-go/tools/portforward/portforward.go
  vendor/modules.txt
Labels: approved, lgtm, kind/feature

#5578 Update help usage to a working example / updated commands
  pkg/odo/cli/build_images/build_images.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/component/component.go
  pkg/odo/cli/delete/delete.go
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/init/init.go
  pkg/odo/cli/login/login.go
  pkg/odo/cli/logout/logout.go
  pkg/odo/cli/preference/preference.go
  pkg/odo/cli/project/project.go
  pkg/odo/cli/url/url.go
  tests/integration/loginlogout/cmd_login_logout_test.go
Labels: approved, lgtm

#5576 Adding missing telemetry to init, deploy and dev commands
  pkg/envinfo/envinfo.go
  pkg/odo/cli/build_images/build_images.go
  pkg/odo/cli/component/get.go
  pkg/odo/cli/component/list.go
  pkg/odo/cli/delete/component.go
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/init/init.go
  pkg/odo/cli/init/init_test.go
  pkg/odo/cli/login/login.go
  pkg/odo/cli/logout/logout.go
  pkg/odo/cli/preference/registry/add.go
  pkg/odo/cli/preference/registry/delete.go
  pkg/odo/cli/preference/registry/list.go
  pkg/odo/cli/preference/registry/update.go
  pkg/odo/cli/preference/set.go
  pkg/odo/cli/preference/set_test.go
  pkg/odo/cli/preference/unset.go
  pkg/odo/cli/preference/unset_test.go
  pkg/odo/cli/preference/view.go
  pkg/odo/cli/preference/view_test.go
  pkg/odo/cli/project/create.go
  pkg/odo/cli/project/create_test.go
  pkg/odo/cli/project/delete.go
  pkg/odo/cli/project/delete_test.go
  pkg/odo/cli/project/get.go
  pkg/odo/cli/project/list.go
  pkg/odo/cli/project/set.go
  pkg/odo/cli/telemetry/telemetry.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/delete.go
  pkg/odo/cli/url/list.go
  pkg/odo/cli/utils/terminal.go
  pkg/odo/cli/version/version.go
  pkg/odo/genericclioptions/runnable.go
  pkg/preference/implem.go
  pkg/segment/context/context.go
  pkg/segment/segment.go
  pkg/util/config_util.go
  pkg/util/util.go
  tests/helper/helper_generic.go
  tests/helper/helper_telemetry.go
  tests/integration/devfile/cmd_dev_test.go
  tests/integration/devfile/cmd_devfile_deploy_test.go
  tests/integration/devfile/cmd_devfile_init_test.go
  tests/integration/devfile/utils/utils.go
Labels: approved, lgtm, kind/task

#5571 [#5561] Remove `odo url`
  Makefile
  docs/website/versioned_docs/version-3.0.0/using-odo/create-url.md
  pkg/component/component.go
  pkg/component/pushed_component.go
  pkg/component/types.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/envinfo/envinfo.go
  pkg/envinfo/envinfo_test.go
  pkg/envinfo/types.go
  pkg/envinfo/url.go
  pkg/envinfo/url_test.go
  pkg/kclient/fake/ingress.go
  pkg/kclient/ingress.go
  pkg/kclient/ingress_test.go
  pkg/kclient/interface.go
  pkg/kclient/kclient.go
  pkg/kclient/mock_Client.go
  pkg/kclient/routes.go
  pkg/kclient/routes_test.go
  pkg/localConfigProvider/localConfigProvider.go
  pkg/localConfigProvider/mock_localConfigProvider.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/url/create.go
  pkg/odo/cli/url/delete.go
  pkg/odo/cli/url/list.go
  pkg/odo/cli/url/url.go
  pkg/odo/genericclioptions/context.go
  pkg/testingutil/routes.go
  pkg/url/kubernetes.go
  pkg/url/kubernetes_test.go
  pkg/url/labels/labels.go
  pkg/url/labels/labels_test.go
  pkg/url/mock_Client.go
  pkg/url/status.go
  pkg/url/status_test.go
  pkg/url/types.go
  pkg/url/url.go
  pkg/url/url_test.go
  pkg/url/utils.go
  pkg/url/utils_test.go
  scripts/mockgen.sh
  tests/helper/odo_utils.go
  tests/integration/devfile/cmd_dev_test.go
Labels: approved, lgtm, kind/code-refactoring, kind/task

#5601 Fix odo interactive with verbosity flags
  pkg/init/init.go
  pkg/init/interface.go
  pkg/init/mock.go
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/init/init.go
  pkg/odo/cli/init/init_test.go
  tests/integration/devfile/cmd_devfile_init_test.go
  tests/interactive/cmd_deploy_test.go
  tests/interactive/cmd_dev_test.go
  tests/interactive/cmd_init_test.go
Labels: kind/bug, approved, lgtm

#5602 [#5322] Add `PROJECT_SOURCE` to the container image build command environment
  pkg/devfile/image/docker_compatible.go
  tests/examples/source/devfiles/nodejs/devfile-outerloop-project_source-in-docker-build-context.yaml
  tests/integration/devfile/cmd_devfile_build_images_test.go
  tests/integration/devfile/cmd_devfile_deploy_test.go
Labels: kind/bug, approved, lgtm

#5598 odo delete component - show warning that something was not deleted
  pkg/component/delete/delete.go
  pkg/component/delete/delete_test.go
  pkg/component/delete/interface.go
  pkg/component/delete/mock.go
  pkg/odo/cli/delete/component.go
  pkg/odo/cli/delete/component_test.go
  tests/integration/devfile/cmd_delete_test.go
Labels: approved, lgtm, kind/feature

#5608 [#5330] Make `odo build-images` return an error if no Image component found in Devfile
  pkg/devfile/image/image.go
  pkg/libdevfile/errors.go
  tests/integration/devfile/cmd_devfile_build_images_test.go
Labels: kind/bug, approved, lgtm

#5605 Updates the backend error messages more clearly
  pkg/devfile/image/image.go
Labels: approved, lgtm

#5612 Remove italic output throughout odo
  cmd/odo/odo.go
  pkg/auth/login.go
  pkg/odo/cli/init/init.go
Labels: approved, lgtm

#5572 Use .gitignore file for odo dev
  pkg/dev/dev.go
  pkg/dev/interface.go
  pkg/dev/mock.go
  pkg/odo/cli/dev/dev.go
  tests/integration/devfile/cmd_dev_test.go
Labels: kind/bug, approved, lgtm

#5599 Fix flaky test "should expose two endpoints on localhost"
  pkg/kclient/interface.go
  pkg/kclient/mock_Client.go
  pkg/kclient/port_forwarding.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/dev/writer.go
  tests/helper/helper_dev.go
  tests/integration/devfile/cmd_delete_test.go
  tests/integration/devfile/cmd_dev_test.go
  tests/interactive/cmd_dev_test.go
Labels: approved, lgtm, kind/tests
