Repository redhat-developer/odo, pull requests merged in 2022-10, with the labels that each got.

#6177 Fix Windows tests for PR targeting branches other than `main`
  .ibm/pipelines/windows-test-script.ps1
  tests/e2escenarios/e2e_devfile_test.go
Labels: kind/bug, area/testing, approved, lgtm, kind/tests

#6182 Update USAGE_DATA.md
  USAGE_DATA.md
Labels: approved, lgtm, kind/documentation, area/documentation

#6168 telemetry: start tracking flags usage
  pkg/odo/genericclioptions/runnable.go
  pkg/segment/context/context.go
  pkg/segment/context/context_test.go
  tests/integration/cmd_devfile_deploy_test.go
  tests/integration/cmd_devfile_init_test.go
Labels: approved, lgtm, kind/feature, area/telemetry

#6184 suspend quarkus test
  tests/e2escenarios/e2e_devfile_test.go
Labels: approved, lgtm, kind/tests

#6167 Fix help and doc for `odo completion zsh`
  docs/website/docs/command-reference/completion.md
  pkg/odo/cli/completion/completion.go
Labels: kind/bug, approved, lgtm, kind/documentation

#6190 Fix postgreSQL containers failing due to file permissions errors
  scripts/ansible/kubernetes-cluster/create.yml
Labels: approved, lgtm, kind/tests

#6197 Bump odo version from 3.0.0-rc2 to 3.0.0
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#6191 Note regarding image visibility for odo deploy
  docs/website/docs/_imageregistrynote.mdx
  docs/website/docs/command-reference/deploy.md
  docs/website/docs/user-guides/advanced/deploy/_running_deploy.mdx
Labels: approved, lgtm, kind/documentation

#6187 Support a generic --run-on flag
  pkg/machineoutput/types.go
  pkg/odo/cli/add/binding/binding.go
  pkg/odo/cli/alizer/alizer.go
  pkg/odo/cli/build_images/build_images.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/create/namespace/namespace.go
  pkg/odo/cli/delete/component/component.go
  pkg/odo/cli/delete/namespace/namespace.go
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/cli/describe/binding.go
  pkg/odo/cli/describe/component.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/init/init.go
  pkg/odo/cli/init/init_test.go
  pkg/odo/cli/list/binding/binding.go
  pkg/odo/cli/list/component/list.go
  pkg/odo/cli/list/list.go
  pkg/odo/cli/list/namespace/namespace.go
  pkg/odo/cli/list/services/services.go
  pkg/odo/cli/login/login.go
  pkg/odo/cli/login/login_test.go
  pkg/odo/cli/logout/logout.go
  pkg/odo/cli/logs/logs.go
  pkg/odo/cli/preference/add/registry.go
  pkg/odo/cli/preference/remove/registry.go
  pkg/odo/cli/preference/set.go
  pkg/odo/cli/preference/set_test.go
  pkg/odo/cli/preference/unset.go
  pkg/odo/cli/preference/unset_test.go
  pkg/odo/cli/preference/view.go
  pkg/odo/cli/preference/view_test.go
  pkg/odo/cli/registry/registry.go
  pkg/odo/cli/remove/binding/binding.go
  pkg/odo/cli/set/namespace/namespace.go
  pkg/odo/cli/telemetry/telemetry.go
  pkg/odo/cli/version/version.go
  pkg/odo/commonflags/context/context.go
  pkg/odo/commonflags/context/context_test.go
  pkg/odo/commonflags/main_test.go
  pkg/odo/commonflags/output.go
  pkg/odo/commonflags/output_test.go
  pkg/odo/commonflags/run_on.go
  pkg/odo/commonflags/run_on_test.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/genericclioptions/context_test.go
  pkg/odo/genericclioptions/runnable.go
  pkg/odo/util/flag.go
Labels: approved, lgtm, kind/feature

#6203 Update Algolia settings
  docs/website/docusaurus.config.js
Labels: approved, lgtm

#6214 Fix broken links in the installation guide
  docs/website/docs/overview/installation.md
Labels: kind/bug, approved, lgtm, area/documentation

#6218 Removal from OWNERS
  OWNERS
Labels: approved, lgtm

#6209 Add GitHub Workflow for issue management
  .github/workflows/issue-management.yaml
Labels: approved, lgtm, kind/feature

#6231 Bump odo to v3.1.0
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#6224 enable quarkus e2e test
  tests/e2escenarios/e2e_devfile_test.go
Labels: approved, lgtm, kind/tests

#6202 Build context as part of GenericRun
  pkg/binding/binding_test.go
  pkg/binding/interface.go
  pkg/binding/list.go
  pkg/binding/list_test.go
  pkg/binding/mock.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/delete/delete.go
  pkg/component/delete/delete_test.go
  pkg/component/delete/interface.go
  pkg/component/delete/mock.go
  pkg/dev/dev.go
  pkg/logs/interface.go
  pkg/logs/logs.go
  pkg/odo/cli/add/binding/binding.go
  pkg/odo/cli/alizer/alizer.go
  pkg/odo/cli/build_images/build_images.go
  pkg/odo/cli/create/namespace/namespace.go
  pkg/odo/cli/delete/component/component.go
  pkg/odo/cli/delete/component/component_test.go
  pkg/odo/cli/delete/namespace/namespace.go
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/cli/describe/binding.go
  pkg/odo/cli/describe/component.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/init/init.go
  pkg/odo/cli/list/binding/binding.go
  pkg/odo/cli/list/component/list.go
  pkg/odo/cli/list/list.go
  pkg/odo/cli/list/namespace/namespace.go
  pkg/odo/cli/list/services/services.go
  pkg/odo/cli/logout/logout.go
  pkg/odo/cli/logs/logs.go
  pkg/odo/cli/remove/binding/binding.go
  pkg/odo/cli/set/namespace/namespace.go
  pkg/odo/cmdline/cobra.go
  pkg/odo/commonflags/context/context.go
  pkg/odo/context/kubernetes.go
  pkg/odo/context/odo.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/genericclioptions/context_test.go
  pkg/odo/genericclioptions/devfile.go
  pkg/odo/genericclioptions/init.go
  pkg/odo/genericclioptions/resolve.go
  pkg/odo/genericclioptions/runnable.go
  pkg/odo/genericclioptions/util.go
  pkg/odo/util/completion/completion.go
  pkg/odo/util/completion/completionhandlers.go
  pkg/odo/util/flag.go
  pkg/watch/interface.go
  pkg/watch/mock.go
  pkg/watch/watch.go
Labels: approved, lgtm, kind/code-refactoring, area/odo-on-podman

#6188 odo 3.0.0 GA blog
  docs/website/blog/3.0.0-GA-blog.md
Labels: approved, lgtm, kind/documentation, area/documentation

#6220 Update version to 3.0.0 in doc and `build/VERSION` file
  build/VERSION
  docs/website/docs/overview/installation.md
  docs/website/docusaurus.config.js
Labels: approved, lgtm, area/release-eng, kind/documentation, area/documentation

#6230 Minor fixes to documentation
  README.md
  docs/website/docs/command-reference/build-images.md
  docs/website/docs/command-reference/deploy.md
  docs/website/docs/command-reference/list-component.md
  docs/website/docs/overview/configure.md
  docs/website/docs/user-guides/advanced/deploy/deploy.md
  docs/website/docs/user-guides/quickstart/quickstart.md
Labels: do-not-merge/hold, approved, lgtm, kind/documentation

#6235 fix test failure due to devfile-registry
  tests/integration/cmd_devfile_registry_test.go
  tests/integration/interactive_deploy_test.go
  tests/integration/interactive_dev_test.go
  tests/integration/interactive_init_test.go
Labels: approved, lgtm, kind/tests

#6217 Make exec package agnostic of platform
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/exec/exec.go
  pkg/exec/exec_test.go
  pkg/kclient/interface.go
  pkg/kclient/kclient.go
  pkg/kclient/pods.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/odo/genericclioptions/runnable.go
  pkg/platform/interface.go
  pkg/sync/copy.go
  pkg/sync/interface.go
  pkg/sync/sync.go
  pkg/sync/sync_test.go
Labels: approved, lgtm, area/odo-on-podman

#6259 Document in which version an environment variable controlling odo behavior appeared
  docs/website/docs/overview/configure.md
Labels: approved, lgtm, area/documentation

#6252 Exclude the 'dist' folder in 'check-gofmt.sh' script
  scripts/check-gofmt.sh
Labels: kind/bug, approved, lgtm

#6260 Fix potential issue preventing application from being restarted correctly by `odo dev`
  pkg/remotecmd/kubeexec.go
  pkg/remotecmd/kubexec_test.go
Labels: kind/bug, approved, lgtm, area/dev

#6268 Set empty component name in context if no devfile exists in the current directory
  pkg/odo/genericclioptions/devfile.go
  tests/integration/cmd_devfile_list_test.go
Labels: kind/bug, approved, lgtm

#6245 add make release-bin target
  Makefile
Labels: approved, lgtm

#6258 Allow controlling telemetry via the `ODO_TRACKING_CONSENT` environment variable
  .golangci.yaml
  USAGE_DATA.md
  docs/website/docs/overview/configure.md
  pkg/odo/genericclioptions/runnable.go
  pkg/segment/segment.go
  pkg/segment/segment_test.go
  tests/helper/helper_cmd_wrapper.go
  tests/helper/helper_generic.go
  tests/helper/helper_run.go
  tests/helper/helper_telemetry.go
  tests/integration/cmd_devfile_init_test.go
Labels: approved, lgtm, kind/feature, area/telemetry

#6276 Bump odo to v3.2.0
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#6242 Isolate no cluster tests
  .ibm/pipelines/kubernetes-tests.sh
  .ibm/pipelines/nocluster-tests.sh
  .ibm/pipelines/openshift-tests.sh
  .ibm/pipelines/windows-test-script.ps1
  Makefile
  tests/helper/helper_generic.go
  tests/helper/labels.go
  tests/integration/cmd_analyze_test.go
  tests/integration/cmd_devfile_init_test.go
  tests/integration/cmd_devfile_registry_test.go
  tests/integration/cmd_pref_config_test.go
  tests/integration/interactive_init_test.go
Labels: approved, lgtm, kind/tests
