Repository redhat-developer/odo, pull requests merged in 2022-04, with the labels that each got.

#5614 Fix potential issue with `image.TestSelectBackend` unit tests when `PODMAN_CMD` env var is set
  pkg/devfile/image/image.go
  pkg/devfile/image/image_test.go
Labels: approved, lgtm, kind/tests

#5610 Updates the error output for an empty directory
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/cli/dev/dev.go
Labels: approved, lgtm

#5596 Cleans up innerloop resources upon Ctrl+c
  pkg/component/delete/mock.go
  pkg/dev/dev.go
  pkg/dev/interface.go
  pkg/dev/mock.go
  pkg/init/mock.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/odo/genericclioptions/runnable.go
  pkg/testingutil/devfile.go
  pkg/watch/interface.go
  pkg/watch/mock.go
  pkg/watch/watch.go
  pkg/watch/watch_test.go
  tests/helper/helper_kubectl.go
  tests/integration/devfile/cmd_dev_test.go
Labels: approved, lgtm

#5619 Adds/updates code comments and removes unused client
  pkg/dev/dev.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/watch/interface.go
Labels: approved, lgtm, kind/documentation

#5604 Wait deletion
  pkg/component/delete/delete.go
  pkg/component/delete/delete_test.go
  pkg/component/delete/interface.go
  pkg/component/delete/mock.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/kclient/deployments.go
  pkg/kclient/dynamic.go
  pkg/kclient/interface.go
  pkg/kclient/mock_Client.go
  pkg/kclient/operators.go
  pkg/kclient/owner_reference.go
  pkg/kclient/owner_reference_test.go
  pkg/kclient/utils.go
  pkg/odo/cli/delete/component.go
  pkg/odo/cli/delete/component_test.go
  pkg/service/service.go
  pkg/watch/watch.go
  tests/helper/helper_cli.go
  tests/helper/helper_dev.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/devfile/cmd_dev_test.go
Labels: approved, lgtm, kind/feature

#5624 Ignore PackageManifets resources when listing components
  pkg/component/component.go
Labels: kind/bug, approved, lgtm

#5623 Set list command in main help section
  pkg/odo/cli/list/list.go
Labels: kind/bug, approved, lgtm

#5630 Hide warnings for dynamic client
  pkg/kclient/kclient.go
Labels: kind/bug, approved, lgtm

#5587 Update devfiles' information and used images for s390x
  docs/website/docs/tutorials/deploying-a-devfile-using-odo-on-IBM-Z-and-Power.md
  docs/website/versioned_docs/version-3.0.0/tutorials/deploying-a-devfile-using-odo-on-IBM-Z-and-Power.md
Labels: approved, lgtm, ok-to-test

#5626 update devfiles on v2 branch
  tests/examples/source/devfiles/nodejs/devfile-registry.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-link.yaml
  tests/examples/source/devfiles/python/devfile-registry.yaml
  tests/examples/source/devfiles/springboot/devfile-registry.yaml
  tests/integration/devfile/cmd_dot_devfile_test.go
  tests/integration/operatorhub/cmd_link_test.go
Labels: approved, lgtm, kind/tests

#5639 [Hotfix] Always ignore `command` and `args` defined in Devfile container components
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils_test.go
  tests/examples/source/devfiles/nodejs/issue-5620-devfile-with-container-command-args.yaml
  tests/integration/devfile/cmd_dev_test.go
Labels: kind/bug, approved, lgtm

#5640 [Hotfix][v2] Always ignore `command` and `args` defined in Devfile container components
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils_test.go
  tests/examples/source/devfiles/nodejs/issue-5620-devfile-with-container-command-args.yaml
  tests/integration/devfile/cmd_devfile_push_test.go
Labels: kind/bug, approved, lgtm

#5649 Bumping odo version to v2.5.1
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: approved, lgtm

#5609 Updates the odo dev output for logging
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/dev/writer.go
  tests/integration/devfile/cmd_dev_test.go
Labels: approved, lgtm

#5629 Adds warning for running podman on Apple Silicon
  pkg/devfile/image/image.go
  pkg/log/status.go
Labels: approved, lgtm, kind/feature

#5633 Tests cleanup after odo dev terminates
  tests/integration/devfile/cmd_dev_test.go
  tests/integration/devfile/cmd_devfile_deploy_test.go
Labels: approved, lgtm, kind/tests

#5651 Terminate process on windows
  tests/e2escenarios/e2e_devfile_test.go
  tests/helper/helper_dev.go
  tests/helper/helper_nowindows.go
  tests/helper/helper_run.go
  tests/helper/helper_windows.go
  tests/integration/devfile/cmd_delete_test.go
  tests/integration/devfile/cmd_dev_test.go
  tests/integration/devfile/cmd_devfile_deploy_test.go
  tests/integration/devfile/cmd_devfile_list_test.go
Labels: kind/bug, approved, lgtm

#5613 Updates odo init output, fixes colorized output for tests.
  Makefile
  go.mod
  go.sum
  pkg/log/status.go
  pkg/odo/cli/init/init.go
  pkg/odo/cli/messages/messages.go
  tests/helper/helper_interactive.go
  tests/interactive/cmd_init_test.go
  vendor/github.com/fatih/color/README.md
  vendor/github.com/fatih/color/color.go
  vendor/github.com/fatih/color/doc.go
  vendor/github.com/fatih/color/go.mod
  vendor/github.com/fatih/color/go.sum
  vendor/github.com/mattn/go-colorable/noncolorable.go
  vendor/github.com/mattn/go-isatty/.travis.yml
  vendor/github.com/mattn/go-isatty/go.mod
  vendor/github.com/mattn/go-isatty/isatty_bsd.go
  vendor/github.com/mattn/go-isatty/isatty_others.go
  vendor/github.com/mattn/go-isatty/isatty_plan9.go
  vendor/github.com/mattn/go-isatty/isatty_solaris.go
  vendor/github.com/mattn/go-isatty/isatty_tcgets.go
  vendor/github.com/mattn/go-isatty/isatty_windows.go
  vendor/github.com/mattn/go-isatty/renovate.json
  vendor/modules.txt
Labels: approved, lgtm, kind/feature

#5662 Update devfiles information and used images for ppc64le
  docs/website/docs/tutorials/deploying-a-devfile-using-odo-on-IBM-Z-and-Power.md
  docs/website/versioned_docs/version-3.0.0/tutorials/deploying-a-devfile-using-odo-on-IBM-Z-and-Power.md
Labels: approved, lgtm, ok-to-test, area/System-PZ

#5658 `odo init` json output
  docs/website/versioned_docs/version-3.0.0/command-reference/json-output.md
  pkg/alizer/alizer.go
  pkg/alizer/mock.go
  pkg/api/component.go
  pkg/api/devfile-data.go
  pkg/api/devfile-location.go
  pkg/api/doc.go
  pkg/api/utils.go
  pkg/component/delete/mock.go
  pkg/init/backend/alizer.go
  pkg/init/backend/alizer_test.go
  pkg/init/backend/flags.go
  pkg/init/backend/flags_test.go
  pkg/init/backend/interactive.go
  pkg/init/backend/interactive_test.go
  pkg/init/backend/interface.go
  pkg/init/backend/mock.go
  pkg/init/init.go
  pkg/init/init_test.go
  pkg/init/interface.go
  pkg/init/mock.go
  pkg/libdevfile/libdevfile.go
  pkg/log/status.go
  pkg/odo/cli/init/init.go
  tests/integration/devfile/cmd_alizer_test.go
  tests/integration/devfile/cmd_devfile_init_test.go
Labels: approved, lgtm, kind/feature

#5657 Fix issue with `build-images` and `deploy` not working with Docker if optional `buildContext` field is not set in Devfile (#5600)
  pkg/devfile/image/docker_compatible.go
  pkg/devfile/image/docker_compatible_test.go
  tests/examples/source/devfiles/nodejs/issue-5600-devfile-with-image-component-and-no-buildContext.yaml
  tests/integration/devfile/cmd_devfile_build_images_test.go
  tests/integration/devfile/cmd_devfile_deploy_test.go
Labels: kind/bug, approved, lgtm

#5655 fix artifact collection
  scripts/openshiftci-periodic-tests.sh
Labels: approved, lgtm, v2, kind/tests

#5678 Remove Mrinal and add Armel to OWNERS
  OWNERS
Labels: approved, lgtm

#5675 Adds `odo dev --no-watch`
  pkg/odo/cli/dev/dev.go
  pkg/watch/interface.go
  pkg/watch/mock.go
  pkg/watch/watch.go
  tests/helper/helper_dev.go
  tests/integration/devfile/cmd_dev_test.go
Labels: approved, lgtm, kind/feature

#5673 Removing bash for building images using podman/docker
  pkg/devfile/image/docker_compatible.go
  pkg/devfile/image/docker_compatible_test.go
Labels: kind/bug, approved, lgtm

#5688 Error when running odo list and there are no components deployed
  pkg/odo/cli/list/list.go
Labels: kind/bug, approved, lgtm

#5687 Add additional checks to golangci-lint (#5567)
  .golangci.yaml
  Makefile
  pkg/component/delete/delete.go
  pkg/component/starter_project.go
  pkg/deploy/deploy.go
  pkg/devfile/adapters/helper.go
  pkg/devfile/adapters/kubernetes/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/storage/utils.go
  pkg/devfile/image/image.go
  pkg/init/backend/interactive.go
  pkg/kclient/deployments.go
  pkg/kclient/kclient.go
  pkg/kclient/namespace.go
  pkg/kclient/oc_server.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/preference/registry/list.go
  pkg/odo/cli/project/delete.go
  pkg/odo/cli/project/set.go
  pkg/odo/cmdline/cobra.go
  pkg/odo/genericclioptions/context.go
  pkg/odo/genericclioptions/localprovider.go
  pkg/odo/genericclioptions/resolve.go
  pkg/odo/genericclioptions/runnable.go
  pkg/service/service.go
  pkg/service/service_binding_builder.go
  pkg/sync/adapter.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, lgtm, kind/task

#5692 change path to fix windows log
  .ibm/pipelines/windows-test.sh
Labels: approved, lgtm, kind/tests

#5689 Fix ignores files during sync
  pkg/dev/dev.go
  pkg/sync/adapter.go
  pkg/sync/sync.go
  pkg/sync/sync_test.go
  pkg/util/file_indexer.go
  pkg/watch/watch.go
  pkg/watch/watch_test.go
  tests/integration/devfile/cmd_dev_test.go
Labels: kind/bug, approved, lgtm

#5699 Favor use of "allowlist" and "denylist" in `wwhrd` license check config
  .wwhrd.yml
Labels: approved, lgtm, kind/task

#5618 Refactor labels
  pkg/application/labels/labels.go
  pkg/application/labels/labels_test.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/delete/delete.go
  pkg/component/delete/delete_test.go
  pkg/component/labels/labels.go
  pkg/component/labels/labels_test.go
  pkg/component/pushed_component.go
  pkg/deploy/deploy.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/storage/utils.go
  pkg/kclient/deployments.go
  pkg/kclient/deployments_test.go
  pkg/kclient/interface.go
  pkg/kclient/kclient.go
  pkg/kclient/kclient_test.go
  pkg/kclient/mock_Client.go
  pkg/kclient/services.go
  pkg/kclient/services_test.go
  pkg/labels/builder.go
  pkg/labels/constants.go
  pkg/labels/labels.go
  pkg/labels/labels_test.go
  pkg/labels/selector_builder.go
  pkg/service/link.go
  pkg/service/service.go
  pkg/storage/kubernetes.go
  pkg/storage/kubernetes_test.go
  pkg/storage/labels/labels.go
  pkg/storage/labels/labels_test.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  pkg/storage/utils.go
  pkg/testingutil/deployments.go
  pkg/testingutil/pods.go
  pkg/testingutil/services.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/helper/helper_run.go
Labels: approved, lgtm

#5628 refactoring generic-test
  .ibm/pipelines/kubernetes-tests.sh
  .ibm/pipelines/openshift-tests.sh
  tests/integration/generic_test.go
Labels: approved, lgtm, kind/tests

#5702 fix PATH for odo binary
  .ibm/pipelines/windows-test-script.ps1
Labels: approved, lgtm, kind/tests

#5696 Adds odo dev command reference
  docs/website/docusaurus.config.js
  docs/website/src/css/custom.css
  docs/website/versioned_docs/version-3.0.0/command-reference/dev.md
Labels: approved, lgtm, kind/documentation

#5705 Fix dev integration tests not finishing
  tests/helper/helper_dev.go
  tests/integration/devfile/cmd_dev_test.go
Labels: approved, lgtm, kind/tests
