Repository redhat-developer/odo, pull requests merged in 2023-03, with the labels that each got.

#6626 Use Node image compatible with Z and P environments
  tests/examples/source/nodejs/Dockerfile
Labels: area/testing, lgtm, ok-to-test

#6625 Fix failing tests due to notifications related to update in output
  tests/helper/helper_generic.go
  tests/integration/cmd_add_binding_test.go
  tests/integration/cmd_devfile_build_images_test.go
Labels: area/testing, lgtm

#6579 Support exec command
  pkg/deploy/deploy.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/kclient/interface.go
  pkg/kclient/jobs.go
  pkg/kclient/mock_Client.go
  pkg/libdevfile/generator/generators.go
  pkg/odo/cli/delete/component/component.go
  pkg/odo/cli/delete/component/component_test.go
  pkg/odo/cli/deploy/deploy.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/examples/source/devfiles/nodejs/devfile-deploy-exec.yaml
  tests/integration/cmd_delete_test.go
  tests/integration/cmd_devfile_deploy_test.go
Labels: lgtm

#6627 Document air-gapped env
  docs/website/docs/user-guides/advanced/air-gap-environment.md
Labels: lgtm, area/documentation

#6629 Make port-forwarding work on Podman with apps listening on the loopback interface, via a new `--forward-localhost` flag
  pkg/api/component.go
  pkg/dev/interface.go
  pkg/dev/podmandev/pod.go
  pkg/dev/podmandev/pod_test.go
  pkg/dev/podmandev/podmandev.go
  pkg/dev/podmandev/reconcile.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/kclient/interface.go
  pkg/libdevfile/libdevfile.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/podman/interface.go
  pkg/podman/podman.go
  pkg/portForward/interface.go
  pkg/portForward/kubeportforward/portForward.go
  pkg/portForward/kubeportforward/writer.go
  pkg/portForward/kubeportforward/writer_test.go
  pkg/portForward/podmanportforward/portForward.go
  pkg/remotecmd/kubeexec.go
  pkg/remotecmd/kubexec_test.go
  pkg/remotecmd/types.go
  pkg/watch/watch.go
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
Labels: lgtm, kind/feature, area/dev, area/odo-on-podman

#6622 Automatically use in-cluster Devfile registries if any
  pkg/api/preference.go
  pkg/init/backend/flags.go
  pkg/init/backend/flags_test.go
  pkg/init/init.go
  pkg/init/init_test.go
  pkg/kclient/dynamic.go
  pkg/kclient/interface.go
  pkg/kclient/mock_Client.go
  pkg/kclient/registry.go
  pkg/kclient/registry_test.go
  pkg/odo/cli/preference/remove/registry.go
  pkg/odo/cli/preference/view.go
  pkg/odo/cli/preference/view_test.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/preference/implem.go
  pkg/preference/machine_output.go
  pkg/preference/mock.go
  pkg/preference/preference.go
  pkg/registry/registry.go
  pkg/registry/registry_test.go
  tests/examples/manifests/clusterdevfileregistrieslists.yaml
  tests/examples/manifests/devfileregistrieslists.yaml
  tests/helper/helper_generic.go
  tests/integration/cmd_devfile_init_test.go
  tests/integration/cmd_devfile_registry_test.go
  tests/integration/cmd_pref_config_test.go
  tests/integration/interactive_init_test.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
  vendor/modules.txt
Labels: lgtm, kind/feature, area/registry

#6628 Remove podman from experimental mode
  docs/website/blog/2022-11-29-odo-v3.3.0.md
  docs/website/blog/2022-12-13-odo-v3.4.0.md
  docs/website/blog/2023-01-30-local-container-dev-on-podman.md
  docs/website/blog/2023-02-15-odo-v3.7.0.md
  docs/website/docs/command-reference/delete-component.md
  docs/website/docs/command-reference/describe-component.md
  docs/website/docs/command-reference/dev.md
  docs/website/docs/command-reference/docs-mdx/delete-component/delete_named_component_running-in.mdx
  docs/website/docs/command-reference/docs-mdx/delete-component/delete_running-in_with_access_to_devfile.mdx
  docs/website/docs/command-reference/list-component.md
  docs/website/docs/command-reference/list.md
  docs/website/docs/command-reference/logs.md
  docs/website/docs/overview/configure.md
  docs/website/docs/user-guides/advanced/experimental-mode.md.no
  pkg/component/component.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/feature/features.go
  pkg/odo/commonflags/main_test.go
  pkg/odo/commonflags/platform.go
  pkg/odo/commonflags/platform_test.go
  tests/helper/helper_dev.go
  tests/helper/helper_logs.go
  tests/integration/cmd_delete_test.go
  tests/integration/cmd_describe_component_test.go
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
  tests/integration/cmd_devfile_list_test.go
  tests/integration/cmd_logs_test.go
  tests/integration/generic_test.go
Labels: lgtm, kind/feature

#6604 Add mockgen installation to the script
  Makefile
  scripts/mockgen.sh
Labels: lgtm

#6639 Ignore errors that might happen when getting Devfile Registries from the cluster
  pkg/registry/registry.go
  pkg/registry/registry_test.go
Labels: kind/bug, lgtm, area/registry

#6640 Skip DevfileRegistriesList-related tests on non Kubernetes clusters
  tests/integration/cmd_devfile_init_test.go
  tests/integration/cmd_devfile_registry_test.go
  tests/integration/cmd_pref_config_test.go
  tests/integration/interactive_init_test.go
Labels: kind/bug, area/testing, lgtm

#6634 Bump to v3.8.0
  Dockerfile.rhel
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_any_registry_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_specific_registry_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_url_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_directory_with_sources_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_empty_directory_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/latest_versioned_devfile_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/versioned_devfile_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_deploy_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_init_output.mdx
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: lgtm

#6642 Fix potential issue with `odo describe component` integration tests when Podman is installed
  tests/integration/cmd_describe_component_test.go
Labels: kind/bug, area/testing, lgtm

#6659 Fix error handling when trying to delete remote resources not present in Devfile
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
Labels: kind/bug, lgtm

#6660 Fix issue with conflicting ports when starting multiple Dev sessions on Podman
  pkg/util/util.go
  pkg/util/util_test.go
Labels: kind/bug, lgtm, area/odo-on-podman

#6653 Document Podman limitations
  docs/website/docs/development/architecture/podman-support-limitations.md
Labels: lgtm, area/documentation

#6633 Fix: Starterproject not replace existing devfile stack files of the context dir
  pkg/registry/registry.go
  pkg/registry/registry_test.go
  pkg/registry/starter_project.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/examples/source/devfiles/zips/starterproject-with-conflicts-and-empty-dir.zip
  tests/examples/source/devfiles/zips/starterproject-with-conflicts.zip
  tests/examples/source/devfiles/zips/starterproject-with-devfile.zip
  tests/examples/source/devfiles/zips/starterproject-with-no-conflicts-and-empty-dir.zip
  tests/examples/source/devfiles/zips/starterproject-with-no-conflicts.zip
  tests/integration/cmd_devfile_init_test.go
Labels: kind/bug, lgtm

#6673 Fix UX issue when exec command fails to run as part of a deploy command
  pkg/deploy/deploy.go
Labels: kind/bug, area/UX, lgtm, area/deploy

#6672 Documentation: How odo supports exec on Deploy
  docs/website/docs/command-reference/deploy.md
  docs/website/docs/development/devfile.md
Labels: lgtm, kind/feature, area/documentation

#6684 Fix: `odo init` does not ask for starter project if the Devfile stack contains extra files
  pkg/init/init.go
  pkg/init/interface.go
  pkg/init/mock.go
  pkg/odo/cli/init/init.go
  tests/integration/interactive_init_test.go
Labels: kind/bug, lgtm

#6688 odo dev/deploy should display a warning about default namespace on cluster
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/genericclioptions/util.go
  tests/helper/helper_dev.go
  tests/helper/helper_generic.go
  tests/integration/cmd_dev_test.go
  tests/integration/cmd_devfile_deploy_test.go
Labels: kind/bug, lgtm

#6689 Add doc and blog post about using in-cluster Devfile registries
  docs/website/blog/2023-03-22-deploying-and-using-in-cluster-devfile-registry.md
  docs/website/docs/user-guides/advanced/in-cluster-devfile-registry.md
  docs/website/static/img/blog/deploying-and-using-in-cluster-devfile-registry/preview-url-in-cluster-devfile-registry.png
  docs/website/static/img/devfile.png
Labels: lgtm, area/documentation

#6691 Documentation: Debugging with OpenShift Toolkit
  docs/website/docs/assets/user-guides/advanced/Add Breakpoint.png
  docs/website/docs/assets/user-guides/advanced/Application Debugged.png
  docs/website/docs/assets/user-guides/advanced/Debug Session Starts.png
  docs/website/docs/assets/user-guides/advanced/Ping Application.png
  docs/website/docs/assets/user-guides/advanced/Prerequisite Setup.png
  docs/website/docs/assets/user-guides/advanced/Select Debug Session.png
  docs/website/docs/assets/user-guides/advanced/Start Dev Session.png
  docs/website/docs/assets/user-guides/advanced/Wait until Dev Session finishes.png
  docs/website/docs/user-guides/advanced/debugging-with-openshift-toolkit.md
Labels: lgtm, kind/feature, area/documentation

#6705 Get DEVFILE_REGISTRY value for tests, to use local Registry
  .ibm/pipelines/windows-test-script.ps1
  .ibm/pipelines/windows-test.sh
  scripts/devfile-registry/ci-values.yaml
  tests/helper/helper_generic.go
  tests/integration/cmd_devfile_registry_test.go
Labels: area/testing, lgtm
