Repository redhat-developer/odo, pull requests merged in 2023-06, with the labels that each got.

#6863 Make sure the "Syncing files into the container" spinner is displayed on Podman
  pkg/dev/podmandev/podmandev.go
  tests/integration/cmd_dev_test.go
Labels: kind/bug, area/UX, lgtm, area/dev, area/odo-on-podman

#6857 Add an `odo run` command to manually execute command during `odo dev`
  cmd/odo/help_test.go
  pkg/component/component.go
  pkg/component/delete/delete.go
  pkg/component/delete/delete_test.go
  pkg/dev/common/run.go
  pkg/dev/interface.go
  pkg/dev/kubedev/run.go
  pkg/dev/mock.go
  pkg/dev/podmandev/run.go
  pkg/exec/exec_test.go
  pkg/libdevfile/errors.go
  pkg/libdevfile/libdevfile.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/errors/errors.go
  pkg/odo/cli/run/run.go
  pkg/platform/interface.go
  pkg/platform/mock.go
  pkg/podman/component.go
  pkg/podman/mock.go
  pkg/podman/pods.go
  tests/examples/source/devfiles/nodejs/devfile-for-run.yaml
  tests/integration/cmd_run_test.go
Labels: lgtm, kind/feature

#6870 Skip tests if all changes in docs
  .github/workflows/podman-test.yaml
  .ibm/pipelines/functions.sh
  .ibm/pipelines/kubernetes-tests.sh
  .ibm/pipelines/nocluster-tests.sh
  .ibm/pipelines/openshift-tests.sh
  .ibm/pipelines/openshift-unauth-tests.sh
  .ibm/pipelines/unit-tests.sh
  .ibm/pipelines/validate.sh
  .ibm/pipelines/windows-test.sh
Labels: area/testing, lgtm, kind/feature

#6872 Mark issues and pull requests as stale
  .github/workflows/stale.yaml
Labels: lgtm

#6865 Display outputs when executing `odo run`
  docs/website/docs/command-reference/run.md
  pkg/component/delete/delete.go
  pkg/component/execute_terminating.go
  pkg/component/handler.go
  pkg/deploy/deploy.go
  pkg/dev/common/run.go
  pkg/dev/kubedev/innerloop.go
  pkg/dev/podmandev/reconcile.go
  pkg/exec/exec.go
  pkg/podman/exec.go
  tests/examples/source/devfiles/nodejs/devfile-for-run.yaml
  tests/integration/cmd_run_test.go
Labels: lgtm, kind/feature

#6875 Build nightly binaries of odo and make them available (via IBM Cloud Object Storage)
  .github/workflows/nightly-build.yaml
  docs/website/docs/overview/installation.md
Labels: lgtm, area/release-eng

#6874 Unit tests/inject test clientset
  cmd/cli-doc/cli-doc.go
  cmd/odo/alizer_test.go
  cmd/odo/common_test.go
  cmd/odo/help_test.go
  cmd/odo/odo.go
  pkg/alizer/alizer_test.go
  pkg/machineoutput/types.go
  pkg/odo/cli/add/add.go
  pkg/odo/cli/add/binding/binding.go
  pkg/odo/cli/alizer/alizer.go
  pkg/odo/cli/build_images/build_images.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/create/create.go
  pkg/odo/cli/create/namespace/namespace.go
  pkg/odo/cli/delete/component/component.go
  pkg/odo/cli/delete/delete.go
  pkg/odo/cli/delete/namespace/namespace.go
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/cli/describe/binding.go
  pkg/odo/cli/describe/component.go
  pkg/odo/cli/describe/describe.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/init/init.go
  pkg/odo/cli/list/binding/binding.go
  pkg/odo/cli/list/component/list.go
  pkg/odo/cli/list/list.go
  pkg/odo/cli/list/namespace/namespace.go
  pkg/odo/cli/list/services/services.go
  pkg/odo/cli/login/login.go
  pkg/odo/cli/logout/logout.go
  pkg/odo/cli/logs/logs.go
  pkg/odo/cli/preference/add/add.go
  pkg/odo/cli/preference/add/registry.go
  pkg/odo/cli/preference/preference.go
  pkg/odo/cli/preference/remove/registry.go
  pkg/odo/cli/preference/remove/remove.go
  pkg/odo/cli/preference/set.go
  pkg/odo/cli/preference/unset.go
  pkg/odo/cli/preference/view.go
  pkg/odo/cli/registry/registry.go
  pkg/odo/cli/remove/binding/binding.go
  pkg/odo/cli/remove/remove.go
  pkg/odo/cli/run/run.go
  pkg/odo/cli/set/namespace/namespace.go
  pkg/odo/cli/set/set.go
  pkg/odo/cli/telemetry/telemetry.go
  pkg/odo/cli/version/version.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/odo/genericclioptions/runnable.go
  tests/integration/cmd_analyze_test.go
Labels: area/testing, lgtm, kind/code-refactoring

#6891 Stop test as soon as expectation is verified
  tests/integration/interactive_deploy_test.go
  tests/integration/interactive_init_test.go
Labels: kind/bug, area/testing, lgtm

#6871 [Dogfooding] Create website deploy previews for PRs using `odo deploy`
  .github/workflows/pr-website.yaml
  docs/website/.dockerignore
  docs/website/.kubernetes/resources.yaml
  docs/website/Dockerfile
  docs/website/devfile.yaml
Labels: area/testing, lgtm

#6907 Improve website PR preview workflow
  .github/workflows/pr-website.yaml
Labels: area/testing, lgtm, area/outerloop

#6886 Refactor StartDevMode to return a single object instead of multiple args
  docs/website/docs/command-reference/docs-mdx/init/registry_list_output.mdx
  tests/documentation/user-guides/doc_user_guides_quickstart_test.go
  tests/e2escenarios/e2e_test.go
  tests/helper/helper_dev.go
  tests/integration/cmd_add_binding_test.go
  tests/integration/cmd_delete_test.go
  tests/integration/cmd_describe_component_test.go
  tests/integration/cmd_describe_list_binding_test.go
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
  tests/integration/cmd_devfile_deploy_test.go
  tests/integration/cmd_devfile_list_test.go
  tests/integration/cmd_logs_test.go
  tests/integration/cmd_remove_binding_test.go
  tests/integration/cmd_run_test.go
Labels: area/testing, lgtm, kind/code-refactoring

#6910 Add --sync-git-dir flag to odo dev
  docs/website/docs/development/architecture/how-odo-works.md
  pkg/odo/cli/dev/dev.go
  pkg/util/file_indexer.go
  pkg/util/file_indexer_test.go
  tests/helper/helper_dev.go
  tests/integration/cmd_dev_test.go
Labels: lgtm, kind/feature

#6916 Fix GitHub labels in release changelog generator script and PR template
  .github/PULL_REQUEST_TEMPLATE.md
  scripts/changelog-script.sh
Labels: lgtm, area/release-eng, area/refactoring

#6904 Replace odo delete component integration with unit tests
  cmd/odo/alizer_test.go
  cmd/odo/common_test.go
  cmd/odo/delete_test.go
  cmd/odo/doc.go
  pkg/kclient/all_test.go
  pkg/kclient/fakeclient.go
  pkg/kclient/kclient.go
  pkg/log/status.go
  pkg/odo/cli/delete/component/component.go
  pkg/odo/cli/delete/component/component_test.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/podman/podman_test.go
  tests/integration/cmd_delete_test.go
Labels: area/testing, lgtm, area/refactoring

#6905 Do not return an error in `odo analyze` if current directory contains an invalid Devfile
  cmd/odo/alizer_test.go
  cmd/odo/common_test.go
  cmd/odo/delete_test.go
  pkg/dev/kubedev/kubedev.go
  pkg/dev/podmandev/podmandev.go
  pkg/devfile/location/location.go
  pkg/odo/cli/add/binding/binding.go
  pkg/odo/cli/alizer/alizer.go
  pkg/odo/genericclioptions/devfile.go
  pkg/odo/genericclioptions/runnable.go
  pkg/registry/registry.go
  pkg/registry/starter_project.go
  pkg/testingutil/filesystem/fake_fs.go
  pkg/util/util.go
  pkg/util/util_test.go
  pkg/watch/file_watcher.go
Labels: kind/bug, lgtm

#6917 Do not necessarily error out if `odo dev` is stopped via `Ctrl+C`
  cmd/cli-doc/cli-doc.go
  cmd/odo/common_test.go
  cmd/odo/help_test.go
  cmd/odo/odo.go
  pkg/dev/kubedev/cleanup.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/delete/component/component.go
  pkg/odo/cli/delete/namespace/namespace.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/preference/set.go
  pkg/odo/cli/preference/unset.go
  pkg/odo/cli/ui/common.go
  pkg/odo/genericclioptions/runnable.go
  pkg/preference/implem.go
  pkg/sync/copy.go
  pkg/watch/watch.go
  pkg/watch/watch_test.go
  tests/examples/source/devfiles/nodejs/devfile-with-container-failing-to-terminate-before-cleanup-timeout.yaml
  tests/helper/helper_dev.go
  tests/integration/cmd_dev_test.go
Labels: kind/bug, lgtm, area/dev, area/refactoring

#6928 Temporarily downgrade Podman on GitHub to fix CI failures for Podman tests
  .github/workflows/podman-test.yaml
Labels: kind/bug, area/testing, lgtm, area/infra, area/odo-on-podman

#6920 Disable service binding related integration tests
  .ibm/pipelines/windows-test-script.ps1
  .ibm/pipelines/windows-test.sh
  scripts/ansible/Cluster/kubernetes-cluster/README.md
  scripts/devfile-registry/ci-values.yaml
  tests/examples/source/devfiles/nodejs/devfile-fsgroup.yaml
  tests/integration/cmd_add_binding_test.go
  tests/integration/cmd_describe_list_binding_test.go
  tests/integration/cmd_dev_test.go
  tests/integration/cmd_devfile_deploy_test.go
  tests/integration/cmd_list_services_test.go
  tests/integration/cmd_remove_binding_test.go
  tests/integration/interactive_add_binding_test.go
Labels: area/testing, lgtm

#6929 Fix service binding skip on Windows
  .ibm/pipelines/windows-test-script.ps1
Labels: area/testing, lgtm

#6913 Add podman version to odo version output
  docs/website/docs/command-reference/json-output.md
  docs/website/docs/command-reference/version.md
  pkg/api/version.go
  pkg/kclient/oc_server.go
  pkg/odo/cli/version/version.go
  tests/helper/helper_generic.go
  tests/helper/helper_podman.go
  tests/integration/cmd_dev_test.go
  tests/integration/generic_test.go
Labels: lgtm, kind/feature

#6931 Set FsGroup for spring boot test
  tests/documentation/user-guides/doc_user_guides_quickstart_test.go
  tests/helper/helper_devfile.go
Labels: area/testing, lgtm

#6915 Implement API endpoints
  ododevapispec.yaml
  pkg/apiserver-gen/README.md
  pkg/apiserver-impl/api_default_service.go
  pkg/apiserver-impl/starterserver.go
  pkg/component/describe/describe.go
  pkg/dev/interface.go
  pkg/odo/cli/describe/component.go
  pkg/odo/cli/dev/dev.go
  pkg/watch/watch.go
  tests/integration/cmd_dev_api_server_test.go
Labels: lgtm, kind/feature, area/dev

#6933 Fix potential issue in `odo version` nightly tests if user does not have permission to get the OpenShift version
  tests/helper/helper_generic.go
  tests/integration/generic_test.go
Labels: kind/bug, area/testing, lgtm

#6922 List namespace right after namespace has been created
  docs/website/docs/command-reference/docs-mdx/create-namespace/create_namespace.mdx
  docs/website/docs/command-reference/docs-mdx/create-namespace/create_project.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/create_namespace_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/create_project_output.mdx
  pkg/odo/cli/create/namespace/namespace.go
  tests/helper/helper_documentation.go
  tests/integration/cmd_namespace_test.go
Labels: kind/bug, lgtm

#6935 Bump version to 3.12.0
  Dockerfile.rhel
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_any_registry_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_specific_registry_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_url_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_directory_with_sources_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_empty_directory_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/latest_versioned_devfile_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/versioned_devfile_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_deploy_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_init_output.mdx
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: lgtm, area/release-eng

#6938 Document and return JSON data for API errors
  ododevapispec.yaml
  pkg/apiserver-gen/README.md
  pkg/apiserver-impl/api_default_service.go
Labels: kind/bug, lgtm

#6914 Watch for new pods when logs --follow
  pkg/exec/exec_test.go
  pkg/logs/logs.go
  pkg/odo/cli/logs/logs.go
  pkg/platform/interface.go
  pkg/platform/mock.go
  pkg/podman/mock.go
  pkg/podman/pods.go
  tests/examples/source/devfiles/nodejs/devfile-deploy-functional-pods.yaml
  tests/integration/cmd_logs_test.go
Labels: lgtm, kind/feature

#6940 Add `.gitattributes` file with Git-style path matchers customizing how PR changed files appear on GitHub
  .gitattributes
Labels: lgtm, kind/task

#6830 Flake: Attempt at fixing Personalize configuration
  tests/integration/interactive_init_test.go
Labels: area/testing, lgtm, flake
