Repository redhat-developer/odo, pull requests merged in 2023-09, with the labels that each got.

#7062 [ui] Edit resources
  ododevapispec.yaml
  pkg/apiserver-gen/.openapi-generator/FILES
  pkg/apiserver-gen/go/api.go
  pkg/apiserver-gen/go/api_devstate.go
  pkg/apiserver-gen/go/model__devstate_resource__resource_name__patch_request.go
  pkg/apiserver-impl/devstate.go
  pkg/apiserver-impl/devstate/components.go
  pkg/apiserver-impl/swagger-ui/swagger.yaml
  pkg/apiserver-impl/ui/index.html
  pkg/apiserver-impl/ui/main.32ba016d46c6a398.js
  pkg/apiserver-impl/ui/main.dccb7ac93e413890.js
  ui/cypress/e2e/spec.cy.ts
  ui/src/app/api-gen/.openapi-generator/FILES
  ui/src/app/api-gen/api/devstate.service.ts
  ui/src/app/api-gen/model/devstateResourceResourceNamePatchRequest.ts
  ui/src/app/api-gen/model/models.ts
  ui/src/app/forms/resource/resource.component.html
  ui/src/app/forms/resource/resource.component.ts
  ui/src/app/services/devstate.service.ts
  ui/src/app/tabs/resources/resources.component.html
  ui/src/app/tabs/resources/resources.component.ts
Labels: lgtm, kind/feature

#7063 Add a Devfile dependency for commands
  pkg/odo/cli/alizer/alizer.go
  pkg/odo/cli/delete/component/component.go
  pkg/odo/cli/describe/binding.go
  pkg/odo/cli/describe/component.go
  pkg/odo/cli/init/init.go
  pkg/odo/cli/list/services/services.go
  pkg/odo/cli/preference/add/registry.go
  pkg/odo/cli/preference/remove/registry.go
  pkg/odo/cli/preference/set.go
  pkg/odo/cli/preference/unset.go
  pkg/odo/cli/preference/view.go
  pkg/odo/cli/registry/registry.go
  pkg/odo/cli/set/namespace/namespace.go
  pkg/odo/genericclioptions/devfile.go
  pkg/odo/genericclioptions/runnable.go
  tests/helper/helper_filesystem.go
  tests/integration/cmd_delete_test.go
  tests/integration/cmd_describe_component_test.go
  tests/integration/cmd_describe_list_binding_test.go
  tests/integration/cmd_devfile_registry_test.go
  tests/integration/cmd_list_services_test.go
  tests/integration/cmd_pref_config_test.go
Labels: kind/bug, lgtm

#7069 Fix invalid link to installation page from all release blog posts
  .github/workflow-data/release-management/blog-post-header.tpl.md
  docs/website/blog/2022-07-21-odo-v3-beta2.md
  docs/website/blog/2022-08-18-odo-v3-beta3.md
  docs/website/blog/2022-09-01-odo-v3-rc1.md
  docs/website/blog/2022-09-22-odo-v3-rc2.md
  docs/website/blog/2022-11-29-odo-v3.3.0.md
  docs/website/blog/2022-12-13-odo-v3.4.0.md
  docs/website/blog/2023-01-04-odo-v3.5.0.md
  docs/website/blog/2023-01-24-odo-v3.6.0.md
  docs/website/blog/2023-02-15-odo-v3.7.0.md
  docs/website/blog/2023-03-08-odo-v3.8.0.md
  docs/website/blog/2023-04-05-odo-v3.9.0.md
  docs/website/blog/2023-05-04-odo-v3.10.0.md
  docs/website/blog/2023-06-27-odo-v3.12.0.md
  docs/website/blog/2023-07-24-odo-v3.13.0.md
  docs/website/blog/2023-08-22-odo-v3.14.0.md
  docs/website/docusaurus.config.js
Labels: kind/bug, lgtm, area/documentation

#7074 Display Git commit ID in output of `odo` commands where the version is shown
  Makefile
  pkg/log/status.go
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/init/init.go
  pkg/odo/genericclioptions/init.go
  scripts/rpm-prepare.sh
  tests/documentation/command-reference/doc_command_reference_init_test.go
  tests/documentation/user-guides/doc_user_guides_quickstart_test.go
  tests/helper/helper_documentation.go
  tests/helper/helper_generic.go
  tests/integration/generic_test.go
  tests/integration/interactive_init_test.go
Labels: lgtm, kind/task

#7075 Make sure to run parallel commands part of a composite command in parallel
  pkg/component/delete/delete.go
  pkg/libdevfile/command.go
  pkg/libdevfile/command_composite_parallel.go
Labels: kind/bug, lgtm, area/devfile-spec

#7073 [ui] Update commands
  ododevapispec.yaml
  pkg/apiserver-gen/.openapi-generator/FILES
  pkg/apiserver-gen/go/api.go
  pkg/apiserver-gen/go/api_devstate.go
  pkg/apiserver-gen/go/model__devstate_apply_command__command_name__patch_request.go
  pkg/apiserver-gen/go/model__devstate_composite_command__command_name__patch_request.go
  pkg/apiserver-gen/go/model__devstate_exec_command__command_name__patch_request.go
  pkg/apiserver-impl/devstate.go
  pkg/apiserver-impl/devstate/commands.go
  pkg/apiserver-impl/swagger-ui/swagger.yaml
  pkg/apiserver-impl/ui/index.html
  pkg/apiserver-impl/ui/main.30e0dd4eb9375796.js
  pkg/apiserver-impl/ui/main.9400449aa2437590.js
  ui/cypress/e2e/spec.cy.ts
  ui/src/app/api-gen/.openapi-generator/FILES
  ui/src/app/api-gen/api/devstate.service.ts
  ui/src/app/api-gen/model/devstateApplyCommandCommandNamePatchRequest.ts
  ui/src/app/api-gen/model/devstateCompositeCommandCommandNamePatchRequest.ts
  ui/src/app/api-gen/model/devstateExecCommandCommandNamePatchRequest.ts
  ui/src/app/api-gen/model/models.ts
  ui/src/app/controls/select-container/select-container.component.ts
  ui/src/app/forms/command-apply/command-apply.component.html
  ui/src/app/forms/command-apply/command-apply.component.ts
  ui/src/app/forms/command-composite/command-composite.component.html
  ui/src/app/forms/command-composite/command-composite.component.ts
  ui/src/app/forms/command-exec/command-exec.component.html
  ui/src/app/forms/command-exec/command-exec.component.ts
  ui/src/app/forms/command-image/command-image.component.html
  ui/src/app/forms/command-image/command-image.component.ts
  ui/src/app/lists/commands-list/commands-list.component.html
  ui/src/app/lists/commands-list/commands-list.component.ts
  ui/src/app/services/devstate.service.ts
  ui/src/app/tabs/commands/commands.component.html
  ui/src/app/tabs/commands/commands.component.ts
Labels: lgtm, kind/feature

#7078 Display icon in metadata
  pkg/apiserver-impl/ui/index.html
  pkg/apiserver-impl/ui/main.d468134bf8c5f727.js
  pkg/apiserver-impl/ui/main.d81b67faa7ca223c.js
  ui/src/app/forms/metadata/metadata.component.css
  ui/src/app/forms/metadata/metadata.component.html
Labels: lgtm, kind/feature

#7080 Fix API Server panic when volume component has no `ephemeral` field set
  pkg/apiserver-impl/devstate/content.go
  pkg/apiserver-impl/devstate/content_test.go
Labels: kind/bug, lgtm

#7092 Add troubleshooting explaining how to workaround port forwarding issues with the Podman remote client
  docs/website/docs/troubleshooting.md
Labels: lgtm, area/documentation

#7093 Make sure a Deploy command is present in the Devfile before auto-applying components
  pkg/deploy/deploy.go
  tests/examples/source/devfiles/nodejs/devfile-autobuild-deploybydefault-no-deploy-cmd.yaml
  tests/integration/cmd_devfile_deploy_test.go
  tests/integration/interactive_deploy_test.go
Labels: kind/bug, lgtm, area/deploy

#7090 Ignore devstate when existing process name is not odo + delete devstate files with `odo delete component`
  cmd/odo/common_test.go
  cmd/odo/delete_test.go
  docs/website/docs/troubleshooting.md
  go.mod
  go.sum
  pkg/odo/cli/delete/component/component.go
  pkg/odo/cli/delete/component/component_test.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/state/interface.go
  pkg/state/process_unix.go
  pkg/state/process_windows.go
  pkg/state/state.go
  pkg/testingutil/system/default.go
  pkg/testingutil/system/fake.go
  pkg/testingutil/system/system.go
  tests/helper/helper_dev.go
  tests/helper/helper_nowindows.go
  tests/helper/helper_windows.go
  tests/integration/cmd_dev_test.go
  vendor/github.com/mitchellh/go-ps/.gitignore
  vendor/github.com/mitchellh/go-ps/.travis.yml
  vendor/github.com/mitchellh/go-ps/LICENSE.md
  vendor/github.com/mitchellh/go-ps/README.md
  vendor/github.com/mitchellh/go-ps/Vagrantfile
  vendor/github.com/mitchellh/go-ps/process.go
  vendor/github.com/mitchellh/go-ps/process_darwin.go
  vendor/github.com/mitchellh/go-ps/process_freebsd.go
  vendor/github.com/mitchellh/go-ps/process_linux.go
  vendor/github.com/mitchellh/go-ps/process_solaris.go
  vendor/github.com/mitchellh/go-ps/process_unix.go
  vendor/github.com/mitchellh/go-ps/process_windows.go
  vendor/modules.txt
Labels: lgtm, kind/feature, area/dev

#7005 Replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`
  .wwhrd.yml
  go.mod
  go.sum
  pkg/libdevfile/component_kubernetes_utils.go
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/modules.txt
Labels: lgtm, ok-to-test, area/dependency, area/refactoring

#7097 Make warning messages more visible
  pkg/log/status.go
  pkg/log/status_test.go
  pkg/odo/genericclioptions/util.go
  tests/helper/helper_documentation.go
Labels: kind/bug, area/UX, lgtm

#7096 Bump to v3.15.0
  Dockerfile.rhel
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_any_registry_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_specific_registry_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_url_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_with_run-port_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_directory_with_sources_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_empty_directory_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/latest_versioned_devfile_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/versioned_devfile_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_deploy_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_podman_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_podman_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_podman_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_podman_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_init_output.mdx
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: lgtm
