Repository redhat-developer/odo, pull requests merged in 2023-05, with the labels that each got.

#6771 Wait when Build command fails
  pkg/dev/kubedev/components.go
  pkg/dev/kubedev/innerloop.go
  pkg/dev/kubedev/kubedev.go
  pkg/dev/podmandev/podmandev.go
  pkg/dev/podmandev/reconcile.go
  pkg/watch/status.go
  pkg/watch/watch.go
  pkg/watch/watch_test.go
  tests/helper/helper_dev.go
  tests/integration/cmd_dev_test.go
Labels: lgtm, kind/code-refactoring

#6766 Use custom address for port forwarding
  docs/website/docs/command-reference/dev.md
  pkg/dev/interface.go
  pkg/dev/kubedev/innerloop.go
  pkg/dev/podmandev/pod.go
  pkg/dev/podmandev/pod_test.go
  pkg/dev/podmandev/reconcile.go
  pkg/kclient/interface.go
  pkg/kclient/mock_Client.go
  pkg/kclient/port_forwarding.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/dev/dev_test.go
  pkg/portForward/interface.go
  pkg/portForward/kubeportforward/portForward.go
  pkg/portForward/kubeportforward/portForward_test.go
  pkg/portForward/kubeportforward/writer.go
  pkg/portForward/kubeportforward/writer_test.go
  pkg/portForward/podmanportforward/portForward.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/examples/source/devfiles/go-devfiles/devfile.yaml
  tests/helper/helper_dev.go
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
Labels: lgtm, kind/feature

#6783 Bump version to 3.10.0
  Dockerfile.rhel
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_any_registry_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_specific_registry_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_url_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_directory_with_sources_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_empty_directory_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/latest_versioned_devfile_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/versioned_devfile_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_deploy_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_init_output.mdx
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: lgtm

#6782 dev states proposal
  docs/proposals/dev-states.md
Labels: lgtm, area/documentation

#6785 Allow passing extra flags to Podman/Docker
  docs/website/docs/command-reference/build-images.md
  docs/website/docs/command-reference/deploy.md
  docs/website/docs/command-reference/dev.md
  docs/website/docs/overview/configure.md
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/prerequisites.mdx
  pkg/config/config.go
  pkg/devfile/image/docker_compatible.go
  pkg/devfile/image/docker_compatible_test.go
  pkg/devfile/image/image.go
  pkg/podman/component.go
  pkg/podman/exec.go
  pkg/podman/inspect.go
  pkg/podman/logs.go
  pkg/podman/podman.go
  pkg/podman/pods.go
  tests/examples/source/devfiles/nodejs/devfile-composite-apply-commands.yaml
  tests/integration/cmd_dev_test.go
  tests/integration/cmd_devfile_build_images_test.go
  tests/integration/cmd_devfile_deploy_test.go
Labels: lgtm

#6696 Fix HotReloadCapable Build command
  docs/website/docs/command-reference/dev.md
  docs/website/docs/development/architecture/how-odo-works.md
  docs/website/docs/development/devfile.md
  pkg/component/delete/delete.go
  pkg/component/exec_handler.go
  pkg/dev/kubedev/innerloop.go
  pkg/dev/podmandev/reconcile.go
  tests/examples/source/angular/.browserslistrc
  tests/examples/source/angular/.editorconfig
  tests/examples/source/angular/.gitignore
  tests/examples/source/angular/README.md
  tests/examples/source/angular/angular.json
  tests/examples/source/angular/devfile.yaml
  tests/examples/source/angular/karma.conf.js
  tests/examples/source/angular/package-lock.json
  tests/examples/source/angular/package.json
  tests/examples/source/angular/src/app/app-routing.module.ts
  tests/examples/source/angular/src/app/app.component.css
  tests/examples/source/angular/src/app/app.component.html
  tests/examples/source/angular/src/app/app.component.spec.ts
  tests/examples/source/angular/src/app/app.component.ts
  tests/examples/source/angular/src/app/app.module.ts
  tests/examples/source/angular/src/assets/.gitkeep
  tests/examples/source/angular/src/environments/environment.prod.ts
  tests/examples/source/angular/src/environments/environment.ts
  tests/examples/source/angular/src/favicon.ico
  tests/examples/source/angular/src/index.html
  tests/examples/source/angular/src/main.ts
  tests/examples/source/angular/src/polyfills.ts
  tests/examples/source/angular/src/styles.css
  tests/examples/source/angular/src/test.ts
  tests/examples/source/angular/tsconfig.app.json
  tests/examples/source/angular/tsconfig.json
  tests/examples/source/angular/tsconfig.spec.json
  tests/examples/source/java-quarkus/devfile.yaml
  tests/integration/cmd_dev_test.go
Labels: kind/bug, lgtm

#6775 Blog: Helm integration with odo
  docs/website/blog/deploy-and-connect-to-microservice-using-helm-and-exec.md
Labels: lgtm, area/documentation

#6789 Check latest version from index instead of using hardcoded value
  tests/helper/helper_registry.go
  tests/integration/cmd_devfile_init_test.go
Labels: kind/bug, area/testing, lgtm

#6233 Check if namespace exists before the delete confirmation
  docs/website/docs/command-reference/docs-mdx/delete-namespace/delete_namespace.mdx
  docs/website/docs/command-reference/docs-mdx/delete-namespace/delete_project.mdx
  pkg/odo/cli/delete/namespace/namespace.go
  pkg/odo/cli/delete/namespace/namespace_test.go
Labels: kind/bug, lgtm, ok-to-test

#6798 Update the release doc with Sprint 235 updates
  docs/website/blog/2023-05-04-odo-v3.10.0.md
Labels: lgtm

#6802 Delete previous pod and creates new ond when modifying devfile on podman
  pkg/dev/podmandev/pod.go
  pkg/dev/podmandev/pod_test.go
  pkg/dev/podmandev/podmandev.go
  pkg/dev/podmandev/reconcile.go
  tests/integration/cmd_dev_test.go
Labels: lgtm, kind/feature

#6810 Reuse same volumes when devfile is modified, on podman
  docs/website/docs/development/architecture/podman-support-limitations.md
  pkg/dev/podmandev/cleanup.go
  pkg/dev/podmandev/reconcile.go
  pkg/odo/cli/delete/component/component.go
  pkg/odo/cli/delete/component/component_test.go
  pkg/podman/interface.go
  pkg/podman/mock.go
  pkg/podman/podman.go
Labels: lgtm, kind/feature

#6808 Add a timeout when initializing the Podman client (broken Podman should not affect `odo dev` on cluster)
  docs/website/docs/overview/configure.md
  pkg/config/config.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/podman/interface.go
  pkg/podman/mock.go
  pkg/podman/podman.go
  pkg/podman/version.go
  pkg/segment/context/context.go
  tests/helper/helper_filesystem.go
  tests/helper/helper_generic.go
  tests/integration/cmd_dev_test.go
Labels: kind/bug, lgtm, area/dev

#6800 Fix: `odo init` overwrites personalized configuration when downloading starter project
  pkg/init/init.go
  pkg/init/init_test.go
  pkg/init/interface.go
  pkg/init/mock.go
  pkg/odo/cli/init/init.go
  pkg/registry/interface.go
  pkg/registry/mock.go
  pkg/registry/registry.go
  pkg/registry/registry_test.go
  tests/integration/interactive_init_test.go
Labels: kind/bug, lgtm

#6816 Wait after killing odo during integration test
  tests/integration/cmd_dev_test.go
Labels: kind/bug, area/testing, lgtm

#6793 Add spinner when determining a devfile using alizer
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_directory_with_sources_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_init_output.mdx
  pkg/init/backend/alizer.go
  pkg/init/init.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/genericclioptions/runnable.go
Labels: lgtm

#6818 Move parent devfiles in specific directories
  pkg/libdevfile/testdata/child-devfile-commands-only.yaml
  pkg/libdevfile/testdata/child-devfile-complete.yaml
  pkg/libdevfile/testdata/child-devfile-components-only.yaml
  pkg/libdevfile/testdata/child-devfile.yaml
  pkg/libdevfile/testdata/parent/commands-only/parent-devfile-commands-only.yaml
  pkg/libdevfile/testdata/parent/complete/parent-devfile.yaml
  pkg/libdevfile/testdata/parent/components-only/parent-devfile-components-only.yaml
  pkg/libdevfile/testdata/parent/empty/parent-devfile-empty.yaml
  pkg/libdevfile/uris_test.go
Labels: kind/bug, area/testing, lgtm

#6823 Do not run 'odo-infra-stage-test' Workflow on PRs if not needed
  .github/workflows/infra-test.yaml
Labels: kind/bug, area/testing, lgtm, area/infra

#6825 Only run cluster tests on nightly tests, not nocluster tests
  scripts/openshiftci-Nightly-SBO-tests.sh
  scripts/openshiftci-periodic-tests.sh
Labels: kind/bug, area/testing, lgtm

#6834 Replace deprecated `--slow-spec-threshold` Ginkgo flag with `--poll-progress-after`
  Makefile
Labels: area/testing, lgtm

#6837 Use odo logo instead of author image in blog posts
  .github/workflow-data/release-management/blog-post-header.tpl.md
  docs/website/blog/2020-09-24-odo-v2.0.0-ga-release.md
  docs/website/blog/2020-10-28-odo-v2.0.1-release.md
  docs/website/blog/2021-05-04-odo-v2.2.0-breaking-changes.md
  docs/website/blog/2021-12-14-odo-v2.4.3.md
  docs/website/blog/2022-01-14-odo-v2.5.0.md
  docs/website/blog/2022-05-02-odo-v3-alpha1.md
  docs/website/blog/2022-06-14-binding-external-service.md
  docs/website/blog/2022-06-30-binding-database-service-without-sbo.md
  docs/website/blog/2022-07-01-odo-v3-beta1.md
  docs/website/blog/2022-07-21-odo-v3-beta2.md
  docs/website/blog/2022-08-18-odo-v3-beta3.md
  docs/website/blog/2022-09-01-odo-v3-rc1.md
  docs/website/blog/2022-09-22-odo-v3-rc2.md
  docs/website/blog/2022-11-29-odo-v3.3.0.md
  docs/website/blog/2022-12-13-odo-v3.4.0.md
  docs/website/blog/2023-01-04-odo-v3.5.0.md
  docs/website/blog/2023-01-24-odo-v3.6.0.md
  docs/website/blog/2023-01-30-local-container-dev-on-podman.md
  docs/website/blog/2023-02-15-odo-v3.7.0.md
  docs/website/blog/2023-02-17-odo-dotnet-postgresql-openshift.mdx
  docs/website/blog/2023-03-08-odo-v3.8.0.md
  docs/website/blog/2023-03-22-deploying-and-using-in-cluster-devfile-registry.md
  docs/website/blog/2023-04-05-odo-v3.9.0.md
  docs/website/blog/2023-05-04-odo-v3.10.0.md
  docs/website/blog/3.0.0-GA-blog.md
  docs/website/blog/deploy-and-connect-to-microservice-using-helm-and-exec.md
Labels: lgtm, area/release-eng, area/documentation

#6845 Bump Devfile library to latest commit (04a8b3f)
  go.mod
  go.sum
  vendor/github.com/devfile/library/v2/pkg/devfile/parser/parse.go
  vendor/github.com/devfile/library/v2/pkg/git/git.go
  vendor/github.com/devfile/library/v2/pkg/git/mock.go
  vendor/modules.txt
Labels: lgtm, area/dependency

#6833 Fix flaky `odo dev` test on Podman by randomizing component names
  tests/e2escenarios/e2e_test.go
  tests/helper/helper_filesystem.go
  tests/integration/cmd_delete_test.go
  tests/integration/cmd_describe_component_test.go
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
  tests/integration/cmd_devfile_build_images_test.go
  tests/integration/cmd_devfile_deploy_test.go
  tests/integration/cmd_devfile_init_test.go
  tests/integration/cmd_devfile_list_test.go
  tests/integration/cmd_namespace_test.go
Labels: kind/bug, area/testing, lgtm, kind/flake

#6839 Fix issues with describe/list binding tests
  pkg/odo/cli/list/list.go
  tests/integration/cmd_describe_list_binding_test.go
Labels: kind/bug, area/testing, lgtm

#6848 Fix `should print warning about default namespace when running odo dev` test when Dev Session does not start correctly
  tests/integration/cmd_dev_test.go
Labels: kind/bug, area/testing, lgtm

#6826 Use a single handler for executing all commands
  docs/proposals/commands-semantic.md
  pkg/component/component.go
  pkg/component/delete/delete.go
  pkg/component/delete/delete_test.go
  pkg/component/execute_new_container.go
  pkg/component/execute_terminating.go
  pkg/component/handler.go
  pkg/component/handler_test.go
  pkg/deploy/deploy.go
  pkg/dev/kubedev/components.go
  pkg/dev/kubedev/handler.go
  pkg/dev/kubedev/innerloop.go
  pkg/dev/podmandev/command.go
  pkg/dev/podmandev/reconcile.go
  pkg/devfile/image/image.go
  pkg/devfile/image/image_test.go
  pkg/libdevfile/command.go
  pkg/libdevfile/command_apply.go
  pkg/libdevfile/command_apply_test.go
  pkg/libdevfile/command_composite.go
  pkg/libdevfile/command_composite_parallel.go
  pkg/libdevfile/command_exec.go
  pkg/libdevfile/component.go
  pkg/libdevfile/component_container.go
  pkg/libdevfile/component_image.go
  pkg/libdevfile/component_kubernetes.go
  pkg/libdevfile/component_openshift.go
  pkg/libdevfile/component_volume.go
  pkg/libdevfile/handler_mock.go
  pkg/libdevfile/libdevfile.go
  pkg/libdevfile/libdevfile_test.go
  pkg/odo/cli/build_images/build_images.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/platform/mock.go
  pkg/testingutil/pods.go
  scripts/mockgen.sh
  tests/helper/helper_generic.go
  tests/helper/helper_podman.go
  tests/integration/cmd_dev_test.go
Labels: lgtm, kind/code-refactoring

#6843 Track preference options usage
  pkg/odo/cli/preference/set.go
  pkg/odo/cli/preference/unset.go
  pkg/segment/context/context.go
  tests/helper/helper_telemetry.go
  tests/integration/cmd_pref_config_test.go
Labels: lgtm, kind/feature, area/telemetry

#6840 Document how to fix file permission errors while using odo with GKE/AKS/EKS
  docs/website/docs/user-guides/advanced/using-odo-with-other-clusters.md
Labels: lgtm, area/documentation

#6852 Bump version 3.11.0
  Dockerfile.rhel
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_any_registry_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_specific_registry_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_url_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_directory_with_sources_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_empty_directory_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/latest_versioned_devfile_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/versioned_devfile_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_deploy_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_init_output.mdx
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: lgtm
