Repository redhat-developer/odo, pull requests merged in 2023-08, with the labels that each got.

#7008 Do not display API logs
  pkg/apiserver-gen/.openapi-generator-ignore
  pkg/apiserver-gen/.openapi-generator/FILES
  pkg/apiserver-gen/go/api.go
  pkg/apiserver-gen/go/api_default.go
  pkg/apiserver-gen/go/api_devstate.go
  pkg/apiserver-gen/go/logger.go
  pkg/apiserver-impl/api_devstate_service.go
  pkg/apiserver-impl/devstate.go
  pkg/apiserver-impl/starterserver.go
  ui/src/app/api-gen/.openapi-generator/FILES
  ui/src/app/api-gen/api/api.ts
  ui/src/app/api-gen/api/default.service.ts
  ui/src/app/api-gen/api/devstate.service.ts
Labels: lgtm

#7010 Fix podman version check
  pkg/podman/version.go
Labels: kind/bug, lgtm, area/dev, area/odo-on-podman

#7004 odo init filters devfile stacks by supported architectures
  cmd/odo/alizer_test.go
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_directory_with_sources_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_empty_directory_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_init_output.mdx
  pkg/alizer/alizer.go
  pkg/alizer/alizer_test.go
  pkg/alizer/interface.go
  pkg/alizer/mock.go
  pkg/api/analyze.go
  pkg/init/asker/asker.go
  pkg/init/asker/interface.go
  pkg/init/asker/mock.go
  pkg/init/backend/alizer.go
  pkg/init/backend/alizer_test.go
  pkg/init/backend/flags.go
  pkg/init/backend/flags_test.go
  pkg/init/backend/interactive.go
  pkg/init/backend/interactive_test.go
  pkg/init/init.go
  pkg/init/init_test.go
  pkg/odo/cli/alizer/alizer.go
  pkg/odo/cli/init/init.go
  pkg/odo/cli/registry/registry.go
  pkg/registry/registry.go
  tests/documentation/command-reference/doc_command_reference_init_test.go
  tests/documentation/user-guides/doc_user_guides_quickstart_test.go
  tests/e2escenarios/e2e_test.go
  tests/helper/helper_documentation.go
  tests/integration/interactive_deploy_test.go
  tests/integration/interactive_dev_test.go
  tests/integration/interactive_init_test.go
Labels: lgtm, kind/feature, area/registry, area/init

#7011 Makes stopped command terminate normally
  pkg/remotecmd/kubeexec.go
  pkg/remotecmd/kubeexec_test.go
Labels: kind/bug, lgtm, area/dev

#7013 Use image selector feature in "Deploying application" guides
  docs/website/docs/user-guides/advanced/deploy/deploy.md
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/accessing_application.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_Dockerfile.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_describe_component_kubernetes_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_describe_component_openshift_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_final_devfile_kubernetes.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_final_devfile_openshift.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/editing_devfile.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_Dockerfile.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_describe_component_kubernetes_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_describe_component_openshift_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_final_devfile_kubernetes.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_final_devfile_openshift.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_Dockerfile.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_describe_component_kubernetes_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_describe_component_openshift_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_final_devfile_kubernetes.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_final_devfile_openshift.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_Dockerfile.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_describe_component_kubernetes_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_describe_component_openshift_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_final_devfile_kubernetes.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_final_devfile_openshift.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/prerequisites.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/running_deploy_description.mdx
  docs/website/docs/user-guides/advanced/deploy/dotnet.md
  docs/website/docs/user-guides/advanced/deploy/go.md
  docs/website/docs/user-guides/advanced/deploy/java.md
  docs/website/docs/user-guides/advanced/deploy/nodejs.md
  docs/website/docusaurus.config.js
  docs/website/package.json
  docs/website/yarn.lock
Labels: lgtm, area/documentation

#7016 Update Quickstart Guides with Podman support
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_podman_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_podman_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_podman_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_podman_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/odo_dev_description.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/preparing_the_target_platform.mdx
  docs/website/docs/user-guides/quickstart/dotnet.md
  docs/website/docs/user-guides/quickstart/go.md
  docs/website/docs/user-guides/quickstart/java.md
  docs/website/docs/user-guides/quickstart/nodejs.md
  docs/website/docs/user-guides/quickstart/quickstart.md
Labels: lgtm, area/documentation, area/odo-on-podman

#7017 Remove kubeconfig flag
  cmd/odo/odo.go
  pkg/odo/cli/list/list.go
  tests/integration/generic_test.go
Labels: kind/bug, lgtm

#7012 Move UI out of experimental mode
  USAGE_DATA.md
  docs/website/docs/user-guides/advanced/using-gui.md
  docs/website/static/img/ui-chart-representation.png
  docs/website/static/img/ui-graphical-representation.png
  docs/website/static/img/ui-textual-representation.png
  pkg/apiserver-impl/starterserver.go
  pkg/apiserver-impl/ui/favicon.ico
  pkg/apiserver-impl/ui/index.html
  pkg/apiserver-impl/ui/main.1f6f2714e5bbe400.js
  pkg/apiserver-impl/ui/main.6a89d63885b00552.js
  pkg/dev/kubedev/kubedev.go
  pkg/dev/podmandev/podmandev.go
  pkg/informer/doc.go
  pkg/informer/informer.go
  pkg/odo/cli/apiserver/apiserver.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/feature/features.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/watch/watch.go
  tests/helper/helper_dev.go
  tests/integration/cmd_dev_api_server_test.go
  ui/src/app/app.component.css
  ui/src/app/app.component.html
  ui/src/favicon.ico
Labels: lgtm, kind/feature

#7028 Do not set Memory limit on podman when cgroup is v1
  pkg/dev/podmandev/pod.go
  pkg/dev/podmandev/pod_test.go
  pkg/dev/podmandev/reconcile.go
  pkg/podman/capabilities.go
  pkg/podman/info.go
  pkg/podman/interface.go
  pkg/podman/mock.go
Labels: kind/bug, lgtm, area/odo-on-podman

#7029 [ui] Create/Delete volumes
  ododevapispec.yaml
  pkg/apiserver-gen/.openapi-generator/FILES
  pkg/apiserver-gen/go/api.go
  pkg/apiserver-gen/go/api_devstate.go
  pkg/apiserver-gen/go/model__devstate_container_post_request.go
  pkg/apiserver-gen/go/model__devstate_volume_post_request.go
  pkg/apiserver-gen/go/model_container.go
  pkg/apiserver-gen/go/model_devfile_content.go
  pkg/apiserver-gen/go/model_volume.go
  pkg/apiserver-gen/go/model_volume_mount.go
  pkg/apiserver-impl/devstate.go
  pkg/apiserver-impl/devstate/commands_test.go
  pkg/apiserver-impl/devstate/components.go
  pkg/apiserver-impl/devstate/components_test.go
  pkg/apiserver-impl/devstate/content.go
  pkg/apiserver-impl/devstate/content_test.go
  pkg/apiserver-impl/devstate/events_test.go
  pkg/apiserver-impl/devstate/state_test.go
  pkg/apiserver-impl/swagger-ui/swagger.yaml
  pkg/apiserver-impl/ui/index.html
  pkg/apiserver-impl/ui/main.1046d99cec4375b1.js
  pkg/apiserver-impl/ui/main.ae49ed4fe0fa0670.js
  ui/cypress/e2e/spec.cy.ts
  ui/src/app/api-gen/.openapi-generator/FILES
  ui/src/app/api-gen/api/devstate.service.ts
  ui/src/app/api-gen/model/devfileContent.ts
  ui/src/app/api-gen/model/devstateContainerPostRequest.ts
  ui/src/app/api-gen/model/devstateVolumePostRequest.ts
  ui/src/app/api-gen/model/models.ts
  ui/src/app/api-gen/model/volume.ts
  ui/src/app/api-gen/model/volumeMount.ts
  ui/src/app/app.component.html
  ui/src/app/app.module.ts
  ui/src/app/controls/multi-text/multi-text.component.html
  ui/src/app/controls/volume-mounts/volume-mounts.component.css
  ui/src/app/controls/volume-mounts/volume-mounts.component.html
  ui/src/app/controls/volume-mounts/volume-mounts.component.spec.ts
  ui/src/app/controls/volume-mounts/volume-mounts.component.ts
  ui/src/app/forms/command-exec/command-exec.component.html
  ui/src/app/forms/command-exec/command-exec.component.ts
  ui/src/app/forms/container/container.component.html
  ui/src/app/forms/container/container.component.ts
  ui/src/app/forms/volume/volume.component.css
  ui/src/app/forms/volume/volume.component.html
  ui/src/app/forms/volume/volume.component.spec.ts
  ui/src/app/forms/volume/volume.component.ts
  ui/src/app/services/devstate.service.ts
  ui/src/app/tabs/containers/containers.component.css
  ui/src/app/tabs/containers/containers.component.html
  ui/src/app/tabs/containers/containers.component.ts
  ui/src/app/tabs/volumes/volumes.component.css
  ui/src/app/tabs/volumes/volumes.component.html
  ui/src/app/tabs/volumes/volumes.component.spec.ts
  ui/src/app/tabs/volumes/volumes.component.ts
Labels: lgtm, kind/feature, area/Web-UI

#7037 Update README main title and display preview video
  README.md
Labels: lgtm, area/documentation

#7038 Bump version to 3.14.0
  Dockerfile.rhel
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_any_registry_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_specific_registry_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_url_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_with_run-port_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_directory_with_sources_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_empty_directory_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/latest_versioned_devfile_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/versioned_devfile_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_deploy_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_podman_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_podman_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_podman_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_podman_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_init_output.mdx
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: lgtm, area/release-eng

#7041 Fix API Server port detection issue by making sure the same local address is used for listening and checking if the port is available
  pkg/apiserver-impl/starterserver.go
Labels: kind/bug, lgtm, area/dev

#7047 Doc for downstream
  docs/pm-doc.md
Labels: lgtm, area/documentation

#7050 Fix potential namespace name collision issue with `odo create/delete/list/set namespace/project` tests
  tests/helper/helper_generic.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/helper/helper_podman.go
  tests/helper/odo_utils.go
  tests/integration/cmd_namespace_test.go
Labels: area/testing, lgtm

#7049 Use multiarch image for postgresql instance
  tests/examples/manifests/bindablekind-instance.yaml
  tests/examples/source/devfiles/go/cluster.yaml
Labels: area/testing, lgtm
