Repository redhat-developer/odo, pull requests merged in 2023-02, with the labels that each got.

#6560 Correct container-attributes data in release blog
  docs/website/blog/2023-01-24-odo-v3.6.0.md
Labels: kind/bug, lgtm, area/documentation

#6559 Use oc v4.11 instead v4.7 to fix version comparison
  .ibm/images/Dockerfile
Labels: lgtm, kind/tests

#6563 Set the date for the v3 GA blog post
  docs/website/blog/3.0.0-GA-blog.md
Labels: lgtm, area/documentation

#6564 Dogfood odo for working on the website
  docs/website/.gitignore
  docs/website/devfile.yaml
  docs/website/package.json
Labels: lgtm, area/documentation

#6566 Verification file for Google Search console [feloy]
  docs/website/static/googlee17e5687b3174050.html
Labels: lgtm, area/documentation

#6538 Log error when podman client cannot be initialized
  pkg/binding/binding.go
  pkg/kclient/errors.go
  pkg/odo/cli/describe/component.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/list/component/list.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/podman/errors.go
  pkg/podman/podman.go
  tests/integration/cmd_describe_component_test.go
  tests/integration/cmd_dev_test.go
Labels: kind/bug, lgtm

#6562 Add blog post demonstrating how odo can be used with Podman
  docs/website/blog/2023-01-30-local-container-dev-on-podman.md
  docs/website/static/img/odo_podman.png
  docs/website/static/video/odo-dev-podman-demo.webm
Labels: lgtm, area/documentation

#6570 Fix the port value (20001) in the quickstart guides
  docs/website/docs/user-guides/quickstart/docs-mdx/odo_dev_description.mdx
Labels: lgtm, area/documentation

#6574 Fix UX inconsistency when handling commands bound to events
  pkg/component/delete/delete.go
  pkg/component/exec_handler.go
  pkg/dev/podmandev/reconcile.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  tests/integration/cmd_delete_test.go
Labels: kind/bug, area/UX, lgtm, area/dev

#6576 Support `dev.odo.push.path:*` attributes on Podman
  docs/website/docs/user-guides/advanced/pushing-specific-files.md
  docs/website/versioned_docs/version-2.5.0/tutorials/using-devfile-odo.dev.push.path-attribute.md
  pkg/dev/podmandev/podmandev.go
  pkg/devfile/adapters/attributes.go
  pkg/devfile/adapters/attributes_test.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  tests/examples/source/devfiles/nodejs/devfile-with-remote-attributes.yaml
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
Labels: lgtm, kind/feature, area/odo-on-podman

#6577 Support for image component on podman
  docs/website/docs/overview/configure.md
  pkg/config/config.go
  pkg/dev/podmandev/command.go
  pkg/dev/podmandev/podmandev.go
  pkg/dev/podmandev/reconcile.go
  pkg/devfile/image/image.go
  pkg/odo/genericclioptions/clientset/clientset.go
  tests/helper/component_podman.go
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
Labels: lgtm, kind/feature

#6587 Trigger the IBM Cloud Image Workflow on PRs as well
  .github/workflows/build-push-ibm-image.yaml
Labels: area/testing, lgtm

#6596 Bump version to v3.7.0
  Dockerfile.rhel
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_any_registry_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_specific_registry_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_url_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_directory_with_sources_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_empty_directory_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/latest_versioned_devfile_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/versioned_devfile_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_deploy_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_init_output.mdx
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: lgtm, area/release-eng

#6586 Bump Go to 1.19
  .github/workflows/build-push-ibm-image.yaml
  .ibm/images/Dockerfile
  Dockerfile.rhel
  go.mod
  openshift-ci/build-root/Dockerfile
  pkg/preference/implem_test.go
  pkg/registry/registry.go
  pkg/registry/registry_test.go
  pkg/registry/starter_project.go
  pkg/registry/utils_test.go
  pkg/segment/integrations_test.go
  pkg/segment/segment.go
  pkg/segment/segment_test.go
  pkg/sync/sync_test.go
  pkg/testingutil/filesystem/default_fs.go
  pkg/util/config_util.go
  pkg/util/file_indexer.go
  pkg/util/file_indexer_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  scripts/rpm-prepare.sh
  tests/examples/source/devfiles/go/middleware/handlers.go
  tests/helper/helper_configValidate.go
  tests/helper/helper_filesystem.go
  tests/helper/helper_http.go
  tests/helper/helper_oc.go
  tests/helper/helper_telemetry.go
  tests/integration/cmd_dev_test.go
  tests/integration/cmd_devfile_init_test.go
  tests/integration/plugin_handler_test.go
Labels: lgtm, kind/feature

#6603 Adding ritudes user id to tests/OWNERS
  scripts/OWNERS
  tests/OWNERS
Labels: lgtm

#6609 Rename the generated branch for release PRs
  .github/workflows/release-management.yaml
Labels: lgtm

#6608 Make `bump-version.sh` also update the version in documentation sample outputs
  scripts/bump-version.sh
Labels: lgtm

#6500 blog: odo with .NET and PostgreSQL on OpenShift
  docs/website/blog/2023-02-17-odo-dotnet-postgresql-openshift.mdx
  docs/website/static/img/blog/odo-dotnet-postgresql-openshift/app_running_inmemory_db.png
  docs/website/static/img/blog/odo-dotnet-postgresql-openshift/app_running_postgresql_db.png
  docs/website/static/img/blog/odo-dotnet-postgresql-openshift/odc_copy_login_command.png
  docs/website/static/img/blog/odo-dotnet-postgresql-openshift/odc_db_step_1.png
  docs/website/static/img/blog/odo-dotnet-postgresql-openshift/odc_db_step_2.png
  docs/website/static/img/blog/odo-dotnet-postgresql-openshift/odc_db_step_3.png
  docs/website/static/img/blog/odo-dotnet-postgresql-openshift/odc_db_step_4.png
  docs/website/static/img/blog/odo-dotnet-postgresql-openshift/odc_db_step_5.png
Labels: lgtm, area/documentation

#6616 fix links to devfile 2.2.0 spec
  docs/website/docs/command-reference/deploy.md
  docs/website/docs/command-reference/dev.md
  docs/website/docs/development/architecture/how-odo-works.md
  docs/website/docs/development/devfile.md
  docs/website/versioned_docs/version-2.5.0/command-reference/deploy.md
Labels: kind/bug, lgtm, area/documentation

#6614 Adding check in odo dev interactive mode for pod/sync to complete
  tests/integration/interactive_dev_test.go
Labels: lgtm

#6615 Describe non-odo component
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/labels/labels.go
  tests/examples/manifests/ingress-app-label.yaml
  tests/examples/manifests/route-app-label.yaml
  tests/integration/cmd_describe_component_test.go
Labels: lgtm

#6624 Allow `:` character in devfile registry URI
  pkg/util/util.go
  pkg/util/util_test.go
Labels: kind/bug, lgtm
