Repository redhat-developer/odo, pull requests merged in 2023-10, with the labels that each got.

#6866 blogpost: writing devfile from scratch
  docs/website/blog/2023-10-10-writing-devfile-from-scratch.mdx
Labels: lgtm, area/documentation

#7119 Group Dependabot updates to `@docusaurus/*` together
  .github/dependabot.yml
Labels: lgtm, area/dependency

#7123 Instruct Dependabot to maintain dependencies for GitHub Actions
  .github/dependabot.yml
Labels: lgtm, area/dependency, kind/task

#7129 Use staging Devfile registry for PR tests
  .ibm/pipelines/kubernetes-tests.sh
  .ibm/pipelines/nocluster-tests.sh
  .ibm/pipelines/openshift-tests.sh
  .ibm/pipelines/windows-test-script.ps1
  .ibm/pipelines/windows-test.sh
  Makefile
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_empty_directory_output.mdx
  docs/website/docs/overview/configure.md
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx
  pkg/config/config.go
  pkg/config/config_test.go
  scripts/openshiftci-config.sh
  tests/documentation/command-reference/doc_command_reference_createnamespace_test.go
  tests/documentation/command-reference/doc_command_reference_deletenamespace_test.go
  tests/documentation/command-reference/doc_command_reference_init_test.go
  tests/documentation/user-guides/doc_user_guides_quickstart_test.go
  tests/e2escenarios/e2e_test.go
  tests/helper/helper_generic.go
  tests/helper/helper_registry.go
  tests/integration/cmd_devfile_registry_test.go
  tests/integration/interactive_dev_test.go
  tests/integration/interactive_init_test.go
Labels: area/testing, lgtm
