Repository redhat-developer/odo, pull requests merged in 2023-07, with the labels that each got.

#6946 Fix CI Devfile Registry URL used in OCP interop tests
  scripts/openshiftci-config.sh
Labels: kind/bug, area/testing, lgtm

#6951 [UX] Fix default value of ImageRegistry in odo preference view output
  pkg/odo/cli/preference/view.go
Labels: kind/bug, lgtm

#6952 Implement odo api-server command
  pkg/odo/cli/apiserver/apiserver.go
  pkg/odo/cli/cli.go
  pkg/util/util.go
Labels: lgtm, kind/feature

#6953 Add new `--run-port` flag to `odo init` to set ports non-interactively
  docs/website/docs/command-reference/docs-mdx/init/devfile_with_run-port_output.mdx
  docs/website/docs/command-reference/init.md
  pkg/init/backend/applicationports.go
  pkg/init/backend/flags.go
  pkg/init/backend/flags_test.go
  pkg/init/init.go
  pkg/libdevfile/libdevfile.go
  pkg/odo/cli/init/init.go
  tests/documentation/command-reference/doc_command_reference_init_test.go
  tests/helper/helper_devfile.go
  tests/integration/cmd_devfile_init_test.go
Labels: lgtm, kind/feature, area/init

#6950 Add /devfile PUT and GET endpoints
  .gitattributes
  ododevapispec.yaml
  pkg/apiserver-gen/.openapi-generator/FILES
  pkg/apiserver-gen/go/api.go
  pkg/apiserver-gen/go/api_default.go
  pkg/apiserver-gen/go/model__devfile_get_200_response.go
  pkg/apiserver-gen/go/model__devstate_container_post_200_response.go
  pkg/apiserver-gen/go/model__devstate_metadata_put_200_response.go
  pkg/apiserver-gen/go/model_devfile_put_request.go
  pkg/apiserver-gen/go/model_devstate_devfile_put_request.go
  pkg/apiserver-gen/go/model_metadata.go
  pkg/apiserver-gen/go/model_metadata_request.go
  pkg/apiserver-impl/api_default_service.go
  pkg/apiserver-impl/devstate.go
  pkg/apiserver-impl/starterserver.go
  pkg/odo/cli/apiserver/apiserver.go
  pkg/odo/cli/dev/dev.go
  ui/src/app/api-gen/.openapi-generator/FILES
  ui/src/app/api-gen/api/default.service.ts
  ui/src/app/api-gen/model/devfileGet200Response.ts
  ui/src/app/api-gen/model/devfilePutRequest.ts
  ui/src/app/api-gen/model/metadata.ts
  ui/src/app/api-gen/model/metadataRequest.ts
  ui/src/app/api-gen/model/models.ts
  ui/src/app/app.component.html
  ui/src/app/app.component.ts
  ui/src/app/forms/metadata/metadata.component.html
  ui/src/app/services/odoapi.service.spec.ts
  ui/src/app/services/odoapi.service.ts
Labels: lgtm, kind/feature

#6954 Serve UI from api server
  .gitattributes
  .github/workflows/check-generated-files.yaml
  .sonarcloud.properties
  Makefile
  pkg/apiserver-impl/starterserver.go
  pkg/apiserver-impl/ui/103.a91ee51a71a891e1.js
  pkg/apiserver-impl/ui/11.056f3ebd8a590b3c.js
  pkg/apiserver-impl/ui/276.9f963a0fd1365056.js
  pkg/apiserver-impl/ui/299.b6bd942dffceeea6.js
  pkg/apiserver-impl/ui/322.ae1afb6543b1e4a4.js
  pkg/apiserver-impl/ui/330.aa8e97600a53f037.js
  pkg/apiserver-impl/ui/3rdpartylicenses.txt
  pkg/apiserver-impl/ui/450.1756491cf50c2969.js
  pkg/apiserver-impl/ui/571.d4ff05732590cfb8.js
  pkg/apiserver-impl/ui/598.45cf43e9a099cc7e.js
  pkg/apiserver-impl/ui/6.e9c32fa3193aa48e.js
  pkg/apiserver-impl/ui/608.906465dee653ee56.js
  pkg/apiserver-impl/ui/61.021401352c8fac58.js
  pkg/apiserver-impl/ui/612.634d6c1c5de81831.js
  pkg/apiserver-impl/ui/719.83bb129036b7dcdd.js
  pkg/apiserver-impl/ui/736.6667486e1f659685.js
  pkg/apiserver-impl/ui/784.f79a6e5c423dd7d1.js
  pkg/apiserver-impl/ui/806.c6ff18a1f12536c9.js
  pkg/apiserver-impl/ui/807.04e2b45e478bfa14.js
  pkg/apiserver-impl/ui/883.8dbb7430ed8af2ea.js
  pkg/apiserver-impl/ui/905.32f9d8e99950acca.js
  pkg/apiserver-impl/ui/911.f351650d584d08a4.js
  pkg/apiserver-impl/ui/963.b8dda41c64c45e9f.js
  pkg/apiserver-impl/ui/964.301dc27cc2e0e79c.js
  pkg/apiserver-impl/ui/97.24bb8167eebd4975.js
  pkg/apiserver-impl/ui/973.fabe6d6ee4bc5e5a.js
  pkg/apiserver-impl/ui/CNAME
  pkg/apiserver-impl/ui/assets/github-24.svg
  pkg/apiserver-impl/ui/common.a64b1ed6000c8d46.js
  pkg/apiserver-impl/ui/favicon.ico
  pkg/apiserver-impl/ui/index.html
  pkg/apiserver-impl/ui/main.cf0a00d9d9051ab2.js
  pkg/apiserver-impl/ui/polyfills.8b3b37cedaf377c3.js
  pkg/apiserver-impl/ui/runtime.35da7df5cf523a35.js
  pkg/apiserver-impl/ui/styles.5ea7ce8b76eff1c2.css
Labels: lgtm, kind/feature

#6957 odo dev --logs
  pkg/logs/interface.go
  pkg/logs/logs.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/logs/logs.go
  tests/helper/helper_dev.go
  tests/integration/cmd_logs_test.go
Labels: lgtm, kind/feature

#6959 Support Architectures in `odo registry`
  docs/website/docs/command-reference/docs-mdx/init/registry_list_output.mdx
  docs/website/docs/command-reference/json-output.md
  docs/website/docs/command-reference/registry.md
  docs/website/docs/user-guides/quickstart/quickstart.md
  pkg/api/registry.go
  pkg/odo/cli/registry/registry.go
  pkg/registry/registry.go
  pkg/registry/registry_test.go
  tests/integration/cmd_devfile_registry_test.go
Labels: lgtm, kind/feature, area/registry

#6967 Fix Dev UI Cypress E2E tests
  .github/workflows/ui-e2e.yaml
  ui/angular.json
  ui/cypress.config.ts
  ui/cypress/support/commands.ts
  ui/cypress/support/e2e.ts
  ui/package-lock.json
  ui/package.json
Labels: area/testing, lgtm

#6965 Add a Troubleshooting page with most common issues and solutions
  docs/website/docs/command-reference/_category_.json
  docs/website/docs/overview/_category_.json
  docs/website/docs/troubleshooting.md
  docs/website/docs/user-guides/_category_.json
  docs/website/docs/user-guides/advanced/_category_.json
Labels: lgtm, area/documentation

#6949 Fix oc to odo project translation
  pkg/auth/login.go
  pkg/auth/login_test.go
Labels: kind/bug, lgtm, area/openshift

#6974 Add Preference dependency to api-server command
  pkg/odo/cli/apiserver/apiserver.go
Labels: kind/bug, lgtm

#6970 Propagate local Devfile changes to the UI
  .github/workflows/ui-e2e.yaml
  pkg/apiserver-impl/sse/event.go
  pkg/apiserver-impl/sse/notifications.go
  pkg/apiserver-impl/sse/watcher.go
  pkg/apiserver-impl/starterserver.go
  pkg/apiserver-impl/ui/index.html
  pkg/apiserver-impl/ui/main.2ab96df0533a01ab.js
  pkg/apiserver-impl/ui/main.cf0a00d9d9051ab2.js
  pkg/odo/cli/apiserver/apiserver.go
  pkg/odo/cli/dev/dev.go
  ui/cypress/e2e/errs.cy.ts
  ui/cypress/e2e/spec.cy.ts
  ui/cypress/fixtures/input/devfile-new-version.yaml
  ui/cypress/support/commands.ts
  ui/src/app/app.component.ts
  ui/src/app/services/sse.service.ts
Labels: lgtm, kind/feature, area/dev

#6980 Fix invalid links in `v3.11.0` blog post
  docs/website/blog/2023-05-30-odo-v3.11.0.md
Labels: lgtm, area/documentation

#6981 Add UI telemetry
  ododevapispec.yaml
  pkg/apiserver-gen/.openapi-generator/FILES
  pkg/apiserver-gen/go/api.go
  pkg/apiserver-gen/go/api_default.go
  pkg/apiserver-gen/go/model__telemetry_get_200_response.go
  pkg/apiserver-gen/go/model_telemetry_response.go
  pkg/apiserver-impl/api_default_service.go
  pkg/apiserver-impl/ui/3rdpartylicenses.txt
  pkg/apiserver-impl/ui/index.html
  pkg/apiserver-impl/ui/main.2ab96df0533a01ab.js
  pkg/apiserver-impl/ui/main.64f53365507b1341.js
  pkg/odo/genericclioptions/runnable.go
  pkg/segment/integrations.go
  pkg/segment/segment.go
  ui/package-lock.json
  ui/package.json
  ui/src/app/api-gen/.openapi-generator/FILES
  ui/src/app/api-gen/api/default.service.ts
  ui/src/app/api-gen/model/models.ts
  ui/src/app/api-gen/model/telemetryGet200Response.ts
  ui/src/app/api-gen/model/telemetryResponse.ts
  ui/src/app/app.component.html
  ui/src/app/app.component.ts
  ui/src/app/app.module.ts
  ui/src/app/forms/command-apply/command-apply.component.ts
  ui/src/app/forms/command-composite/command-composite.component.ts
  ui/src/app/forms/command-exec/command-exec.component.ts
  ui/src/app/forms/command-image/command-image.component.ts
  ui/src/app/forms/container/container.component.ts
  ui/src/app/forms/image/image.component.ts
  ui/src/app/forms/metadata/metadata.component.ts
  ui/src/app/forms/resource/resource.component.ts
  ui/src/app/services/odoapi.service.ts
  ui/src/app/services/telemetry.service.spec.ts
  ui/src/app/services/telemetry.service.ts
  ui/src/app/tabs/commands/commands.component.ts
  ui/src/app/tabs/events/events.component.ts
Labels: lgtm, kind/feature, area/telemetry

#6988 Update home page with Podman
  docs/website/docusaurus.config.js
  docs/website/src/pages/index.tsx
Labels: lgtm, area/documentation

#6995 Fix potential port conflict issue with the API server tests by using a random server port if `--random-ports` is set
  pkg/apiserver-impl/starterserver.go
  pkg/odo/cli/apiserver/apiserver.go
  pkg/odo/cli/dev/dev.go
  tests/integration/cmd_dev_api_server_test.go
Labels: kind/bug, area/testing, lgtm

#6985 Remove API Server from experimental mode, set UI Server as experimental
  pkg/api/component.go
  pkg/apiserver-impl/starterserver.go
  pkg/component/describe/describe.go
  pkg/odo/cli/describe/component.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/feature/features.go
  pkg/state/state.go
  tests/helper/helper_dev.go
  tests/integration/cmd_dev_api_server_test.go
Labels: lgtm, kind/feature

#6996 Alert user when Devfile is synced
  pkg/apiserver-impl/ui/index.html
  pkg/apiserver-impl/ui/main.64f53365507b1341.js
  pkg/apiserver-impl/ui/main.a562f09a5f00f55f.js
  ui/cypress/support/commands.ts
  ui/src/app/app.component.ts
  ui/src/app/app.module.ts
  ui/src/app/components/confirm/confirm.component.css
  ui/src/app/components/confirm/confirm.component.html
  ui/src/app/components/confirm/confirm.component.spec.ts
  ui/src/app/components/confirm/confirm.component.ts
Labels: lgtm, kind/feature

#6997 Cleanup OWNERS files
  OWNERS
  docs/OWNERS
  docs/website/OWNERS
  openshift-ci/build-root/OWNERS
  scripts/OWNERS
  tests/OWNERS
Labels: lgtm

#7000 Bump to version 3.13.0
  Dockerfile.rhel
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_any_registry_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_specific_registry_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_url_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_with_run-port_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_directory_with_sources_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_empty_directory_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/latest_versioned_devfile_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/versioned_devfile_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_deploy_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_init_output.mdx
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: lgtm, area/release-eng
