Repository redhat-developer/odo, pull requests merged in 2023-04, with the labels that each got.

#6690 Fix issue preventing app from being restarted if `/proc/[pid]/task/[tid]/children` is missing in container (case of Minikube with VirtualBox or KVM drivers)
  pkg/remotecmd/kubeexec.go
  pkg/remotecmd/kubeexec_test.go
Labels: kind/bug, lgtm, area/dev

#6678 Speedup odo registry --details
  docs/website/docs/command-reference/json-output.md
  docs/website/docs/command-reference/registry.md
  go.mod
  go.sum
  pkg/alizer/alizer.go
  pkg/alizer/alizer_test.go
  pkg/api/registry.go
  pkg/init/backend/interactive.go
  pkg/init/backend/interactive_test.go
  pkg/odo/cli/registry/registry.go
  pkg/registry/interface.go
  pkg/registry/mock.go
  pkg/registry/registry.go
  pkg/registry/registry_test.go
  tests/integration/cmd_devfile_registry_test.go
  vendor/github.com/devfile/registry-support/index/generator/schema/schema.go
  vendor/modules.txt
Labels: lgtm, kind/feature

#6707 Update alizer
  go.mod
  go.sum
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/framework/python/django_detector.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/framework/python/flask_detector.go
  vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/python_enricher.go
  vendor/github.com/redhat-developer/alizer/go/pkg/utils/langfiles/resources/languages-customization.yml
  vendor/modules.txt
Labels: lgtm

#6710 Fix nodejs-react versions on generated doc
  docs/website/docs/command-reference/docs-mdx/init/registry_list_output.mdx
Labels: lgtm

#6712 Update the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm

#6711 Exit a test early if a session has exited while waiting for an output to contain a substring
  tests/helper/helper_dev.go
  tests/helper/helper_run.go
Labels: lgtm

#6654 Support `autoBuild` and `deployByDefault` on Image and Kubernetes/OpenShift components
  docs/website/docs/development/devfile.md
  go.mod
  go.sum
  pkg/deploy/deploy.go
  pkg/dev/kubedev/kubedev.go
  pkg/dev/podmandev/podmandev.go
  pkg/dev/podmandev/reconcile.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/push.go
  pkg/devfile/components.go
  pkg/devfile/components_test.go
  pkg/devfile/devfile.go
  pkg/init/init.go
  pkg/libdevfile/component.go
  pkg/libdevfile/component_image.go
  pkg/libdevfile/component_image_test.go
  pkg/libdevfile/component_kubernetes.go
  pkg/libdevfile/component_kubernetes_test.go
  pkg/odo/cli/init/init.go
  pkg/testingutil/devfile.go
  pkg/watch/status.go
  tests/examples/source/devfiles/nodejs/devfile-autobuild-deploybydefault.yaml
  tests/examples/source/devfiles/nodejs/devfile-deploy-functional-pods.yaml
  tests/helper/helper_devfile.go
  tests/helper/helper_filesystem.go
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
  tests/integration/cmd_devfile_build_images_test.go
  tests/integration/cmd_devfile_deploy_test.go
  vendor/github.com/devfile/library/v2/pkg/devfile/parser/parse.go
  vendor/modules.txt
Labels: lgtm, kind/feature, area/devfile-spec

#6716 Fix problem when odo deploy processes do not terminate
  tests/helper/helper_cmd_wrapper.go
Labels: kind/bug, area/testing, lgtm

#6717 Bump version to 3.9.0
  Dockerfile.rhel
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_any_registry_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_specific_registry_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_url_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_directory_with_sources_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_empty_directory_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/latest_versioned_devfile_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/versioned_devfile_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_deploy_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_init_output.mdx
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: lgtm, area/release-eng

#6704 Allow users to define custom port-mappings for port forwarding [Kubernetes]
  pkg/dev/interface.go
  pkg/dev/kubedev/kubedev.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/types.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/cli/dev/dev_test.go
  pkg/portForward/kubeportforward/portForward.go
  pkg/portForward/kubeportforward/portForward_test.go
  pkg/watch/watch.go
  tests/helper/helper_dev.go
  tests/helper/helper_http.go
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
Labels: lgtm, kind/feature

#6720 Follow-up to comments on #6654 (support for `autoBuild` and `deployByDefault`)
  docs/website/docs/development/devfile.md
  pkg/deploy/deploy.go
  pkg/dev/podmandev/reconcile.go
  pkg/devfile/adapters/kubernetes/component/push.go
  pkg/libdevfile/component_image.go
  pkg/libdevfile/component_image_test.go
  pkg/libdevfile/component_kubernetes.go
  tests/examples/source/nodejs/package.json
  tests/helper/helper_podman.go
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
  tests/integration/cmd_devfile_build_images_test.go
  tests/integration/cmd_devfile_deploy_test.go
Labels: lgtm, kind/code-refactoring

#6703 Doc automation:Command Reference: odo create namespace
  docs/website/docs/command-reference/create-namespace.md
  docs/website/docs/command-reference/docs-mdx/create-namespace/create_namespace.mdx
  docs/website/docs/command-reference/docs-mdx/create-namespace/create_project.mdx
  tests/documentation/command-reference/doc_command_reference_createnamespace_test.go
Labels: lgtm

#6727 For custom port mapping, handle case where ranged random port matches a custom local port
  pkg/odo/cli/dev/dev_test.go
  pkg/portForward/kubeportforward/portForward.go
  pkg/portForward/kubeportforward/portForward_test.go
Labels: kind/bug, lgtm

#6725 Revert "Add DEVFILE_REGISTRY env var for periodic tests (#6709)"
  scripts/openshiftci-Nightly-SBO-tests.sh
  scripts/openshiftci-periodic-tests.sh
  scripts/openshiftci-presubmit-all-tests.sh
Labels: area/testing, lgtm

#6735 Fix e2e test failures and doc test failures due to updated devfile registry
  docs/website/docs/command-reference/docs-mdx/init/registry_list_output.mdx
  tests/e2escenarios/e2e_test.go
Labels: kind/bug, area/testing, lgtm

#6701 Wait until expected ports are opened in the container before starting port-forwarding
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx
  pkg/dev/podmandev/reconcile.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/port/port.go
  pkg/port/port_test.go
  tests/helper/helper_documentation.go
  tests/integration/cmd_dev_test.go
Labels: lgtm, kind/feature, area/dev

#6733 Fix: PodSecurity Admission: Display duplicate warnings only once
  pkg/kclient/kclient.go
Labels: kind/bug, lgtm

#6698 Automount volumes
  docs/website/docs/development/architecture/podman-support-limitations.md
  docs/website/docs/user-guides/advanced/air-gap-environment.md
  docs/website/docs/user-guides/advanced/automounting-volumes.md
  pkg/configAutomount/doc.go
  pkg/configAutomount/interface.go
  pkg/configAutomount/kubernetes.go
  pkg/configAutomount/kubernetes_test.go
  pkg/configAutomount/mock.go
  pkg/deploy/deploy.go
  pkg/dev/kubedev/kubedev.go
  pkg/dev/podmandev/pod.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/adapter_test.go
  pkg/devfile/adapters/kubernetes/storage/utils.go
  pkg/devfile/adapters/kubernetes/storage/utils_test.go
  pkg/devfile/adapters/kubernetes/utils/utils.go
  pkg/devfile/adapters/kubernetes/utils/utils_test.go
  pkg/kclient/configmap.go
  pkg/kclient/interface.go
  pkg/kclient/mock_Client.go
  pkg/odo/genericclioptions/clientset/clientset.go
  pkg/storage/kubernetes.go
  scripts/mockgen.sh
  tests/examples/manifests/config-automount/as-env-configmap.yaml
  tests/examples/manifests/config-automount/as-env-secret.yaml
  tests/examples/manifests/config-automount/default-configmap.yaml
  tests/examples/manifests/config-automount/default-pvc.yaml
  tests/examples/manifests/config-automount/default-secret.yaml
  tests/examples/manifests/config-automount/mount-path-configmap.yaml
  tests/examples/manifests/config-automount/mount-path-pvc.yaml
  tests/examples/manifests/config-automount/mount-path-secret.yaml
  tests/examples/manifests/config-automount/readonly-pvc.yaml
  tests/examples/manifests/config-automount/subpath-configmap.yaml
  tests/examples/manifests/config-automount/subpath-secret.yaml
  tests/integration/cmd_dev_test.go
  tests/integration/cmd_devfile_deploy_test.go
Labels: lgtm, kind/feature

#6729 Podman custom port mapping
  pkg/dev/podmandev/pod.go
  pkg/dev/podmandev/pod_test.go
  pkg/dev/podmandev/podmandev.go
  pkg/dev/podmandev/reconcile.go
  pkg/odo/cli/dev/dev.go
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
Labels: lgtm

#6737 Fix flaky unit Test_getCompleteCustomPortPairs
  pkg/portForward/kubeportforward/portForward.go
Labels: area/testing, lgtm, kind/flake

#6713 Use devstats.PID.json as devstate
  cmd/odo/odo.go
  pkg/dev/podmandev/reconcile.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/odo/cli/describe/component.go
  pkg/odo/cli/dev/dev.go
  pkg/odo/context/odo.go
  pkg/portForward/interface.go
  pkg/portForward/kubeportforward/portForward.go
  pkg/portForward/podmanportforward/portForward.go
  pkg/registry/mock.go
  pkg/state/const.go
  pkg/state/doc.go
  pkg/state/errors.go
  pkg/state/interface.go
  pkg/state/process_unix.go
  pkg/state/process_windows.go
  pkg/state/state.go
  pkg/state/state_test.go
  pkg/state/types.go
  tests/helper/helper_dev.go
  tests/integration/cmd_dev_test.go
Labels: lgtm, kind/feature

#6745 Document .gitignore and .odoignore usage
  docs/website/docs/development/architecture/how-odo-works.md
  docs/website/docs/user-guides/advanced/pushing-specific-files.md
Labels: lgtm

#6746 Set vcs-uri annotation on podman
  pkg/dev/podmandev/pod.go
  pkg/dev/podmandev/pod_test.go
  pkg/dev/podmandev/reconcile.go
  tests/helper/component_cluster.go
  tests/helper/component_interface.go
  tests/helper/component_podman.go
  tests/helper/helper_podman.go
  tests/integration/cmd_dev_test.go
Labels: lgtm

#6736 Allow to cancel execution of `odo dev` at any phase (e.g. if build command is taking long)
  pkg/component/delete/delete.go
  pkg/component/delete/delete_test.go
  pkg/component/delete/interface.go
  pkg/component/delete/mock.go
  pkg/component/exec_handler.go
  pkg/component/execute_run.go
  pkg/deploy/deploy.go
  pkg/dev/kubedev/cleanup.go
  pkg/dev/podmandev/command.go
  pkg/dev/podmandev/podmandev.go
  pkg/dev/podmandev/reconcile.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/devfile/adapters/kubernetes/component/handler.go
  pkg/exec/exec.go
  pkg/exec/exec_test.go
  pkg/exec/interface.go
  pkg/exec/mock.go
  pkg/kclient/mock_Client.go
  pkg/kclient/pods.go
  pkg/libdevfile/command.go
  pkg/libdevfile/command_apply.go
  pkg/libdevfile/command_apply_test.go
  pkg/libdevfile/command_composite.go
  pkg/libdevfile/command_composite_parallel.go
  pkg/libdevfile/command_exec.go
  pkg/libdevfile/handler_mock.go
  pkg/libdevfile/libdevfile.go
  pkg/libdevfile/libdevfile_test.go
  pkg/odo/cli/delete/component/component.go
  pkg/odo/cli/delete/component/component_test.go
  pkg/platform/interface.go
  pkg/podman/exec.go
  pkg/podman/mock.go
  pkg/port/port.go
  pkg/port/port_test.go
  pkg/portForward/interface.go
  pkg/portForward/kubeportforward/portForward.go
  pkg/portForward/podmanportforward/portForward.go
  pkg/remotecmd/interface.go
  pkg/remotecmd/kubeexec.go
  pkg/remotecmd/kubeexec_test.go
  pkg/sync/copy.go
  pkg/sync/interface.go
  pkg/sync/mock.go
  pkg/sync/sync.go
  pkg/sync/sync_test.go
  tests/helper/helper_dev.go
  tests/integration/cmd_dev_test.go
Labels: kind/bug, lgtm

#6738 Cleanup e2e tests
  tests/e2escenarios/e2e_devfile_test.go
  tests/e2escenarios/e2e_test.go
  tests/examples/source/devfiles/springboot/devfile-deploy.yaml
  tests/examples/source/devfiles/springboot/devfile.yaml
  tests/examples/source/devfiles/springboot/project/docker/Dockerfile
  tests/examples/source/devfiles/springboot/project/kubernetes/deploy.yaml
  tests/helper/helper_dev.go
Labels: area/testing, lgtm

#6753 Update image for springboot devfiles
  tests/examples/source/devfiles/springboot/devfile-with-missing-projectType-and-language-metadata.yaml
  tests/examples/source/devfiles/springboot/devfile-with-missing-projectType-metadata.yaml
  tests/examples/source/devfiles/springboot/devfile-with-subDir.yaml
Labels: area/testing, lgtm

#6750 Add annotation for setting access mode on automounted configmap/secret files
  docs/website/docs/user-guides/advanced/automounting-volumes.md
  pkg/configAutomount/interface.go
  pkg/configAutomount/kubernetes.go
  pkg/configAutomount/kubernetes_test.go
  pkg/devfile/adapters/kubernetes/storage/utils.go
  pkg/devfile/adapters/kubernetes/storage/utils_test.go
  tests/examples/manifests/config-automount/access-mode-configmap-decimal.yaml
  tests/examples/manifests/config-automount/access-mode-configmap.yaml
  tests/examples/manifests/config-automount/access-mode-secret.yaml
  tests/examples/manifests/config-automount/access-mode-subpath-configmap.yaml
  tests/examples/manifests/config-automount/access-mode-subpath-secret.yaml
  tests/integration/cmd_dev_test.go
Labels: lgtm, kind/feature

#6760 Check files to sync with gitignore library
  pkg/sync/sync.go
  tests/integration/cmd_dev_test.go
Labels: kind/bug, lgtm

#6769 Test flaky devfile modification test
  tests/integration/cmd_dev_test.go
Labels: kind/bug, area/testing, lgtm

#6756 Doc automation:Command reference: odo delete,list and set namespace
  docs/website/docs/command-reference/delete-namespace.md
  docs/website/docs/command-reference/docs-mdx/delete-namespace/delete_namespace.mdx
  docs/website/docs/command-reference/docs-mdx/delete-namespace/delete_project.mdx
  docs/website/docs/command-reference/docs-mdx/list-namespace/list_namespace.mdx
  docs/website/docs/command-reference/docs-mdx/list-namespace/list_project.mdx
  docs/website/docs/command-reference/docs-mdx/set-namespace/set_namespace.mdx
  docs/website/docs/command-reference/docs-mdx/set-namespace/set_project.mdx
  docs/website/docs/command-reference/list-namespace.md
  docs/website/docs/command-reference/set-namespace.md
  tests/documentation/command-reference/doc_command_reference_deletenamespace_test.go
  tests/documentation/command-reference/doc_command_reference_listnamespace_test.go
  tests/documentation/command-reference/doc_command_reference_setnamespace_test.go
Labels: area/testing, lgtm, area/documentation

#6774 PODMAN_USE_NAMESPACES to disable using namespaces on podman integration tests for podman v4.5
  docs/website/docs/overview/configure.md
  tests/helper/helper_podman.go
Labels: area/testing, lgtm

#6776 Support variable substitution with `--var` and `--var-file` in `odo build-images`
  docs/website/docs/command-reference/build-images.md
  pkg/odo/cli/build_images/build_images.go
  tests/examples/source/devfiles/nodejs/devfile-variables.yaml
  tests/integration/cmd_devfile_build_images_test.go
Labels: lgtm, kind/feature
