Repository redhat-developer/odo, pull requests merged in 2023-01, with the labels that each got.

#6437 odo delete component on podman with --name
  pkg/component/delete/delete.go
  pkg/component/delete/delete_test.go
  pkg/component/delete/interface.go
  pkg/component/delete/mock.go
  pkg/odo/cli/delete/component/component.go
  pkg/odo/cli/delete/component/component_test.go
  tests/integration/cmd_delete_test.go
Labels: lgtm, kind/feature

#6431 Make `odo describe component` show information about components running on Podman
  pkg/api/component.go
  pkg/api/running-mode.go
  pkg/api/running-mode_test.go
  pkg/component/component.go
  pkg/component/component_test.go
  pkg/component/errors.go
  pkg/dev/podmandev/pod.go
  pkg/dev/podmandev/pod_test.go
  pkg/odo/cli/cli.go
  pkg/odo/cli/describe/component.go
  pkg/odo/cli/describe/describe.go
  pkg/podman/pods.go
  tests/integration/cmd_describe_component_test.go
Labels: lgtm, kind/feature, area/odo-on-podman

#6449 Fix typo in odo remove binding
  pkg/odo/cli/add/binding/binding.go
  pkg/odo/cli/remove/binding/binding.go
Labels: kind/bug, lgtm

#6450 Bump to v3.5.0
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: lgtm

#6443 Refactor Quickstart guide doc to use framework specific output
  docs/website/docs/user-guides/quickstart/_creating_app.mdx
  docs/website/docs/user-guides/quickstart/_running_command.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/connecting_to_the_cluster_description.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/create_namespace_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/create_project_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/initial_source_code_description.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/odo_dev_description.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/odo_init_description.mdx
  docs/website/docs/user-guides/quickstart/dotnet.md
  docs/website/docs/user-guides/quickstart/go.md
  docs/website/docs/user-guides/quickstart/java.md
  docs/website/docs/user-guides/quickstart/nodejs.md
Labels: lgtm, kind/feature, area/documentation

#6444 Refactor Advanced guide doc to use framework specific output
  docs/website/docs/user-guides/advanced/deploy/_accessing_application.mdx
  docs/website/docs/user-guides/advanced/deploy/_delete_resources.mdx
  docs/website/docs/user-guides/advanced/deploy/_running_deploy.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/accessing_application.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/delete_resources.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_Dockerfile.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_delete_component_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_describe_component_kubernetes_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_describe_component_openshift_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_final_devfile_kubernetes.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_final_devfile_openshift.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/editing_devfile.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/final_devfile.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_Dockerfile.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_delete_component_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_describe_component_kubernetes_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_describe_component_openshift_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_final_devfile_kubernetes.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_final_devfile_openshift.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_Dockerfile.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_delete_component_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_describe_component_kubernetes_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_describe_component_openshift_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_final_devfile_kubernetes.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_final_devfile_openshift.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_Dockerfile.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_delete_component_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_describe_component_kubernetes_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_describe_component_openshift_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_final_devfile_kubernetes.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_final_devfile_openshift.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/overview.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/prerequisites.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/running_deploy_description.mdx
  docs/website/docs/user-guides/advanced/deploy/dotnet.md
  docs/website/docs/user-guides/advanced/deploy/go.md
  docs/website/docs/user-guides/advanced/deploy/java.md
  docs/website/docs/user-guides/advanced/deploy/nodejs.md
Labels: lgtm, kind/feature, area/documentation

#6462 Fix odo init output in java quickstart guide
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx
Labels: kind/bug, lgtm, area/documentation

#6464 [docs] Add note to use SpringBoot 2.7
  docs/website/docs/user-guides/quickstart/java.md
Labels: lgtm, area/documentation

#6467 Remove extra caution from Java Quickstart
  docs/website/docs/user-guides/quickstart/java.md
Labels: kind/bug, lgtm, area/documentation

#6469 Tell readers of the QuickStart Guide to select "Maven" on Spring Initializr
  docs/website/docs/user-guides/quickstart/java.md
Labels: lgtm, area/documentation

#6385 Adding Github Actions for podman testing
  .github/workflows/podman-test.yaml
  tests/examples/config/containers.conf
  tests/integration/cmd_delete_test.go
Labels: lgtm, kind/tests

#6473 Do not output log to stdout
  pkg/exec/exec.go
Labels: kind/bug, lgtm

#6470 Automate Doc: Quickstart Guides
  docs/website/docs/user-guides/quickstart/docs-mdx/create_namespace_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/create_project_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx
  tests/documentation/user-guides/doc_user_guides_quickstart_test.go
  tests/documentation/user-guides/user_guides_suite_test.go
  tests/examples/source/devfiles/springboot/project/.gitignore
  tests/examples/source/devfiles/springboot/project/Dockerfile
  tests/examples/source/devfiles/springboot/project/HELP.md
  tests/examples/source/devfiles/springboot/project/mvnw
  tests/examples/source/devfiles/springboot/project/mvnw.cmd
  tests/examples/source/devfiles/springboot/project/pom.xml
  tests/examples/source/devfiles/springboot/project/src/main/java/application/Info.java
  tests/examples/source/devfiles/springboot/project/src/main/java/application/SBApplication.java
  tests/examples/source/devfiles/springboot/project/src/main/java/application/rest/v1/Example.java
  tests/examples/source/devfiles/springboot/project/src/main/java/com/example/demo/DemoApplication.java
  tests/examples/source/devfiles/springboot/project/src/main/resources/application-local.properties
  tests/examples/source/devfiles/springboot/project/src/main/resources/application.properties
  tests/examples/source/devfiles/springboot/project/src/test/java/com/example/demo/DemoApplicationTests.java
  tests/examples/source/dotnet/Controllers/HomeController.cs
  tests/examples/source/dotnet/Models/ErrorViewModel.cs
  tests/examples/source/dotnet/Program.cs
  tests/examples/source/dotnet/Properties/launchSettings.json
  tests/examples/source/dotnet/Startup.cs
  tests/examples/source/dotnet/Views/Home/Index.cshtml
  tests/examples/source/dotnet/Views/Home/Privacy.cshtml
  tests/examples/source/dotnet/Views/Shared/Error.cshtml
  tests/examples/source/dotnet/Views/Shared/_Layout.cshtml
  tests/examples/source/dotnet/Views/Shared/_Layout.cshtml.css
  tests/examples/source/dotnet/Views/Shared/_ValidationScriptsPartial.cshtml
  tests/examples/source/dotnet/Views/_ViewImports.cshtml
  tests/examples/source/dotnet/Views/_ViewStart.cshtml
  tests/examples/source/dotnet/app.csproj
  tests/examples/source/dotnet/appsettings.Development.json
  tests/examples/source/dotnet/appsettings.json
  tests/examples/source/dotnet/asp-net-hello-world.csproj
  tests/examples/source/dotnet/wwwroot/css/site.css
  tests/examples/source/dotnet/wwwroot/favicon.ico
  tests/examples/source/dotnet/wwwroot/js/site.js
  tests/examples/source/dotnet/wwwroot/lib/bootstrap/LICENSE
  tests/examples/source/dotnet/wwwroot/lib/jquery-validation-unobtrusive/LICENSE.txt
  tests/examples/source/dotnet/wwwroot/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js
  tests/examples/source/dotnet/wwwroot/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js
  tests/examples/source/dotnet/wwwroot/lib/jquery-validation/LICENSE.md
  tests/examples/source/dotnet/wwwroot/lib/jquery/LICENSE.txt
  tests/examples/source/go/README.md
  tests/examples/source/go/go.mod
  tests/examples/source/go/main.go
  tests/helper/helper_dev.go
  tests/helper/helper_documentation.go
Labels: lgtm, kind/tests, area/documentation

#6472 Make odo dev work if no endpoint is defined
  pkg/libdevfile/libdevfile.go
  pkg/libdevfile/libdevfile_test.go
  pkg/portForward/portForward.go
  tests/examples/source/devfiles/nodejs/devfile-no-endpoint.yaml
  tests/integration/cmd_dev_test.go
Labels: kind/bug, lgtm

#6432 Get binding information without cluster connection
  pkg/alizer/mock.go
  pkg/api/binding.go
  pkg/binding/binding.go
  pkg/binding/list_test.go
  pkg/init/asker/mock.go
  pkg/kclient/binding.go
  pkg/kclient/interface.go
  pkg/kclient/mock_Client.go
  pkg/odo/cli/describe/binding.go
  pkg/odo/cli/list/binding/binding.go
  pkg/odo/cli/list/list.go
  tests/examples/source/devfiles/nodejs/devfile-with-service-binding-envvars.yaml
  tests/integration/cmd_describe_list_binding_test.go
Labels: kind/bug, lgtm

#6474 Compatibility with podman v3
  .github/workflows/podman-test.yaml
  pkg/podman/podman.go
  tests/helper/component_interface.go
  tests/helper/component_podman.go
  tests/integration/cmd_delete_test.go
  tests/integration/cmd_dev_test.go
Labels: kind/bug, lgtm

#6408 Change wording for dev/deploy
  cmd/odo/help_test.go
  docs/website/docs/command-reference/dev.md
  docs/website/docs/user-guides/advanced/connecting-a-service.md
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx
  pkg/odo/cli/deploy/deploy.go
  pkg/odo/cli/dev/dev.go
Labels: kind/bug, lgtm

#6481 [podman] show logs when command fails
  pkg/component/delete/delete.go
  pkg/component/delete/delete_test.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/kclient/errors.go
  pkg/kclient/pods.go
  pkg/platform/errors.go
  pkg/podman/component.go
  pkg/podman/inspect.go
  pkg/podman/logs.go
  pkg/podman/pods.go
  tests/examples/source/devfiles/nodejs/devfileCompositeBuildRunDebugInMultiContainersAndSharedVolume.yaml
  tests/helper/component_cluster.go
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
  tests/integration/interactive_dev_test.go
Labels: lgtm, kind/feature

#6495 Fix adding .odo to .gitignore file
  pkg/util/util.go
  pkg/util/util_test.go
Labels: kind/bug, lgtm

#6496 Add more tests for odo dev on Podman (1)
  tests/helper/component_cluster.go
  tests/helper/component_interface.go
  tests/helper/component_podman.go
  tests/integration/cmd_delete_test.go
  tests/integration/cmd_dev_test.go
Labels: lgtm, kind/tests

#6502 Fix typo with file_indexer.go
  pkg/util/file_indexer.go
Labels: kind/bug, lgtm

#6505 Port-forward Debug endpoints only when running `odo dev` with `--debug`
  pkg/dev/podmandev/pod.go
  pkg/dev/podmandev/pod_test.go
  pkg/dev/podmandev/reconcile.go
  pkg/devfile/adapters/kubernetes/component/adapter.go
  pkg/libdevfile/libdevfile.go
  pkg/libdevfile/libdevfile_test.go
  pkg/portForward/interface.go
  pkg/portForward/portForward.go
  tests/examples/source/devfiles/nodejs/devfile-with-debugrun.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-multiple-endpoints.yaml
  tests/examples/source/devfiles/nodejs/project-with-multiple-endpoints/package.json
  tests/examples/source/devfiles/nodejs/project/package.json
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
Labels: lgtm, kind/feature, area/debug, area/dev

#6506 Add more tests for odo dev on Podman (2)
  tests/examples/source/devfiles/nodejs/devfile-with-MR-CL-CR-modified.yaml
  tests/examples/source/devfiles/nodejs/devfile-with-MR-CL-CR.yaml
  tests/examples/source/devfiles/springboot/devfile-registry.yaml
  tests/helper/component_cluster.go
  tests/helper/component_interface.go
  tests/helper/component_podman.go
  tests/integration/cmd_dev_test.go
Labels: lgtm

#6509 hotReloadCapable recognized on podman
  pkg/dev/podmandev/reconcile.go
  pkg/watch/status.go
  tests/integration/cmd_dev_test.go
Labels: kind/bug, lgtm

#6515 Add more tests for odo dev on Podman (3)
  tests/examples/source/devfiles/springboot/devfile.yaml
  tests/helper/helper_dev.go
  tests/integration/cmd_dev_test.go
Labels: area/testing, lgtm, kind/tests

#6516 Make doc tests pass
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_any_registry_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_specific_registry_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_url_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/latest_versioned_devfile_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/registry_list_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/registry_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/versioned_devfile_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/create_namespace_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/create_project_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx
  pkg/init/backend/interactive.go
  tests/documentation/command-reference/doc_command_reference_init_test.go
  tests/documentation/user-guides/doc_user_guides_quickstart_test.go
Labels: lgtm, kind/tests

#6507 Fix: odo dev unable to sync files with name containing special characters
  pkg/util/file_indexer.go
  pkg/util/file_indexer_test.go
Labels: kind/bug, lgtm

#6520 Set experimental mode in telemetry
  pkg/odo/genericclioptions/runnable.go
  pkg/segment/context/context.go
  tests/integration/cmd_dev_test.go
  tests/integration/cmd_devfile_deploy_test.go
Labels: lgtm, kind/feature

#6499 Isolate Podman tests in namespaces
  .github/workflows/podman-test.yaml
  Makefile
  pkg/dev/podmandev/pod.go
  pkg/dev/podmandev/pod_test.go
  pkg/dev/podmandev/reconcile.go
  pkg/podman/podman.go
  tests/helper/helper_generic.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/helper/helper_podman.go
  tests/helper/labels.go
  tests/helper/odo_utils.go
  tests/integration/cmd_dev_test.go
Labels: area/testing, lgtm, kind/tests, area/odo-on-podman

#6511 Add instructions to quickstart guide to create and cd into a directory
  docs/website/docs/user-guides/quickstart/docs-mdx/connecting_to_the_cluster_description.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/initial_source_code_description.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/odo_init_description.mdx
  docs/website/docs/user-guides/quickstart/dotnet.md
  docs/website/docs/user-guides/quickstart/java.md
Labels: kind/bug, lgtm, area/documentation

#6485 Implement `odo delete component --running-in`
  docs/website/docs/command-reference/delete-component.md
  docs/website/docs/command-reference/docs-mdx/delete-component/delete_named_component.mdx
  docs/website/docs/command-reference/docs-mdx/delete-component/delete_named_component_running-in.mdx
  docs/website/docs/command-reference/docs-mdx/delete-component/delete_running-in_with_access_to_devfile.mdx
  docs/website/docs/command-reference/docs-mdx/delete-component/delete_with_access_to_devfile.mdx
  docs/website/docs/command-reference/docs-mdx/delete-component/delete_with_files_and_access_to_devfile.mdx
  pkg/component/delete/delete.go
  pkg/component/delete/delete_test.go
  pkg/component/delete/interface.go
  pkg/component/delete/mock.go
  pkg/odo/cli/delete/component/component.go
  pkg/odo/cli/delete/component/component_test.go
  tests/helper/helper_cmd_wrapper.go
  tests/integration/cmd_delete_test.go
Labels: lgtm, kind/feature

#6528 Version bump to 3.6.0
  Dockerfile.rhel
  pkg/version/version.go
  scripts/rpm-prepare.sh
Labels: lgtm

#6522 Display error message when odo dev fails on podman and clean resources
  pkg/dev/podmandev/reconcile.go
  pkg/podman/podman.go
  tests/integration/cmd_dev_test.go
Labels: kind/bug, lgtm

#6533 test: use `t.TempDir` to create temporary test directory
  pkg/sync/sync_test.go
  pkg/util/file_indexer_test.go
  pkg/util/util_test.go
Labels: lgtm, ok-to-test, kind/code-refactoring, kind/tests

#6535 Stop containers after Podman tests
  .github/workflows/podman-test.yaml
  Makefile
Labels: lgtm, kind/tests

#6521 Run Docs tests on CI/CD
  .ibm/pipelines/kubernetes-docs-tests.sh
  Makefile
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_any_registry_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_specific_registry_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/devfile_from_url_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_directory_with_sources_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/interactive_mode_empty_directory_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/latest_versioned_devfile_output.mdx
  docs/website/docs/command-reference/docs-mdx/init/versioned_devfile_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/dotnet/dotnet_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/go/go_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/java/java_deploy_output.mdx
  docs/website/docs/user-guides/advanced/deploy/docs-mdx/nodejs/nodejs_deploy_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/go/go_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/java/java_odo_init_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_dev_output.mdx
  docs/website/docs/user-guides/quickstart/docs-mdx/nodejs/nodejs_odo_init_output.mdx
  tests/helper/helper_documentation.go
Labels: lgtm, kind/tests

#6541 Make sure to delete the component resources after each "delete component" test spec
  .github/workflows/podman-test.yaml
  tests/integration/cmd_delete_test.go
Labels: area/testing, lgtm, kind/tests

#6544 Fix identification of message on github PR
  .ibm/pipelines/functions.sh
Labels: lgtm, kind/tests

#6543 Fix potential issues with E2E tests
  tests/e2escenarios/e2e_test.go
  tests/examples/source/devfiles/go/router/router.go
  tests/helper/component_cluster.go
  tests/helper/component_interface.go
  tests/helper/component_podman.go
  tests/helper/helper_cli.go
  tests/helper/helper_component.go
  tests/helper/helper_dev.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/cmd_dev_debug_test.go
  tests/integration/cmd_dev_test.go
Labels: area/testing, lgtm, kind/tests

#6553 Run podman tests on 10 nodes
  .github/workflows/podman-test.yaml
Labels: lgtm, kind/tests

#6550 Implement odo logs on podman
  pkg/odo/cli/logs/logs.go
  pkg/podman/logs.go
  pkg/podman/pods.go
  tests/helper/helper_logs.go
  tests/integration/cmd_logs_test.go
Labels: lgtm, kind/feature

#6551 Test version upon oc/kubectl version
  tests/helper/helper_cli.go
  tests/helper/helper_kubectl.go
  tests/helper/helper_oc.go
  tests/integration/cmd_dev_test.go
  tests/integration/cmd_devfile_deploy_test.go
Labels: lgtm, kind/tests
